### ISSUE TITLE
2.0.14 breaks links in chrome

### ISSUE THREAD

**Issue by freder** [goldfire/howler.js#1011]
I noticed that since a recent update of my app dependencies, the first click on an element (in my case a [`<Link>`](https://reacttraining.com/react-router/web/api/Link)) has no effect — but only in chrome. 

at first I thought it was a `react-router-dom` problem, but then https://stackoverflow.com/questions/20490931/how-to-find-what-is-causing-a-preventdefault-which-overrides-normal-click-behavi lead me to https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L306

going back to `2.0.13` fixes it.

**Comment by benwick** [comment]
Every first click on an a tag is ignored in chrome. That is really bad. When you use Howler 2.0.14 and your first click is on a link, nothing happens!

**Comment by brunosimon** [comment]
Got the same problem with Vue.js. First click on router-links doesn't do anything, then it works fine. 
Nothing in the console.
Click events on random elements seems to work.

I downgraded to `2.0.13` thanks to @freder

**Comment by matthewoates** [comment]
This appears to be the same issue as https://github.com/goldfire/howler.js/issues/1025

**Comment by goldfire** [comment]
Thanks, this has now been fixed and I'll get a v2.0.15 out soon.
