### ISSUE TITLE
The first of the examples Audio Player is incompatible with some browsers

### ISSUE THREAD

**Issue by ZhenZY** [goldfire/howler.js#1012]
The first of the examples Audio Player is incompatible with chrome 49，Microsoft Edge 41.16299.547.0 and so on. 
  When clicking the start button of Audio Player, the button disappears and the music can not be played correctly.
![edge](https://user-images.githubusercontent.com/25266953/43683631-899d9cc4-98c2-11e8-9cdb-7b3525cf65b5.png)

**Comment by goldfire** [comment]
Are you still seeing this issue? I just tested in the latest Chrome and on Edge 42.17134.1.0 and couldn't replicate this issue.

**Comment by ZhenZY** [comment]
Yes. You can use these versions of browsers to test, such as Google Chrome Version 49.0.2623.110, Internet Explorer 11.228.17134.0 and so on.

**Comment by anesask** [comment]
> Are you still seeing this issue? I just tested in the latest Chrome and on Edge 42.17134.1.0 and couldn't replicate this issue.

Seeking on random points don't work very well on Chrome "latest" Version 69.0.3497.100.

**Comment by ZhenZY** [comment]
Sorry, I made a mistake. It didn't work properly on ie11, and it had some problems when I clicked the progress bar several times on the latest version of chrome

**Comment by goldfire** [comment]
Can you provide steps to reproduce? I'm still not able to get any issues to happen with this.

**Comment by ZhenZY** [comment]
![ogg_test](https://user-images.githubusercontent.com/25266953/51170823-5476da80-18ea-11e9-9bb4-fee8ed978944.gif)
This is a GIF diagram for testing the Ogg file.When I dragged the progress bar, it disappeared.
