### ISSUE TITLE
IE11 - Play error - Unable to get property 'then' of undefined or null reference

### ISSUE THREAD

**Issue by jtolj** [goldfire/howler.js#1015]
Getting the following error in IE11 when trying to play HTML5 audio: 
"Unable to get property 'then' of undefined or null reference"

Looks to be from this change:
https://github.com/goldfire/howler.js/commit/b8591f0e32228bb05bd346d15a1a302d3ebc8017#diff-7914ff876c66c464fe6ee7ea5ceb6eefL768

**Comment by goldfire** [comment]
I'm not able to replicate this error on IE11 with the latest version of howler. Do you have sample code how to get this to happen?
