### ISSUE TITLE
IE11 - No events are fired since 2.0.14

### ISSUE THREAD

**Issue by benwick** [goldfire/howler.js#1017]
It is all in the title.  

```
var sound = new Howl({
    src: ['sound.ogg', 'sound.mp3'],
    onplay: function() {
        console.log('Played!');
    },
    onend: function() {
        console.log('Finished!');
    }
});

sound.play();
```
The console will be empty in IE11...

**Comment by saury** [comment]
Same issue on iOS < 10 @goldfire

**Comment by benwick** [comment]
The problem in IE was fixed with 2.0.15... It can still be reproduced in 2.0.14. But it is gone with the new version.

**Comment by goldfire** [comment]
@benwick Thanks for the confirmation!

**Comment by boringwong** [comment]
Glad to see the fix when I'm about to open an issue.
