### ISSUE TITLE
play (resume) not working after fade + pause

### ISSUE THREAD

**Issue by Salitehkat** [goldfire/howler.js#1018]
Hi, 
I have a sound that after it finishes fading out it pauses (using the callback function inside fade)

```javascript
// This is the initial code for the sound

var soundId;
sound = new Howl({
  src: 'audio/music.mp3',
  html5: true,
  preload: true,
  autoplay: true,
  volume: 0,
  loop:true,
  paused:true,
  onload: function(){
    console.log("song loaded")
  }
})
  

//code to fade out and pause

sound.fade( sound.volume(), 0, 3000, soundId);
sound.on('fade', function(){
  sound.pause(soundId);
},soundId);`


//code to resume:

sound.fade( sound.volume(), 1, 30000, soundId);
```

The problem is that when i trigger an event to resume the sound , it wont play/start again and If i add  sound.play() together with the fade in the sound starts double. 

please can anyone tell me what I am doing wrong?

thanks so much

**Comment by Salitehkat** [comment]
Note: on console.log appears that the volume is rising and in the fade out event that is fading out, but can hear no sound anyway. Pls, anyone? many thanks

**Comment by goldfire** [comment]
You aren't ever calling `play` on the sound. You call `pause` when it fades, but don't start it again. `fade` on its own won't start playing the sound.
