### ISSUE TITLE
iPhone iOS latest plus latest Howler, issue starting sound on mobile

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#1020]
Good day, Im developing a web app for mobile  where sound has to be played in different occasions,
Im using the very latest howler.js
/*! howler.js v2.0.14 | (c) 2013-2018, James Simpson of GoldFire Studios | MIT License | howlerjs.com */
and also latest versions of iOS and iPhones,

Apart from the automatic way in which howler tries to kickstart audio playback on mobile, I also try to play my own silent sounds on click events to encourage it as well,

so problem is this, on android everything is perfect, no issues.

Issues are on iPhones, current ones.
On an old iPAD running ios 10 all works well.
But, on latest iphones running latest iOS,  sound playback will stop sometimes and I cannot restart it unless I do weird stuff like playing a youtube video inside the webapp and then  it will restart

how can I consistently ensure that audio playback will work with latest iphones latest ios?
I am already playing a silent sound on click
easysoundtrigger = new Howl({src: ['audio/silent.mp3'],autoplay: false,loop: false,volume: 1,buffer: false});
easysoundtrigger.play();

but despite of that sometimes sound will just go away

thank u

**Comment by goldfire** [comment]
Do you happen to have a simple test case of this? We use howler extensively on our games, which have a lot of iOS users, and we haven't run into any issues like this.

**Comment by petemcwilliams** [comment]
Thanks for re-looking at this... I find that on iphone 6s os version 12.1.1 Music Player example works fine, Audio Sprites does not (i've cleared safari's history and website data). I think this indicates the  issue is not with html audio, and that Audio Sprites is not falling back to web audio.  Which indicates that howler considers that the device should be playing web audio fine.

**Comment by that-ben** [comment]
"is your mute switch off by chance?"

WOW.  I cannot believe I just spent 15 minutes trying to debug this when the mute switch was ON.  WOW... Thanks
