### ISSUE TITLE
html5 mode not working in iOS Safari

### ISSUE THREAD

**Issue by NemoAlex** [goldfire/howler.js#1023]
Version:
iOS 11.4.1
howler.js 2.0.14

For example:
https://howlerjs.com/#radio

**Comment by ilblog** [comment]
I do confirm. Seems like Apple has tighten its audio policy.

**Comment by LukeWalsh** [comment]
It looks like this is still an issue. I'm not too familiar with Howler, was audio unlocking ever implemented for HTML5 or is it something that needs to be added?

I'm seeing this: https://github.com/goldfire/howler.js/issues/1057

**Comment by goldfire** [comment]
This should be fixed with https://github.com/goldfire/howler.js/pull/1008, which I'll try to have pushed out with several other updates in v2.1.0 early next week.
