### ISSUE TITLE
Major breaking issue with preventDefault added to global document click handler

### ISSUE THREAD

**Issue by xdumaine** [goldfire/howler.js#1025]
https://github.com/goldfire/howler.js/commit/310736b33da50bb8f075eab2eb8a34f66fbc857b

This commit is breaking clicks (namely clicking links (anchor tags)) in my app in some situations. Basically, somehow, the `onended` function is never invoked, and the click handler never gets removed, and then my app is totally busted. I'm trying to figure how exactly how or when this happen, but if you have any tips, I'd love to hear them. For now, I have to pin howler back to an earlier version.

**Comment by matthewoates** [comment]
I've noticed this myself, and was surprised to find that howler was to blame. I'm able to reproduce this consistently.

On OSX with Chrome:
- visit web app
- hit reload (actually click the refresh button), wait for page to finish loading and don't click on anything
- click on a link

expected: link works
actual: nothing happens

Note that this only happens for the first click during the page session, and this does not happen if you use CMD + R to reload.

**Comment by matthewoates** [comment]
@xdumaine a temporary work around is to use `v2.0.13`

**Comment by goldfire** [comment]
Thanks, this has now been fixed and I'll get a v2.0.15 out soon.
