### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by simonyouth** [goldfire/howler.js#1026]
> howler.js:308 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

[See] [https://www.chromestatus.com/features/5093566007214080](https://www.chromestatus.com/features/5093566007214080).
Is it necessary to modify related code to be like this?

` if (e.cancelable) {
        if (!e.defaultPrevented) {
            e.preventDefault();
        }
 }`

**Comment by goldfire** [comment]
Thanks, this has now been fixed and I'll get a v2.0.15 out soon.
