### ISSUE TITLE
sound.fade() doesn't trigger onfade if from parameter is string

### ISSUE THREAD

**Issue by CorySanin** [goldfire/howler.js#1027]
If the `from` parameter is the string representation of a number, `_volume` is set to `NaN` and onfade never gets triggered. Strangely, the fade still occurs (which is why it took me several hours to figure out what was actually causing the problem). It should either attempt to parse the string as a number, or it shouldn't perform the fade if the parameter isn't valid.
Another thing to consider is that when the `to` parameter is set to a string, it doesn't seem cause any issues.

**Comment by goldfire** [comment]
Thanks, should be fixed now with https://github.com/goldfire/howler.js/commit/8362b756924d63544f846544d02342a2b8a562ac.
