### ISSUE TITLE
Angular (2+) : Audio file not found (404)

### ISSUE THREAD

**Issue by kzanagodev** [goldfire/howler.js#1028]
Hi,

I tried to play a basic sound in an Angular app but the audio file is never found.
What I did : 

- npm i --save howler
- npm i --save-dev @types/howler

In a service I have a sample method playSound : 

`  playSound() {
    const sound = new Howl({
      src: ['/assets/sounds/alert.mp3'],
    });
    sound.play();
  }`

Imports are : 

`import { Howl, Howler } from 'howler';`

When I'm calling this method I got the 404 error : 

`GET http://localhost:5002/assets/sounds/alert.mp3 404 (Not Found)`

I tried with a lot of values for the 'src' parameter and it's always displaying this error.
I think that it's normal because of the routing system of Angular.. 

Anyone already make it work inside an Angular app ?

Thank you,

**Comment by goldfire** [comment]
You might have more luck asking this somewhere like StackOverflow. I haven't used Angular, so unfortunately I'm not sure what the answer is here.

**Comment by rrdirnens** [comment]
Did you manage to solve this?

**Comment by facundovcp** [comment]
Do yo solve it dude?

**Comment by hippohipporhino** [comment]
Found it! Ok so by default the Angular CLI restricts static content to the assets folder. You can find this configuration in the angular.json file

```
 "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
```

You put your files in the src/assets or modify this configuration. For me I made a new folder called audio and put some mp3 in there. I was then able to access them with Howler like this:

```
sound = new Howl({
            src: ['assets/audio/g_chord.mp3'],
            loop: true,
            volume: 0.5,
            onend: function() {
                console.log('Finished!');
            }
        });
```

https://stackoverflow.com/questions/44552328/angular-4-file-not-found
