### ISSUE TITLE
UC Browser on Mi4 phones does not stop when in background

### ISSUE THREAD

**Issue by mmick66** [goldfire/howler.js#1035]
I know, it sounds a little too specific but any help would be appriciated. The problem appears to be on line 966 of the howler.js file and more specifically in this condition:

```
if (sound._node.bufferSource) {
    if (typeof sound._node.bufferSource.stop === 'undefined') {
        sound._node.bufferSource.noteOff(0);
    } else {
        sound._node.bufferSource.stop(0);
    }
    ...
```

The bufferSource does not seem to be there... 

Any ideas?

**Comment by ChangChiao** [comment]
This worked out well for me.
`var hiddenProperty = 'hidden' in document ? 'hidden' :    
    'webkitHidden' in document ? 'webkitHidden' :    
    'mozHidden' in document ? 'mozHidden' :    
    null;
var visibilityChangeEvent = hiddenProperty.replace(/hidden/i, 'visibilitychange');

document.addEventListener(visibilityChangeEvent, function () {
  if (!document[hiddenProperty]) { 
    // sound play
  } else { 
    // sound stop
  }
});`
