### ISSUE TITLE
How to make continuous looping audio work

### ISSUE THREAD

**Issue by cdcv** [goldfire/howler.js#1041]
I am trying to make continuous background noise (eg white noise, water noise, etc).
There is a very noticeable break in between successive plays of an audio file that is supposed to loop.  Here is example code:
whitenoise = new Howl({
    src: ['audio/audiomed/noise001.webm','audio/audiomed/noise001.mp3'],
    volume: 1,
    loop:true
});

I have looked at other issues and posts about this problem, and tried several approaches, including hacky things like:

focusSounds[0] = new Howl({src: ['audio/audiomed/waterBackground001.webm','audio/audiomed/waterBackgrou0nd001.mp3'],
    volume: 1,
    onplay: ()=>{
        console.log('waterBackground onplay');
        looper00 = setTimeout(()=>{focusSounds[0].play();console.log('loop background');},29990);
    },
    onstop: ()=>clearTimeout(looper00) });

I have not been able to get consistent behavior.  This has become a large time suck, and each time that a solution seems to be working, it ultimately doesn't, and behaves weirdly.  This also seems to do different things in different browser contexts, mobile, etc.

Help, or a fix to loop:true, would be greatly appreciated.

Thanks

**Comment by themoonrat** [comment]
Just setting loop to true gets you what you require; you don't need to try and write hacks for it. A couple of points.
1. Looping isn't great when using html5 audio. WebAudio is usually fine
2. mp3 is not always the best format for looping audio; encode into m4a instead

**Comment by dennisrcao** [comment]
Make sure you don't have `html5: true` set  and also use the LAME encoder when encoding mp3s, other encoders such as the built in one to Music (fka iTunes) for Mac have a small ms of silence padding at the beginning and end.
