### ISSUE TITLE
IE11: setupAudioContext is called every Howl instantiation & blocks the browser process!

### ISSUE THREAD

**Issue by benwick** [goldfire/howler.js#1046]
Hello,

the [setupAudioContext](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L2284) function and Howlers [_setup](url) method should only run once and rerun if the global unload method is called. The problem is, that the calls of the setupAudioContext function are regulated by this condition: 
```
      if (!self.ctx) {
        setupAudioContext();
      }
```
This condition is always true in environments which do not support the Web Audio API, like in IE11. So the method is **called everytime** an Howler instance is spawned. But the setupAudioContext and the subsequent _setup and _setupCodecs calls are **very expensive in IE**. It can take up to half a second!

If you load 20 audio files, it can take up to **10 seconds** before all Howler instances are initalized - not even loaded! During this time, the whole browser is blocked... 

The setupAudioContext should only be called once in environments without the Web Audio API. I could make a pull request...

**Comment by benwick** [comment]
I think this fix will make problems with this line, or am I wrong?

https://github.com/goldfire/howler.js/blob/62d501d227975276631ad4d17cc76c1428dae601/src/howler.core.js#L164

**Comment by goldfire** [comment]
@benwick In what way?
