### ISSUE TITLE
Safari 12 and preloading

### ISSUE THREAD

**Issue by sudara** [goldfire/howler.js#1049]
I'm seeing a problem with `preload: true` in Safari 12.

Calling `play()` while a file is preloading leaves things in a strange state where playback doesn't happen in the browser, but Howler thinks it is playing:

```
> Howler._howls[3].state()
< "loaded"
> Howler._howls[3].playing()
< true
> Howler._howls[3]._playLock
< false
> Howler._howls[3]._sounds[0]._node.readyState
< 4
```
From what I can tell

1) Enabling "Auto-Play" in Safari for the website in question fixes the behavior.
2) Making a manual call before play to `Howler._enableMobileAudio()` doesn't help (#1047 doesn't fix it)
3) Things work as expected if `play()` is called *after* the song is in a loaded state.
4) Things work as expected if the user manually clicks somewhere on the page before clicking the play button
5) onplayerror throws `Playback was unable to start. This is most commonly an issue on mobile devices and Chrome where playback was not within a user interaction.`
6) I've confirmed my play button event propagates via `document.addEventListener('click')`

**Comment by cmckni3** [comment]
Ran into this as well

**Comment by fabswt** [comment]
Running into this too. Fine in Safari 11.x, started with Safari 12.

In my scenario, I have different ways to trigger playback: via a list of HTML links or via some SVG graph that gives info about each audio file. Clicking the links *appears* to be without effect (though the click events do propagate). Meanwhile, clicking the SVG links work same as before. Once I click an SVG link, it also plays back anything I tried to play earlier with the HTML link, as if releasing some sort of queue.

I'm unclear yet how Safari decides which user interactions are OK to honor right away and which ones are not. It's getting late here and will investigate some more tomorrow.

Hints welcome if anyone else got it to work.

(Firefox and Chrome are fine. Chrome does show this in the console `The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu` so maybe this will become a concern on Chrome too.)

**Comment by katiasmet** [comment]
I still have issues in Safari 12 when 'Stop Media With Sound' is enabled. 

Expected behaviour: 
You surf to the website, audio starts to play. 
You click on a button, another audio starts to play. 

Current behaviour in Safari 12
You surf to the website. Nothing is playing but playing() gives true. So I don't hear anything but the howler playing func. gives back 'true'. But this audio.on('play') is not fired. 

```

**Comment by fabswt** [comment]
@sudara yes, I'm using the WebAudioAPI by default.

@katiasmet did you try with this pull https://github.com/goldfire/howler.js/pull/1047 ?

**Comment by katiasmet** [comment]
@fabswt I updated my Howler version but the 'on play error' function is never called. 

I 'fixed' it with a dirty fix for now. 
```

**Comment by goldfire** [comment]
The `playing()` issue is fixed in master and will be released in an update soon.
