### ISSUE TITLE
Support iOS HTML5 audio unlocking

### ISSUE THREAD

**Issue by LukeWalsh** [goldfire/howler.js#1057]
There's no way to create a Howl with HTML5 and have mobileAutoEnable work -- therefore there's no way to create an HTML5 Howl that works on iOS (and I believe some other mobile browsers that implement audio locking).

For example:
```
    Howler.mobileAutoEnable = true;
    this.audio = new Howl({
      src: `myaudio`,
      format: ['mp3'],
      autoplay: false,
      loop: true,
      html5: true
    });
```

After the above Howler.mobileAutoEnable will be false.

I'm not sure if A/ more needs to be done to set up automatic audio unlocking using HTML5 such that it's expected behavior for mobileAutoEnable to be forced to false since it's not supported for HTML or B/ if something is accidentally flipping the mobileAutoEnable boolean.

**Comment by scottanderson42** [comment]
Linking this here for reference: https://github.com/goldfire/howler.js/pull/1008

**Comment by goldfire** [comment]
This should be fixed with https://github.com/goldfire/howler.js/pull/1008, which I'll try to have pushed out with several other updates in v2.1.0 early next week.

**Comment by psntr** [comment]
Can anyone confirm that #1008 did fix that issue?
