### ISSUE TITLE
My songs not play and my IDM start downloading them!

### ISSUE THREAD

**Issue by hrahimi270** [goldfire/howler.js#1058]
Hello.
When I build my project and open it in my browser, my songs not play and then my IDM start to download them.
What is the problem?!
Of course, I test it in another Laptop and it's worked.
There is any problem with my browser? because I test it with Chrome and FireFox and same result!

**Comment by goldfire** [comment]
Can you provide some sample code that shows the issue?

**Comment by IrhamMaulani** [comment]
i have the same problem 

this is my code
```
var suara1 = new Howl({
        src: ['1.wav'],
        preload : false
      });
 $("#btn-sounds").click(function () {
        suara1.play();
       
    });
```

i only using it in html and javascript without back-end.my OS is windows 10 thanks before
