### ISSUE TITLE
Both IDs are same

### ISSUE THREAD

**Issue by hrahimi270** [goldfire/howler.js#1060]
Hello guys.
I use Howler but when I want access to IDs, it returns 2 IDs with the same number!
It's my code:
```javascript
var intro = './assets/audio/bensound-creativeminds.mp3';
var backAudio = './assets/audio/bensound-betterdays.mp3';
var sound = new Howl({
 src: [intro, backAudio],
 autoplay: true,
 loop: true,
 volume: 0.1
});
var id1 = sound.play();
var id2 = sound.play();
console.log(id1, id2)
```

And it's the console print:
`1002 1002`
Both are same!
Is this a problem?
I want to fade the first sound and speed the second.

**Comment by goldfire** [comment]
Yes, this is due to this line: https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L665. For now, you can avoid this issue by calling those inside of `onload`.
