### ISSUE TITLE
IOS volume change error

### ISSUE THREAD

**Issue by zigou13** [goldfire/howler.js#1064]
Hello,
I develop a mobile application with IONIC 3 and when changing the volume it does not work while on ANDROID no problem

**Comment by zigou13** [comment]
On IOS12

**Comment by goldfire** [comment]
Are you using the `html5` setting?

**Comment by zigou13** [comment]
yes html5: true,

**Comment by goldfire** [comment]
You can't change volume on iOS with HTML5 Audio (only the system volume works). If you want to be able to change volume, you need to turn off the `html5` setting (which is recommended in most cases anyway).

**Comment by zigou13** [comment]
ok thank you !

**Comment by dorofino** [comment]
Hi, 
Did you ever get it working on iOS? I have been trying to control the volume without HTML5 and it does not even play.
