### ISSUE TITLE
Resuming audio causes page freeze

### ISSUE THREAD

**Issue by sharife** [goldfire/howler.js#1065]
I'm using howler.js for HTML5 game audio, and when I leave the game open in a browser window, move to a different app, then return to the game, the next time a sound is triggered the game freezes. Inspector shows an issue with the howler.js pause function, specifically this line: 
`void 0 === r._node.bufferSource.stop ? r._node.bufferSource.noteOff(0)  : r._node.bufferSource.stop(0),`

In Chrome, the error reported is this: 
```
Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at o.pause (https://vitalmindmedia.com/test/phage_invaders/4_28/lib/howler.min.js:2:10518)
```

Using version 2.0.15, tested in Firefox, Safari, and Chrome on Mac.

**Comment by goldfire** [comment]
Can you provide a working test case of this issue? It must be very specific to how you are using the library.
