### ISSUE TITLE
Chrome 71 event when Chrome autoplay restriction blocks sound

### ISSUE THREAD

**Issue by MalcolmDwyer** [goldfire/howler.js#1070]
Regarding the upcoming Chrome 71 changes to the autoplay policy, I'm still looking for a way to make Howler tell me when the sound failed to play.

I'm on Chrome 70, but getting 71 behavior by starting up Chrome like this:
(As described [here](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio))
```bash
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-features=AutoplayIgnoreWebAudio
```

Here's the behavior:
 
![howlereventsautoplay](https://user-images.githubusercontent.com/714353/48278968-c1668380-e414-11e8-92cc-646b73db5599.png)

I've seen the instructions [here](https://github.com/goldfire/howler.js#mobilechrome-playback), but they don't help because `onplayerror` never fires. Also `mobileAutoEnable` `true` or `false` makes no difference.

Is there any way to catch the fact that the sound didn't play?  Do I need to have onunlock() set a value somewhere, then poll that to check if it was never set?

**Comment by ex3ndr** [comment]
Same here on latest Safari

**Comment by goldfire** [comment]
Unfortunately, there is currently no way to detect this (I've asked both Google and the Web Audio team). There are some proposals in the works, but nothing solidified just yet. Going to close in favor of #939.

**Comment by envobgm** [comment]
Did you set option `html5: true`?

**Comment by envobgm** [comment]
I resolved it by removing `html5: true`, it's effective for me.

**Comment by envobgm** [comment]
![image](https://user-images.githubusercontent.com/50568423/57782626-35386e80-775f-11e9-8735-b3bc1a3bf217.png)
![image](https://user-images.githubusercontent.com/50568423/57782634-38cbf580-775f-11e9-8382-9c43b2d2fd69.png)

**Comment by envobgm** [comment]
![image](https://user-images.githubusercontent.com/50568423/57782694-54cf9700-775f-11e9-8e69-374ddaec12ce.png)
![image](https://user-images.githubusercontent.com/50568423/57782713-5e58ff00-775f-11e9-8665-b204c83da5f9.png)

**Comment by envobgm** [comment]
The latter works for me.
