### ISSUE TITLE
playing() issue since last commit

### ISSUE THREAD

**Issue by LaCollision** [goldfire/howler.js#1073]
Hi,

The [commit a155a1933b99dfb7be3e8ce553ece850f231a2e5](https://github.com/goldfire/howler.js/commit/a155a1933b99dfb7be3e8ce553ece850f231a2e5) unfortunately created a bug...

I'm not sure from where it comes exactly... but the `.playing()` value sometimes may have a `false` value, although the sound is playing.

Try to run your example "Player" with your latest source:
When clicking on the waveform, the sound correctly jumps to the new position. But the **timer is stopped**, and the **progress bar is stuck**.

It happens in the function `step()`: the timer is set to 0, and the `sound.playing()` value is `false`, so the `requestAnimationFrame()` is not called any longer... and everything is stuck.

So this commit introduced many negative side effects :(

Thank you for your help,

**Comment by goldfire** [comment]
Thanks! This actually turned out to be an issue with that example.
