### ISSUE TITLE
_enableMobileAudio temporarily disables click event

### ISSUE THREAD

**Issue by cfw100** [goldfire/howler.js#1076]
By default _enableMobileAudio is called on the first invocation of the Howl constructor.
This has the side effect of temporarily disabling click events:
      // Setup a touch start listener to attempt an unlock in.
      document.addEventListener('touchstart', unlock, true);
      document.addEventListener('touchend', unlock, true);
      document.addEventListener('click', unlock, true);
This creates problems for other elements on the page. For example, the next time you attempt to tick a checkbox, nothing happens.

Steps to recreate:
// invoke the Howl constructor, eg.
const howl = new Howl({ src: url, loop: false });
howl.play();
// manually try to tick a checkbox - nothing happens
// manually try to tick it again - this time it works
// invoke the Howl constructor again - this time _enableMobileAudio is skipped so...
// manually try to tick a checkbox - again this time it works

I was able to work around the bug by setting Howler.mobileAutoEnable = false;

**Comment by goldfire** [comment]
This was fixed in v2.0.15.
