### ISSUE TITLE
sounds are not played at all in Version 70.0.3538.102 if users are checking other content in different tabs

### ISSUE THREAD

**Issue by tywang2006** [goldfire/howler.js#1083]
Sound is not played in chrome not matter mute or unmute after opening and viewing other tabs in chrome for a while

**Comment by themoonrat** [comment]
If I go to https://howlerjs.com/ and run the basic functions test, they all seem to kick off ok even in another tab...

**Comment by tywang2006** [comment]
I bet it might be related to chrome auto play policy, my machine is fine but my colleague doesn't have sounds

**Comment by goldfire** [comment]
@tywang2006 The auto suspend feature only suspends when no sounds have played for 30 seconds. I'm not seeing this either, we need a test case.
