### ISSUE TITLE
Awesome Library!!! KUDOS!!!

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1084]
Congratulations for your Amazing Work!!!

One question though: I tested your Demo page inside safari on an iPhone 8. Funny thing that fadein and fadeout work seamlessly on the iPhone but your first demo (a purple audio player with audio volume slider) does not respond on the iPhone.

What would be the simplest approach to control the volume using your amazing library on the iPhone Safari Mobile Browser? Is there a way to use or adapt/incorporate a slider to handle the volume directly from the audio stream rather than from the device itself?

UPDATE: I went through the tests again. and the web audio test works beautifully on the iPhone. Is there a way to adapt a Volume Slider to that type of set up? Are all the audio files the you mention on your demo page fully functional through the web audio api that your script handles? 

Regards

**Comment by goldfire** [comment]
Thanks! Unfortunately, HTML5 Audio volume can't be changed on an iPhone as it just uses the system volume. As you saw, you can control it when using Web Audio (which is the default in howler.js).
