### ISSUE TITLE
AbortError: The operation was aborted.

### ISSUE THREAD

**Issue by codedmonkey** [goldfire/howler.js#1085]
I was hesitant to post an issue about this but after debugging some more I'm unable to find where I went wrong, so if I don't get any response or it's not related to this library I'll gladly close the issue.

After my webpage with Howler working perfectly for a few months, it seems everything has been broken now and I'm getting a lot of `AbortError: The operation was aborted.` errors, for example when I'm seeking through the audio which _only sometimes_ results in the player not being able to move it's position and it either keeps playing the previous position or it resets to an older position. The audio does load correctly though.

Simultaneously, I've been getting `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable` errors and after googling the issue they say it has to do with audio/video playback, but I can't find how this in any way affects Howler.

All the errors I'm getting don't have any trace associated with them, so I don't know what part of the code is actually causing these errors. I only vaguely know they are associated with audio playback.

**Comment by mohanklein** [comment]
same here

**Comment by kPanesar** [comment]
I also get the same errors. Both the `InvalidStateError` and the `Abort Error`. The `AbortError` I only get when seeking. Perhaps you should consider reopening this issue.

**Comment by Tehsurfer** [comment]
Are you using Firefox? There has been a[ reported bug for seeking through video and audio](https://bugzilla.mozilla.org/show_bug.cgi?id=1507193) that displays that error message

**Comment by kPanesar** [comment]
@Tehsurfer Well, yes I am. I didn't know about the bug report. I just checked edge and I don't see this issue there so that's good. Thanks!
