### ISSUE TITLE
What is the best way to control loop points for a sound?

### ISSUE THREAD

**Issue by patrick99e99** [goldfire/howler.js#1086]
Often in video game development, you want a sound to start at the beginning, but then continuously loop between two sample points for a specific duration, and then continue playing to the end of the sample...  Strangely, I have never seen an audio library ever support this sort of behavior, so I am curious what the best way to do it with Howler would be?

Is the best way to to do this have 3 sounds:

sound1 is not looped and has an onend callback which plays sound2 (that is looped), and then at some time in the future, stop sound2, and play sound3.

Is this really the only way to do this?

**Comment by goldfire** [comment]
That is basically how we are doing it in our game https://exocraft.io. To me, things like that make more sense to implement at the application level instead of bloating the library.
