### ISSUE TITLE
Incorrect value from seek() after changing rate

### ISSUE THREAD

**Issue by trevorblades** [goldfire/howler.js#1088]
When you call `seek()` on a paused sound after changing its rate, the wrong value is returned. There is one exception: things do work as expected if the rate is changed when the seek value is `0`.

```js
import { Howl } from "howler";

const sound = new Howl({
  src: "YOUR_URL_HERE"
});

sound.on("load", () => {
  sound.rate(0.5);
  console.log(sound.rate()); // 0.5 👍
  sound.seek(10);
  console.log(sound.seek()); // 10 👍
  sound.seek(20);
  console.log(sound.seek()); // 20 👍 
  sound.rate(1);
  console.log(sound.rate()); // 1 👍
  sound.seek(10);
  console.log(sound.seek()); // 20 👎
});
```

You can see this in action on [CodeSandbox](https://codesandbox.io/s/v806z5x1k7). As a workaround, the following code can be used to avoid the issue:

```js
sound.rate(0.5);
if (!sound.playing()) {
  const initialVolume = sound.volume();
  sound.volume(0);
  sound.play();
  sound.pause();
  sound.volume(initialVolume);
}
```

[These lines](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L1521) seem to be the ones causing the issue. I've found that if the lines dealing with `this._rateSeek` are removed and `seek()` only returns `this._seek` here, the issue gets resolved. It seems like these lines are the only ones that make use of `this._rateSeek`, and I'm not sure what its purpose is. I would be happy to understand more about what it's used for, or I can make a pull request that removes it if it's not necessary.

**Comment by trevorblades** [comment]
@goldfire thanks for fixing this! Any idea when you plan to cut a release?

**Comment by goldfire** [comment]
@trevorblades I've got a few more things to get into this release, but I'm hoping to have it out within the next few days (going to be out of town the rest of the weekend or I'd probably have it out sooner).
