### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by fernandofranca** [goldfire/howler.js#1089]
Subscribing to any event causes the error `Cannot read property 'push' of undefined`.

```
import soundFileMP3 from './my-sound.mp3';

const testSoundInstance = new Howl({
  src: [soundFileMP3],
  autoplay: false,
  loop: false,
  volume: 1,
});
testSoundInstance.on('onplayerror', (id, errorMessage) => {
  console.log(id, errorMessage);
});
testSoundInstance.play();
```

Removing `testSoundInstance.on('onplayerror', (id, errorMessage) => {...` it will play the sound as expected.

I'm using Howler v2.0.15 with Chrome 70.0.3538.102 and compiling with Webpack and Babel.

However, setting callbacks in the constructor object works fine.

```
const testSoundInstance = new Howl({
  src: [soundFileMP3],
  autoplay: false,
  loop: false,
  volume: 1,
  onend: () => {
    console.log("Done");
  },
  onloaderror: (id, err) => {
    console.log("OnLoadError", err);
  },
  onplayerror: (id, err) => {
    console.log("OnPlayError", err);
  },
});
```

**Comment by goldfire** [comment]
The callbacks are in the format of `onplayerror`, `onplay`, etc, but when using `.on()` you drop the `on` from the event name (see docs here: https://github.com/goldfire/howler.js#onevent-function-id).

**Comment by AlGantori** [comment]
I get this error the moment I add listening to this event, I am using the latest 2.2.3
the other events (loaderror, end) work fine.
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.core.min.js"></script>
```
Here are the errors on the console
![image](https://user-images.githubusercontent.com/11699920/154303503-9559801f-a268-4aa0-bbb7-9ed6b1892c39.png)

Here is my code...
![image](https://user-images.githubusercontent.com/11699920/154302852-dd53588a-2938-45f1-bf19-fa816e0727da.png)
![image](https://user-images.githubusercontent.com/11699920/154302898-23870f40-3eea-4940-86c7-236d8b10c480.png)

**Comment by AlGantori** [comment]
I recreated the error here
https://stackblitz.com/edit/ionic-skkgf6?file=pages%2Fhome%2Fhome.ts

When I comment out the playerror event registration I don't get the error, however I ran into a different problem on Stackblitz ONLY, I am not able to play the test audio either.

![image](https://user-images.githubusercontent.com/11699920/154396523-4e3e2e76-9e8d-47dc-a3d3-918726dbb46c.png)

**Comment by Megnatis** [comment]
You have 'playerror ' and need remove space 'playerror' . if adding multi event in howler it's seems to be good like : 'stop pause etc..'

**Comment by AlGantori** [comment]
Thank you! Wow! what a single chr$(32) can do :)
