### ISSUE TITLE
Suggestion: Multiple Master Volumes

### ISSUE THREAD

**Issue by SebastianNette** [goldfire/howler.js#109]
This is just a suggestion. When writing my game code, I always have to write a class on top of Howler that manages my master volumes.

A game usually has 2 kind of sounds.
1. Sound Effects
2. Background Music

So I think it would be nice if we could load our Audios into different Masters.

``` javascript
var sound = new Howl({
  urls: ['sound.mp3', 'sound.ogg', 'sound.wav'],
  autoplay: true,
  loop: true,
  volume: 0.5,
  master: "sound",
  onend: function() {
    console.log('Finished!');
  }
});
```

And then toggle all sound effects via

``` javascript
Howler.volume("sound", 0);
or
Howler.disable("sound");
or
Howler.toggle("sound");
```

While writing this setting into local storage and as fallback a cookie maybe. So if the user disables sound, howler will already know on the next page load if we have to play the sound at all.

``` javascript
if( Howler.enabled("sound") ) {
 console.log("sound effects are playing");
}
if( Howler.enabled("music") ) {
 console.log("bacground music is playing");
}
```

Maybe there could even be an assetloader for howler. There are quite a lot audios that I wish to load right away to not have a delay when playing them. It would be nice to have a reliable way to just say:

``` javascript
Howler.AssetLoader(JSON, function() {
 console.log("Now our audio files are ready. We can skip the loading screen and run the app");
});
```

If the audio toggle is part of howler, the callback could immediately fire if we detect that the user doesn't wish to play these sounds. 

User has disabled background music -> We dont need to load it before calling the callback.

Not everyone might need that but most use cases for a reliable audio lib like howler are games.

Right now I do this to calculate my game volumes:

``` javascript
...
options: { audio: [1,1] , music: [0, 0.7], sound: [1, 1] },
audios: [ ... ],

toggle: function( master ) {
 this.options[ master ][0] = Math.abs( this.options[ master ][0] - 1);
 if( master === "audio" ) {
  Howler.volume( this.options[ master ][0] * this.options[ master ][1] );
 } else {
  this.setVolume( master, this.options[ master ][0] * this.options[ master ][1] );
 }
}

setVolume: function( master, volume ) {
 _.each(this.audios, function( audio ) {
  if( audio.master === master ) {
   audio.player.volume( volume * audio.volume );
  }
 }
}
...
```

The first value of the options means enabled/disabled and the second value is the actual master volume. In my example the user wants to hear audios, but not background music. So all audios with "music" as master will be 0 volume.
If music was enabled all music would play at 1 \* 1 \* 1 \* 0.7 \* audio volume.

Just a suggestion and probably not needed too much but wanted to ask for it anyway ;)

**Comment by luknei** [comment]
Can somebody explain to me is this feature already implemented or not? The issue closed and there are something mentioned about groups in the docs, but it is still unclear to me how to implement multiple master volumes..

**Comment by goldfire** [comment]
In 2.0 a "group" is just a new `Howl`. If you modify the volume without passing in a sound ID, it'll change the volume of all sounds playing in that `Howl` rather than just one sound like in 1.x.

**Comment by medoingthings** [comment]
@goldfire I don’t really get the concept of the group thing. Could you point me in a direction how to create a group with multiple sounds? Would be much appreciated. Didn’t find anything that helped me in the docs. Google couldn’t help me as well.

In my understanding I have to do this for each sound that I want to use:
```
    var soundA = new Howl({
      src: ['sound-a.webm', 'sound-a.mp3']
    });

    var soundB = new Howl({
      src: ['sound-b.webm', 'sound-b.mp3']
    });

```
How can I combine the two into a group? E.g. to mute the group instead of each individual sound.

**Comment by themoonrat** [comment]
In the readme/documentation, what you're looking for is the section "Define and play a sound sprite". Here it describes using one Howl, to load one audio file that contains multiple sounds. In this way, you could have one Howl soundsprite for all your music, and one Howl soundsprite for all your other sound effects. These 2 Howls can have their volume controlled to achieve your requirement

**Comment by medoingthings** [comment]
@themoonrat oh I see. Thanks for the heads up! Quite different from what I expected to be "groups", but this does the trick, indeed.
