### ISSUE TITLE
How can I make smooth and gradual sound transition from left to right?

### ISSUE THREAD

**Issue by SeminYun** [goldfire/howler.js#1095]
Hi. Holwer.js 
we are using 'Spatial' but we have a problem..
Please check the following link. This is Spatialized audio in 2D.

https://webaudioapi.com/samples/spatialized/

On the example from the above link, when I change the position the sound’s direction and volume change smoothly and gradually.  But when I use Spatial in our game, the direction transition is sudden, it’s either absolute left or absolute right.

Could you tell me what we should do to make the direction transition gradual and smooth like the above example?

**Comment by goldfire** [comment]
Can you provide sample code of what you are currently trying?

**Comment by SeminYun** [comment]
<!doctype html>
<html>
<head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="howler.core.js"></script> 
    <script type="text/javascript" src="howler.spatial.js"></script> 


</head>

<style>
    div { width: 1024px; height:1024px; margin: 0; padding: 0; background-color: #1c94c4; }
</style>

<body>
<div id="main" onmousemove="myFunction(event)"></div>
<script>

	function myFunction(ev) {
		console.log(ev.clientX, ev.clientY);
		//Howler.pos(ev.clientX, ev.clientY, -0.5);
		Howler.pos(300, 300, -0.5, id);
    }

    var sound = new Howl({
	    src: ['wind_if.ogg','wind_if.mp4'],
        loop:true,
        volume:1.0,
    });

    var id = sound.play();
    if(1) {
	    sound.pannerAttr({
		    distanceModel: 'linear',
		    maxDistance: 900,
		    volume: 1.0
	    }, id);

	    sound.pos(300, 300, -0.5, id);
    }


</script>
</body>

</html>

Hi. Is there wrong?

 - I set 'Howler.pos(300, 300, -0.5, id);' on mousemove,  sound noisy
 - I set 'Hower.pos(client.x, client.y, -0.5, id)' on mousemove, Can't sound. I can't find why 'maxDistance' not available.


[sound.zip](https://github.com/goldfire/howler.js/files/2665903/sound.zip)

**Comment by goldfire** [comment]
You might take a look at https://github.com/goldfire/howler.js/tree/master/examples/3d for an example of how spatial audio is supposed to work. However, if you just need left/right then you'll get much better/easier results using the `stereo` method instead (https://github.com/goldfire/howler.js#stereopan-id).
