### ISSUE TITLE
Only WAV works

### ISSUE THREAD

**Issue by stealman** [goldfire/howler.js#1096]
Hello guys I am little bit frustrated, I just can WAV files playing correctly. I have tried tens of mp3s and oggs but it just never works. Sometimes it plays for like 0.1s, sometimes it plays corrupted in FF / Chrome / IE .. everywhere. 

I dont do anything else than just 

```
function playSound() {
    var sound = new Howl({
      src : [ "sounds/sound.mp3" ]
    });

    sound.play();
  }
```

But I can only play wav files correctly, I have no idea about whats wrogn, maybe I am extremely unlucky and all my random test files are somehow corrupted ? I have to say that example howler pages works well in all my browsers. 

Someone faced similar issue that just nothing else than WAV file works ?

There is link to my test site, I think it cannot be any simpler - all 4 files are playing well, when I drag them directly into browser, but on the page, nothing happens :(

http://darkenlight.net/mediteranea/test.html

**Comment by goldfire** [comment]
How are you creating the test files?

**Comment by stealman** [comment]
Sorry mister !!! I have already found the issue - it is funny, I wasnt able to find it for several months and then found it one day after I posted this :)

My issue was my Maven build tool - it corrupted MP3 files. Source files was ok but they were corrupted during building process. Already fixed that.

Sorry for irrelevant thread !!
