### ISSUE TITLE
HTML5 Audio with src array merges array into 1 url

### ISSUE THREAD

**Issue by ItsOnlyBinary** [goldfire/howler.js#1098]
```
this.howler = new Howl({
  src: ['http://example.com/stream1-mp3', ''http://example.com/stream1-aac'],
  html5: true,
  format: ['audio/mpeg', 'audio/aacp'],
});
```

results in the chromium trying to open `"http://example.com/stream1-mp3,http://example.com/stream1-aac"`

**Comment by ItsOnlyBinary** [comment]
the extra quotation mark was me typo'ing when adding a readable example to here.
for format i just put what i got from dirble, guess i need to make a map for those.

this issue is real though, thanks for speedy reply

**Comment by ItsOnlyBinary** [comment]
Howl object dumped with JSON.stringify(this.howl, null, 2);

https://gist.github.com/ItsOnlyBinary/9ec06c313ffb3468a8462b8e9aa77145

The Error from chromium:
`GET http://streams.rock-avenue.bzh/rockavenue-128.mp3,http://streams.rock-avenue.bzh/rockavenueaac.aac net::ERR_ABORTED 404 (Not Available)`

**Comment by goldfire** [comment]
If the extension is included then you don't need format, and again, that is not the correct value for the format.

**Comment by ItsOnlyBinary** [comment]
ok thats somewhat a strange way to fail, but dropping the format for that stream did work.
i will write a mimeToExtension function to work around this as I cannot be sure every stream will have an extension. adding support for mime types instead of file extensions would be nice addition

Thanks for your time
