### ISSUE TITLE
seek no longer works in 2.1.0

### ISSUE THREAD

**Issue by smakinson** [goldfire/howler.js#1101]
Updating to 2.1.0 causes seek(position) to no longer work. It always plays from the start. If I revert to 2.0.15 it works again. I am using html5: true and format: ['mp3']. Setting the html5PoolSize to 0 did not resolve the issue. I have the same result in chrome & safari.

**Comment by smakinson** [comment]
Sure. If I switch between 2.0.15 and 2.1.0 in the pen I get different results when I press seek.

https://codepen.io/smakinson/pen/maPRNe

**Comment by ardeois** [comment]
I've got the same issue and found the problem.
See https://github.com/goldfire/howler.js/pull/1102

**Comment by ardeois** [comment]
@smakinson If you change your codepen howler version to my branch it should work. Can you confirm?
 
https://cdn.jsdelivr.net/gh/ardeois/howler.js@610ed0c02f07680fd4e73a87cc6ebed8ab273188/dist/howler.min.js

**Comment by smakinson** [comment]
@ardeois Looks like that fixes it!

**Comment by paulrosen** [comment]
I think you can also pass the id back in when calling play the second time:
```
var howl = new Howl(...);
...
var id = howl.play();
...
howl.pause();
...
howl.play(id); // will not start back at beginning.
```

**Comment by ardeois** [comment]
Good point, it should work. However it looks to me like a workaround on a regression

**Comment by goldfire** [comment]
This should now be fixed with https://github.com/goldfire/howler.js/commit/d22ddcf76f58861ce23ca1f6fc21d9895c253902.

**Comment by smakinson** [comment]
Thank you for addressing this so quickly!

**Comment by stevenleeg** [comment]
Has this issue come back again? I'm noticing calls to `seek` always causing the playhead to reset to 0 in v2.1.2.

**Comment by Mani7TAM** [comment]
I am also facing this seek issue in chrome and opera for version. But working without issues in firefox.

**Comment by tsukinose81** [comment]
Version 2.2.3 also has this problem. It works normally in firefox

**Comment by JoshKasap** [comment]
I found the url that you get your audio file from needs to include the response header `Accept-Ranges: bytes` in order for the seek and duration counters to work properly in chrome. 

IDK how you do this using other languages but for cold fusion you need to add `<cfheader name="Accept-Ranges" value="bytes">` to the top of page that returns the audio file. 

For more context that might help people. 
In my case the url I provided to howler was not a direct path to an audio file but instead a path to a page that would accept certain url parameters which would in turn be used to search a db and return the file. So I just needed to add the `Accept-Ranges: bytes` header to the top of this page that returned the audio file. Hopefully this information can be used to help determine the solution to this issue in more commonly used languages.

**Comment by F8ER** [comment]
> Accept-Ranges: bytes

Holy smokes... You are a hero... Ha! Thank you very much! That was it! The same exact issue: from direct path to a custom reference - missing header.

Hurray!

Please have a pleasant time and stay safe! :sparkles:
