### ISSUE TITLE
Spatialization orientation not clearly defined in Chrome

### ISSUE THREAD

**Issue by MrSonicMaster** [goldfire/howler.js#1112]
Using the public spatial audio demo located [here](https://howlerjs.com/assets/howler.js/examples/3d/), the audio does not mix very well and favors the right channel in Chrome. Other browsers such as Edge and Firefox offer better separation, making it much easier to distinguish the location of sounds. Other implementations that use Howler.js spatial audio, such as [krunker.io](https://krunker.io) seem to work correctly in all browsers.

**Comment by alessandroTola** [comment]
Hi, I've the same problem, in my project I have located 4 sounds, front-left, front-right, rear-left, rear-right, the camera is in the center and I can only rotate. With firefox I hear the sound changing position when I rotate the camera, on Chrome the sound doesn't change. I try to search this issue online but I didn't find anything.

**Comment by MrSonicMaster** [comment]
The owner seems to be ignoring this issue though, unfortunate that we can't get some insight into what might be causing it because its possible for it to work on Chrome.

**Comment by Joeywp** [comment]
Having the same issue here. I found that v2.0.9 (the one Krunker uses) actually does do the spatial audio correctly in Chrome, couldn't yet find however, why the newer versions don't handle this correctly anymore.

**Comment by Joeywp** [comment]
It appears to be be related to this commit and in specific these lines:
https://github.com/ringcrl/howler.js/commit/e9b7e8cd5633cfd9be2cacac3a894ddea845e9e2#diff-a34d0d8427da25a3cae0aae630554c45R117

I tested to see if undoing this hunk of the commit did work, so just using the setOrientation here and it actually did work. I don't however know why the setTargetAtTime implementation doesn't work there, trying to find that out now.
