### ISSUE TITLE
Handling Audio Events in Angular2+ with Typescript?

### ISSUE THREAD

**Issue by nikhilbhalwankar** [goldfire/howler.js#1115]
How to handle various events related to song state in Angular2+ with TypeScript? e.g. I am trying to detect song ended event but the function can not detect variables present in typescript class.

```
this.currentSound = new Howl({
      src: [this.selectedSongSignedUrl.url],
      autoplay: true,
      html5: true
    });

this.currentSound.on('end', function(){
      console.log('Finished!');
      this.isSongPlayingInd = false;
      this.progressBarValue = 0;
    });
```
Console correctly shows finished message. However, progressBarValue and isSongPlayingInd are members of typescript class but these are not detected by the function().

**Comment by themoonrat** [comment]
This is a 'capturing this' question as opposed to anything related to Howler
Changed
`this.currentSound.on('end', function(){`
to
`this.currentSound.on('end', () => {`

this method of anonymous function will capture the meaning of `this`, thus allowing access to the member variables

**Comment by nikhilbhalwankar** [comment]
> This is a 'capturing this' question as opposed to anything related to Howler
> Changed
> `this.currentSound.on('end', function(){`
> to
> `this.currentSound.on('end', () => {`
> 
> this method of anonymous function will capture the meaning of `this`, thus allowing access to the member variables

**Comment by nikhilbhalwankar** [comment]
> This is a 'capturing this' question as opposed to anything related to Howler
> Changed
> `this.currentSound.on('end', function(){`
> to
> `this.currentSound.on('end', () => {`
> 
> this method of anonymous function will capture the meaning of `this`, thus allowing access to the member variables

Thanks for this. Will check it out and get back.
