### ISSUE TITLE
OT: Where can I find more free radio stream online?

### ISSUE THREAD

**Issue by cekvenich** [goldfire/howler.js#1116]
I'm looking for 'programing' music, no words, a bit techno or such.
Or just where can I find a bunch of free 24x7 streams.

**Comment by HerHde** [comment]
We often play [DEF CON Radio](https://somafm.com/defcon/) in our hackerspace, one of many good [SomaFM](https://somafm.com/) streams. [Chillstep](https://chillstep.info/) might also be something for you.
Take a look at the [icecast directory](http://dir.xiph.org/) for a thousands of free radio stations in general.

**Comment by darren-dev** [comment]
Please close this issue as off topic
