### ISSUE TITLE
more precise seek

### ISSUE THREAD

**Issue by danbulant** [goldfire/howler.js#1117]
Hello.
I love using howler as it's easy to use, but have a saw a little limitation in seek (get), because when using slider for playback, it's little bit bigger jumps than I expected. Is there a way to get more precise seek?

**Comment by goldfire** [comment]
Seek can already take any float value and will seek to that position, so the size of the jump is completely dependent on your own code.

**Comment by danbulant** [comment]
@goldfire I know, you can SET seek into any float, but the GET is always(as far as I know) in seconds.

>  saw a little limitation in seek **(get),**

**Comment by goldfire** [comment]
@danbulant Getting the seek value also returns a float in seconds. If you aren't seeing this can you provide a test case?
