### ISSUE TITLE
Sound through Howler is "muffled" with default settings, sounds fine via simple <audio> tag

### ISSUE THREAD

**Issue by altryne** [goldfire/howler.js#112]
Hi,
I'm trying to get to the bottom of this, and can't seem to understand, why this is happening. 
When I simple go to my sounds URL in browser, it sounds crisp and clear. 
When I play it through Howler with the default settings from examples, it sounds lower quality, the sounds are a bit muffled.

I tried to look in documentation for different "quality" settings but didn't find anything.

P.S. I've reproduced this on both chrome and safari with ogg and mp4

**Comment by qhyun2** [comment]
My sounds were also sounding muffled and setting the `panningModel` to `equalpower` fixed it!
```js
sound.pannerAttr({
  distanceModel: "linear",
  maxDistance: 17,
  panningModel: "equalpower", // <- sounds are crispy again!!!
  refDistance: 1,
  rolloffFactor: 1,
  coneInnerAngle: 360,
  coneOuterAngle: 360,
  coneOuterGain: 0,
});
```
