### ISSUE TITLE
play mp3 data recieved from websocket

### ISSUE THREAD

**Issue by richtier** [goldfire/howler.js#1125]
I have mp3 audio streaming from a websocket.

Does howlet support playing the audio?

**Comment by richtier** [comment]
yes:

```
        var blob = new Blob([samples]);
        var howlSound = new Howl({
          autoplay: true,
          src: [URL.createObjectURL(blob)],
          html5: true,
          format: ['mp3'],
        })
```

**Comment by AhmedBHameed** [comment]
Hi @richtier according to your question i assume that you are sending chunks over time as WebRTC right ?
In this case how can you keep playing sound while updating [sampls] ?
I want to play audio immediately and keep updating samples.

Is that possible ?
