### ISSUE TITLE
.stop() only works once in chromium

### ISSUE THREAD

**Issue by ItsOnlyBinary** [goldfire/howler.js#1129]
if i stop and start in chromium it will only allow me to stop once, issue is not present in firefox

i created the following codepen to show the issue, it continues playing after the last stop

https://codepen.io/anon/pen/mvrpKB

**Comment by goldfire** [comment]
Just as an update, this appears to be a bug in Chrome where the play promise stays pending forever when being played for a 2nd time. I'm still trying to figure out a workaround.

**Comment by goldfire** [comment]
Another observation is that it appears to only be an issue with live streaming audio that has a duration of Infinity. Resetting the `src` on the audio node seems to fix the issue, but that doesn't seem like a great solution.
