### ISSUE TITLE
[Critical] Every stream will continue downloading permanently

### ISSUE THREAD

**Issue by Redsandro** [goldfire/howler.js#1143]
Stopping a stream doesn't stop downloading the stream. You'll end up downloading so many streams at the same time that your internet connection becomes slow. Plus of course this is not nice to the streaming servers.

You can see this in the [radio example](https://howlerjs.com/#radio):

![image](https://user-images.githubusercontent.com/1702193/53810787-fa90a980-3f57-11e9-8ed8-ae95eb2f09c0.png)

If you stop the playback of a stream _before_ it's fully buffered and started playing, it _will_ stop the download, as you can see in the first stream. The second one was clicked before playback on the first one started.

Tested on Chrome Version 74.0.3717.0 (Official Build) dev (64-bit) Linux. Firefox doesn't capture data streams in the dev panel afaik so I cannot test this on Firefox. I assume it will be the same.

**Comment by Redsandro** [comment]
I did not know an `.unload()` was needed because I learn from the examples, and the example does not unload streams.

Here is a mini PR: #1144 to remedy this.

**Comment by crazywire** [comment]
The unload function uloads the who sound. WIll it still be in buffer? Do you need to save the seek position so you can start from where you left?

**Comment by crazywire** [comment]
I think downloading of the who file in the background is HTML5 issue not howler specific.
