### ISSUE TITLE
Multiple Sound Issue Mobile Safari

### ISSUE THREAD

**Issue by tonyrf** [goldfire/howler.js#1148]
I am experiencing problems with multiple sound playback on iOS / Safari Mobile. If I play one sound immediately after another in javascript only the first sound plays.

When I run your howler demo tests on my iPhone iOs 12.1.4 using Safari, the multiple sound portion also does not appear to work, I only hear a single sound file.

**Comment by darren-dev** [comment]
Please include your code as an example so people can better understand your issue.

**Comment by goldfire** [comment]
If you can provide a test case I'll re-open this. All of our examples are working correctly on iOS for me.
