### ISSUE TITLE
CDN - Origin Policy Issue

### ISSUE THREAD

**Issue by ncacace** [goldfire/howler.js#115]
After many iterations of audio plugins for HTML5 we found Howler to be the only solution that satisfied all demands for our project.

After uploading to the CDN, however, we are experiencing an issue regarding Access Control (Cross Domain Policy Control)

From Chrome's Console Window:
"The 'Access-Control-Allow-Origin' whitelists only 'http://cnd.acme.org'. Origin 'http://acme.org' is not in the list, and is therefore not allowed access."

And this: 
"XMLHttpRequest cannot load http://cdn.acme.org/test/audio.mp3. The 'Access-Control-Allow-Origin' whitelists only 'http://cdn.acme.org'. Origin 'http://acme.org' is not in the list, and is therefore not allowed access."

We found this post relating to HTML5 aproaches to Cross Domain Policy:
http://omarrr.com/cors-html5-approach-to-crossdomain-policies/

And have narrowed down the issue to Howler's implementation of XML over JSONP - we think....

We've added a CORS policy to the Apache Server but no cigar

Has any one else experienced this issue using Content Delivery Networks? 

It would be great to hear from any insight that the developer of this awesome plugin may have.

**Comment by jyurow** [comment]
I am experiencing a similar issue with a sound file downloaded from Github.  Using the CDN for Howler 2.0.0 with the appropriate syntax, I get the error:

howler.core.min.js:2 XMLHttpRequest cannot load file:///D:/circles/sounds/bubbles.mp3. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by acherny** [comment]
I know this is old but I am having the same issue. We are loading MP3s from S3. Our bucket has the following CORS settings:

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

Any ideas why we are getting CORS errors?

**Comment by Tatsujinichi** [comment]
Seems that if I try to use assets using https, it instead tries to use http.  Causing the same error as above.

**Comment by ncacace** [comment]
try "//domain.com..."  I've found that omitting the protocol at the
beginning of the URI can allow for implicit inclusion of the required
protocol BUT it obviously depends on the server setup so just give it a
quick try and if it works then great

https://stackoverflow.com/questions/9161769/url-without-httphttps

**Comment by Tatsujinichi** [comment]
Well, the thing is, I am sometimes coming from http, otherwise that would work.

**Comment by Tatsujinichi** [comment]
Sorry, my fault.  Nevermind.

**Comment by qroft** [comment]
I have one general question about this:
an app that i created with Phonegap, locally works perfect. I mean: via "phonegap serve" i can try out my app LIVE while i make it and the radio streams that i have implemented work without a problem.

Then i build the app and uploaded it to the Play-Store, but here the radio streams do not work.
Could this be such an origin / CORS policy problem?

Greetings and thanks in advance for your time!

**Comment by Moongazer** [comment]
Is there any option in Howl to configure the CORS behavior? I find it problematic that `new Howl({src: ['myAudioURL']})` sends a request for this file containing a `Origin` header, which forces the server to respond properly, or (if it doesn't) leads to a browser CORS error crashing the whole application (e.g. if the response `Access-Control-Allow-Origin` is missing).
