### ISSUE TITLE
Scheduling audio playback in the future

### ISSUE THREAD

**Issue by btmorex** [goldfire/howler.js#1150]
Is there a way to schedule audio playback in the future like there is in the raw web audio api and some other libraries like sound.js? (necessary for precise timing of game audio) Thanks!

**Comment by TombolaShepless** [comment]
@goldfire is there a way to do this? I can't see a way to do it?

**Comment by waspeer** [comment]
Did any of you figure out how to do this with Howler? Or did you end up using the Web Audio API directly?
