### ISSUE TITLE
3-4 Second Load Time Increase for Live Stream in Chrome

### ISSUE THREAD

**Issue by clintLandrum** [goldfire/howler.js#1155]
I'm trying to isolate the cause of a recent increase in load time for a live stream player in Chrome only.

**Has anyone encountered any unexpected issues with their player load times (specifically early March) in Chrome?**

My speculation is that there was a Chrome update (through autoupdating) that has caused an increase in load times for live streams.

**Update**
Confirmed in BrowserStack that this load time increase appeared in Chrome 71.

**Comment by darren-dev** [comment]
From your findings, this seems to be a chrome issue and not a direct Howler issue. It most likely is due to the recent security updates.

Could you close this issue?

**Comment by clintLandrum** [comment]
@darren-dev Yeah, this is a Chrome issue. I expected for there to be others dealing with it and looking for information on it here.
Closing this issue. Thx.
