### ISSUE TITLE
How to stop when android press home button/ switch app

### ISSUE THREAD

**Issue by david43** [goldfire/howler.js#1160]
Hi,
I use android chrome to play music,
when I switch the app,
music still playing
Is it any option to stop it?

**Comment by darren-dev** [comment]
This is not a howler issue - it's your browser allowing audio to play in the background. You are thinking about this 'issue' wrong. 

What you need to do is see if your webpage looses context, and then stop your sound when it does.

```
private visibilityChange() {
		let hidden = 'hidden'

		// Standards:
		if (hidden in document)
			document.addEventListener('visibilitychange', onchange)
		else if ((hidden = 'mozHidden') in document)
			document.addEventListener('mozvisibilitychange', onchange)
		else if ((hidden = 'webkitHidden') in document)
			document.addEventListener('webkitvisibilitychange', onchange)
		else if ((hidden = 'msHidden') in document)
			document.addEventListener('msvisibilitychange', onchange)
		// IE 9 and lower:
		else if ('onfocusin' in document)
			document.onfocusin = document.onfocusout = onchange
		// All others:
		else
			window.onpageshow = window.onpagehide = window.onfocus = window.onblur = onchange

		function onchange(evt) {
			let v = false,
				h = true,
				evtMap = {
					focus: v,
					focusin: v,
					pageshow: v,
					blur: h,
					focusout: h,
					pagehide: h
				}

			evt = evt || window.event

			let windowHidden = false
			if (evt.type in evtMap) {
				windowHidden = evtMap[evt.type]
			} else {
				windowHidden = this[hidden]
			}

			if (howl) {
				if (windowHidden) {
					// howl.mute(true)
				} else {
					// howl.mute(false)
				}
			}
		}

		// set the initial state (but only if browser supports the Page Visibility API)
		if (document[hidden] !== undefined)
			onchange({
				type: document[hidden] ? 'blur' : 'focus'
			})
	}
```

**Comment by david43** [comment]
Thank you for the help

> This is not a howler issue - it's your browser allowing audio to play in the background. You are thinking about this 'issue' wrong.
> 
> What you need to do is see if your webpage looses context, and then stop your sound when it does.
> 
> ```
> private visibilityChange() {
> 		let hidden = 'hidden'
> 
> 		// Standards:
> 		if (hidden in document)
> 			document.addEventListener('visibilitychange', onchange)
> 		else if ((hidden = 'mozHidden') in document)
> 			document.addEventListener('mozvisibilitychange', onchange)
> 		else if ((hidden = 'webkitHidden') in document)
> 			document.addEventListener('webkitvisibilitychange', onchange)
> 		else if ((hidden = 'msHidden') in document)
> 			document.addEventListener('msvisibilitychange', onchange)
> 		// IE 9 and lower:
> 		else if ('onfocusin' in document)
> 			document.onfocusin = document.onfocusout = onchange
> 		// All others:
> 		else
> 			window.onpageshow = window.onpagehide = window.onfocus = window.onblur = onchange
> 
> 		function onchange(evt) {
> 			let v = false,
> 				h = true,
> 				evtMap = {
> 					focus: v,
> 					focusin: v,
> 					pageshow: v,
> 					blur: h,
> 					focusout: h,
> 					pagehide: h
> 				}
> 
> 			evt = evt || window.event
> 
> 			let windowHidden = false
> 			if (evt.type in evtMap) {
> 				windowHidden = evtMap[evt.type]
> 			} else {
> 				windowHidden = this[hidden]
> 			}
> 
> 			if (howl) {
> 				if (windowHidden) {
> 					// howl.mute(true)
> 				} else {
> 					// howl.mute(false)
> 				}
> 			}
> 		}
> 
> 		// set the initial state (but only if browser supports the Page Visibility API)
> 		if (document[hidden] !== undefined)
> 			onchange({
> 				type: document[hidden] ? 'blur' : 'focus'
> 			})
> 	}
> ```
