### ISSUE TITLE
Firefox now blocks automatically playing audio too

### ISSUE THREAD

**Issue by chris-bingham** [goldfire/howler.js#1166]
As of version 66, firefox is now the latest browser to block automatically playing audio
See https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/

Can we get FF added to the `shouldUnlock` regex test string, line 286 of `src/howler.core.js`?

Happy to open a PR but dont have permission to push to the repo

**Comment by themoonrat** [comment]
@goldfire at this point, is there any harm in this just always running rather than a regex test? At this point, it's only IE and Edge that don't require it, and Edge soon will when it starts using Chromium.

**Comment by goldfire** [comment]
I started to do some IE testing and then realized there is no need since it skips IE anyway due to lack of Web Audio. I've removed that check completely in https://github.com/goldfire/howler.js/commit/5f4c37e0a4123b322f4383f6cc383478570414dc.
