### ISSUE TITLE
_canPlayEvent value assign is wrong

### ISSUE THREAD

**Issue by DZG-MELODY** [goldfire/howler.js#1174]
in source code, line 204 

```js
            // Check if the canplaythrough event is available.
            if (typeof test.oncanplaythrough === 'undefined') {
              self._canPlayEvent = 'canplay';
            }
```

is the condition should be `typeof test.oncanplaythrough !== 'undefined'` ?

**Comment by goldfire** [comment]
No, that is correct. The event used by default is canplaythrough, but if that doesn't exist it falls back to canplay.
