### ISSUE TITLE
Neither sound nor listener spatialized after initial call?

### ISSUE THREAD

**Issue by thely** [goldfire/howler.js#1178]
I've been racking my brain over this, which probably means I'm missing something.

I'm trying to work with `spatial`, but I can't seem to update any of the `pos` values, for anything, after initially declaring them. `.vs1` is a range slider going from -20 to 20; I know it's sending values based on the console. I've tried using it to update values on both (I tried the sound first, then the listener when the sound wasn't working). But if I log `sound.pos` after updating it via the set method, not only does nothing happen, it returns null. If I log `Howler.pos` after trying to update it (as below), I get [0,0,0]. So clearly, nothing is updating. I've looked over the 3D example a lot, but nothing has helped me figure out what I'm doing wrong.

edit: I'm using Firefox 66.0.3.

```
$(function() {
	var sound = new Howl({
		src: ['audio/breakbeat.wav'],
		autoplay: true,
		loop: true,
		volume: 0.2,
		onend: function() {
			console.log('Finished!');
		}
	});

	var id = sound.play();

	sound.pos(0, 0, 0, id);
	Howler.pos(10, 5, 0);

	$(".vs1").on("input", function(ev) {
		Howler.pos(ev.target.value, 0, 0);
	});
});
```

**Comment by goldfire** [comment]
I've tried your sample code and it works correctly. Keep in mind that the positions you have selected are going to be barely audible if at all. Also keep in mind that when changing the pos of a single sound, the _pos value is specific to the sound, so logging sound._pos won't show the updated value.
