### ISSUE TITLE
Can't get the orientation to work (no effect)

### ISSUE THREAD

**Issue by MrPotatoPotatoPotato** [goldfire/howler.js#1179]
`var sound = new Howl({
		  src: ['audio/bigroom.mp3'],
		  sprite: {
			begin: [3000, 30000]
		  }
		  });
		sound.load();	
		Howler.volume(0.5);
		sound.volume(1);
		sound.pos(2,0,0);
		Howler.orientation(0, 0, -1, 0, 1, 0);	
		sound.play('begin');
`

When I disable the Howler.orientation line, I hear the sound to my right. But when I enable the Howler.orientation line, I just hear it like normal. I have tried many values, but it doesn't seem to effect the panning.

Am I doing something wrong with the values?

**Comment by subi211** [comment]
Just had exactly this issue myself, and it looks like it's cause by a typo in HowlerGlobal.prototype.orientation:

```
      if (typeof self.ctx.listener.forwardX !== 'undefined') {
        self.ctx.listener.forwardX.setTargetAtTime(x, Howler.ctx.currentTime, 0.1);
        self.ctx.listener.forwardY.setTargetAtTime(y, Howler.ctx.currentTime, 0.1);
        self.ctx.listener.forwardZ.setTargetAtTime(z, Howler.ctx.currentTime, 0.1);
        self.ctx.listener.upX.setTargetAtTime(x, Howler.ctx.currentTime, 0.1);
        self.ctx.listener.upY.setTargetAtTime(y, Howler.ctx.currentTime, 0.1);
        self.ctx.listener.upZ.setTargetAtTime(z, Howler.ctx.currentTime, 0.1);
      } else {
        self.ctx.listener.setOrientation(x, y, z, xUp, yUp, zUp);
      }
```

The self.ctx.listener.up[N].setTargetAtTime calls are using the forward vector instead of the up vector.  Change those to use the up vector and everything works fine.

**Comment by goldfire** [comment]
This was fixed a while back and I missed this issue. Let me know if there is still an issue.
