### ISSUE TITLE
Did Howler is supporting for Wav GSM 610 Audio formats?

### ISSUE THREAD

**Issue by Arunkhannen** [goldfire/howler.js#1181]
James, Did Howler is supporting for WAV GSM 6.10 Audio formats?! We are doing the review for WAV GSM 6.10 compressed audio formats. Is that any solutions with you?

**Comment by goldfire** [comment]
If it isn't supported by browsers then there is no way for howler to play it. Here is the compatibility chart on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by Arunkhannen** [comment]
Thanks James. Will try to fix with the alternate options.
