### ISSUE TITLE
Play / Pause function for Howler.js

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1182]
Hello:

How can I re-create this function on Howler to PLAY / STOP a single audio file using the same button or image as trigger.

function togglePlay() {
  return myAudio.paused ? myAudio.play() : myAudio.pause();
};

**Comment by rdb-github** [comment]
Hello!
According to the (Howler documentation)[https://github.com/goldfire/howler.js#examples]:

> **playing(id)**
> Check if a sound is currently playing or not, returns a ``Boolean`` (...)

So the method you were looking for is ``myAudio.playing``.

Here is that code example you sent, adapted to this method.

```js
function togglePlay(){
return myAudio.playing() ? myAudio.pause() : myAudio.play();
};
```

**Comment by Pallavi-09** [comment]
Will be great if working code is provided for better clarity of playing

**Comment by Pallavi-09** [comment]
Thanks for the reply !

Actually I set the timer to get the position of the song after every 3 sec. Post the song is paused player.pos() is giving me the normal song speed position it didn't giving me the paused song position.
so i have a doubt that song is actually getting paused or not.

Any solution for this ?

**Comment by sleepsou** [comment]
Sorry. How did you do this?

```
function togglePlay(){
return myAudio.playing() ? myAudio.pause() : myAudio.play();
};
```

Is not pausing the sound in this codepen when clicking the image, whats missing?
https://codepen.io/FunkeXMix/pen/NWbjKzr
