### ISSUE TITLE
seek() returning howler object unexpectedly

### ISSUE THREAD

**Issue by matt-way** [goldfire/howler.js#1189]
If the `seek()` function is called while audio is loaded, except the play lock is `true`, it will return the howler object instead of the current time.

https://github.com/goldfire/howler.js/blob/030db918dd8ce640afd57e172418472497e8f113/src/howler.core.js#L1579

**Comment by martinratinaud** [comment]
This happens to me also

**Comment by JetDu0319** [comment]
How to deal with this problem

**Comment by lamasfoker** [comment]
Me too

**Comment by soend** [comment]
Need help with this also.

**Comment by inear** [comment]
Same here. Plus, is it useful to add it to the _queue array if the seek call has no arguments? I have a problem where I read the time with seek() each frame to display the time, and the array keeps filling up if playLock is true. No reason to run a seek() later when playLock is false. Could even fix so any seek(time) that exists earlier in the queue for a specific sound is removed to avoid jumping all over the file later.

**Comment by inear** [comment]
My workaround since long time ago is:

```
let time = Number(this.mergedChannel.audioInstance.seek())
if (isNaN(time)) {
  time = this.mergedChannel.audioInstance._sounds[0]._seek
}
```

**Comment by TrevorHinesley** [comment]
Definitely still an issue, but @inear's workaround works great.

**Comment by DurinMusicspear** [comment]
I also have this issue, took me a while to find out what was happening!

**Comment by Rem486** [comment]
I had the same problem, especially `.wav`

**Comment by madStitcher** [comment]
This is an issue we are running up against as well. Next month this issue will be a year old!

**Comment by s16h** [comment]
@goldfire, what are you thoughts on this?

**Comment by blmage** [comment]
Shouldn't the `_playLock` flag be considered only when `seek` is a number?

**Comment by fritzfr** [comment]
Still an issue...

**Comment by andybloch** [comment]
Still seems to be an issue. (This plus a couple of other issues make me regret ever using howler.)
