### ISSUE TITLE
ReferenceError: Audio is not defined

### ISSUE THREAD

**Issue by Glutch** [goldfire/howler.js#1191]
> npm install howler

test.js
```
const {Howl, Howler} = require('howler')

var sound = new Howl({
  src: ['hello.wav']
})

sound.play()
```

output:
```
/node_modules/howler/dist/howler.js:409
      var testPlay = new Audio().play();
                     ^
ReferenceError: Audio is not defined
```

node -v 12.4.0
MacOS

**Comment by ehiskes** [comment]
Issue closed,  but it is still happening as of 10/21/2019.   How to fix it?

**Comment by nathanwfranke** [comment]
Latest is v2.1.2, which is before https://github.com/goldfire/howler.js/commit/808fe3421962b04007cc7e58b951c89572fba4ab
To use the updated version, you'll have to figure out how to build. `npm build` does not work and there is no documentation about building, so good luck

**Comment by MoffKalast** [comment]
Still an issue.
