### ISSUE TITLE
html5 looping stops looping when in background on mobile

### ISSUE THREAD

**Issue by nmegrant** [goldfire/howler.js#1193]
It appears to be caused by some timeout javascript happening behind the scenes for the seamless looping, because browsers will not execute background javascript outside of web workers.

I can work around the issue by using straight javascript calls to the audio element API with loop=true instead of using Howler.

When investigating, I saw the audio elements under `_sounds[0]._node` had loop=true, so I'm a bit confused why it's not working.

**Comment by lunatic-hombre** [comment]
Closed this because I submitted whilst logged in with the wrong account.
