### ISSUE TITLE
Skip forward feature

### ISSUE THREAD

**Issue by ManuelFrigerio** [goldfire/howler.js#1197]
Hi, I'm using Howler to create a podcast player.

I'd like the option to skip backwards and forward in the audio file but I can't seem to be able to find that option.

Also, some podcasts are hosted on servers that block CORS requests. What's the best practice in this case? Downloading it on my server and using that file with Howler?

Thanks

**Comment by janis-kra** [comment]
For skipping forward and backwards, you can do something like this (assuming you have the howl saved as `this.howl`):

``` js
    public skipForward() {
        const sound = this.howl.pause()._sounds[0];
        const currentSeek = sound._seek;
        const forwardTo = currentSeek + 30;
        const duration = this.howl.duration();
        if (forwardTo >= duration) {
            return;
        }
        console.log('skipping to ' + forwardTo + ' from ' + currentSeek);
        this.howl.seek(forwardTo);
        this.howl.play();
    }
```
