### ISSUE TITLE
Play audio based on the time

### ISSUE THREAD

**Issue by IgorRedaelli** [goldfire/howler.js#1203]
I cannot identify the parameter of the play button so that when it is pressed it does not start the audio at the beginning (0 seconds) but it starts from a precise point that would be the time practically.

I used this code earlier:

```
var audio = new Audio();
audio.src = "MI24H.mp3";
ORA_ATTUALE_IN_SECONDI=(new Date().getHours()*60*60)+(new Date().getMinutes()*60)+(new Date().getSeconds());
audio.currentTime = ORA_ATTUALE_IN_SECONDI
//audio.currentTime = 50;
audio.play();
function playAudio() {
audio.play();
}
```

**Comment by themoonrat** [comment]
https://github.com/goldfire/howler.js#seekseek-id is what you're after I believe

**Comment by IgorRedaelli** [comment]
> https://github.com/goldfire/howler.js#seekseek-id is what you're after I believe

Yes, that's exactly what I was looking for.
Do you have any idea how I can apply it?
I calculate the time in seconds or minutes and I would like the sound to always start there.
Do you have any idea how to integrate it?

**Comment by IgorRedaelli** [comment]
Nobody knows how I can do it? thank you so much

**Comment by IgorRedaelli** [comment]
I solved using the _seek_ variable in this way: 

`
TIME_IN_SECONDS=(new Date().getHours()*60*60)+(new Date().getMinutes()*60)+(new Date().getSeconds());
var seek = TIME_IN_SECONDS || 0;`
