### ISSUE TITLE
Howler + Phonegap + online streams not working within build, but whilst in development.

### ISSUE THREAD

**Issue by qroft** [goldfire/howler.js#1207]
I have created a small music player and while developing locally within the so called Phonegap Developer App, everything works smoothly.
Now i have build my app and uploaded it to the Play store.
Everything works, exxcept the audio streams.

My suggestion at the moment:
Must i include anything into my config.xml allowing the streaming?

**Comment by qroft** [comment]
**So here comes the solution.**
It indeed seems to be a CORS problem. What i had to add were these steps, in case anyone else has the same problem.

1. Install the cordova-whitelist-plugin via npm or any other of your prefered way inside your project's folder (not the www folder, but the root with all the phonegap specific folders!)
2. Add this to your config.xml file: <plugin name="cordova-plugin-whitelist" spec="1.3.4" />

Please be aware to use the correct spec version!

**Comment by NSamuelN** [comment]
Hello qroft, been looking all over for this, my cordova app's player(howler js) wont play. i have the whitelist plugin but still nothing. kindly assist
