### ISSUE TITLE
pause for some second(s) between audio files / mp3 files in the src property

### ISSUE THREAD

**Issue by handhikadj** [goldfire/howler.js#1216]
How do I pause for some seconds (e.g 10 seconds) between the audio file in the src property?

```javascript
const sound = new Howl({
                    src: ['a.mp3','b.mp3'],
                    
                });

                sound.play();
```

I want to put a delay for the second song, in this case the `b.mp3` for 10 seconds. so when the `a.mp3` reaches its end, it pauses for 10 seconds, and play the `b.mp3` aftwards

**Comment by goldfire** [comment]
Listen to the `end` event and wait before playing the next sound.
