### ISSUE TITLE
Any way to start audio without touch?

### ISSUE THREAD

**Issue by csetera** [goldfire/howler.js#1219]
I was attempting to (re)write an alarm clock application using web technologies and planning to use Chromium on Raspberry Pi to act as the alarm clock.  I was surprised to stumble on to the auto play issues.  More specifically, I was surprised I could not find any kind of command-line switches to allow auto play without user interaction first.  Obviously, it is really important that alarms are able to play for an alarm clock to be able to really be useful.  Is there any way to get around this, assuming that I have control of the browser instance being launched?  Would Electron help in any way?

Thanks for any insights.

**Comment by goldfire** [comment]
I'm pretty sure you can do it with Electron or something similar, but there isn't a way to do it from within a standard browser environment.
