### ISSUE TITLE
When to use unload? 

### ISSUE THREAD

**Issue by dorofino** [goldfire/howler.js#1222]
I'm having issues with mobile iOS Chrome (snap crash! ) and sometimes crashes on mobile Safari. 
Basically, I have 25 small Mp3 tracks(36kb-11mg) that I'm trying to mixing one after the other on user click. 

I have a couple questions. 
How many tracks I can load on initiation? 
Do I need to specify preload: false and load each on user click? 
Do I have to unload each track after the user is done mixing to free up cache? 
Do I need to set pool:25, if so where I set up a general pool? 
Im using Web Audio API because iOS does not let me control de volumen if I use HTML5. 

Any help would be greatly helpful. 
Thanks 
Diego

**Comment by goldfire** [comment]
These are all very context-based, so there isn't really a way to answer these in a general sense. Unload is helpful to free up memory, so that would certainly be one way to approach it.
