### ISSUE TITLE
How to overcome overlapping an mp3 audio stream when pressing a button twice?

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1227]
I have noticed that if I keep clicking on a button which triggers an mp3 audio file onclick="playGreeting()" .... How can I prevent Howler.js from playing it on top of each other, if the user keeps clicking the (e.g. Speaker icon) just to give you an idea.

Is there an API function which plays an audio after clicking a button, and it stops playing until the mp3 file has played completely?

or do you have a better approach without the need of a setTimeout function.

Thanks

**Comment by irongaze** [comment]
Disable the button on starting playback, re-enable using onend event.  This isn't something a sound library should handle for you.

**Comment by sanjarbek** [comment]
Disabling the button is not the solution. User can not wait for onend event and just play next track.

**Comment by oybek9508** [comment]
You can use useSound Hook if your project is React based. useSound hook uses howler behind the scene, and it has `interrupt: boolean` prop to avoid overlapping sounds and just truncates the sound once you stop it
