### ISSUE TITLE
Howler extension check broken

### ISSUE THREAD

**Issue by AshotN** [goldfire/howler.js#1248]
I think this is related to  #623

The following URL

`http://localhost:8080/play/index.php?ssid=dcf6f392e2268190992973a0ea5bfecb&type=song&oid=237&uid=1&player=api&name=Eminem%20-%20Hell%20Breaks%20Loose%20.flac`

Fails Howlers extension support check because it thinks the file extension is PHP. This line is seemingly the issue https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L657

**Comment by goldfire** [comment]
That is because .php is the extension of the file. In edge cases like this you need to specify the format yourself: https://github.com/goldfire/howler.js#format-array-.
