### ISSUE TITLE
Cannot play audio after using seek( )

### ISSUE THREAD

**Issue by frontBOI** [goldfire/howler.js#1254]
Hello,

I want to have **one and only one** audio track playing at the same time. 
Here is my implementation of a play() method (I'm sorry code tag doesn't work for the first lines) :

```javascript
function playAudio () 
{
		if (isNotNullNorUndefined(howlerPlayer)) 
		{
			const currentTimestamp = isNaN(howlerPlayer.seek()) ? 0 : howlerPlayer.seek();
			howlerPlayer.stop();

			howlerPlayer.fade(0, 1, 500);
                        howlerPlayer.play();
			howlerPlayer.seek(currentTimestamp);

		        if (this.isPaused()) {
			        console.log('yes it is paused')
			        this.playingSoundId = this.howlerPlayer.play();
			        this.howlerPlayer.seek(0);

			        if (this.isPaused())
				        console.log('it is still paused')
		        }
	}
}
```

Unfortunately, this code always logs _yes it is paused_ and _it is still paused_... But as soon as I remove the currentTimestamp calculation, the code works like a charm. Any idea why ?

**Comment by blakyris** [comment]
What is the format of the timeStamp ?

**Comment by frontBOI** [comment]
The timestamp is a float number (it is actually the returned value of seek( )
Yes I did check the headers, my audio file has no problem being retrieved. The problem seems to come from the fact that I try to seek( ) while the file isn't fully loaded. I added the security below that made my code work:
`
if (!this.hasAudioFileFinishedLoading()) {
				this.playingQueue.push(1); // will call play( ) whenever the audio file is loaded
			} else {
				const currentTimestamp = this.getCurrentTime();
				this.stopAudio();
				this.playingSoundId = this.howlerPlayer.play();
				this.howlerPlayer.seek(currentTimestamp);
			}
`

**Comment by blakyris** [comment]
You have to initialize a new Howler instance per track.
When you want to change the track you have to unload the track before playing an other.
