### ISSUE TITLE
URLs in src param concatenate - is this intended behavior?

### ISSUE THREAD

**Issue by filingroove** [goldfire/howler.js#1259]
Hi :)

It seems like I ran into something like #1098, but dropping file extensions didn't work for me
![](https://i.imgur.com/K6JRrmo.png)

My config
```javascript
{
  preload: false,
  src: ["http://air.aristocrats.fm:8000/ajazz","http://air.aristocrats.fm:8000/ajazz-128"],
  html5: true,
  volume: 1
}
```

Can't wrap my head around why this happens, docs don't have this info and they state that if there are multiple streams, the first compatible one will be used

**Comment by goldfire** [comment]
As stated in #1098, you need to use the `format` property: https://github.com/goldfire/howler.js#format-array-.

**Comment by filingroove** [comment]
@goldfire it doesn't fix it for me 

![](https://i.imgur.com/CqF0lZX.png)

**Comment by filingroove** [comment]
@goldfire 

I feel like it's the issue with docs and my understanding of how I should format my Howl configs. It's genuinely a confusing behavior – concatenating two URLs from array into one :)

**Comment by goldfire** [comment]
Can you provide your config being used?

**Comment by filingroove** [comment]
@goldfire 

https://codepen.io/filingroove/pen/OJPjbRy

I'm actually using `preload: false` and removing it fixed the issue

**Comment by Yahav** [comment]
@filingroove  that is because when you use preload true, you are calling the load function which set the _src property to a single url.
the problem lies within  the create method (for HTML5 audio):
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L2217
