### ISSUE TITLE
Playing an array of short sounds simultaneously

### ISSUE THREAD

**Issue by ceehaupt** [goldfire/howler.js#1264]
I'm trying to play an array of short sounds simultaneously, but if im trying to do a forEach function for sound = new Howl({  src: [url], loop: true }); it doesn't work. 
How can I play an array of sounds assembled on click?

**Comment by aareeph** [comment]
@ceehaupt isn't your variable `sound` being redeclared over and over again in forEach function? Can you please share complete code?

**Comment by ceehaupt** [comment]
`for (let i = 0; i < this.playBtn.length; i++) {
            this.playBtn[i].addEventListener('click', (e) => {
                e.preventDefault();

                var allSounds = [];
                var url = this.playBtn[i].nextElementSibling.getAttribute('data-audio');
                var checker = $('.js-campaign').not('.is-active').find('.js-input');

                allSounds.push(url);

                for(let a = 0; a < checker.length; a++) { 
                    if(checker[a].checked) {
                        allSounds.push(checker[a].parentNode.getAttribute('data-audio'));
                    }
                }

                var sound= [];
                for (let b=0; b < allSounds.length; b++) {
                        sound[b] = new Howl({
                        src: [allSounds[b]],
                        loop: true
                    }) 
                }

                console.log(sound);

                if(this.playBtn[i].classList.contains('is-playing')) {
                    this.playBtn[i].classList.remove('is-playing');
                    this.playBtn[i].setAttribute("title", "Play");

                } else {
                    this.playBtn[i].classList.add('is-playing');
                    this.playBtn[i].setAttribute("title", "Pause");
                }
            });
        }`

**Comment by aareeph** [comment]
@ceehaupt have you added `sound[b].play()`?

**Comment by ceehaupt** [comment]
that's the thing the play button is also the stop button so it should be in the if at the end but then it doesn't work

**Comment by aareeph** [comment]
`b` is the private variable and it's scope is within the loop. Therefore `b` is undefined when you call the play/stop method.

**Comment by ceehaupt** [comment]
That's what the console is saying!

**Comment by ceehaupt** [comment]
The problem now is that it doesn't stop the sounds when i click on the button the second time!
 ```
for (let i = 0; i < this.playBtn.length; i++) {
            this.playBtn[i].addEventListener('click', (e) => {
                e.preventDefault();

                var allSounds = [];
                var url = this.playBtn[i].nextElementSibling.getAttribute('data-audio');
                var checker = $('.js-campaign').not('.is-active').find('.js-input');

                allSounds.push(url);

                for(let a = 0; a < checker.length; a++) { 
                    if(checker[a].checked) {
                        allSounds.push(checker[a].parentNode.getAttribute('data-audio'));
                    }
                }
                var sound = [];
                allSounds.forEach(Function1);
                function Function1(currentValue, index) {
                        sound[index] = new Howl({
                        src: currentValue,
                        loop: true
                    }) 
                    return sound[index].playing() ? sound[index].stop() : sound[index].play();
                }

                if(this.playBtn[i].classList.contains('is-playing')) {
                    this.playBtn[i].classList.remove('is-playing');
                    this.playBtn[i].setAttribute("title", "Play");
                } else {
                    this.playBtn[i].classList.add('is-playing');
                    this.playBtn[i].setAttribute("title", "Pause");
                }
            });
        }
```

**Comment by ceehaupt** [comment]
same problem
