### ISSUE TITLE
Why does an error occur during a delayed call?Only iOS!

### ISSUE THREAD

**Issue by Eacolt** [goldfire/howler.js#1269]
Hi everyone, I have a problem for help ! I want to use DOM Audio on IOS Device , (not WebAudio), when it called on delayed function, an error log appears , eg: 
`
var myaudio = new Howl({
    src:["bomb.mp3"],
    html5:true // this is must be a DOM Audio, not WebAudio
});
setTimeout(()=>{
   myaudio.play();  // here are error  appears
}, 3000);
`
here is  error information :
Playback was unable to start. This is most commonly an issue on mobile devices and Chrome where playback was not within a user interaction.

So what should I do??

**Comment by themoonrat** [comment]
You must call 'play' after a user interaction, such as a click or a touchstart. You can't just create sound and then play it automatically. It started with just iOS, but all browsers are moving to this requirement.

Blame those making annoying ads that automatically play sounds when you loaded a page. This is to combat that. There's no way around it.

**Comment by Eacolt** [comment]
> You must call 'play' after a user interaction, such as a click or a touchstart. You can't just create sound and then play it automatically. It started with just iOS, but all browsers are moving to this requirement.
> 
> Blame those making annoying ads that automatically play sounds when you loaded a page. This is to combat that. There's no way around it.

So it is thank you !
