### ISSUE TITLE
Does Howler support audio file name in language other than English like Spanish?

### ISSUE THREAD

**Issue by Shivam-code95** [goldfire/howler.js#1270]
The project I am working on have audio files with Spanish text, example : qué.mp3.
Howler seems to encode the Spanish part of the text which cause it to not find the correct audio file from repository? Is there any way that howler does not encode this text and support Spanish text also?

**Comment by davidecampello** [comment]
Hi, I'm using Howler into a Ionic app that play files with spanish name like Afinação.mp3 so I think It work
