### ISSUE TITLE
ReferenceError: Howl is not defined

### ISSUE THREAD

**Issue by Suhail** [goldfire/howler.js#1277]
I did: `yarn add howler`

```
$ node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> const {Howl, Howler} = require('howler');
Thrown:
ReferenceError: Howl is not defined
    at /Users/suhail/Desktop/workspace/cloudbox/examples/audio-capture/node_modules/howler/dist/howler.js:2640:3

```

$ yarn --version
1.21.1

"howler": "^2.1.3",

macOS 10.14.6

Did a simple clean test: https://www.dropbox.com/s/sjd9j97s5omjgjq/Screenshot%202020-01-31%2012.21.40.png?dl=0

**Comment by TheOddler** [comment]
I just got this as well, I used yarn as well.
