### ISSUE TITLE
Calling stop() causes bugs

### ISSUE THREAD

**Issue by HernanZh** [goldfire/howler.js#128]
There's a big issue when calling the stop() method of the Howl object.
Howl.play() has a setTimeout which will run regardless if you called stop() before. This in itself is bad, but it gets worse. Inside setTimeout the following things happen:
self._nodeById(data.id).paused = true;
self._nodeById(data.id)._pos = 0;

Between the time you call stop() and the callback of setTimeout, there is a chance _drainPool  happens. The node disappears and _nodeById returns self._audioNode[0](_nodeById handles this completely wrongly, it should return null or something when you can't find the node!)

Result: a completely random sound is marked as inactive and overwritten by the next sound.

Workaround: stop has parameters id and timerId. However, timerId is defined inside a function scope inside setTimeout. There is no clean way of getting this timerId other than grabbing it from _onendTimer array. So you will need to store this timerId right after playing the sound and pass it back to stop() when you call it.

**Comment by JacoBotha** [comment]
I am still experiencing this problem, when a sound gets stopped to quickly it never stops.  Has it been fixed?

**Comment by goldfire** [comment]
@JacoBotha Are you using 1.x or 2.0?

**Comment by JacoBotha** [comment]
I am using 2.0

**Comment by goldfire** [comment]
@JacoBotha Can you provide a code sample? I'm not able to reproduce the above issue in the latest 2.0.
