### ISSUE TITLE
Howto get simple stereo panning

### ISSUE THREAD

**Issue by pbc278** [goldfire/howler.js#1281]
Hi,

I have a slider
`<input type="range" min="-1" max="1" step="0.1" value="" id="pan1" oninput="updatePanning(this.value, sound1)">`
It passes a value to the **stereo** method...

```
updatePanning = function(value, id) {
var v =  parseFloat(value);
id.stereo(v);
}
```
this works on PC-chrome but on ios-Mobile browser(Safari or Chrome) it's setting the value to iether -1, 0 or 1 not anything in between like 0.68 or -0.23
What am I doing wrong?

**Comment by goldfire** [comment]
Closing since this isn't related to howler.js.
