### ISSUE TITLE
Which formats are best for sprites on Mobile? (Web Audio API only)

### ISSUE THREAD

**Issue by chadananda** [goldfire/howler.js#1282]
I'm doing a Chrome/PWA app for mobile and noticed that `.m4a` has very poor sprite accuracy on Android -- often overplaying by a second.  So I switched to `.mp3` and `.webm` to see if they were better on Android/Chrome but weirdly they did not seem to output audio at all. (Although they all work perfectly fine on desktop)

Short of bloating downloads with .wav files, is there any format which works well for Web Audio API sprites? At present I'm only targeting Chrome since it has good Android support for PWA.

**Comment by themoonrat** [comment]
I've found m4a to be much more accurate than mp3s, especially when it comes to looping. Our games have a combination of m4a and ogg, and not had an issue with audio sprite seeking at all. Our audio sprites can reach 3 or 4 minutes worth of audio, and vary from short sharp sounds to longer background music. 

What kind of sounds are you atlassing? Using which tool? If overplaying is the only issue, then couldn't you increase the padding when atlassing the audio?

**Comment by chadananda** [comment]
Yes, I started with m4a because the internal timing seems more accurate (I'm mapping actions to partial-second audio timing within sprites). Unfortunately, my sprites are clipped out of larger audio segments so I am not atlassing together files and therefore cannot add padding to make up for overplay.  I just need to find a solution that plays a sprite accurately and does not overplay. 

I suppose I'll have to watch the expected sprite endpoint with an animation frame and mute the sprite when it goes over it's endpoint. I hope the player responds fast enough to make that work. It seems wrong that I have to do this.

**Comment by themoonrat** [comment]
Unfortunately, accurate timing is not one of the webs strong points :(

**Comment by goldfire** [comment]
If you are seeing sprites off by such a wide margin I would think there is something wrong with how you are generating the files. We use a combination of webm and mp3 and they are synced perfectly with animations, including on Android.

**Comment by ajfarkas** [comment]
I see this problem as well. My team has been working hard on finding the right padding to handle the inaccuracy, which is over 150ms in some instances. The real trouble is the inconsistency between desktop and mobile. When we find sprite length and padding combination that works on desktop, it's off by over a syllable in just about any language we're using.

I notice that the start time on our mp3's are not zero, and have been using `ffprobe` to find that time and account for it, but even with that, I find that adding 100ms of slug doesn't resolve the alignment issues. I assume this has to do with the tool I'm using to concatenate the files (`fluent-ffmpeg`), but the sprite creation method can't account for the discrepancy in mobile and desktop.

The other thing to note is that the misalignment is _consistent_ by platform: when desktop is aligned, it stays aligned through all builds, but mobile is off by 120ms every time until I make a new adjustment. This would make sense as a "javascript gonna javascript" problem if it were arbitrary, but it's not (and the large differences aren't accounted for by JS's rounding errors, anyway). I can't find anything in Howler that would cause this, but I also can't find anything outside of Howler that would cause this.
