### ISSUE TITLE
Question: FadeIn / FadeOut HTML Live Audio

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1292]
Does the FadeIn or FadeOut work with LIVE Stream (eg. Shoutcast URL's) ?

Or can a trick be implemented using ontimeout with volume set ?

Regards

**Comment by inglesuniversal** [comment]
I would like to add to my question if audio can be restarted while leaving my Wi-Fi network and reconnect on the street while using my carrier's 4G network.

It typically stops and no error is shown in console.

Best regards

**Comment by goldfire** [comment]
Yes, fading just changes the volume, so there shouldn't be any issue with it on live audio.
