### ISSUE TITLE
Playing mutliple sounds

### ISSUE THREAD

**Issue by alalfakawma** [goldfire/howler.js#1300]
I have a problem playing multiple sounds, even if I follow exactly what is written in the README file. I have a pool of sounds - 
```
    const howl = new Howl({
        src: [s1, s2, s3]
    });
```
How should I be able to first play s1, then s2, then s3 and so on? I'm really not sure about how to go about doing this. What do I do to play them in succession, when one finishes, I play the other. Something like that. I would be very happy if someone would be able to give me some tips regarding this.

EDIT: I keep getting only a single ID even though I pass in multiple sounds.

**Comment by themoonrat** [comment]
In src: this is the sounds for each of the different formats, such as mp3, m4a, ogg etc, not the source for each individual sound.

If you had a sound sprite created, then you could do something like

```
const sounds = new Howl({
  src: ['sounds.webm', 'sounds.mp3'],
  sprite: {
    blast: [0, 3000],
    laser: [4000, 1000],
    winner: [6000, 5000]
  }
});

// play the laser sound, and when it ends, play the blast sound
const id = sounds.play('laser');
sounds.on( 'end', () => { 
  sounds.play('blast') 
}, id );
```
