### ISSUE TITLE
Doesn't autoplay on mobile?

### ISSUE THREAD

**Issue by Maadtin** [goldfire/howler.js#1303]
Hello Im trying to autoplay a sound on page load, im following the example given in the docs but it isn't working.

Could anyone help me? im trying to use this in a react app with the following code:

```
useEffect(() => {
        let sound = new Howl({
            src: `audio.mp3`,
            onplayerror: function() {
                sound.once('unlock', function() {
                    sound.play();
                });
            }
        });
        sound.play();
    }, []);
```

This works perfectly fine on desktop, the only problem mobile. both chrome and safari.

Please I need some help..Thanks!

**Comment by themoonrat** [comment]
You need a user interaction to initially play sound. You can't just auto trigger it on a page load. There is no way around this.
