### ISSUE TITLE
HowlerJS not working on Edge.

### ISSUE THREAD

**Issue by alucardu** [goldfire/howler.js#1304]
I'm trying to get HowlerJS play a sound file on Microsoft Edge but it doesn't seem to work.

Microsoft Edge version:
    Microsoft Edge 44.18362.449.0
    Microsoft EdgeHTML 18.18363

HowerJS version:
https://github.com/goldfire/howler.js/blob/master/dist/howler.js

My script:

        HowerJs
        <script src="Scripts/Javascript/howerljs/howler.js"></script>
        <div onclick="play()">Click</div>
        <script>
            var sound = new Howl({
                src: ['Scripts/Javascript/howerljs/file_example_OOG_1MG.ogg']
            });
            function play() {
                console.log('play', sound);
                sound.play();
            }
        </script>

The log in Chrome:
![image](https://user-images.githubusercontent.com/779921/76946801-e0c4c900-6904-11ea-982f-cd7b12c919f8.png)

The log in Edge:
![image](https://user-images.githubusercontent.com/779921/76946837-f33f0280-6904-11ea-84dc-366b588ea4dc.png)

HowlerJS demo's are also not working on Edge:
![image](https://user-images.githubusercontent.com/779921/76946963-2e413600-6905-11ea-8e25-bc3786546ca6.png)

**Comment by davidholyko** [comment]
I'm having the same issue! Has any progress been done with this?

**Comment by goldfire** [comment]
I'm still unable to replicate this, but I'll reopen if you are still having this issue.
