### ISSUE TITLE
[Question] Best "place" to handle the howler sound object in a Vue application?

### ISSUE THREAD

**Issue by rowild** [goldfire/howler.js#1306]
I use a sound sprite for playing piano sounds in a Vue app. Meanwhile the app is split up in various components and since all those components talk to the sound object somehow, I need to find a good way to place the Howler object, but so far I didn't succeed.

After trying out App.vue, which lead to a "props and emit" hell on the various components, I ended up placing the Howler sound object on the state of a vuex store. But that does not feel right, either, because `onload` or `onloaderror` call functions that live on the store, too. And `volume` is also a global value on the store that howler should use.

This all feels very strange and not correct at all. I wonder if anybody could advise on how to properly approach this problem.

A code excerpt:

```javascript
export default new Vuex.Store({
  state: {
    activeKey: '',
    activeSoundfile: '/sounds/piano.mp3',
    activeSoundfileSpriteDuration: 3000,
    activeSoundfileStartTimeIndex: 0,
    globalVolume: 0.25,
    howlerSoundObj: new Howl({
      src: ['/sounds/piano.mp3'], // <== should be taken from the state property `activeSoundfile`
      autoplay: false,
      volume: 0.25,
      onload () {
        commit('SET_LOADING_SOUND', false) // <== committing from state?
        // create Sprites
        dispatch('createSoundSprites') // <== dispatching from state?
      },
      onloaderror (id, error) {
        commit('SET_LOADING_SOUND', false) // <== committing from state?
      },
      onplay (id) {
        console.log('soundfile ' + activeSoundfile + ' playing, id =', id)
      }
    }), // [etc ...]
```

I should mention that I am currently thinking that, when using a soundSprite and therefore the HTML5 audio element, there should be one central place, where the Howler Sound Object is initially instantiated and re-used further on, as opposed to the idea of creating a new instance each and every time a piano key is hit. Maybe this thinking is wrong?

**Comment by goldfire** [comment]
Maybe take a look at how the vue-howler module did it? https://github.com/mickdekkers/vue-howler
