### ISSUE TITLE
I can't stop all sounds in one web page

### ISSUE THREAD

**Issue by jkiss** [goldfire/howler.js#1308]
I init some sounds in one web page, I want other sounds will stop when I playing the one, BUT I can't find a global method to do it

**Comment by abrehamgezahegn** [comment]
Same problem here. Can someone work on `Howler.stop()` and `Howler.pause()` please?

**Comment by goldfire** [comment]
The global `Howler` methods are still working in my testing. Can you provide a sample of where they aren't working?

**Comment by abrehamgezahegn** [comment]
`Howler.stop()`, seems like there is no such method. And thanks for the quick response.

**Comment by goldfire** [comment]
Sorry, I misunderstood what you were asking. These would be easy to add, though the only thing to keep in mind is that I'm not sure there would be a way to add a global play/resume method if you stop/pause globally.

**Comment by bootleg-icarus** [comment]
So, is Howler.stop() available or not? 
the docs say it is but I cant find it, is it in development at the moment?

**Comment by jkiss** [comment]
@bootleg-icarus I have seen v2.2.0 include this feature released 4 days ago 🤣

**Comment by gtolarc** [comment]
Howler.stop() is not found in "@types/howler": "^2.2.0"

**Comment by JPilson** [comment]
I have updated to version 2.2.0 but still the same behavior "player.stop();" It does not stop the loading process so I'm still having 2 songs playing.
I'm using howler for My streaming Web App 
```javascript
playSong(){
player = data.howl = new Howl({
          src:[data.url],
          html5:true,
          autoUnlock:true,
          onplay:()=>{
          this.isPlaying = true;
            this.isBufferingSong =false;
            this.setMediaSessionData();
            this.setSongDuration( parseInt(this.currentSong.howl.duration))
          },
          onload:()=>{
            window.audio = player;
            window.commit('setAudioLoaded', { loaded: true })
          },);
     } 
 player.play();
}

nextSong:function(){
      let playListSize = this.playableList.length-1;
      if( this.currentSongIndex < playListSize){
        let player = this.currentSong.howl;
        if (player) player.stop(); // This is where the Audio should be stoped 
        this.isPlaying =false;
        this.currentSongIndex++;
        this.playSong();
}
```
