### ISSUE TITLE
Streaming Sprites

### ISSUE THREAD

**Issue by biellls** [goldfire/howler.js#1310]
I've seen that sprites need to come from the same audio file, with a start and length. Is it possible to have sprites from different audio sources (like streams)?

I'm trying to have two sound streams playing all the time but I want to be able to change their position while they are playing. If there's a way to do that without sprites please let me know too.

Thanks.

**Comment by themoonrat** [comment]
Sprites are for multiple sounds within the same sound file, just like you get texture atlases for multiple textures in the same image.

Just create and manage multiple Howls that have their different sources

**Comment by biellls** [comment]
Thanks @themoonrat. Also is there a way to create a howl from a MediaStream? I'm trying with `html5: true` but getting `404 (File not found)`.

```
navigator.mediaDevices.getUserMedia({
  audio: true
}).then(function (stream) {
  sound = new Howl({
    src: stream,
    html5: true,
    volume: 1.0,
  });
  console.log('New howl created')
  sound.play()
})
```

**Comment by biellls** [comment]
Created new issue and closing: https://github.com/goldfire/howler.js/issues/1314
