### ISSUE TITLE
attempting to load 32mb of .m4a files on my iPhone6 crashes every time...

### ISSUE THREAD

**Issue by patrick99e99** [goldfire/howler.js#1311]
My game loads all of my audio assets up-front, and it is a total of 37mb.

I am creating them via ffmpeg with the flags: `-c:a aac -b:a 192k`

As my game boots and begins loading, about 50% of the files get loaded and then safari auto refreshes the page and starts the process all over again, and then eventually says "A problem repeatedly occured"

**Comment by patrick99e99** [comment]
Seems others have had similar problems...

https://www.construct.net/en/forum/construct-2/closed-bugs-22/ios-safari-crashes-loading-115371

**Comment by goldfire** [comment]
If you are loading with Web Audio then you'll want to switch it to HTML5 Audio with `html5: true` as you are going to have issues loading that much into Web Audio on mobile.

**Comment by patrick99e99** [comment]
html5 audio is not an option because it can't seamlessly loop...

**Comment by themoonrat** [comment]
I'm afraid there's not much Howler can do about this. 32mb of m4a files will need to be decompressed by WebAudio into many hundreds of megs worth of memory. The iPhone 6 only has 1gb in total, so I'm not surprised the browser crashes.
