### ISSUE TITLE
Chrome (latest version) is auto switching ShoutCast links to https:

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1318]
My json file has all radio stations starting with http://

Somehow Chrome is forcing the connection under https:// so obviously the radio stations won't play on my desktop computer (macbook air)

I have no issues with Safari (desktop and mobile) or Firefox (desktop)

Best regards

Hugo

**Comment by QadiymStewart** [comment]
Any update doing it to me as well can't play on only chrome

**Comment by inglesuniversal** [comment]
Just to inform that Chrome has made tighter restrictions accessing http content such as ShoutCast on the browser. Is there a workaround or a feature that can be added to Howler.js to be able to play the radio stations without any restrictions?

**Comment by inglesuniversal** [comment]
I'd like to know if there is a workaround this issue of chrome converting shoutcast urls from http: to https:

Can howler.js have a function to force it to play with http: or do I need to set up a proxy

**Comment by goldfire** [comment]
Can you provide a test case to show this happening?
