### ISSUE TITLE
No seamless looping with html5 and sprites

### ISSUE THREAD

**Issue by sakopov** [goldfire/howler.js#1323]
I can't seem to get seamless looping to work with html5 and sprites as I see suggested in multiple places. Here's a [fiddle](https://jsfiddle.net/Lbw1csau/) with an obvious gap using html5 (30s audio loop).

If html5 is turned off the audio plays just fine as demonstrated in this [fiddle](https://jsfiddle.net/L6oyt18a/).

The problem is I really would like to use html5 instead of web audio due certain requirements. Am I doing something wrong?

Using Howler v2.1.3 and testing on latest Chrome, FF and Edge.

**Comment by goldfire** [comment]
Unfortunately, HTML5 just isn't very precise, so there is no way to guarantee perfect seamless loops. You could try tweaking the loop point in the sprite definition to eliminate the gap if that would work for your use-case.
