### ISSUE TITLE
Updating dist ?

### ISSUE THREAD

**Issue by Seblor** [goldfire/howler.js#1327]
Hello,

I starting working an a project with howler.js, and I noticed that the `dist` folder hasn't been updated for 4 months (at the time of writing), despite being pointed as the `main` files in the `package.json`.

This causes some features recently implement, like the global `stop` function to not exist.

Shouldn't it be updated ?

**Comment by goldfire** [comment]
Sorry about that, I got delayed in releasing the new version. I'm finishing up a few things on the update and should hopefully have it updated this weekend.
