### ISSUE TITLE
Error loading audio file.

### ISSUE THREAD

**Issue by oxk4r01** [goldfire/howler.js#1334]
Firefox 76.0.1
Windows 10 pro
Using Howler.js with Parcel.js and Node in visual Studio Code.

I tried to load this file in 3 different formats: mp3, ogg and webm, but I get in all cases the same error:
The buffer passed to decodeAudioData contains an unknown content type.
Error null Decoding audio data failed.

Here is some of the code and structure:
![image](https://user-images.githubusercontent.com/1032224/81581845-949b7f80-93af-11ea-93f9-3402937c5766.png)

Similar error in Chrome:
Error null Decoding audio data failed.

**Comment by goldfire** [comment]
Do you get the same error if you use one of the audio files in the examples?

**Comment by oxk4r01** [comment]
Yes. For example here I'm using sprite.mp3 which is one of the files in the 3d samples folder, and I'm getting same error.

![image](https://user-images.githubusercontent.com/1032224/82191789-580ddd80-98f3-11ea-8bf8-3e968a03013b.png)

**Comment by oxk4r01** [comment]
???

**Comment by goldfire** [comment]
Are you able to replicate in a codepen? I don't see anything from what you've posted to go off of.

**Comment by metmac** [comment]
This is an old thread here but @oxk4r01 you need to construct a URL first for parcel to copy/build your static audio assets properly. Like so:
```
let soundFile = new URL("../static/some-sound.wav", import.meta.url)
const sound = new Howl({
    src: [soundFile],
    html5: true
});
sound.volume(0.4);
```

**Comment by hypervillain** [comment]
@metmac Probably more `soundFile.href`
