### ISSUE TITLE
stop method added recently is not available in npm package

### ISSUE THREAD

**Issue by retedys** [goldfire/howler.js#1337]
Firstly, lovely stuff you did with howler.js.

About the issue, I think it's just a publishing issue and maybe you forgot to push it to npm.
https://github.com/goldfire/howler.js/commit/e2b72fe720628cbdcfa12eb65603aafb0667c895
This above commit has the method that I'm looking for but it's not on npm apparently because I used howler with
`npm install`

Glad to share any additional info you may need regarding this, thanks.

**Comment by goldfire** [comment]
Yes, sorry about that. I had a few more issues I wanted to get into that release and I got busier over the last few weeks than expected. I should have the version finished and pushed to npm hopefully this weekend.

**Comment by retedys** [comment]
Thanks for the update! tbh, eagerly waiting for that then ;)
