### ISSUE TITLE
Pause/Stop not working on CocoonJS when using  HTML5 Audio

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#136]
Once the #133 patch is applied to the current 1.1.18 version,  the pause()` and `stop()` function are not working when using  the Accelerated Canvas/WebGL view in cocoonJS (that specific view does not support the web audio API , but only HTML5 Audio)

When using the webView (that uses the iOS system web audio API) everything is fine, and this is also fully working on desktop when forcing audio to HTML5 Audio (through the browser settings).

I'm not sure that this is a bug in Howler however, but seeing all the fix mentioned in #133, I do prefer to have a ticket opened here to ensure it has the proper attention/focus.

thanks !

**Comment by goldfire** [comment]
Has anyone tried this lately? Trying to figure out if this is still an issue or not, especially in 2.0.

**Comment by calclavia** [comment]
I can't get sounds to work currently on CocoonJS with the latest Howler
