### ISSUE TITLE
Fade in/out sometimes never resolves

### ISSUE THREAD

**Issue by alvov** [goldfire/howler.js#1368]
There can be a case when fading in/out will never resolve. 

Inside `_startFadeInterval` method `vol` is first clamped to the `to` value, and then is rounded:
```javascript 
        // Make sure the volume is in the right bounds.
        if (diff < 0) {
          vol = Math.max(to, vol);
        } else {
          vol = Math.min(to, vol);
        }

        // Round to within 2 decimal points.
        vol = Math.round(vol * 100) / 100;
```
In case `to` is a float like `0.901`, then `vol` might first be assigned with `0.901`, and then rounded to `0.9`. After that the `vol >= to` check would fail, and runtime would fall into infinite loop.

I assume this could be fixed by moving rounding higher above the clamping part.

**Comment by goldfire** [comment]
Nice catch, thanks for the PR!
