### ISSUE TITLE
Is there a list of error codes anywhere

### ISSUE THREAD

**Issue by paulrosen** [goldfire/howler.js#1370]
A customer got a `onloaderror` when trying to load an mp3 into howler. All I know is that it returned the error code "3". I've been looking everywhere I can think to find a list of those error codes but I haven't found it.

If you point me to the error code list I will do a pull request to put them in the docs next to the onloaderror entry.

**Comment by goldfire** [comment]
The docs have been updated with this at: https://github.com/goldfire/howler.js#onloaderror-function

**Comment by fromage9747** [comment]
@goldfire Any chance expanding on this?  For example Error codes 1013, 1001, 1002 are produced from the onloaderror and I would like to know what they mean so that I can handle them. 

Cheers.
