### ISSUE TITLE
Setting Authorization header doesn't seem to be working

### ISSUE THREAD

**Issue by madStitcher** [goldfire/howler.js#1377]
If I set an Authorization header, such as this...
```
    this.howl = new Howl({
      xhr: {
        method: 'GET',
        headers: {
          Authorization: 'Bearer:' + this.store.state.auth.token,
        },
        withCredentials: true,
      }...,
```

And then I inspect the request for the audio file, the authorization header is not present. I can inspect the Howl object, and see that the _xhr.headers.Authorization is set correctly. withCredentials is set correctly. But, the request itself has no sign of an authorization header. 

In fact, when I try to just change the request to a post using the code in the documentation...

```
    this.howl = new Howl({
      xhr: {
        method: 'POST',
      },
      html5: true,
      ...
```

The request is still a GET, like the xhr property isn't being respected at all. I'm not sure what I'm missing.

Expected Behavior: The Authorization header gets added to the request. 

Version:  2.2.0

**Comment by adduc** [comment]
Did you try using a space between Bearer and the token instead of a colon? Most web servers expect bearer tokens to be provided in the format `Authorization: Bearer <token>`, not `Authorization: Bearer: <token>`

**Comment by jcvegan** [comment]
Having same issue.

This issue only happens when you set the option html5 to true.

**Comment by goldfire** [comment]
As noted in the docs, the `xhr` property only works with Web Audio. An HTML5 Audio request doesn't use XHR.
