### ISSUE TITLE
WEIRD: unload() works with the first half but fails for the second half of the sounds in the array

### ISSUE THREAD

**Issue by The-Linguist** [goldfire/howler.js#1378]
There are 10 different sounds in the app (short sounds for button clicks etc).
User makes progress and at some point I want to unload the sounds that are not needed anymore (in this case the last 6 of them).
I try
```
for (let i = 4; i < Howler._howls.length; i++) {
    Howler._howls[i].unload();
    console.log(Howler._howls.length);
  }
```
console output in Chrome says,
```
9
8
7
Uncaught TypeError: Cannot read property 'unload' of undefined
15
```
What could actually be happening? Any ideas?

**Comment by Shubham-Thackeray** [comment]
for (let i = Howler._howls.length; i > 0; i--) {
                        Howler._howls[i - 1].unload();
                        console.log(Howler._howls.length);
                      }

**Comment by The-Linguist** [comment]
Thanks. That makes sense.
Nice addition to the knowledge base.
For other people note that unloading sounds one by one by hard coding is still another option that is guaranteed to work if you are not lazy, right?
