### ISSUE TITLE
How to control the number of loop play

### ISSUE THREAD

**Issue by nuangnian** [goldfire/howler.js#1380]
How to control the number of loop play

**Comment by hagopjay** [comment]
I don't think there is a loop count available.  I have dealt with that by setting the timeout to equal using length of the audio file * Amount to loop.

example if sound file is 3 seconds and you want 3 loops, then timeout = 9000 milliseconds.

setTimeout( 
             function() {  
                     sound.stop();
             }, 
             9000);
