### ISSUE TITLE
Stereo panning has no effect

### ISSUE THREAD

**Issue by NorthFred** [goldfire/howler.js#1388]
Tested on both Firefox and Chrome (latest versions), with various audio sources / mp3: it appears that the stereo panning has no effect. It doesn't have effect when setting it up when creating the Howl object, and neither does it seem to work when calling the `stereo` method.
Is this flawed, or am I using incorrect setup?

```
    this.audioByHowler = new Howl({
      src: [this.audioStream.streamURL],
      format: ['mp3'],
      autoUnlock: true,
      html5PoolSize: 1,
      autoSuspend: false,
      usingWebAudio: true,
      ctx: false,
      preload: true,
      buffer: true,
      html5: true, 
      loop: false,
      stereo: -0.65,
      volume: 0.7 
    });
```

```
this.audioByHowler.stereo(0.40);
```

**Comment by goldfire** [comment]
You have HTML5 mode turned on, which doesn't support any sort of spatialized sound.
