### ISSUE TITLE
Use Howler to stream audio and prevent downloading the file

### ISSUE THREAD

**Issue by whadaday** [goldfire/howler.js#1394]
Hello everyone,

I'm using Howler in a WordPress subscription-based platform, where you can listen to audio files. For now, there are 2 improvements:
1. If you know how to use the inspector, you are able to download the audio file directly, since the files are stored in the WordPress uploads folder
2. Some files are a bit laggy

I was wondering if you know some solutions to these improvements. I was thinking (if possible) to use Soundcloud to host the audio files. 

Please let me know your thoughts. Thank you so much for your time.
All the best!

**Comment by jacobraccuia** [comment]
You need to host your files on a CDN to improve the lag.  Soundcloud could work.  Neither issue is related to Howler. 

If you use AWS S3 for your CDN, you can sign the URLS and prevent them from being accessible outside of your origin.
