### ISSUE TITLE
Channel gain

### ISSUE THREAD

**Issue by Chriztiaan** [goldfire/howler.js#1397]
Is there a way to modify a specific channel's gain/volume?

**Comment by Chriztiaan** [comment]
It's really easy. Grab the masterGain, disconnect it's destination. Then just follow the Web Audio APIs documentation. Howler exposes the correct instance.

**Comment by azael-leal** [comment]
Hello, @Chriztiaan.

I followed the Web Audio APIs documentation and I was able to split the channels and change the volume, but now I'm trying to do the same with Howler but I can't, can you help me with an example, please?
