### ISSUE TITLE
seek() is not set on chrome browser 

### ISSUE THREAD

**Issue by thisispooya** [goldfire/howler.js#1403]
track.seek(10) does not set in the Chrome browser and the sound starts from zero, but in the Firefox browser the sound starts from 10 seconds. please guide me. In the Chrome browser, the sound resumes even when paused and played again.
$('.music-list-player .play-btn').on('click', function () { //'It happens by Click the list play Button

**I tried different methods but my problem was not solved**
 ```
$('.play').on('click', function(){
            track = new Howl({
                src: '/uploads/tracks/test.mp3',
                html5: true,
                volume: 1,
            });
            track.load();
            track.seek(10);
            track.play()
})
```

**Comment by goldfire** [comment]
You shouldn't be setting up the`new Howl` inside the play button.

```javascript
track = new Howl({
    src: '/uploads/tracks/test.mp3',
    html5: true,
    volume: 1,
});

$('.play').on('click', function(){
    track.play();
    track.seek(10);
})
```
