### ISSUE TITLE
2 missing features that would be nice having

### ISSUE THREAD

**Issue by FreddyCrugger** [goldfire/howler.js#1405]
Hello,

I have noticed that 2 really good features missing in your script:

-Joining multiple sounds into 1 file.
-Adding a sound on the top of another one(watermark) while setting a pause between the watermark.

It would be great having these :-)

**Comment by goldfire** [comment]
I recommend checking out https://github.com/tonistiigi/audiosprite.

**Comment by FreddyCrugger** [comment]
Nice!

Thank you so much :-)
