### ISSUE TITLE
Howler.js 2.2.0 won't play on Safari Mac OS or Safari iOS 14

### ISSUE THREAD

**Issue by inglesuniversal** [goldfire/howler.js#1406]
Sample LINK provided below:

[https://inglesuniversal.com/share/?r=20201007094154638](url)

It was working fine until apple updated Safari on both Mac and iOS 14.0.1

No errors shown inside Safari console

Best regards

**Comment by AitorG** [comment]
Having the same issue here, at least in iOS 14 (could not test on Mac).

**Comment by goldfire** [comment]
Are you using WAV? If so, #1415 fixes the issue. However, the link you provided is working on Safari 14 for me.

**Comment by goldfire** [comment]
I'll close this in favor of duplicate issue #1406.

**Comment by AitorG** [comment]
I am sorry to say that sounds are still don't working on iOS 14. My sounds are WAV files, I'm using howler in master branch where you merged the solution for WAV files and sounds are still not working on iOS 14 even activating Modern Web Audio API on safari settings.

**Comment by goldfire** [comment]
@AitorG Can you provide an example? All of the examples in the repo are working fine for me when switched to WAV.

**Comment by AitorG** [comment]
My game is made in phaser and it's not easy to make and example about my code, but I do something like this:
```
this.stepSounds = [
  new Howl({
    src: ['sound/steps/23.wav'],
    volume: 1
  }), 
  new Howl({
    src: ['sound/steps/24.wav'],
    volume: 1
  })
]
```

after, when needed, I do something like 
`this.stepSounds[0].volume(0.25).play()`

I don't know if it's enought, I have iPhone Xs with iOS 14.1

**Comment by goldfire** [comment]
Are you playing after user input and with the mute switch off?

**Comment by AitorG** [comment]
Sure mate, it's a more than one year development game and always runned OK in iOS 13, I know how to make it works xD

**Comment by AitorG** [comment]
I change one resource to mp3 and it sounds fine at the same time other button plays wav sound and it does not work

**Comment by AitorG** [comment]
Ok just please forget all my comments while I'm stupid and even using this `"howler": "git://github.com/goldfire/howler.js.git#master",` on NPM dependences seems like not using ur last commit on master :-/

**Comment by goldfire** [comment]
Ah, good to hear. I'll have 2.2.1 out with that fix fairly soon, just trying to wrap up a few other issues first.

**Comment by AitorG** [comment]
Can you commit compiled files to use the #commit in npm dependence and then test in on mobile? so I could, if possible, get it working on production :)

**Comment by goldfire** [comment]
@AitorG v2.2.1 is now available on npm with this fix.

**Comment by kahoot-karl** [comment]
I'm still having problems with playing `webm` files. Is that confirmed to work with Safari 14.1? mp3 works fine
