### ISSUE TITLE
Howler.js 2.2.0 doesn't play MP3 files in Firefox 81.0.2 on Mac OS (plays fine in Chrome)

### ISSUE THREAD

**Issue by achernyavskaya** [goldfire/howler.js#1411]
We are currently working on using Howler.js for one of our projects and unfortunately .MP3 files are not playing on Firefox 81.0.2. Audio fires Play, Pause events but nothing else happens and it dies after couple of minutes. .WAV files play perfectly fine on all browsers, Chrome has no issues as well. Any recommendation will be appreciated.

**Comment by goldfire** [comment]
Can you provide a test case of the issue? I've tested all of our examples with MP3 forced on Firefox 81.0.2 on Mac and everything worked without issue.

**Comment by Ariphaos** [comment]
This appears to only be happening with html5 streaming. Firefox plays downloaded mp3s normally.
