### ISSUE TITLE
Howler.js 2.2.0 doesn't play WAV files in Safari 14

### ISSUE THREAD

**Issue by jusephe** [goldfire/howler.js#1414]
I tried to play WAV file in new Safari 14, but it does not work. I also tried to play WAV file without Howler and it works.
Here is code to reproduce the error: [https://stackblitz.com/edit/js-nclrak](https://stackblitz.com/edit/js-nclrak)
It gives this loaderror: 'No codec support for selected audio sources.'

So I dig into this and hopefully found a solution.
This method is returning empty string (i.e. false) in Safari 14: `audioTest.canPlayType('audio/wav; codecs="1"')`
So I added another option without specifying `codecs` attribute and it fixes the problem. Here is demo to test it: [https://stackblitz.com/edit/js-bvgnv8?file=index.js](https://stackblitz.com/edit/js-bvgnv8?file=index.js)

I submitted new pull request with this fix -> #1415

**Comment by goldfire** [comment]
Thanks for the PR!

**Comment by AitorG** [comment]
I am sorry to say that sounds are still not working on iOS 14. My sounds are WAV files, I'm using howler in master branch where you merged the solution for WAV files and sounds are still not working on iOS 14 even activating Modern Web Audio API on safari settings.

MP3 files are working fine. WAV files still not working
