### ISSUE TITLE
Docs are not obvious about how to stream an audio

### ISSUE THREAD

**Issue by marwan-nwh** [goldfire/howler.js#1429]
I am not sure if I am missing something. I see some issues about streaming, but it doesn't exist in the docs.
Does it require a special endpoint? Does howler support that in the first place?

I have a large music file and don't want the user to wait until the whole file is loaded.

**Comment by nzkozar** [comment]
+1 on this issue.
There is a Radio example, but zero documentation on the topic also the example is really "dry". Apart from setting the radio stream URL, no other controls are shown.

Is there a way to control how Howl sets the values of 'Range' HTTP header of file requests? By default it is always set to `bytes=0-` which signals the server that the whole file should be returned.

**Comment by kPanesar** [comment]
Streaming is supported in html5 mode only I believe. You have to manually set html5 to true when creating a Howl object. It is mentioned in the docs under html5:
![image](https://user-images.githubusercontent.com/4018041/102993971-26de3700-44ec-11eb-8238-8f561c355b4c.png)
