### ISSUE TITLE
Playback of multiple sounds at once

### ISSUE THREAD

**Issue by eeepad86** [goldfire/howler.js#1435]
hi all, i would like to try to play 2 audios at the same time and i am following this example
`
var sound = new Howl({
  src: ['sound1.mp3, 'sound2.mp3']
});

// Clear listener after first call.
sound.once('load', function(){
  sound.play();
});
`
but only sound1 is played
Where am I doing wrong ?

**Comment by sebsojeda** [comment]
The docs state that "howler.js will automatically load the first [sound] that is compatible with the current browser". If you want to play two different sounds, I suggest creating two sounds and calling `.play()` on each one: https://github.com/goldfire/howler.js#src-arraystring--required
