### ISSUE TITLE
sound.loop error

### ISSUE THREAD

**Issue by zxm1985** [goldfire/howler.js#1442]
I'm using it `sound.loop (true, soundid);` has no effect when it is used.
First `let soundid = sound.play ();` after setting `sound.loop (true, soundId);`
Once it was played, it was suspended. The problem was in the firebox desktop. Other browsers were normal.

**Comment by logaoleg** [comment]
Have the same issues. Only Firefox ^84.0 is affected

**Comment by themoonrat** [comment]
Here too. Firefox is the only effected out of the browsers on my Windows machine

**Comment by themoonrat** [comment]
2.1.x series also does not work
But 2.0.x series _does_ work in Firefox

**Comment by themoonrat** [comment]
Drilling down even further for latest version.... 
Checkout the repo, and get the 'sprite' example running - but add 
`self.sound.loop(true, id);` 
on line 73.
So after you play a sound, it'll loop. 

The first sound you click on will loop correctly in Firefox... but any subsequent presses will _not_ loop

**Comment by themoonrat** [comment]
This is because when you go through looping via '_refreshBuffer' - looping works fine. But if you go via 'loop', it does not, on Firefox, for some reason

**Comment by irongaze** [comment]
+1 - Causing issues on my WebGL-based game platform.

**Comment by arilotter** [comment]
+1 Causing issues in our WebGL-based game too.

**Comment by fagn88** [comment]
+1 Causing issues in our application

**Comment by goldfire** [comment]
Fixed with #1445.
