### ISSUE TITLE
play a section of the audio file

### ISSUE THREAD

**Issue by rodbs** [goldfire/howler.js#1450]
Is it possible with Howl to play x sec of an audio? (first x sec)

Is it possible to play:  full  duration - x seconds ? (kind of trimming end of the file)

thx

**Comment by aaronkw** [comment]
The only way I'm aware of is to define the segment as a sprite

**Comment by whimsical-sam** [comment]
Play, seek to location, poll for the playback location, call stop/mute etc when you cross the threshold you want to stop at.
