### ISSUE TITLE
firefox alsa not working with this lib

### ISSUE THREAD

**Issue by lulcat** [goldfire/howler.js#1452]
Hi it seems this lib doesn't work with firefox alsa. (linux). I have sounds on all websites except for one site, lichess.org. 

They told me you are their library for sound. Is there some way I can test, or set values or any other measures?

Or is this something I have to replace/patch out? Thank you.

Oh, testing on your "live demos" section, the first 2 worked fine, the latter two did not. 
i.e. spatial and sprites do _not_ work.

**Comment by lulcat** [comment]
bump

**Comment by goldfire** [comment]
I'm not familiar with this, what is Firefox Alsa? I couldn't find much from a quick search.

**Comment by lverona** [comment]
@goldfire ALSA is Advanced Linux Sound Architecture.

It's the standard audio framework used by many Linux distros.
https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture

**Comment by lulcat** [comment]
it IS how one has sound in linux. pulse, jack you name it all need the alsa modules, after oss being obsoleted.
the sound where howler.js is used works when 'apulse' is used. SO it is probably a firefox configuration issue, although as I said, 2/4 tests failed on your site. however with using apulse (fake pulse stubs iirc), I get sound indeed on lichess.org AND on your website, all tests. So, it means I can probably hunt this down , (and determine if it's a "mistake" on your side or on firefox'). With the knowledge of knowing it works if just properly comms between the kmods and this lib I should be able to hunt it down. I will close for now and I can let you know ( if I find it to be ff or this lib ). Cheers.
