### ISSUE TITLE
iOS doesn't honor volume = 0.0 for HTML5 audio

### ISSUE THREAD

**Issue by strygo** [goldfire/howler.js#1454]
I am using Howls for song and short audio playback. For the former, I use HTML5 audio so the entire file doesn't need to load. I am separately adjusting the respective volumes of these so that they mix properly. When disabling the song, I have been setting the volume to 0.0 for the song - this works everywhere except iOS. I've confirmed that using mute instead works as expected. A small repro is available here:

https://codepen.io/strygo/pen/bGBpOzY

**Comment by nushydude** [comment]
I dunno if this is a Howler issue. Feels more like a Safari issue. 

We had to switch to web audio for background music because of this in our web app. :(

**Comment by deltayeisson** [comment]
I am having the same issue, I have a pre-roll and a Stream, the pre-roll starts and I load the stream with volume 0 and it works as expected in android, desktop, and Mac but on iOS it starts playing with volume 1 omitting the stream.volume(0) line.

**Comment by goldfire** [comment]
Unfortunately, this is the expected behavior in iOS. I don't believe there is a workaround beyond what was mentioned, but if anyone finds one I'm happy to implement it or take a PR for it.
