### ISSUE TITLE
Trying to cross-fade audio clips

### ISSUE THREAD

**Issue by mknowlton** [goldfire/howler.js#146]
Hi there - I just recently started using howler.js and am really digging it. Great audio framework! I'm trying to work out a nice way to cross fade two different background audio files. So for instance when file1.mp3 is 1 second from being done, I start to play the file2.mp3.

I saw there is a method for getting the position of the audio being played but I can't figure out how to implement something like this. Do you have any advice or examples you would point me towards? Thanks in advance.

**Comment by mundisyum** [comment]
maybe using a window.requerstAnimation function would also work
