### ISSUE TITLE
Cannot play the mp3 file in my project directory.

### ISSUE THREAD

**Issue by vaish-vs** [goldfire/howler.js#1460]
I cannot play any of the mp3 files in the project directories. But if I use some link to an mp3 file such as a file-sample link, it works totally fine. 

Code handling playing of sound (this is in Slideone.tsx, check the image below)
```
 const sound  = new Howl({
        src: ["../music/clap.mp3"]
    });

    const handlePlay = () =>{
            sound.play()
            console.log("Playing now")
    }
```
Calling the function:
```
<IonButton onClick={handlePlay}>Click for Sound</IonButton>
```

My project directory looks like this:
![directory](https://user-images.githubusercontent.com/44785723/108394462-bf6a0c80-723a-11eb-9a5d-59a773c00040.PNG)

**Comment by Frustrated-Programmer** [comment]
???
How'd you solve this. Is it smt stupid I missed or what?

**Comment by vaish-vs** [comment]
Well, it was my own stupid mistake. It started working when I moved the audio file to the Public folder, which makes sense. I don't know why I didn't think of it before.
