### ISSUE TITLE
Unable to get howler.unload to work

### ISSUE THREAD

**Issue by DrewTheGeek** [goldfire/howler.js#1461]
https://jsfiddle.net/mkfh3cxj/1/
I know my code is incredibly simple. My understanding is that howl.unload() should stop and unload all sound. I'm using streaming audio instead of static sounds. Using sound.unload() does work fine but then I would have to unload every sound individually. 
Simply put if I have a playlist of files that I've coded manually, I looking for some kind of a single button that will just stop any sound that's playing. (using jquery library as well)
```
$("#stop0").click(function () {
	howl.unload();
	});
```

**Comment by goldfire** [comment]
You should be using `Howler.unload()` to unload all sounds. If you just want to stop them, you can also use `Howler.stop()`.
