### ISSUE TITLE
Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by anyuser** [goldfire/howler.js#1462]
When playing sounds while the window/tab is in the background, I sometimes get this error:

```
Uncaught InternalError: too much recursion
    action howler.js:1513
    _loadQueue howler.js:1922
    _loadQueue howler.js:1917
    _emit howler.js:1897
    volume howler.js:1267
    action howler.js:1235
    _loadQueue howler.js:1922
    _loadQueue howler.js:1917
    _emit howler.js:1897
    rate howler.js:1558
    action howler.js:1513
    _loadQueue howler.js:1922
    _loadQueue howler.js:1917
    _emit howler.js:1897
    volume howler.js:1267
    action howler.js:1235
    _loadQueue howler.js:1922
    _loadQueue howler.js:1917
//[...]
```

I'm playing sounds like this:

```
sound.play();
sound.rate(.8);
sound.volume(.8);
```

Any ideas how to fix that?

Version: Howler 2.2.1

**Comment by goldfire** [comment]
Do you have a more complete test case by chance?

**Comment by anyuser** [comment]
No, sorry, couldn't find a consistent way to reproduce it. I found it a few times after something (with howler sounds playing) was running in the background for a while, but reproducing always failed. Tried it for a hour or so, but no luck.
