### ISSUE TITLE
Recommendations on how to reuse sounds?

### ISSUE THREAD

**Issue by kujukuju** [goldfire/howler.js#1466]
I'm going through and trying to min-max optimize my game. Currently howler is causing some garbage collection frame stutters because each sound is required to be created, and then dropped.

I'm trying to find ways to reuse the existing sounds in a kind of object pool so that no creation or garbage collection has to happen in the game loop.

I see from the documentation that the audio is only cleaned up if it's not looping.
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L1969-L1981

Currently whenever I set up my non-looping howls to loop anyways, and on audio end, they pause the sound.

I believe this is essentially forcing all sounds to persist in memory, but pause when completed. This is what I want.

However, this method seems to be not perfectly synchronous with how the audio actually works. Certain sounds that start playing immediately will clip and cause a little bit of static right when the loop ends.

Any recommendations on how to fix this? My ultimate goal is just to reuse sounds so that howler doesn't have to do any work when I resume a currently paused sound at time 0. I'm thinking I may need to edit howler source code to add something like loop that will prevent the sound from being cleaned up, but won't restart.

**Comment by kujukuju** [comment]
My current solution to this loop end pause audio clipping problem is that, I'm not letting the howl sound end as normal (not forcing a loop), and when I want to replay it, I just resume play as if it were paused.

```
howl.seek(0, sounds[i]);
howl.volume(howl.volume(), sounds[i]);
howl.play(sounds[i]);
```

I'm not sure how correct this is. It's assuming that howler understands that an ID used potentially 10 minutes ago for this specific howl is still assigned to this specific howl even currently. This could be a very incorrect assumption that's going to lead to issues later on, and I'm not even sure if it is reusing memory at all inside the black box of howler.

**Comment by lverona** [comment]
I would like to also ask this. In my game I frequently hear sound being suddenly cut, like, stopping prematurely. I am not using looping and I assumed that the sound is cached. But based on what I'm reading here, these frame drops might have to do with the sound being unloaded.

I will try to, perhaps, make the sound longer, because currently all of my effects are really short, tiny wav files. Perhaps, adding a silent tail will allow the unloading to happen inaudibly.

**Comment by kujukuju** [comment]
You may be interested in this:
https://github.com/kujukuju/NotShitWebAudio

I don't plan to maintain it, but it's extremely simple.

It's a massively more simple web audio library. FWIW the sample code I posted above does work and I didn't have any issues, but there were enough little minor issues in the audio playback that forced me to write my own simple library. I'll close this I guess.
