### ISSUE TITLE
Decoding audio data failed

### ISSUE THREAD

**Issue by jellohouse** [goldfire/howler.js#1467]
I'm using Electron and tried with Howler versions 2.2.1 & 2.1.3

```
var sound = new Howl({
  src: ['../guitar.mp3'],
  onload: function() { console.log('song loaded!')},
  onloaderror: function(id, error) { console.log('loadError: ' + id +' - ' + error)},
});
```

I keep getting the error `Decoding audio data failed`
I tried using many different audio files including some wav files.

I also tried setting `html5: true`, then I get error `4` but I'm not sure what that means.

Is this an issue because I'm using Electron? 
Has anyone else encountered this?

**Comment by blkhwks19** [comment]
> 
> 
> I'm using Electron and tried with Howler versions 2.2.1 & 2.1.3
> 
> ```
> var sound = new Howl({
>   src: ['../guitar.mp3'],
>   onload: function() { console.log('song loaded!')},
>   onloaderror: function(id, error) { console.log('loadError: ' + id +' - ' + error)},
> });
> ```
> 
> I keep getting the error `Decoding audio data failed`
> I tried using many different audio files including some wav files.
> 
> I also tried setting `html5: true`, then I get error `4` but I'm not sure what that means.
> 
> Is this an issue because I'm using Electron?
> Has anyone else encountered this?

I'm also running into this error message while using Howler in a Vue app. Tried all the same things you did, just doesn't want to work. Exact same code as you too. Would be very interested if anyone has any thoughts on this.

**Comment by blkhwks19** [comment]
My issue was solved [here.](https://stackoverflow.com/questions/52082968/vue-js-2-vue-cannot-find-files-from-assets-folder-v-for) The problem for me was I am trying to load sounds from /src/assets. I moved them to /public/assets, then just linked to them like this: '/public/assets/sound.mp3' in my template. Stopped getting that error and everything works fine now! Hope that helps some!

**Comment by jellohouse** [comment]
Ok I got it working! A bit based of this https://github.com/goldfire/howler.js/issues/1271

In my case the audio files src are actually coming from absolute paths on the users computer. 
I solved it like this - hope it helps someone in the future!

```
import {Howl, Howler} from 'howler';
const fs = window.require('fs');

....

let filepath = /absolute/path/to/song.mp3

fs.readFile(filepath, function(err, buffer) {

    if (err) console.log(err);
    var blob = new window.Blob([new Uint8Array(buffer)]);

    var howlSource = URL.createObjectURL(blob)

    var sound = new Howl({
      src: [howlSource],
      format: [ 'ogg'],
      onload: function() { console.log('song loaded 222!') },
      onloaderror: function(id, error) { console.log('loadError 222: ' + id +' - ' + error) },
    });


  });
```

I'm not too sure why but I indeed had to specify `format: [ 'ogg']`, otherwise I was getting an error.

**Comment by sangyoo91** [comment]
I'm having the same error on Vue running in a chromium environment (not chrome). The audio doesn't work the first time it plays, but starts working on the second time .

**Comment by mitchiru** [comment]
Im having this on Chrome / iOS Monterey. However I cant use the HTML5 option because the auto play doesnt work there :)
