### ISSUE TITLE
"Decoding audio data failed" error on Safari 14.1 with WebM files

### ISSUE THREAD

**Issue by hugomartinet** [goldfire/howler.js#1476]
# Issue
Since v14.1, Safari should support WebM sound files. However I get a `Decoding audio data failed` error when trying to load a sound with Howler.

The files are linked below. The WebM file was encoded from the MP3 file using
```
ffmpeg -i ./April.mp3 -c:a libvorbis ./April.webm
```

Do you have any clue why the WebM file cannot be loaded?

Thanks a lot!

# Files (both play fine when opened in Safari 14.1)
- The original MP3 file: https://s3.eu-west-3.amazonaws.com/assets.staging.lalilo.com/en/words/April.mp3
- The encoded WebM file: https://s3.eu-west-3.amazonaws.com/assets.staging.lalilo.com/en/words/April.webm

# Sandbox (with Howler to play files)
https://codesandbox.io/s/safari-sound-bug-83xxo?file=/src/App.tsx

**Comment by Hfimy** [comment]
I also encountered this problem on ios 14.1, is there a solution?

**Comment by goldfire** [comment]
Is this only happening on Big Sur? I'm running Safari 14.1 on macOS 10.15.7 and not seeing any issues.

**Comment by hugomartinet** [comment]
I guess so since it works on Catalina.
However on Catalina, if I run
```
// On Catalina, Safari 14.1
const audio = new Audio()
audio.canPlayType('audio/webm; codecs="vorbis"') // --> returns ""
```
So even for Safari 14.1 on version earlier than Big Sur, howler loads the mp3 file

**Comment by goldfire** [comment]
Yes, it looks like only Big Sur supports Webm in Safari. I've been meaning to finally update, so this should be as good an excuse as any.

**Comment by kahoot-karl** [comment]
I can reproduce for Big Sur 11.4, Safari 14.1.1

**Comment by goldfire** [comment]
This unfortunately appears to be a bug in Safari. I've gone ahead and opened a bug report at https://bugs.webkit.org/show_bug.cgi?id=227198.

**Comment by goldfire** [comment]
I'd prefer to keep these types of hacks to a minimum, but it seemed necessary to add a check for Safari <15 and disable WebM support until this issue is resolved. That has been completed in https://github.com/goldfire/howler.js/commit/09a3b289bc78a9134d7426f27c39d728df6242c5.
