### ISSUE TITLE
Excellent project - jquery modal problem: audio stop and mute

### ISSUE THREAD

**Issue by ladysilvia** [goldfire/howler.js#1477]
Hi, I'm using jquery.modal.js [ https://github.com/kylefox/jquery-modal ]
when i close modal, the audio doesn't stop .. and if i open modal again the mp3 song overlaps the previous one.
is it possible to stop the songs when modal is closed?

**Comment by dheimoz** [comment]
Hey @ladysilvia 

I wonder if you have tried to use the stop method when the modal is closed.
https://github.com/goldfire/howler.js#stop

Cheers.
