### ISSUE TITLE
Cue Event - Callback at certain position?

### ISSUE THREAD

**Issue by EXPSTUDIOmo** [goldfire/howler.js#1479]
First of all thanks for this great library!

I couldn't find any documentation about adding cue events to sound playback.
I want to be notified (get a callback) when a sound hits a certain position, for example "if this sound reaches 2.5 secs trigger this event".

Is this possible? :) 

Thanks!

**Comment by dheimoz** [comment]
Hello @EXPSTUDIOmo 

Out of the box I do not think there is a specific method to achieve this.
However, you can set an Interval to run every second or half second and with
https://github.com/goldfire/howler.js#seekseek-id
Check you have reach the threshold.

```js SetInterval(_checkThreshold.bind(options),
			milliseconds);```

**Comment by EXPSTUDIOmo** [comment]
Hello @dheimoz ,

Thanks for the fast answer :)

Yeah thought about that workaround. Its a bit "clunky" to do it "by hand", if I want to fade in another soundfile 5 seconds before file 1 ends. But should work I guess.

Thanks!

**Comment by dheimoz** [comment]
@EXPSTUDIOmo yeah, I could not agree more that this is not the best way. Maybe you can also combine with events.

**Comment by EXPSTUDIOmo** [comment]
Already closed,
