### ISSUE TITLE
Tone file is playing with high volume .

### ISSUE THREAD

**Issue by mdascoder** [goldfire/howler.js#1482]
Hi,

 I am using the howler library to play the tone files inside my application. In the first-time tone, the volume is smooth as expected, but when I try to play it a second time it will increase the volume sound which is squeaking volume. I have tried to set the volume param offered by the library from 0 to 1 to set the volume of the tone file, but I am still experiencing the same thing.

**Comment by goldfire** [comment]
Can you provide a test case? Not much to go off of otherwise.

**Comment by mdascoder** [comment]
Hi @goldfire,

Thank you for your time!

I am attaching the Recorded Video clip for my scenario, Hope it will help you to understand the problem better .

Video link - :
https://user-images.githubusercontent.com/53813079/122003351-9b759c80-cdd0-11eb-93c3-44900ab7a45c.mp4

Problem - : When I try to play the tone for first time when it is properly downloaded by the browser it will play with original volume that is expected but when I try to play it again  when the tone file is played by the disk cache the volume of the tone is suddenly gets very high kind of squeaking sound cannot bearable . Attaching the Webpage and the tone file link below  so that if you want to try it by your own then you will do it using that  - : 

1) Webpage link - : https://3c-serverless-demo.s3.amazonaws.com/howler/tone.html
2) Tone file link - : https://3c-serverless-demo.s3.amazonaws.com/howler/tones/preview-broken.wav

Thank you in Advance !

**Comment by VertexZero** [comment]
Hi, I'm having similar issue with the latest version.
The first time a file plays, the volume is normal, but upon re-playing the same sound, the volume is louder.
In the console both master volume and file volume display initial settings.

**Comment by goldfire** [comment]
Thanks for sharing the test case! At least in this particular example, the issue is caused by using both `autoplay: true` and calling `play`, which ends up playing the sound twice over itself on the 2nd playthrough since the audio on the page has been unlocked. Just removing the `autoplay` property seems to fix the issue, though you may want to think about calling `unload()` on the prior `Howl()` as well.
