### ISSUE TITLE
Looping sounds on FireFox

### ISSUE THREAD

**Issue by aerian-darren** [goldfire/howler.js#1487]
Hi there,

I'm using this package and have had some reports of looping sounds not playing within FireFox. I've seen a commit go in that would rectify this https://github.com/goldfire/howler.js/pull/1445/commits

But as I can see it's not part of a release. Sorry to be a pain but would you know when the next release is planned?

I can confirm that for me the PR mentioned above worked when I pulled in that code on the 2.2.1 version and 2.0.4 version.

Thanks!

**Comment by goldfire** [comment]
I'll have a new version up on npm later today.
