### ISSUE TITLE
Fatal error on iOS Chrome

### ISSUE THREAD

**Issue by saltire** [goldfire/howler.js#1491]
Hi,

My app uses howler@2.2.2 and crashes on Chrome for iOS, throwing this error:
`null is not an object (evaluating 'ua.match(/Version\/(.?) /)[1]')`

which corresponds to this line: https://github.com/goldfire/howler.js/blob/4957be0dd1b473ef94e3db260914bebed2a577d6/src/howler.core.js#L271

The user agent string is: `Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.80 Mobile/15E148 Safari/604.1`

**Comment by rhummelmose** [comment]
Same issue here

**Comment by goldfire** [comment]
And this is why I always try to avoid touching the UA. I'll get a fix shortly and push up 2.2.3. Thanks for the heads up.

**Comment by saltire** [comment]
Amazing, thanks for the fast turnaround!

**Comment by rhummelmose** [comment]
Awesome, fix already live on our site. Thanks! :)
