### ISSUE TITLE
Howler.js doesn't work in Node.js

### ISSUE THREAD

**Issue by akash07k** [goldfire/howler.js#1496]
Hi there,
so, I'm trying to use howler in my node application but it is not working.
Can you please look into this?
If I run below code then it throws the error: "no audio support":
const { Howl, Howler } = require("howler");
let sound = new Howl({
src: ["sound.mp3"],
    onloaderror: (e, e2) => {
        console.log(`${e}, ${e2}`);
    },

});
sound.play();

**Comment by MCArth** [comment]
This is because node doesn't support web APIs by default. See https://stackoverflow.com/questions/33725402/why-web-audio-api-isnt-supported-in-nodejs

You could have a go with https://www.npmjs.com/package/web-audio-api but I image there would be some porting work to be done

**Comment by MCArth** [comment]
A quick search shows other issues related to Node.js - searching is always a good first step before posting an issue!

Have a look at https://github.com/goldfire/howler.js/issues/1265 😄

**Comment by akash07k** [comment]
Oh I see, so we can't use howler in commandline based node apps. actually I was trying to use it in the main process of my electron app.
> This is because node doesn't support web APIs by default. See https://stackoverflow.com/questions/33725402/why-web-audio-api-isnt-supported-in-nodejs
> 
> You could have a go with https://www.npmjs.com/package/web-audio-api but I image there would be some porting work to be done

**Comment by akash07k** [comment]
Actually I searched a lot on google but not on Github. :-)
> A quick search shows other issues related to Node.js - searching is always a good first step before posting an issue!
> 
> Have a look at #1265 😄
