### ISSUE TITLE
cannot get Frequency Data due to CORS?

### ISSUE THREAD

**Issue by tutaru99** [goldfire/howler.js#1498]
**Problem** - I am unable to get Frequency Data from the internet radio audio stream. Console log gives a CORS issue, however, I'm unsure if that's really the case. To solve the cors issue I've tried using Chrome's Allow CORS plugin just to see if it would work - it didn't. Also apparently - from Howler documentations "html5: true" should take care of CORS. Also, Since I don't have an < audio > element I cant use crossorigin="anonymous".
I've also tried using both HTTP and HTTPS internet audio stream links.

**I'm trying** - to get getByteFrequencyData from the stream in order to create an audio visualizer from the received internet radio audio.

```
 testAnalyzer() {
      var audio = new Howl({
        src: ['http://149.56.175.167:5461/;stream/1'], 
        html5: true,
        volume: 1
      });

        audio.play();
        const audioCtx = Howler.ctx;
        const audioSourceNode = audioCtx.createMediaElementSource(audio._sounds[0]._node);
        console.log('Audio CTX', audioCtx);

        const analyser = audioCtx.createAnalyser();
        console.log('Audio Source Node - ', audioSourceNode);

        analyser.fftsize = 512;
        const bufferLength = analyser.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);

        //Set up audio node network
        audioSourceNode.connect(analyser);
        analyser.connect(audioCtx.destination);

        analyser.getByteFrequencyData(dataArray)
        console.log('Frequency Data - ', dataArray)
    }

```
Output 
![console](https://user-images.githubusercontent.com/43951824/126133103-8c7b3162-96b6-4d26-9bd3-6621f62b51ab.png)

What am I doing wrong?  Why getByteFrequencyData doesn't work?

**Comment by dheimoz** [comment]
hey @tutaru99 , mind sharing with the community if you could sort the issue and if so, how did you do it?
Cheers.

**Comment by tutaru99** [comment]
@dheimoz Sure thing,
So essentially my code was wrong. In order to solve CORS and later on more different issues coming out -  I had to separate my code and create an Audio element and assign anonymous cors that way. The audio element was created through JS. 
Here is the code:, hope it helps 
```
initAudioVisualizer() {
      var AudioContext = window.AudioContext || window.webkitAudioContext;
      // Create an analyser node in the Howler WebAudio context
      var analyser = Howler.ctx.createAnalyser();
      this.audio = !this.audio
        ? Howler._html5AudioPool.slice(-1)[0]  : this.audio;
      this.audio.crossOrigin = "anonymous";
      this.sourceAudio = !this.sourceAudio ? Howler.ctx.createMediaElementSource(this.audio) : this.sourceAudio;
      this.sourceAudio.connect(analyser);
      this.frequency = new Uint8Array(analyser.frequencyBinCount);
      this.ffrequency = new Uint8Array(1);

      if (this.gainNode === null) {
 /* If we're launching audio source for the first time - create gainNode */
        Howler.ctx.createGain = Howler.ctx.createGain || Howler.ctx.createGainNode;
        var gainNode = Howler.ctx.createGain();
        gainNode.gain.setValueAtTime(1, Howler.ctx.currentTime);
        Howler.masterGain.connect(analyser);
        analyser.connect(gainNode);
        gainNode.connect(Howler.ctx.destination);
      } else {
        /* If gainNode exists, You must disconnect gainNode before connecting with a
    new one otherwise sound will get more distorted with each new station chosen/each time this method runs */
        this.gainNode.disconnect();
        Howler.ctx.createGain = Howler.ctx.createGain || Howler.ctx.createGainNode;
        gainNode = Howler.ctx.createGain();
        gainNode.gain.setValueAtTime(1, Howler.ctx.currentTime);
        Howler.masterGain.connect(analyser);
        analyser.connect(gainNode);
        gainNode.connect(Howler.ctx.destination);
      }
    },
```
I hope the code makes sense and helps you out. If you are interested in the visualizer check out my repo, that might make more sense. Cheers.

**Comment by dheimoz** [comment]
@tutaru99 thank you very much. Yes, will take a look at your repo. Thanks for sharing.
