### ISSUE TITLE
Cannot set property bufferSource of undefined

### ISSUE THREAD

**Issue by kane-mason** [goldfire/howler.js#1508]
We were looking through our error logs and found we get a **lot** of this error:

![image](https://user-images.githubusercontent.com/23186829/129333795-a2de2d54-aa6f-40d6-bc16-b8dadcc9d13f.png)

We are developing games that transition in and out of scenes, loading and unloading new audio so might be a case of refreshing the buffer for a sound that has been unloaded?

Using howler `2.0.8` and have been for probably 2 years

Errors **all** on iOS

**Comment by obiot** [comment]
I actually just upgraded to the latest version and have a similar issue, with the below exception :
`Exception with thrown value: InvalidStateError: The buffer was already set`

and with the debugger pointing to that line :
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L2177
`node.bufferSource = null;`
