### ISSUE TITLE
Change playback rate while looping

### ISSUE THREAD

**Issue by aron-elal** [goldfire/howler.js#158]
This could be useful in situations, where a samples playbackrate/pitch has to change but loop is set to true to repeat it at a steady interval.

**Comment by nickpolet** [comment]
I am also having issues getting the rate variable to work when it's changed at runtime. Running Chrome Version 39.0.2171.95 on Ubuntu 14.04. Everything else works fine for me, apart from changing rate after the sound object has been created and played.

**Comment by Bagongo** [comment]
Is it now possible to change _rate while looping?
I'd need to do this in the update function of a game I am developing...
Thanks!
