### ISSUE TITLE
`sound.play().pause()` on a playing sound does not pause the sound

### ISSUE THREAD

**Issue by namuol** [goldfire/howler.js#164]
When a sound is already playing, pausing it immediately after playing it again will not result in the sound being paused.

Example:

``` js
sound.play();
setTimeout(function () {
  sound.play().pause();
}, 100);
```

It doesn't need to be chained for this problem to occur, as long as the `play()` and `pause()` calls occur on the same event tick:

``` js
sound.play();
setTimeout(function () {
  sound.play();
  // ...as long as it happens on the same event cycle...
  sound.pause();
}, 100);
```

This occurs for me in Chromium 34 and Firefox 29 (Ubuntu).

**Comment by wmodes** [comment]
One use case is if you want to start a sound paused, but also want to get an ID number. Since play is the only core method that returns an ID, there is no other way to generate the ID to work with later.

**Comment by jeremygillespiecloutier** [comment]
I am still having this issue with the version 2.0.15
