### ISSUE TITLE
A buffered sound won't loop

### ISSUE THREAD

**Issue by ysbaddaden** [goldfire/howler.js#165]
Im trying to buffer sound samples, to reduce latency, but I found a problem : loops won't loop anymore. They do play once, the end event is fired but the sound will never be played again.

If I disable buffering, samples will loop correctly.

Update: Chromium 34.0.1847.116 Ubuntu 12.04 (260972)

**Comment by huwllewellyn** [comment]
This was my solution
```
let gasLooper;
let gasSound = new Howl({
    preload:true
  , src: require('./assets/audio/Gas-loop.mp3')
  , autoplay: true
  , volume: 0.5
  , onplay: ()=>{
    gasLooper = setTimeout(()=>{
      gasSound.play();
    },450);
  }
  , onstop: ()=>{
    clearTimeout(gasLooper);
  }
});
```
