### ISSUE TITLE
gap when audio is in loop using html5

### ISSUE THREAD

**Issue by harvindersingh5** [goldfire/howler.js#1708]
### The Problem

there is a gap at the ending of playback audio when audio is in loop while using html5 true , 
i want to remove the gap when loop is true with using html5 value's true or keeping the pitch same when playback rate changes  

### Reproduction Steps

            html5 : true,
            loop: true,
            rate: 2,
            rateVariation: 0.0,
            src: [  'https://planet-music.s3.amazonaws.com/audio_file/80751698258685.wav'  ],

### Context

i have tried preload , autoplay but not working 
but by using html5 attributes values false , the loop gap vanished  but the pitch changes while playback audio rate changes 
so i want to remove gap at the end keeping the loop attribute value's true , and keeping the pitch same while playback rate changes 

### Howler.js Version

v2.2.3

**Comment by alinav12** [comment]
@harvindersingh5  hi, have you fixed this issue somehow?
