### ISSUE TITLE
keep crash on Safari 17.5 beta

### ISSUE THREAD

**Issue by RayJi0428** [goldfire/howler.js#1714]
### The Problem

Hi, I use iOS 17.5 beta + Safari easily get crash when play multiple times, but it's fine with iOS 17.4, any idea?

### Reproducible Example

https://rayji0428.github.io/demo/howler/index.html

### Reproduction Steps

play sound with multiple times will crash, i thought there's something wrong with release audio buffer.

### Howler.js Version

v2.2.4

### Affected Browser(s)/Versiuon(s)

Safari 17.5 beta

**Comment by macguffin** [comment]
Hi I don't use howler but have also found this issue when using soundjs with an audio sprite. Looks like there is something going on with the webAudio garbage collection.

I am going to report this to webkit - would you be able to keep your link up as I will reference it in the ticket.

Thanks

**Comment by RayJi0428** [comment]
https://bugs.webkit.org/show_bug.cgi?id=273041
It's fixed in iOS 17.5 beta 3. Thanks to Apple and @macguffin !
