### ISSUE TITLE
iOS 17.4 playback issue

### ISSUE THREAD

**Issue by torbentschechne** [goldfire/howler.js#1718]
### The Problem

I experience problems with playing mp3 files with Howler since iOS 17.4. It is independent wether I use Safari or Chrome. In both cases the audio file is not played. I see a spinner which does not resolve, but I have no error in the console. 

Did anybody else ran into this issue and knows how to fix it? We use version 2.2.3. When I open the underlying mp3 link, I can play the file in the Browser.

### Reproduction Steps

Use Howler on iOS 17.4 and try to play a file.

### Howler.js Version

2.2.3

**Comment by betanyeli** [comment]
Same issue here! 
there is another issue related to this https://github.com/goldfire/howler.js/issues/1711 and some people proposed some ways to fix it. 
For me works, for now, setting the HTML attribute to false, until the lib fixes the problem.

**Comment by torbentschechne** [comment]
> Same issue here! there is another issue related to this #1711 and some people proposed some ways to fix it. For me works, for now, setting the HTML attribute to false, until the lib fixes the problem.

Yep, thanks. I found the other thread afterwards and could use the workaround. I would close this one here, as the other thread exists.
