### ISSUE TITLE
Opera GX  LVL5 (core: 109.0.5097.62) not working but Chrome, Firefox, Edge and Safari are all okay.

### ISSUE THREAD

**Issue by a4jp-com** [goldfire/howler.js#1720]
### The Problem

I pressed play but nothing happened.

### Reproducible Example

https://agreatdream.com/quiz47.php

### Reproduction Steps

Select English then Food.

### Possible Solution

No solution yet.

### Context

I like to use Opera GX.

### Howler.js Version

v2.2.3

### Affected Browser(s)/Versiuon(s)

Opera GX  LVL5 (core: 109.0.5097.62)

**Comment by a4jp-com** [comment]
Any ways to get around this bug or new versions of this software coming out soon?

**Comment by robinfriedli** [comment]
Are you using https://github.com/joshwcomeau/use-sound by any chance? Or an outdated version of howler? I had the same issue (mp3s just would not work with useSound in OperaGX, but m4a's worked fine). Then I installed howler to call howler directly to debug what is going on and suddenly it just worked on account of having a newer version of howler (2.2.4 vs 2.1.3)

**Comment by a4jp-com** [comment]
I was on v2.2.3 then updated to 2.2.4 on April 27th at 6:10am. I think it is working properly now but I'm not sure what was fixed.

**Comment by a4jp-com** [comment]
Thanks for the message @robinfriedli
