### ISSUE TITLE
Multiple sounds in a row on Internet Explorer breaks sprite

### ISSUE THREAD

**Issue by kluplau** [goldfire/howler.js#173]
Hi,

Great plugin.

If you, on Internet Explorer (I tested with IE11), go to your demo site and click on the "Play 'blast'" button once, everything is fine. But if you spam the button twice or more, it will break the audio sprite and play the entire audio file.

Is this a new issue I can resolve by downgrading, or has this always been like that?

**Comment by fsrojash** [comment]
Apparently this issue is still affecting IE11, my game has some problems with multiple sounds (sprite sounds) only on IE11. It breaks the audio sprite and play the entire audio file.

**Comment by AleksandarMIlenkovic** [comment]
This issue is still happening to me on IE11:/
