### ISSUE TITLE
script for generating sprites for howler

### ISSUE THREAD

**Issue by gingerlime** [goldfire/howler.js#19]
howdy!

We're playing around with howler, and it's really sweet.

What we're currently trying to work out however is how to generate an mp3 sprite and timing info most effectively. We have a bunch of small mp3s that we'd like to bunch together, and also probably generate a json or a dictionary to fit in the the `new Howl` statement.

Any suggestions on external tools (preferably in linux bash / python / ruby environment)?

**Comment by Benraay** [comment]
Hi I found one over here : https://github.com/tonistiigi/audiosprite
did someone test it ?

**Comment by goldfire** [comment]
@Benraay Yes, we use this with our own projects and it works great.

**Comment by Benraay** [comment]
ok Thanks I'm writing a script using it it's working well ! thanks !
