### ISSUE TITLE
IE11, how to detect disabled audio?

### ISSUE THREAD

**Issue by whizzkid** [goldfire/howler.js#207]
when you use IE11 and have your  internet options/advanced/multimedia/"play sounds in webpages"
turned OFF,   howler doesn't work. loading audio files just doesn't happen, no error triggered etc.

I'm using a workaround like this now

```javascript
var tmp = new Audio()
if (tmp.muted)
{
 // no audio, dont load samples
}
else
{
   new Howl(... etc
}
```

I don't know if this is the correct way of checking if audio is enabled, but it works in my project :)

you can also use an <audio> tag, load a sample and then check for the error property. (but that would load an unneccesary sample when audio is enabled, which I don't like)

It would be nice if howler can also detect this.

**Comment by goldfire** [comment]
This check has been added in c7cd9961315c4b593b6c69674d2b8d055111b122.
