### ISSUE TITLE
Sound playback isn't canceled if .stop() is called before the sound is played.

### ISSUE THREAD

**Issue by peat-psuwit** [goldfire/howler.js#209]
Steps to reproduce:
1. Open about:blank in Google Chrome
2. Open "Developer console", click "Network" tab, then tick "Disable cache". (This simulate the situation that may delay the playback.)
3. Press "Esc" to open console, and type following command in order:
- document.write('<script src="https://rawgit.com/goldfire/howler.js/2.0/howler.min.js"></script>');
- var aaaa = new Howl({src:["http://www.peat-network.ga/LittleHistorian/levelAssets/1/q1-2-slow.m4a"], html5: true});
- aaaa.play();
- aaaa.stop(); **//Type this one before sound start playing**

Expected result:
Sound playback is canceled. No sound should be played back.

Actual result:
Sound will be eventually played back when the file is downloaded.

**Comment by gilesbutler** [comment]
I have this same issue, I'm loading src files from an API and if I click on multiple items they all start playing over the top of each other when each file has finished loading. I'm on the 2.0 branch as well.
