### ISSUE TITLE
First load of audio causes it to play twice if invoking .play().

### ISSUE THREAD

**Issue by agamemnus** [goldfire/howler.js#213]
37.0.2062.120 m (64-bit)

1) Clear your Chrome cache.
2) Play an audio file. (mp3 in my case, and autoplay set to true)
3) Run play on it... it will play twice.

This only happens on first load.

Workaround: run .pause (), then .play ().

**Comment by awingit** [comment]
I am experiencing the same issue. This plays the audio twice, slightly overlapped:
const audio = new Howl({
			src: src,
			autoplay: true,
			loop: false,
			pool: 1,
			volume: 0.3
		});

Very basic, so no idea why....

**Comment by pitops** [comment]
Hey got same issue any fix? @awingit
