### ISSUE TITLE
HowlerJS & Phonegap +3.0 seed? (Android, iOS, Win)

### ISSUE THREAD

**Issue by hugolpz** [goldfire/howler.js#224]
Are there known use cases for howlerJS use within Phonegap ?

Does it works ? What are the pitfalls ? Are there some seeds or demo projects you could share ?

See also: Stackoverflow > [Phonegap HowlerJS - Playing html5 audio from local ressource ?](http://stackoverflow.com/questions/25358169/phonegap-playing-html5-audio-from-local-ressource) ([seed](https://dl.dropboxusercontent.com/u/34209136/2014-08-18%20phonegap%20html5audio%20test.zip)), and [Audio not working with PhoneGap+Android](http://stackoverflow.com/questions/10556437/audio-not-working-with-phonegap)

**Comment by goldfire** [comment]
If the sound hasn't loaded, the `play` method should correctly add it to the queue and then play it when it has (however, there are some issues with this in 1.1.x). Has anyone tried the 2.0 branch with this?
