### ISSUE TITLE
issues with iOS stopping background music when loading webpage.

### ISSUE THREAD

**Issue by bart3r** [goldfire/howler.js#239]
I have one small audio sound I'm playing on page when someone clicks a button, but whenever someone on an iOS device loads the page it always stops the background music playing, which is a problem. I'm happy for the music to stop if they click the button and activate the sound, but not every time they just load the page.

Here is my code:

Howler.iOSAutoEnable = false;
snd=new Howl({urls:["/assets/sb.wav","/assets/sb.mp3"]})

I have also tried setting buffer=true, but this didn't make a difference.

Has anyone else had problems with howler stopping background music on Apple devices?

**Comment by jasonhibbs** [comment]
I believe the issue described above refers to music or audio from another source, such as the Music app, as I’ve landed here looking for a way around the same problem.

As a page containing Howler loads, external audio is stopped. Not sure why yet.

**Comment by tobemedia** [comment]
@goldfire As soon as I load Howler in mobile Safari the Background music (music app, ...) is stopped at iOS. Will there be a solution in 2.0?

**Comment by goldfire** [comment]
The solution is to set `Howler.mobileAutoEnable` to `false`.
