### ISSUE TITLE
Plays from wrong position using sprites on Android 4.4.4 with a Nexus 5

### ISSUE THREAD

**Issue by tobemedia** [goldfire/howler.js#243]
Hi, 

I have a very strange issue only on a nexus 5 running android 4.4.4 
within a cordova webview.

Some demo code to demonstrate the problem:

```javascript
handleClick: function() {
    if(window.p) {
        p.stop();
    }
    else {
        window.p = new Howl({
            urls: ['path/to/file_sprite.mp3'], // same problem with .ogg files
            sprite: {
                "1-4-42-116":[0,8882],
                "1-4-42-116_1":[9000,4284],
                "1-4-42-116_2":[14000,4467],
                "1-4-42-116_3":[19000,4232]
            }
        })
    }

    p.play("1-4-42-116_2"); 
}
```

On the first call of `handleClick` it seems that howler is playing from position 0, 
but on the second click it plays like it should, at `1-4-42-116_2` which means 
position `14000`.

Same problem with the current 2.0 version.

Anyone have a clue what's going on or already experienced such an issue?

**Comment by goldfire** [comment]
Unfortunately, the older Android webviews have some serious bugs with regard to returning the correct (or any) duration of audio files. The good news is that newer versions don't seem to have the same issues, but I've yet to find any sort of workaround that will work in this instance.
