### ISSUE TITLE
HowlerJS does not work with video on iOS

### ISSUE THREAD

**Issue by galinawind** [goldfire/howler.js#247]
on iOS if you have a web page with an audio file and then you dare to play a video, the audio stops working after the video completes. I have a completely self-contained example with media that I can e-mail to anyone interested in helping out with this. All you have to do is hit "play sound", the sound will play. Then hit "add video", the sound will still play. Then hit "play" on the video to play it, no autoplay, this is iOS. Then try hitting "play sound" again. You will get nothing on iPad2 and distorted, garbled sound on iPad Air. I posted the code here, but it will not work without the media files. There is nothing to the code, it's 84 lousy lines. https://gist.github.com/anonymous/c564528ef81787245dea 

If you reload the page, then everything kind of works. This is only an issue on "first entry" to the page. However having the user to navigate to a page and then reload it before they do anything else is not acceptable.

**Comment by DFortun81** [comment]
Any progress on this? The mobile QA team for our app has been pushing "garbled audio" bugs to our redmine and there really isn't anything we can do about it without directly modifying the HowlerJS library to implement the fix galinawind posted.

**Comment by goldfire** [comment]
If you want to create a new AudioContext, this is actually now built into 2.0 (sorry, forgot to reply to this). If you call `Howler.unload()``, it'll actually destroy the current AudioContext and create a new one.

**Comment by heand** [comment]
Hi, I have the same issue. If I play a video from the html5 video tag. And then start an Audiofile, the audio gets destorted on ipad (not desktop PC). I can set html5:true, but then i cannot control the file volume etc on the audio. Audio and Video are supposed to play together, this is a tool for listening training.. Any ideas?
