### ISSUE TITLE
IE9 non-sprite audio stops playing (howler.js 1.0 and 1.1)

### ISSUE THREAD

**Issue by PaulMorris** [goldfire/howler.js#25]
With both howler.js 1.0.11 and 1.1, in IE9, using non-sprite HTML5 audio, the audio clips will play at first, a few times (5?) and then will stop responding when you click to play them.  At that point different audio clips will play once each but not again.  This happens both with 1.0.11 and the most recent 1.1 branch.

I thought it might be a problem with the playback position not getting reset to 0, but it appears to be a problem with not finding an inactive node to use.  I traced it back as far this function (around line 790 in 1.0.11):

```
/**
 * Get the first inactive audio node (HTML5 audio use only).
 * If there is none, create a new one and add it to the pool.
 * @param  {Function} callback Function to call when the audio node is ready.
 */
_inactiveNode: function(callback) {
  var self = this,
    node = null;

  // find first inactive node to recycle
  for (var i=0; i<self._audioNode.length; i++) {
    if (self._audioNode[i].paused && self._audioNode[i].readyState === 4) {
      callback(self._audioNode[i]);
      node = true;
      break;
    }
  }
```

The if clause stops resolving to true and so the callback to play the audio stops getting called.  I haven't had time to test any further with it yet.  (I have to go to a library to test with IE9, which is why I didn't catch this before.)

This might have been caused by my fix for issue #15.  Before that fix non-sprite audio would also be paused on completion.  After that fix it is not paused (so that the playback position can return to zero, and not get paused/stuck at the end of the track).  So, if IE9 does not automatically set an audio clip to "paused" when it finishes playing, then that would cause this problem.  

If that's the case, here are 2 possible fixes:
1. figure out what state IE9 audio ends up in when it finishes playing, and have this if clause also check for that, in order to identify those inactive nodes.
2. revert the fix for issue #15, so that all HTML5 audio is paused upon completion, but then explicitly reset the playback position to zero if the audio is not a sprite.

I should be able to work on this a little more tomorrow.

**Comment by vincentg01** [comment]
I have recently used Howler for one of my projects, and I must say that it's a neat and nifty little JS. I am posting a comment here because I am facing a similar issue that's mentioned in this thread; but with IE10 and IE11. My project uses audio sprites and version 1.1.26 of Howler. Just wanted to know if this issue still persists with higher versions of IE as well.
