### ISSUE TITLE
Experiencing lags with setPosition

### ISSUE THREAD

**Issue by gre** [goldfire/howler.js#258]
![](http://i.imgur.com/5nkFtZA.png)

When using Howler v2 position system (Howler.pos) I'm experiencing periodic lags on Chrome as shown in the screenshot: it is quite annoying and visually noticeable because blocking the JavaScript for 160ms !

I guess it comes from [this call](https://github.com/goldfire/howler.js/blob/2.0/src/plugins/howler.effects.js#L65) to Web Audio API's `setPosition`. So I don't know if we can do anything about that..

Have you ever experienced this issue too and do you know a workaround for this? (and if so, may this workaround be used in Howler?)

I wish the audio system was not blocking the JS like this.. (I thought Web Audio API was running on another thread?)
My guess is it looks like a load issue (maybe we need to wait something before calling .setPosition ?) because it  seems to usually only happen once in my game.

![screen shot 2015-01-01 at 15 25 32](https://cloud.githubusercontent.com/assets/211411/5592341/7f159b2e-91ca-11e4-8802-65646d4f55cc.png)

Thanks

**Comment by goldfire** [comment]
Do you have any sample code for this? We are using quite a bit of spatial audio in CasinoRPG and haven't seen any performance hits from it that I've noticed.

**Comment by gre** [comment]
http://bonhomme.herokuapp.com

Using this code:
https://github.com/gre/bonhomme/blob/master/client/audio.js

When profiling I observe some freeze (some frame blocking the js for up to
100ms) coming from the setPosition webaudio function. I should try to
contact some webaudio guys if it doesn't come from any of the js code ;-)

Maybe the best it to wrap up a very tiny example to reproduce the issue.
I'll try that if you want
