### ISSUE TITLE
Not working on latest Firefox Mac

### ISSUE THREAD

**Issue by jkjwong** [goldfire/howler.js#260]
Firefox 34.

Not getting any sound at all, tried .wav, .ogg and .mp3 in combinations of standalone sounds and fallback.

I saw here you switched to using ogg first on your demos - https://github.com/goldfire/howler.js/issues/249
However even the demo page is not working.

Working fine in Chrome and Safari.

**Comment by pronebird** [comment]
Works on FF 35 / Mac.

**Comment by goldfire** [comment]
Are you still seeing this? I'm not seeing any issues on either Firefox 34 or 35 for Mac or Windows.
