### ISSUE TITLE
Sound position (using sound.seek()) continues increasing after sound has ended

### ISSUE THREAD

**Issue by TylerFisher** [goldfire/howler.js#266]
I have a sound that is approximately ~20s long, and to animate a progress bar, I am calculating the percentage complete by dividing the position received from sound.seek() by sound.duration(). I noticed that the seek position continues increasing after the sound has ended and has stopped.

(I'm using the 2.0 beta branch)

**Comment by goldfire** [comment]
Thanks, this is now fixed in the latest commit on the 2.0 branch.
