### ISSUE TITLE
Question : [2.0-beta]  Sound volume decrease with pos(-1,1,1)

### ISSUE THREAD

**Issue by tdurand** [goldfire/howler.js#267]
Hi, 

First, thanks a lot for this amazing library.

I'm working on an app and i want to dynamically spatialize a sound. 

I'm using the pos method with arguments (-1,1,1), it works great, with my earbuds i can feel the sound on the side.

But, i've noticed a small decrease of the overall volume when applying this method. Even if the arguments are < 1.0.

Is it normal ? Is there a way to have this dynamic stereo effect without having the drop of volume ?

Thanks.

Thibault

**Comment by goldfire** [comment]
Yes, this is expected. If you want to adjust that you'll need to play around with the settings in `pannerAttr`. You might want to try `equalpower` for the `panningModel`.

**Comment by tdurand** [comment]
Thanks, i've just tried with equalpower, i didn't notice much change on volume, and the panning effect feels much better with the default option HRTF ;-) .
