### ISSUE TITLE
add cdninfo

### ISSUE THREAD

**Issue by PeterDaveHello** [goldfire/howler.js#270]
HI @goldfire,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme and the website?

This is the page we provide cdn for howler.js - https://cdnjs.com/libraries/howler

Thanks!

**Comment by goldfire** [comment]
Added in 21fea99a3bb2605a4daa180cef7dde6e156846ce.

**Comment by PeterDaveHello** [comment]
Thanks @goldfire
