### ISSUE TITLE
resume html5 audio after more data is loaded?

### ISSUE THREAD

**Issue by makc** [goldfire/howler.js#271]
if it loads slower than it plays, it gets paused and not resumed back when the rest of data loads. can we do something about it?

**Comment by goldfire** [comment]
The `canplaythrough` event is *supposed* to keep that from happening. What browser are you seeing this in and do you have a test case?

**Comment by goldfire** [comment]
Based on #389, it seems like `canplaythrough` may not always work correctly. I'll update after I've done some more testing.

**Comment by makc** [comment]
Sorry did not notice your earlier message. The project was using howler, then at some time after this problem was reported, they switched to raw html audio, so I have no test case now.

**Comment by goldfire** [comment]
This is an issue with OGG. I now recommend using WebM instead.
