### ISSUE TITLE
[2.0-beta] Bug with html5:true , pos() method doesn't work

### ISSUE THREAD

**Issue by tdurand** [goldfire/howler.js#274]
Hello, 

I've noticied a bug, if you set load a sound with streaming by setting the option html5:true , the pos() method doesn't work.

Sample: 

    sound = new Howl({
          src: ['wt-pregonmandarina-boyaca-clle51-52-51Tmono.mp3'],
          html5:true,
          loop:true
        })

    sound.pos(-1,1,1); => Doesn't work, still hear it the same on the left / right earbuds
    sound.play();

If you remove html5:true, it works.

Any thoughts ?

Thanks

**Comment by goldfire** [comment]
This isn't a bug, the `pos` method is only available with the effects plugin and is only supported by Web Audio. There is no way to control spatial audio with HTML5 Audio.

**Comment by tdurand** [comment]
Apologies, you are right, hum... so , it's not possible with Web Audio API to start playing the sound without waiting the complete download ?

**Comment by goldfire** [comment]
Unfortunately, it isn't because it must download the audio file via XHR and then decode the full audio data before beginning playback.

**Comment by tdurand** [comment]
Ok, i understand, do you think in the future there will be a way to decode on the fly ?

**Comment by goldfire** [comment]
I haven't heard of anything, would be pretty handy I agree. Even if something were in the works though, you'd have to wait several years at least before you could reliably use it.

**Comment by tdurand** [comment]
Yep, was just curious , ok ! Well, will preload the sounds so ;-) . Thanks a lot !

**Comment by tdurand** [comment]
I've just see this: http://stackoverflow.com/questions/18215349/web-audio-api-mediaelementsource-node-and-soundcloud-not-working-with-effects , didn't have the time to experiment with it, but seems like you can connect an audio to web audio api when the canplaythrough event is fired. I'll do some test ;-)
