### ISSUE TITLE
Play after a second pause doesn't work

### ISSUE THREAD

**Issue by fralmei** [goldfire/howler.js#275]
I am working with branch 2.0. When a sound is paused and resumed for first time, it continues playing correctly. But if you pauses it again (without having ended since the first pause/resume) and resume it, it continues playing from a wrong position.
It seems to be due to the seek value.

**Comment by goldfire** [comment]
This appears to have been fixed in commit https://github.com/goldfire/howler.js/commit/d33e302fcf04c6dd30cac6d36ea6295ac0750a5d.

**Comment by Stanley80** [comment]
I solved the issue!!!

html5 stream becomes Seekable only if the server accepts byte ranges 

So I added the following http header

header('Accept-Ranges: bytes');
header('Content-length: '. filesize($file->getFilenameOnFilestore()));

in the php file that dynamically send a audio file
