### ISSUE TITLE
CHROME CRASH!!! Version 40.0.2214.111 m

### ISSUE THREAD

**Issue by szymonc** [goldfire/howler.js#277]
Awwww Snap! 
This is serious issue, can you fix that NOW?
Im using the the v1.1.25

**Comment by kyl2007** [comment]
https://code.google.com/p/chromium/issues/detail?id=458055
fix pls!!!

**Comment by goldfire** [comment]
Anyone have any luck narrowing this down? It seems like this must be a Chrome bug rather than an issue with the library, but I could be wrong. Also, I can't get it to happen in Canary (Chrome 42), so it may already be fixed in the upcoming Chrome update.

**Comment by AleBles** [comment]
It does seem to be a Chrome bug indeed, and from the guys over at SoundJS I saw they had some temp fix by disabling WebAudio for this specific Chrome version that crashes: http://stackoverflow.com/questions/28393885/why-would-my-app-crash-in-chrome-if-i-refresh-a-few-times/28458945#28458945.

I managed to achieve similar results by adding:
    usingWebAudio = (navigator && navigator.userAgent && navigator.userAgent.match("40.0.2214.111")) ? false : true

This is ofcourse, a temporary fix

**Comment by goldfire** [comment]
We haven't seen this at all in several weeks, is anyone else still seeing the issue (if so I'll reopen the issue)?
