### ISSUE TITLE
After sound.seek(10) position goes to 0

### ISSUE THREAD

**Issue by anajavi** [goldfire/howler.js#280]
After doing seek(10), most browsers report position from start, not the seeked position. Tested on Mac/Firefox and Safari.

Mac/Chrome gives the right position, but only when html is loaded from file-url. When loaded through http, chrome also goes to 0.

Or am I missing something?

Code:
```html
<script>
(function() {
	function loopandlog(sound) {
			setTimeout(function (){
				var elem = document.getElementById("test");
				elem.innerHTML =  "playing?: "+sound.playing()+" seek: "+sound.seek();

				sound.seek(10);
				loopandlog(sound,id);
			},5000);
	}
	
	var sound = new Howl({
		src: ["sound1.mp3"]
	});
	var id=sound.play();
	loopandlog(sound);
})();
</script>
<html>
<body>
	<span id="test"></span>
</body>
</html>
```

**Comment by anajavi** [comment]
PR https://github.com/goldfire/howler.js/pull/276 seems to fix this.

**Comment by russellgoldenberg** [comment]
Had a similar problem: Calling the seek() function with no parameters (to show progress) then paused clip. Calling play() subsequent times restarts the clip. PR #276 seems to solve this as well.

**Comment by goldfire** [comment]
This appears to have been fixed in commit https://github.com/goldfire/howler.js/commit/d33e302fcf04c6dd30cac6d36ea6295ac0750a5d.
