### ISSUE TITLE
Howler 2 says it plays the sound, but there is no sound in Firefox

### ISSUE THREAD

**Issue by nhoizey** [goldfire/howler.js#281]
With this code from [branch ```esviji2```](https://github.com/nhoizey/esviji/blob/esviji2/src/js/esviji.js#L182):

```
sounds = new Howl({
        src: ['sounds/sprite.ogg', 'sounds/sprite.mp3'],
        sprite: {
          soundFall: [0, 204.05895691609976],
          soundHitFloor: [2000, 2000],
          soundHitOtherBallKo: [5000, 468.7528344671206],
          soundHitOtherBallOk: [7000, 500],
          soundHitSameBall: [9000, 1000],
          soundHitWall: [11000, 1835.941043083901],
          soundLevel: [14000, 2947.0068027210878],
          soundLifeDown: [18000, 1000],
          soundLifeUp: [20000, 1000],
          soundThrow: [22000, 797.1201814058943]
        },
        volume: 1,
        onload: function(){
          console.info('Sounds loaded!');
        },
        onplay: function(){
          console.info('Sounds playing!');
        }
      });
```

The console shows both ```Sounds loaded!``` and ```Sounds playing!``` when I run the script, without asking Howler to play anything.

When I play a sprite, it then shows ```Sounds playing!``` in the console. I hear the sound in Chrome 40.0.2214.111 (64-bit) on Mac OS X 10.9.5, but nothing in Firefox 35.0.1 on the same Mac.

**Comment by nhoizey** [comment]
It works perfectly with Howler 1.1.25

**Comment by goldfire** [comment]
Do you have a jsfiddle or some other hosted page showing this bug? I setup a sample exactly like your code and can't reproduce this issue on Firefox 35.0.1 on Mac.

**Comment by nhoizey** [comment]
Sorry, tried to put a demo online, and now it works… :-/

I plan to release [v2 of my game](https://github.com/nhoizey/esviji/tree/esviji2) soon, it will use Howler v2… ;-)
