### ISSUE TITLE
Fade not respecting mute status.

### ISSUE THREAD

**Issue by aholla** [goldfire/howler.js#283]
If I create a Howl, then call mute on it and then call FadeIn. The sounds fades in.

I would expect it to respect that it is in a muted state and the fade it should not change it.

If I set the global mute on Howler and then call fade in on the same object, it does not fade in. The same should happen when you set the mute state on the Howl itself.

The reason for needing this is I have different sound groups: sfx, vo and music. I would like to be able to mute one group without the other groups being muted. So I save a local mute state for each group and based upon this call mute on the howl when it is created. This works for all sounds except those that are faded in.

Thanks.

**Comment by goldfire** [comment]
This has now been fixed in https://github.com/goldfire/howler.js/commit/bdba746237d420ec0a4b232683030c3aac1a5287.
