### ISSUE TITLE
Sound wont trigger play from swipe callback

### ISSUE THREAD

**Issue by christill** [goldfire/howler.js#292]
As I understand it, on iOS you can't autoplay a sound and it must be triggered from a user action.

I have a carousel (http://idangero.us/swiper/demos/) and I'm trying to trigger a `play()` from the callback of the slide changing. This just remains silent. However, it does work if I just add an on click handler to a button on the page.

Is there a way to get it work from the change of a slide / swipe rather than a click event?

**Comment by goldfire** [comment]
It should now be working at the end of any touch on the screen. There's no other way to enable the audio.
