### ISSUE TITLE
Sound on Dolphin browser (for Android) only playing once

### ISSUE THREAD

**Issue by Friksel** [goldfire/howler.js#298]
In Dolphin browser with howler every sound only plays at the first trigger. After that never again if the page is not reloaded. Not sure if it's only Dolhin browser that lacks here or that it's possible to create a workaround or some tweak inside howler to make this work.

I use mouseclicks to trigger a howler soundinstance to play a sound-instance with a single audiofile. This works fine in all desktop and most mobile browsers, but not in Dolphin on Android:
In Dolphin browser for Android (latest version: v11.4.3 with jetpack enabled) the sound only plays the first time. After that it's never playing again on new mousetriggers. The sounds are loaded beforehand and I see the onsound event is getting raised for each sound instance initialisation.

I'm using the latest v1 hower at the moment: 1.1.26

Here's my code:
```javascript

var soundsLoaded = [false, false, false];

 function initSounds() {
        var onLoad = function(ID) {
            soundsLoaded[ID] = true;
            alert(ID);
        };

        for (var i = 0; i < 3; i++) {
            soundInst[i] = new Howl({
                urls: [ sndFolder + settings.elements.sounds[i].sndID + '.ogg', sndFolder + settings.elements.sounds[i].sndID + '.mp3', sndFolder + settings.elements.sounds[i].sndID + '.wav'],
                autoplay: false,
                loop: false,
                volume: 1,
                onload: onLoad(i)
            });
        }
    }

    function playSound(ID) {
        if (soundsLoaded[ID]) {
            soundInst[ID].stop().play();
        }
    }
```

**Comment by goldfire** [comment]
This doesn't appear to be an issue on the latest Dolphin browser.
