### ISSUE TITLE
Strange behaviour SoundSprite on Dolphin browser (for Android)

### ISSUE THREAD

**Issue by Friksel** [goldfire/howler.js#299]
I'm using soundsprites in howler. Each sound got triggered by a mouseclick event.
This works fine on all desktop browsers and most mobile browsers, but not in Dolhin browser for Android. In Dolphin some audio from the sprite gets played, but it's not the right part, but instead it's playing sequencial, so at the first click (no matter if it's button 1, 2 or 3), it playes the first sprite-sound, on second click the second sprite-sound and third the third sprite-sound. After that it's never playing again. So strange and very unwanted behaviour.
Not sure if this is a bug in Dolhin or some issue inside howler. Would be great if there would be some workaround or fix for this, 'cause at this time using audio in Dolphin is just unrealistic.
I'm using: Dolphin browser for Android (latest version: v11.4.3 with jetpack enabled) and Howler 1.1.26 (on a samsung galaxy s4 btw)
The sounds are loaded beforehand and I see the onsound event is getting raised at instance initialisation.

Here's my code:
```javascript

var soundsLoaded = false;

function initSounds() {
        soundInst = new Howl({
            urls: [sndFolder + 'allsounds.ogg', sndFolder + 'allsounds.mp3', sndFolder + 'allsounds.wav'],
            sprite: {
                sound1: [20, 526],
                sound2: [600, 631],
                sound3: [1269, 1473]
            },
            onload: function() {
                soundsLoaded = true;
            }
        });
    }

    function playSound(sndID) {
        if(soundsLoaded) { soundInst.stop().play(sndID); }
    }
```

**Comment by goldfire** [comment]
This doesn't appear to be an issue on the latest Dolphin browser.

**Comment by goldfire** [comment]
This no longer appears to be an issue with the dolphin browser. However, if you are still seeing issues, I would suggest trying webm rather than ogg.
