### ISSUE TITLE
TypeError: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by kamilbiela** [goldfire/howler.js#300]
Hi, we have following error on production, sadly I don't have information what browser.
(please ignore filename and lines, see below)
```
Stack trace: 
0 {anonymous}()@vendors.min.js?v=7843a9e247bc17f1eb7e7595f56b05e1:9:10708 
1 l.prototype._inactiveNode@vendors.min.js?v=7843a9e247bc17f1eb7e7595f56b05e1:9:14207 
2 l.prototype.play@vendors.min.js?v=7843a9e247bc17f1eb7e7595f56b05e1:9:9524 
```

It seems that this code causes this error https://github.com/goldfire/howler.js/blob/master/howler.js#L510
We are using v1.1.25, but I don't see anything that could be related in newest v1.1.26 release.
We are minifying code and we are putting "use strict" at the start of minified file.

**Comment by goldfire** [comment]
Have you tried upgrading to 2.0 (it is beta, but it is quite stable)? The 2.0 library is in strict mode, so it is fully compatible with that.
