### ISSUE TITLE
Force HTML5 audio in Howler 2.0.0-beta

### ISSUE THREAD

**Issue by fabswt** [goldfire/howler.js#301]
Hi,

Because of this [distorted audio in iOS 7.1. issue](http://stackoverflow.com/questions/29901577/distorted-audio-in-ios-7-1-with-webaudio-api), I'm forcing the use of HTML5 audio on that OS, as it gets rid of the issue.

It works fine with Howler 1.1.25 using the `buffer: true` option (see [test case for 1.1.25](https://bilingueanglais.com/tmp/howler/v1-howler-hello-forcehtml5.html).)

However, with Howler 2.0.0-beta I believe that Howler still uses the Web Audio API and not HTML5 (see [test case for 2.0.0-beta](https://bilingueanglais.com/tmp/howler/v1-howler-hello-forcehtml5.html).)

How can I enter debug mode to check what kind of audio (HTML5 or API) Howler is using ? 

Best regards -
Fabien

**Comment by goldfire** [comment]
The API for that has been changed. You need to set `html5` to `true` instead.
