### ISSUE TITLE
urls method is broken, sound won't play (v1.1.26)

### ISSUE THREAD

**Issue by Youdaman** [goldfire/howler.js#302]
This plays:
```
var sound = new Howl({
  urls: [soundUrl],
  loop: true
});
//sound.urls([soundUrl]);
console.log(sound.urls());
sound.play();
```

This does not play:
```
var sound = new Howl({
  //urls: [soundUrl],
  loop: true
});
sound.urls([soundUrl]);
console.log(sound.urls());
sound.play();
```

Both print out the array of one sound correctly, but it seems that the urls method doesn't properly set up the sound to be played?

**Comment by joeylin** [comment]
I have this problem too , do you have solution to this ?

**Comment by Youdaman** [comment]
I have a project where I have a number of slides, and each slide has its own sound. Here is the code I'm using (I call playSound every time a slide changes, with the url of the sound or I grab the sound from the data attribute of the present slide):

```javascript
var currentSound = null;
var sounds = new Array();

var playSound = function(url) {

  sounds.forEach(function(s) {
    s.fade(1, 0, fadeTime, function () {
      s.stop();
    });
  }); 

  delete sounds;
  sounds = new Array();

  var soundUrl = url || $('.present').data('sound');

  if (soundUrl) {
    soundId = purl(soundUrl).attr('file');

    var sound = new Howl({
      urls: [soundUrl],
      loop: true,
    });

    sounds.push(sound);
    sound.play(null, function() {
      currentSound = sound;
    }).fade(0, 1, fadeTime);

  } else {
    currentSound = null;
  }
}
```

It's been some months since I worked on this, but I can see that I'm deleting the sounds array entirely because I only ever want to play one sound at a time. This might not be of any use to you if you're wanting to load multiple sounds, but you can see that I am passing "urls: [soundUrl]" to the new Howl so it seems to be working for me now.

Not sure if I can be of any further help but hopefully you solve your problem!

**Comment by goldfire** [comment]
This was always pretty buggy unfortunately, which is why it has been removed in 2.0.
