### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by filfat** [goldfire/howler.js#303]
Using [TypeScript](http://www.typescriptlang.org/) for this JavaScript library would not only allow us to easily down level compile (eg use ES6 features on a ES5 browser).
It would also remove make the library a lot more usable (not that it isn't already) with projects that uses TypeScript; Angular for example.

Also refactor the code wouldn't be too hard as TypeScript is 100% compatible with javascript so everything will not have to be rewritten for it to work.

Cheers! :D

**Comment by pmoelgaard** [comment]
+1

**Comment by rtsamir** [comment]
+1
