### ISSUE TITLE
onstop event

### ISSUE THREAD

**Issue by zandaqo** [goldfire/howler.js#304]
Hi guys,

Any particular reason we don't have a `stop` event in Howler? 

I would like to have it, at least to change icons on controls if something stops the playback. I'm using a custom wrapper around the stop function for it, but can't think of a reason why the event can't come out of the box. `end` and `pause` are nice, but don't exactly cut it, due to being invoked in other situations.

**Comment by goldfire** [comment]
This has now been added: https://github.com/goldfire/howler.js/commit/592dc680d17e26470d58644163b4945ce6447812
