### ISSUE TITLE
[2.0] when wrapped in MeteorJS cordova sound doesn't play on android

### ISSUE THREAD

**Issue by paolomaffei** [goldfire/howler.js#305]
sound can be heard fine on a mac chrome, on iOS safari and app, on android chrome, but on android app (both on actual device and emulator) it just doesn't produce any sound at all.
sound.playing() returns true.

example code (coffeescript):

```coffeescript
sound = null

Template.playerPage.onCreated ->
  path = "/meditations/filename.mp3"
  
  sound = new Howl {
    src: [path]
    html5: true #it behaves the same with html5: false too
  }
  
Template.playerPage.events {
  'click .player-play': (e) ->
    sound.play()
}
```

I've opened a bug in the [meteor-howler2 repo] (https://github.com/bojicas/meteor-howler2/issues/1) but I'm not sure whether this is actually a problem only when in Cordova, or this is a more general behaviour of Howler in android, posting an issue here so that if somebody knows better they could perhaps help :)

**Comment by goldfire** [comment]
Closing for now as it appears to be the same issue as several other tickets pertaining to Android.
