### ISSUE TITLE
[2.0] on iOS onplay gets triggered but .playing() returns false

### ISSUE THREAD

**Issue by paolomaffei** [goldfire/howler.js#306]
somehow the audio file plays fine, but the console.log below echoes "onplay triggered, false"

```coffeescript
externalMedia = new Howl {
      src: [path]
      html5: true #so that file starts playing before being fully loaded
      onplay: () ->
        dep.changed()
        console.log "onplay triggered", @playing()
```

is this expected behaviour?

**Comment by paolomaffei** [comment]
furthermore, triggering externalMedia.pause() doesn't cause the audio to stop but externalMedia.playing() then returns false

**Comment by goldfire** [comment]
Which version of iOS? I just tested this on iOS 9 and it worked correctly.
