### ISSUE TITLE
No audio on Samsung S3 Native 4.3

### ISSUE THREAD

**Issue by Euden** [goldfire/howler.js#307]
I'm trying to use howler on a Samsung Galaxy S3 with Android 4.3 installed via the native browser, yet I cannot get sound to play no matter what I try, i've set buffer to true, I've tried a sprite. Nothing, no sounds at all.

Any ideas?

**Comment by Vlad-UA** [comment]
the same problem ... waiting on support of Android devices

**Comment by juanpicado** [comment]
Guys, Which version are you using? I have 2 Samsung S3 (4.3 native) devices in my desk and it works for me in both with the examples in the main page.

**Comment by Vlad-UA** [comment]
on ASUS MeMO Pad 10 (ME102A) Android 4.2.2
crash of mobile Chrome 42.0.2311.111
but ok with sound/music on native browser 
tests was done on the page http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library (howlerjs.com)

**Comment by juanpicado** [comment]
It's works for me that tablet (almost the same) as well. Webaudio OK Audiotag OK
ASUS MeMO Pad FHD 10 (ME302KL) 4.4.2

**Comment by Vlad-UA** [comment]
Could you say version of the mobile Chrome, please?
I use this URL to get version of system and browser http://jsperf.com/slug

**Comment by juanpicado** [comment]
The same version, 42.0.2311.111.

**Comment by Vlad-UA** [comment]
but on the betta version of the mobile Chrome 43.0.2357.78 all OK

may be problem with the mob Chrome 42 on android 4.2.2

**Comment by goldfire** [comment]
Unable to reproduce on newer Chrome versions, but will reopen if anyone is still seeing this problem.
