### ISSUE TITLE
[2.0] seek() returns ever-increasing values while track is paused

### ISSUE THREAD

**Issue by ctbailey** [goldfire/howler.js#308]
Hi James,

Really appreciate the hard work you've put into Howler, and 2.0 is shaping up to be even better. That said, I noticed something pretty surprising:

    var h = new Howl({ src: ['example.mp3'] });
    h.play();
    h.pause();
    h.seek() // => 6.693151927437725

    // after a second or so, call it again
    h.seek() // => 7.534875283446809

I would expect seek() to return the same value both times.

**Comment by anzev** [comment]
Found the same issue as you, so I decided to write up a fix. See my PR.

**Comment by filfat** [comment]
+1

**Comment by goldfire** [comment]
This appears to have been fixed in commit https://github.com/goldfire/howler.js/commit/d33e302fcf04c6dd30cac6d36ea6295ac0750a5d.
