### ISSUE TITLE
blocking download in howl 2.0

### ISSUE THREAD

**Issue by gaitat** [goldfire/howler.js#310]
is it possible to reduce the blocking effect of downloading audio files?

![capture](https://cloud.githubusercontent.com/assets/3304370/7999514/23d077c2-0b12-11e5-9b7b-4f956105432f.PNG)

**Comment by goldfire** [comment]
With howler 2 you can prevent preloading from happening and then you can trigger it later (for example, after the rest of the page has loaded).
