### ISSUE TITLE
suspend on no audio plays

### ISSUE THREAD

**Issue by MaximKraev** [goldfire/howler.js#315]
Suspend AudioContext if no audio played https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/suspend
allows decrease CPU usage on idle.

**Comment by goldfire** [comment]
Anyone have any idea whether there is a performance hit to calling this rapidly? Curious if the usage of this should be left up to the application or not, since there could certainly be edge cases where it could get suspended/resumed rapidly.

**Comment by skakri** [comment]
This should be benchmarked & tested.

**Comment by goldfire** [comment]
I've been thinking about this and I think it could be useful for a few reasons. Performance/battery are obviously good, but it can also solve some of the bugs with audio getting stuck. Here's an outline of what I'm thinking of trying out, anyone see any issues with this approach?

* When a sound ends, _autoSuspend() will be called.
* _autoSuspend() will check if any sounds are playing on the context. If none are, a 30 second timeout will be started, which will suspend the context at the end.
* If, during that 30 seconds, any sound starts playing, the timeout is cleared.
* On a new play, if the context's state is 'suspended', resume() will be called.
* A property will be added to Howler global to disable this default behavior.

**Comment by goldfire** [comment]
This functionality has now been added in 7022ab9fb756e12013b4d455b2765b27827c0ac7.

**Comment by MaximKraev** [comment]
Sorry missed notifications on that, on Linux pulseaudio uses about 8-10% of cpu on inactive unsuspended AudioContext, Windows 10 sound server uses about 6-8%. no idea why you need 30 sec timeout, I think it make sense to suspend every time nothing is played.  there is no reason for a timeout.

**Comment by goldfire** [comment]
There is latency introduced if you are suspending/resuming every time you play if you are rapidly playing sounds. The timeout is to keep it active until it thinks it isn't being used for a while.

**Comment by MaximKraev** [comment]
how big the latency is? I haven't noticed any when played with suspend.

**Comment by MaximKraev** [comment]
Checked latency and it is 13-20ms for me, hard to notice.

**Comment by goldfire** [comment]
That is not insignificant when you are talking about games.
