### ISSUE TITLE
Large audioSprite plays the whole sprite on any play() call on Safari (Howler 1.1.26)

### ISSUE THREAD

**Issue by valtterip** [goldfire/howler.js#316]
I have an audioSprite with approx 100 effects, works perfectly on Chrome (PC, OS X) and Android, but any play() call starts playing the whole audio file from the beginning on Safari (OS X and iOS). The sprite is heavily compressed and the size is around 400kb so that shouldn't be an issue.

I have also set the Howler.iOSAutoEnable = false; but it has no effect.

Can't reproduce this on smaller (shorter with less sounds) audioSprite. I can provide the sprite and output.json privately in case it helps. Closed bug #42 might be similar case, but there's really no info on it.

Edit: Tried with  howler.js v2.0.0-beta, still reproduces.
Edit2: Since Safari doesn't play oggs, the file size is actually just above 1mb, should not make any difference though.

**Comment by valtterip** [comment]
Humh, I think I found a solution. Gotta run some extra tests tomorrow. The reason seems to be in the encoding. I created the sourcefiles using the audioSprite (https://github.com/tonistiigi/audiosprite) on OS X (which uses whatever tools the platform offers to create the files). Re-compressing them with iTunes mp3 encoder fixes the issue on Safari. 

No idea if this bug should be actually reported on audioSprite project, some encoder it uses, here, Apple or where, but at least there seems to be a workaround solution.

**Comment by enoex** [comment]
would love to see the solution, I think I may have run into a similar issue before

**Comment by valtterip** [comment]
1. Try to encode your audio sprite with different settings, I did not encounter this when using
audiosprite --bitrate 96 --format howler *.mp3

2. Try to re-encode your generated audio sprite with the iTunes "create mp3 version" function or some other mp3 encoder.

**Comment by goldfire** [comment]
We actually ran into this recently as well and found the same issue was that our audio files were over-compressed. Recompressing the raw audio with ffmpeg fixed it for us.
