### ISSUE TITLE
howler.js play works fine on desktop but not on mobile device

### ISSUE THREAD

**Issue by ashleyjamesbrown** [goldfire/howler.js#321]
ok here is my javascript code - at the minute im just testing with one.

    var Experience=[];

    //object literal
    function Story(sname,filenum,lat,lng){
	
	this.x=lat;
	this.y=lng;
	
	this.locationName=sname;
	
	this.audioFile=filenum;
	this.audioString = "./audio/scene"+this.audioFile+".ogg";
	
	this.locRadius=15;
	
	//functions
	this.createAudio = function(){
		
		return new Howl({
                   urls: [this.audioString],
                   buffer: true,
                   onend: function(){
                   	          this.filenum++; //when finished it will increment the filename - we then just call createAudio into the variable and it will make
                                     }, 
                   });
	}
	
	
	this.setLocation = function(){
	 return new google.maps.LatLng(this.x, this.y);	//make sure its going into a marker variable when its called
	 }
	
      }

    function init(){

    var mapOptions = {
    zoom: 18,
    disableDefaultUI: true,
    center: new google.maps.LatLng(51.504742, -0.126207) //first lcoation until we get gps lock on to the user or they say no ta
    };
    
     map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);

  
    Experience.push(new Story("intro",1, 51.504742, -0.126207));
    var sound = Experience[0].createAudio(); 
    sound.play();

    }

OK so make a map, store a place with a filename, create a new howl object and then auto play it.
Will not work on mobile device at all. There is no sound. ?

Turn off buffer:true and it does load but takes a couple of seconds.

**Comment by goldfire** [comment]
You can't auto play on mobile. However, the implementation of this has been improved in the 2.0 branch.
