### ISSUE TITLE
Howler.orientation() throws an error when called initially.

### ISSUE THREAD

**Issue by joeonmars** [goldfire/howler.js#323]
Calling the getter (with no args) or setter method the first time will both result in the below error:

Uncaught TypeError: Cannot read property '1' of undefinedHowlerGlobal.orientation @ howler.min.js:4

Setting the orientations again after this error would make it work though. Not sure if there's anything I missed or is it a bug?

Thanks for any insights!

**Comment by goldfire** [comment]
Do you have any sample code? I'm not seeing the same behavior.
