### ISSUE TITLE
Cannot play sound immediately after stop

### ISSUE THREAD

**Issue by Bristoled** [goldfire/howler.js#324]
Noticed bug - when stopping sound and after that trying it play again immediately, often its not playing...

So right now did small hack with timeout:

spriteSounds.stop(mySound); //mySound already was initialized and playing once

```javascript
setTimeout(function(){
     spriteSounds.play("mySuperSound", function (spriteID) {
              spriteSounds.volume(0.5, spriteID);
              mySound = spriteID;
    });
}, 300);
```

**Comment by goldfire** [comment]
Do you have an example of this not working? I've been unable to reproduce the issue.
