### ISSUE TITLE
Stop/Pause when page is no longer visible

### ISSUE THREAD

**Issue by gRoberts84** [goldfire/howler.js#325]
Hi there,

Not sure if this is within the scope of howler or else where but I was wondering if it's possible to pause/stop the sound when the user switches tabs or their device goes to sleep.

I'm using howler for SFX on a mobile web app and I've noticed that when the device locks or you change tab, the SFX is still audible. 

Any suggestions?

Thanks

**Comment by ashrzr** [comment]
You can listen for a mouse-move event on the page. Whenever this event doesn't fire for so many miliseconds (user is no longer on the page), you can initiate the Stop/Pause.

**Comment by riyuk** [comment]
I think it's up to you.
See: https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API
