### ISSUE TITLE
2.0.0-beta: decodeAudioData fails on Opera with mp3

### ISSUE THREAD

**Issue by parasyte** [goldfire/howler.js#328]
Discovered this while soak testing melonJS today, and found some additional research here: http://stackoverflow.com/questions/28815810/decoding-mp3-data-with-decodeaudiodata-in-opera-27

That SO question also links to a simple test page that fails on Opera 30: http://www.bubbulon.com/webaudiotest/

The codecs tested by Howler determines that Opera claims it supports mp3:

```javascript
console.log(Howler.codecs("mp3")); //> true
```

**Comment by goldfire** [comment]
This has been fixed in https://github.com/goldfire/howler.js/commit/cb5d497aeb50a3924d885fb4b8ef478ab9bff096.
