### ISSUE TITLE
Fade[Out] does not work by tab change in the browser

### ISSUE THREAD

**Issue by iroks** [goldfire/howler.js#332]
System:
Firefox 39
Howler: 2.0.0-beta
Audio Mode: html5: true in the Howler constructor

Problem description:
The fade out function "sound.fade(1,0,2000, self.soundID);" does not work (the sound is countinuing to play) if the firefox tab will be changed in the the same browser. 

The function works correct by the process change or change to another firefox window. 

If later the tab with howler will be opened (with a still playing sound), the fade function is started automatically (I cannot figure out where) and the sound faded out.

**Comment by goldfire** [comment]
This is due to how the browsers now handle tab changes and throttling. Timeouts are now either paused or slowed significantly, so there's not really anything that can be done about this unfortunately.
