### ISSUE TITLE
Proper error reporting

### ISSUE THREAD

**Issue by pronebird** [goldfire/howler.js#333]
Hi,

Howler should __ALWAYS__ report a proper error and reason why it was not able to play something.

For example:

```coffeescript
error = new Error 'Forgive me brother, I could not figure out that yes, maybe, empty string and all that shite'

self.on 'loaderror', error
```

This is good for debugging.

**Comment by goldfire** [comment]
Do you have a specific example of where you aren't getting a meaningful error message?

**Comment by pronebird** [comment]
We had some problem loading audio files encoded with unsupported codec. I can't give you more details on that since it's been quite some time since I posted this issue.
