### ISSUE TITLE
Looping sound (refs #279)

### ISSUE THREAD

**Issue by patrickfabrizius** [goldfire/howler.js#334]
I'm running 1.2.26 (which according to #279 should have fixed the looping). However, my audio only seems to loop once (i.e plays twice)? Should the audio not loop indefinitely?

What seems to happend is that the volume is set to 0. If I set the volume to 1 it continues, but then resets to 0 again after next loop. (Chrome 44.0.2403.130 )

Update: It only seems to happend when using fadeIn() to play the sound. Have examined the code but havn't been able to pinpoint the error with ease.

**Comment by goldfire** [comment]
Do you have sample code so that this can be reproduced?

**Comment by patrickfabrizius** [comment]
Sure: 

musicObj = new Howl({
  urls: "forest_loop.mp3",
  buffer: false,
  loop: true
}).fadeIn(1,1000);

This particular loop is 30 sec and 618k, but I have the same problem with any sound I've tried. If I change .fadeIn(1,1000) to just .play() it works fine (as I stated above).

**Comment by goldfire** [comment]
The way fading works has been completely reworked in 2.0 and should fix this issue.
