### ISSUE TITLE
Crossfade with html5 audio on mobile device

### ISSUE THREAD

**Issue by unskaa** [goldfire/howler.js#335]
Hey, I tried this:

https://github.com/goldfire/howler.js/issues/146

And it works beautifully on PC and mobile but if I add "buffer: true" to it, it stops working for mobile. I'd like to use HTML5 as it's buffer makes the sounds start much faster.

**Comment by juhani-prospercart** [comment]
I forgot that you need user input for it to work.

But now that I fixed it the lag is terrible. The script crashes my whole phone.

**Comment by goldfire** [comment]
I would strongly suggest not using HTML5 audio on mobile unless there is a specific need for it. The implementation on both iOS and Android is pretty bad.
