### ISSUE TITLE
Play/pause bug only happening on Firefox with Firebug window opened

### ISSUE THREAD

**Issue by that-ben** [goldfire/howler.js#342]
Hi, I've been using Howler JS for 3 months now.  The following sound initialization code never changed in the last 3 months and is working perfectly on all browsers (iPhone Safari, Firefox, IE11, etc...) except today altough I didn't change anything, I experienced a new issue only happening on Firefox and only when Firebug window is opened.  What it does is the sound is playing/pausing VERY quickly and continuously. It's so quickly toggling playback that the speakers output a little bit of static noise like when you play an old vinyl record if you will.

audio_running = new Howl({ src: ['sounds/running.mp3'], loop: true });
audio_running_sound_id = audio_running.play();
audio_running.pause(audio_running_sound_id);

When the Firebug window is not visible, the bug does not occur at all.  Also, it never occurs on other browsers either, like if I open IE11's developper window, it's works fine.

**Comment by goldfire** [comment]
I'm unable to reproduce. Are you still having the issue, and if so, with what version of Firefox/Firebug?

**Comment by that-ben** [comment]
Of course, the problem remained the same after a couple updates.  I'm always using the latest stable/mainstream versions so Firefox at the moment is now 41.0.1 and Firebug is now 2.0.12.

As soon as I open the Firebug window, the sound gets laggy/sluggish and as soon as I close the Firebug window, the sounds are to absolutely normal again.  I don't even need to refresh the page or nothing.

**Comment by goldfire** [comment]
It doesn't seem to happen on OS X for me, are you using Windows?

**Comment by that-ben** [comment]
Yes I'm on Windows 7 64-bits (SP1)

**Comment by goldfire** [comment]
I'm still unable to reproduce this on Windows 7. I'm going to assume that this is an issue with Firebug and not howler.
