### ISSUE TITLE
v2 "off" doesn't allow removing listener added by "once"

### ISSUE THREAD

**Issue by cweezy** [goldfire/howler.js#343]
If I use `once` to add an event listener, there's no way to remove it using `off` (without removing all the listeners for an event), since the callback function is wrapped in another function.

Example
```js
var sound = new Howl(options)
sound.on('end', funcA)
sound.once('end', funcB)

// ... sound is never played

sound.off('end', funcB) // this does not do anything
sound.off('end') // this removes both funcA and funcB
```
Could there be a way to just remove `funcB`?

**Comment by goldfire** [comment]
This should now work based on this commit: https://github.com/goldfire/howler.js/commit/1db1528927bfdbf4d611f86c7ba5d3b543dbe000.

**Comment by cweezy** [comment]
cool thanks :+1: :dancers:
