### ISSUE TITLE
Looping sound: volume changes after loop completed

### ISSUE THREAD

**Issue by X-PRESSIVE** [goldfire/howler.js#348]
If a sound file is loaded and played like this:

```javascript
Music = new Howl({
	  urls: ["snd/music.mp3"],
	  buffer : true,
	  autplay: true,
	  loop   : true,
	  sprite : { track: [10,19940] }
	}).volume(1).play("track");
```

and then the sound's volume is changed while playing:

Music.volume(0);

It happens that the sound's volume jumps back to the full volume after a loop is completed and the sound starts over.

Howler version: 1.1.26

**Comment by goldfire** [comment]
This issue has been fixed in 2.0.
