### ISSUE TITLE
Multiple sounds in a row breaks the sprite sound in IE11.

### ISSUE THREAD

**Issue by fsrojash** [goldfire/howler.js#349]
Apparently this issue is still affecting IE11, my game has some problems with multiple sounds (sprite sounds) only on IE11. It breaks the audio sprite and play the entire audio file. I try the last version of 1.1.26 howler.js and also the 2.0.0-beta.

**Comment by goldfire** [comment]
Do you have any sample code/files? We have a large number of our players on IE11 with large use of sound sprites and haven't seen any issues with this.
