### ISSUE TITLE
Unload all currently playing sounds

### ISSUE THREAD

**Issue by 0Neji** [goldfire/howler.js#350]
Is it possible to unload all sounds set up in Howler - or destroy the current Howler instance?

The reason I ask is that I have a site which loads in different content via Javascript, so it's very difficult to know all of the audio files that could have be initialised in Howler. What I need to do is stop all sounds from playing (without targeting them individually). Something like the global `Howler.mute()` would be perfect but obviously instead of mute have `Howler.unload()` or `Howler.destroy()`.

Hopefully I'm missing something simple but is this possible easily? If not, could this be considered as a future feature?

Thanks!

**Comment by goldfire** [comment]
This has been added in 3dea9b3e6e3185b4f62d850b213145ff14d97442.
