### ISSUE TITLE
ios unlock mechanism does not work on iOS 9

### ISSUE THREAD

**Issue by ninjakatz** [goldfire/howler.js#353]
it seems that the unlock mechanism works on iOS 9 only with the "touchend" user interaction and fails to work with "touchstart" (tested on iPad only)

**Comment by norn** [comment]
+1 for iOS 9 issue

**Comment by obiot** [comment]
https://github.com/goldfire/howler.js/pull/352

**Comment by ielgnaw** [comment]
#352 works well. Thanks~

**Comment by viniciusbo** [comment]
#352 did work for me too!

**Comment by goldfire** [comment]
Thanks, #352 has been merged.
