### ISSUE TITLE
stop fading

### ISSUE THREAD

**Issue by verybigelephants** [goldfire/howler.js#355]
currently there is no way to stop the fade(). it is useful when you want to fade the sound in at the start but also let user control the volume, which then brings unexpected thigns.

right now it is much better to include jquery and use $.animate on some object, and update howler volume() on each step. i don't know about the performance but at least you can .stop(); the animation 

if someone is looking for a hotfix, here's an example of how i currently do it via jquery. you can even set an easing function like this!

let's say we have a list of all sounds in an object `sounds`, they are indexed, let's pick an arbitrary index `some_sound`. now let\s say `sounds[some_sound].howl` contains the holwer sound object

first we define an animator object like this `sounds[some_sound].animator={vol:0, my_id:"some_sound"}` - here 0 will be a starting animation property, because i am fading in

now we can fade into some `some_target_volume` at `some_duration`

    $(sounds[some_sound].animator).stop().animate({
        vol: some_target_volume
    }, {
        'duration': some_duration,
        'easing': 'easeInSine', //or other easing function
        'step':function(a){
            sounds[this.my_id].howl.volume(a);
        }
    });

if you need to stop the fade anytime you do `$(sounds[some_sound].animator).stop()`

**Comment by goldfire** [comment]
This has been fixed in 7c2b9dc0f7c3c42c22eda4a4a67c8e1929a401cf.

**Comment by verybigelephants** [comment]
cool!
