### ISSUE TITLE
Combination of buffer, autoplay and loop causes audio to play simultaneously multiple times 

### ISSUE THREAD

**Issue by blakgeek** [goldfire/howler.js#358]
The following code will reproduce the issue. 

```
var track = new Howl({
    urls: ['some_loop.wav'],
    autoplay: true
    loop: true,
    buffer: true
});
```
 I've been able to reproduce this on the latest version of Chrome, Firefox, mobile Webkit and Crosswalk.

The issue can also occur when buffer (use html5 audio) is not explicitly set to true because when there is an XHR error loading the audio file Howler falls back to html5 audio.  This was case for me and the issue would happen randomly.

The source of the issue is that when the Audio object thinks it's steaming it sets its duration to Infinity.  Howler is then using the duration to calculate the setTimeout delay for replaying the audio.  Passing Infinity to setTimeout will call the function immediately which causes the audio play again basically creating an infinite loop of sound playing with no delay.

I would have just created a PR with a fix but I can't really think of good solution.

**Comment by goldfire** [comment]
Could you create a jsfiddle that demonstrates this issue?
