### ISSUE TITLE
Play / pause between spikes 

### ISSUE THREAD

**Issue by bebekar** [goldfire/howler.js#359]
I have a Howl with a single url audio and 2 sprite and both with their separate set of buttons ( 1 for Play and 1 for pause with id) for each sprite (so 4 buttons with individual onclick )
I play the first sprite and pause; then I play the second and pause. When I play (unpause) the first I notice that it does not continue play form the pos I had paused it . 

another observation when the first play was paused, I hit play twice and had 2 instances of the same spike play, one the continuation of the paused spike and a fresh instance of the same spike begin.

**Comment by goldfire** [comment]
Do you have any sample code and are you using 1.x or 2.0-beta?

**Comment by bebekar** [comment]
Hi 
I am using the standard distribution 
The code is as follows 

<script src="js/howler.min.js"></script>
<script>
var soundId1, soundId2, soundId3, soundId4, soundId5 = 0;

var mysong = new Howl(
	{urls: ['audio/little_boys_temper_s3p10.ogg'],
	 sprite: {
			a1: [0.005, 21467],
			a2: [21472, 17824],
			a3: [39296, 17045],
			a4: [56341, 17085],
			a5: [73991, 8497]
		},
	 volume: 1.0
	});

callbk = function(e) {
	ss = e;
	//alert(ss);
	}

function songPlay(tt) {
	switch(tt) {
		case 'a1':
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;
		case 'a2': 	
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;		
		case 'a3':
			{ mysong.play(tt, callbk); soundId3 = ss; };
			break;
		case 'a4':
			{ mysong.play(tt, callbk); soundId4 = ss; };
			break;
		case 'a5':
			{ mysong.play(tt, callbk); soundId5 = ss; };
			break;
	}
}

function pauseSong(tt){
	if (tt=='a1') 	mysong.pause(soundId1);
	if (tt=='a2') 	mysong.pause(soundId2);
	if (tt=='a3') 	mysong.pause(soundId3);
	if (tt=='a4') 	mysong.pause(soundId4);
	if (tt=='a5') 	mysong.pause(soundId5);
	};
</script>

<body>
	<div class="row">
		<h2>This is a Howler.js test for pause/Play on sprikes</h2>
		<p> first spike </p>
			<button type="button" onclick="songPlay('a1');"> </button>
			<button type="button" onclick="pauseSong('a1');"> </button>
		<<p> Second spike </p>
			<button type="button" onclick="songPlay('a2');"> </button>
			<button type="button" onclick="pauseSong('a2');"> </button>
		<p> Third spike </p>
			<button type="button" onclick="songPlay('a3');"> </button>
			<button type="button" onclick="pauseSong('a3');"> </button>
		<p> Fourth spike </p>
			<button type="button" onclick="songPlay('a4');"> </button>
			<button type="button" onclick="pauseSong('a4');"> </button>
		<p> Fifth spike </p>
			<button type="button" onclick="songPlay('a5');"> </button>
			<button type="button" onclick="pauseSong('a5');"> </button>
	</div>
</body>

**Comment by bebekar** [comment]
The code 
<script src="js/howler.min.js"></script>
<script>
var soundId1, soundId2, soundId3, soundId4, soundId5 = 0;

var mysong = new Howl(
	{urls: ['audio/little_boys_temper_s3p10.ogg'],
	 sprite: {
			a1: [0.005, 21467],
			a2: [21472, 17824],
			a3: [39296, 17045],
			a4: [56341, 17085],
			a5: [73991, 8497]
		},
	 volume: 1.0
	});

callbk = function(e) {
	ss = e;
	//alert(ss);
	}

function songPlay(tt) {
	switch(tt) {
		case 'a1':
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;
		case 'a2': 	
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;		
		case 'a3':
			{ mysong.play(tt, callbk); soundId3 = ss; };
			break;
		case 'a4':
			{ mysong.play(tt, callbk); soundId4 = ss; };
			break;
		case 'a5':
			{ mysong.play(tt, callbk); soundId5 = ss; };
			break;
	}
}

function pauseSong(tt){
	if (tt=='a1') 	mysong.pause(soundId1);
	if (tt=='a2') 	mysong.pause(soundId2);
	if (tt=='a3') 	mysong.pause(soundId3);
	if (tt=='a4') 	mysong.pause(soundId4);
	if (tt=='a5') 	mysong.pause(soundId5);
	};
</script>

<body>
	<div class="row">
		<h2>This is a Howler.js test for pause/Play on sprikes</h2>
		<p> first spike </p>
			<button type="button" onclick="songPlay('a1');"> </button>
			<button type="button" onclick="pauseSong('a1');"> </button>
		<<p> Second spike </p>
			<button type="button" onclick="songPlay('a2');"> </button>
			<button type="button" onclick="pauseSong('a2');"> </button>
		<p> Third spike </p>
			<button type="button" onclick="songPlay('a3');"> </button>
			<button type="button" onclick="pauseSong('a3');"> </button>
		<p> Fourth spike </p>
			<button type="button" onclick="songPlay('a4');"> </button>
			<button type="button" onclick="pauseSong('a4');"> </button>
		<p> Fifth spike </p>
			<button type="button" onclick="songPlay('a5');"> </button>
			<button type="button" onclick="pauseSong('a5');"> </button>
	</div>
</body>

**Comment by bebekar** [comment]
```

<script src="js/howler.min.js"></script>
<script>
var soundId1, soundId2, soundId3, soundId4, soundId5 = 0;

var mysong = new Howl(
	{urls: ['audio/little_boys_temper_s3p10.ogg'],
	 sprite: {
			a1: [0.005, 21467],
			a2: [21472, 17824],
			a3: [39296, 17045],
			a4: [56341, 17085],
			a5: [73991, 8497]
		},
	 volume: 1.0
	});

callbk = function(e) {
	ss = e;
	//alert(ss);
	}

function songPlay(tt) {
	switch(tt) {
		case 'a1':
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;
		case 'a2': 	
			{ mysong.play(tt, callbk); soundId1 = ss;};
			break;		
		case 'a3':
			{ mysong.play(tt, callbk); soundId3 = ss; };
			break;
		case 'a4':
			{ mysong.play(tt, callbk); soundId4 = ss; };
			break;
		case 'a5':
			{ mysong.play(tt, callbk); soundId5 = ss; };
			break;
	}
}

function pauseSong(tt){
	if (tt=='a1') 	mysong.pause(soundId1);
	if (tt=='a2') 	mysong.pause(soundId2);
	if (tt=='a3') 	mysong.pause(soundId3);
	if (tt=='a4') 	mysong.pause(soundId4);
	if (tt=='a5') 	mysong.pause(soundId5);
	};
</script>

<body>
	<div class="row">
		<h2>This is a Howler.js test for pause/Play on sprikes</h2>
		<p> first spike </p>
			<button type="button" onclick="songPlay('a1');"> </button>
			<button type="button" onclick="pauseSong('a1');"> </button>
		<<p> Second spike </p>
			<button type="button" onclick="songPlay('a2');"> </button>
			<button type="button" onclick="pauseSong('a2');"> </button>
		<p> Third spike </p>
			<button type="button" onclick="songPlay('a3');"> </button>
			<button type="button" onclick="pauseSong('a3');"> </button>
		<p> Fourth spike </p>
			<button type="button" onclick="songPlay('a4');"> </button>
			<button type="button" onclick="pauseSong('a4');"> </button>
		<p> Fifth spike </p>
			<button type="button" onclick="songPlay('a5');"> </button>
			<button type="button" onclick="pauseSong('a5');"> </button>
	</div>
</body>
```

**Comment by bebekar** [comment]
hi goldfire, have you been able to reproduce the issue? I have been using 1.x distribution and not the beta. 
Hope  you find something soon

**Comment by goldfire** [comment]
This is one of the issues with 1.x and why 2.0 was a total rewrite. I would suggest trying this with 2.0 instead.
