### ISSUE TITLE
Using loopStart and loopEnd

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#361]
Good day, i love this library,
how can i use loopStart and loopEnd values with howler.js?
they are the only way i have found to produce great gapless loops with the web audio api and would love to use them with your library 
thank you :)

**Comment by goldfire** [comment]
Closing as duplicate of #360.

**Comment by javismiles** [comment]
just to clarify, are loopStart and loopEnd parameters being added to next version of Howler, whose release date is still unknown, correct?
