### ISSUE TITLE
playing sound on iOS iphone

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#364]
I love this library and it works great for me on Android and Desktop. But on iOS iphone nothing sounds. I read that the issue should be that on iOS you need to first activate a sound on user input, and i tried it

 window.addEventListener('touchstart', function() {
  iOSsound.play();
 }, false);	

but nothing, i just cant make a single sound come out on iphone,

any clues?
thank you

**Comment by javismiles** [comment]
i used this to make it work now on iphone, apparently iOS9 broke things and now touchend is necessary, but i still need to play a sound, is there a way to do this more invisibly?

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>touch</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
</head>

<body>

<div id="back" style="font-size:24px; width:1000px;height:1000px;background-color:#C42729;">
LOADING
</div>

<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="howler.min.js"></script>

<script>
	  var sound = new Howl({
	  urls: ["space9.mp3"],
  	  volume: 1,
	  buffer: false,
  	  onend: function() {console.log ("finished");},
  	  onplay: function() {console.log ("Playing");},
	  onload: function() {console.log ("loaded");$("#back").text("READY");}
	});

 window.addEventListener('touchend', function() {
	 console.log("touchend");
	 sound.play();
  	$("#back").css("background-color","#27B853");

 }, false);	

 window.addEventListener('mousedown', function() {
	 console.log("mousedown");
	 sound.play();
	$("#back").css("background-color","#27B853");
 }, false);	


</script>

</body>
</html>

**Comment by fiso** [comment]
Try executing this in a touchevent handler:

```
var unlockIOSAudioPlayback = function () {
    var context = Howler.ctx;
    var oscillator = context.createOscillator();
    oscillator.frequency.value = 200;
    oscillator.connect(context.destination);
    oscillator.start(0);
    oscillator.stop(0);
};
```

That did the trick for me.

**Comment by javismiles** [comment]
Thank you dear Fiso, i will try it

**Comment by goldfire** [comment]
Look at https://github.com/goldfire/howler.js/blob/master/howler.js#L155.

**Comment by javismiles** [comment]
James, that's great except that it doesnt work, at least not with me,
to make it work i had to manually add the suggestion of Filip

function unlockIOSAudioPlayback() {
    var context = Howler.ctx;
    var oscillator = context.createOscillator();
    oscillator.frequency.value = 200;
    oscillator.connect(context.destination);
    oscillator.start(0);
    oscillator.stop(0);
}

attached to a touchend event, and that worked great, but
the code embedded in the library doesnt work for me

best


Javier ideami
Ideami Studios
San Francisco / Barcelona
+1 408 634 9071
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
<http://torchprinciple.com>

**Comment by fiso** [comment]
Yeah I was unsuccessful in making Howler enable audio playback on iOS too, that's how I came up with the workaround.

**Comment by javismiles** [comment]
thank you for the comment Filip, which is odd , looking at the code it kind
of should work but it doesnt ,
thank you so much for your contribution

Javier ideami
Ideami Studios
San Francisco / Barcelona
+1 408 634 9071
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
<http://torchprinciple.com>
