### ISSUE TITLE
Combining howler.js with microphone recording + transcoding 

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#365]
im combining howler.js with recording the mic and transcoding to mp3 using lame and a web worker(for background process), i am trying different libraries for that, combined with howler.js.  The ones i have tried so far are good but they all have different issues

https://github.com/blixt/js-lameworker: process hangs after successive conversions sometimes
https://github.com/higuma/web-audio-recorder-js: Feedback noise and other issues
https://github.com/zhuker/lamejs: doesnt use web worker and some other issue

just want to consult if any of you has a suggestion of a good library to mix with howler.js for doing such thing,

what i need is:
- record from mic with web audio api
- on the fly conversion to mp3 using lame at client, with web worker, in background at same time we record
- output to a blob that i then upload via ajax to server

by the way im focused on mp3 because my web app needs to work in every platform and mp3 works everywhere, also mp3 patents are expiring and lame is open source. Also users that need to upload files are more used to mp3, etc, etc Ogg is awesome but unfortunately support is still not wide enough it seems, i hope to switch to it or add it in future

thanks so much for any advice

Jav

**Comment by goldfire** [comment]
OGG is supported virtually everywhere but IE. It is what I now recommend as the default with MP3 as the fallback.

**Comment by javismiles** [comment]
I wish that was the case, virtually everywhere? You mean virtually
everywhere except the entire iOS, Safari, IE, Edge..... not enough, not
even close to enough...
http://caniuse.com/#search=ogg
http://caniuse.com/#feat=opus
http://caniuse.com/#feat=mp3

I would love to use OGG but the support is far, far from being enough..
If it was recommended as the default im sure that then iOS, safari and edge
would already be supporting it,
i don´t care about IE at all, but Safari.... Edge... iOS.... come on

best





Javier ideami
Ideami Studios
San Francisco / Barcelona
+1 408 634 9071
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
<http://torchprinciple.com>
