### ISSUE TITLE
Fading in when looping in safari

### ISSUE THREAD

**Issue by erlinghoff** [goldfire/howler.js#366]
Just wanted to report this, as it happened after I updated to v2.0.0-beta2. I have a webapp that relies on seemless loops, and after updating the sounds fade-in when they restart, rendering a not-so-seamless experience. It worked great in howler 1.x. The issue occurs in safari 9 with aac/m4a files and in firefox os x with ogg/opus. The audio files i have tried with are approximately 1 minute in length and 44.1khz, and the error occurs in both browsers with the loop flag set to true. If this is a "feature" and not a bug, how can I control or remove the fade-in time? Thanks!

**Comment by goldfire** [comment]
Can you provide the code you are using to setup and play the sounds? I'm not 100% sure I understand the issue you are seeing.

**Comment by erlinghoff** [comment]
Hi. This bug disappeared in beta3. Thanks!

**Comment by goldfire** [comment]
Great, thanks!
