### ISSUE TITLE
[2.0] iOS 9 requires calling Howler._enableiOSAudio() explicitly to unlock audio

### ISSUE THREAD

**Issue by benjarwar** [goldfire/howler.js#367]
I'm testing using 2.0.0-beta2 on iOS 9 and finding that I need to call Howler._enableiOSAudio() to unlock playback.

I've seen #353, which makes it seem like _enableiOSAudio() should be called automatically. I don't think I should be calling the method myself, since the underscore connotes a private method.

Tested in iOS 9 Simulator and on an actual device (iPhone 6S).

**Comment by mmoss** [comment]
+1

**Comment by goldfire** [comment]
I believe this should be fixed in beta4, but if you are still seeing it can you post a code snippet?
