### ISSUE TITLE
[1.1.27] _enableiOSAudio does not work on iOS with cocos2d-html5

### ISSUE THREAD

**Issue by metalim** [goldfire/howler.js#370]
howler.js v1.1.27
touchend listener is not called on window, as cocos2d-html5 captures all events. So howl sounds never start.
Modifying listener to capture events solves the problem:
```window.addEventListener('touchend', unlock, ***true***);```
and corresponding
```window.removeEventListener('touchend', unlock, true);```

**Comment by goldfire** [comment]
Thanks, added in 9367ed5dd70c184ba7c7b6b7d36313cb0e60ea9d.
