### ISSUE TITLE
2.0.0-beta2: iOSAutoEnable functionality is needed for Chrome on Android, too

### ISSUE THREAD

**Issue by kribblo** [goldfire/howler.js#373]
Chrome 46.0.2490.76
Android 5.1.1; Nexus 7 2013

Playing the sound with html5: true.

Just playing the sound after loading it gives an error in the javascript log about sounds having to be initialized by a user action. The problem is on line 205 of howler.core.js where there is an explicit check for iOS user agent:

    if (ctx && (self._iOSEnabled || !/iPhone|iPad|iPod/i.test(navigator.userAgent))) {

If I remove this check, it works in Chrome as well after a button press. This would be the easy fix, but I don't know if this has side effects on other browsers or OS:s? Since the event used is "touchend", at least only touch devices would be affected - maybe a better check would be for something like:

    if (ctx && (self._iOSEnabled || !'ontouchend' in window)) {

Works on my devices (Android + iOS Chrome & Safari + desktop browsers) &ndash; or maybe it's simply not an issue to just run the event on any device if the iOSAutoEnable is true?

Can provide patch, but maybe there is more to this issue?

**Comment by goldfire** [comment]
Thanks, this has been added in 1c2b10f9f6586b1fb010f4cf32679e92436abcbc.
