### ISSUE TITLE
Mixed Content - (https/http) cannot load audio file

### ISSUE THREAD

**Issue by staxmanade** [goldfire/howler.js#374]
I tried playing around with Howler today and noticed an issue loading in Chrome `Version 46.0.2490.71 (64-bit)`

```
Mixed Content: The page at 'https://somedomain.com/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://feeds.wnyc.org/~r/radiolab/~5/0YbD9yZEdyY/radiolab_podcast10success.mp3'. This request has been blocked; the content must be served over HTTPS.
safeXhrSend	@	howler.core.js:1695
loadBuffer	@	howler.core.js:1685
```

Any thoughts about how to work around this? (assuming we can't ask everyone out there to support `https`)

**Comment by goldfire** [comment]
Unfortunately, I don't believe there is anyway around this.

**Comment by staxmanade** [comment]
@goldfire if I stick the URL into an audio src tag it works. So I wonder if this could be detected and fall back?

**Comment by staxmanade** [comment]
Nice :+1:

**Comment by goldfire** [comment]
This has been added in https://github.com/goldfire/howler.js/commit/f5029eb99420301b04473c6f4c3147cd276c9486.
