### ISSUE TITLE
How to set a music loop from a specific pos to end?

### ISSUE THREAD

**Issue by Icemic** [goldfire/howler.js#377]
Hello,

I tried to make my music loop from a specific pos to end, from-5s-to-end, for example, but failed.

i prefer to use sprite, but it must set `duration`, and it seems no way to get the total time of the music.

And i also tried to use `.pos(value)` in `onend` event, but it seems that i cannot set position before playing or after it.

my code: 

```javascript
var music = new Howl({
    .....
    onend: ()=>music.pos(5000);
})

```

If i made some mistakes or not? If not, how to realize the function?

**Comment by goldfire** [comment]
If you are using 2.0, there is a `duration` method. If you are using 1.x, you can access duration with `_duration`.
