### ISSUE TITLE
streaming music

### ISSUE THREAD

**Issue by ray007** [goldfire/howler.js#378]
I was so far successful using howler to play either local or remote files, but didn't manage to play music from a streaming source, i.e. internet radio.
Is this not supported or could I get to see a working example for that?

**Comment by thomasduenser** [comment]
Same question, is it possible to stream music with howler?

**Comment by goldfire** [comment]
You should be able to do it like this:

```javascript
var stream = new Howl({
	src: ['...'],
    ext: ['mp3'],
    autoplay: true,
    html5: true
});
```

Note that you must use HTML5 Audio to stream, it isn't possible with Web Audio since the full audio must be loaded and decoded first.

**Comment by ray007** [comment]
Thank you, that worked.
But what do I do if I don't know the stream is in mp3 format? In my case the target url is customer data and may or may not be streaming data...

**Comment by goldfire** [comment]
Thanks, the stopping issue has been fixed in bb903a631f21b77f9b254cf6602e3254fa0cec33. As for knowing the format, there's no way I'm aware of getting that on the client. There's certainly ways to determine that on the server side though.

**Comment by oms36** [comment]
Friend, I have an icecast server, how can I use your Howler.js to create a small radio station in my workplace?

**Comment by Ivan8R** [comment]
goldfire, please, can you show to us working example of streaming?
`var stream = new Howl({
    src: ['...'],
    ext: ['mp3'],
    autoplay: true,
    html5: true
});`

I'm write understand that we need to upload data to <audio></audio>, in src: getelementbyId ?

**Comment by Fredbam** [comment]
@goldfire Is it possible to call a pls file to stream radio stations ?

**Comment by mblackritter** [comment]
@Fredbam, ah yeah, this works well with the current version, #OhHellboyYeah! 😻 I was also pleasingly surprised, as I was already worried I'd to parse that myself! 😹💦
