### ISSUE TITLE
2.0.0-beta3: HTML5 streaming doesn't work when buffer option is set to true

### ISSUE THREAD

**Issue by benjarwar** [goldfire/howler.js#380]
I have large mp3s, so I'm looking to use the ```buffer: true``` option. I tried doing so with the latest 2.0.0-beta3 version, but it doesn't seem to work. I'm instantiating like so:

```
var audio = new Howl({
  src: ['myfile.mp3'],
  buffer: true,
  autoplay: true
});
```

But on the remote server, watching the network tab in Chrome, the file doesn't play until after it's fully downloaded. Snooping in the console, when I examined the ```Howler._howls``` array, I found my sound and noticed that the ```_buffer``` attribute is set to false, and ```_webAudio``` is set to true. I would expect the reverse to be the case, according to the documentation.

I've switched back to v1.1.28, and HTML5 playback/buffering works as expected with the following code:

```
var audio = new Howl({
  urls: ['myfile.mp3'],
  buffer: true,
  autoplay: true
});
```

**Comment by goldfire** [comment]
The `buffer` option has been changed to `html5` in 2.0.

**Comment by benjarwar** [comment]
Ah, gotcha. Thanks!
