### ISSUE TITLE
Howler with loop loaded continously causing memoryleak

### ISSUE THREAD

**Issue by jeppeandreasen** [goldfire/howler.js#382]
I'm using a short silent mp3 for background music in case another file has not been specified. However the file is loaded continuously faster and faster, so in the end the browser runs out of memory

```javascript
        var howl = new Howl({
            urls: [sound.src],
            autoplay: true,
            loop: true,
            volume: 0.1,
            buffer: true
        });
```

**Comment by goldfire** [comment]
I'm unable to replicate this issue. What browser were you testing in and can you get the same thing to happen with 2.0?

**Comment by jeppeandreasen** [comment]
Hi James,

 

Yes, I just downloaded the latest version from github, and the problem still exists. I’ve had to set loop=false on the short silent sound as it would otherwise break the application. 

 

It happens both in Firefox and in Chrome. 

 

What I can see in the network inspector is that the code repeatedly requests the empty sound file. In the beginning only once each 10 seconds or so, but then the rate seems to grow exponentially. 

 

 

Venlig hilsen

Jeppe Andreasen

 

Beru Aps

Njalsgade 21E

2300 København S

Tlf: +45 53563534

Email:  <mailto:jeppe@beru.dk> jeppe@beru.dk

 

Beskrivelse: LOGO-outline-black

 

 

 

 

Fra: James Simpson [mailto:notifications@github.com] 
Sendt: 6. november 2015 20:55
Til: goldfire/howler.js
Cc: jeppeandreasen
Emne: Re: [howler.js] Howler with loop loaded continously causing memoryleak (#382)

 

I'm unable to replicate this issue. What browser were you testing in and can you get the same thing to happen with 2.0?

**Comment by goldfire** [comment]
I still am unable to reproduce. I've created a fiddle with what I believe to be the setup you are referencing and it doesn't display the behavior. Is there something different about what you are doing than this?

http://jsfiddle.net/t09gm749/
