### ISSUE TITLE
Feature Request: loop X number of times

### ISSUE THREAD

**Issue by jayknowstheway** [goldfire/howler.js#383]
Looping is cool! What about looping a specific number of times?

To me, howler has some real potential even though there are still lots of limitations when used as a music player.. keep at it Goldfire, every time it's better and better!

**Comment by goldfire** [comment]
howler.js isn't meant to be specifically a music player, it is intended to be general-use. It should be trivial to implement this in an app if needed, I'm not sure it makes sense to include it in core. I do plan on creating a music player as an example before releasing 2.0.

**Comment by jayknowstheway** [comment]
Hello James, Thank you for your willingness to address my request! I understand your point of view, and more than anything am grateful for your work and product. Sometimes I feel that the fact that it's geared towards general-use may cause limitations for the user. It's like erring on the side of safety and caution when there could be more risks and bold moves to be explored. Although it isn't intended to be a music player, there are certain things inherent to music players that could enhance general use. For example, the ability to easily organize audio clips and more functionality on playback controls. 

I appreciate your intention to create a music player as an example, and feel like it would be emulated. It seems that you do have extensive expertise, but something you might consider trivial, such as implementing x number of loops, might be beyond the scope of many users. I hope you take this constructive criticism as a request towards more flexible use of the audio capabilities of howler.js, and a push towards more functional engineering!

**Comment by goldfire** [comment]
Thanks for the feedback! Setting up the example music player will certainly be an exercise in learning, so I'm sure some things will arise out of that :smile:

**Comment by momander** [comment]
Hi there, I just wanted to highlight another use case for the "loop X times, then stop" functionality. I am building a web-based game using Howler and the title screen, where you select your mission, plays a melody loop. If the user puts away their laptop or phone while the browser is on the title page, the device will keep playing the melody loop forever. It would be nice if it would stop by itself at some point.

Thanks for building an awesome library!

**Comment by Stenerson** [comment]
@momander any reason why you can't use `onend` to stop the loop after a predetermined number of loops?

```js
var counter = 0;
var maxIterations = 3;

var howl = new Howl({
  src: [soundSrc],
  loop: true,
  autoplay: true,
  rate: 2.5,
  onend: function() {
    counter++;
    console.log("Finished iteration " + counter);
    if (counter === maxIterations - 1) {
      console.log("Last time!")
      howl.loop(false);
    }
  }
});
```

Also see: [working jsbin example](https://jsbin.com/wabiyuw/edit?js,console,output)

**Comment by momander** [comment]
Oh, I didn't know of the `onend` technique. Thanks for showing me -- I really appreciate it!

Will update my game so the title page only plays the music loop ten times. When I demoed my game last weekend, one attendee was left wondering what the strange sound was coming from her phone late at night. It was my game's music, as she had left the game's title page open in her browser :-)
