### ISSUE TITLE
Edge always shows that there is an active sound 

### ISSUE THREAD

**Issue by esase** [goldfire/howler.js#384]
I don't start any audio on my page but Edge thinks differently. Edge consider's that I've started some audio. It also appeared on your demo page (look my screen shot)

![sasha](https://cloud.githubusercontent.com/assets/3234529/10991037/ecce7aa8-8483-11e5-9f84-9e00dd5f5d6c.jpg)

**Comment by goldfire** [comment]
This doesn't appear to be an issue in 2.0.
