### ISSUE TITLE
IOS sound doesn't stop after quitting safari

### ISSUE THREAD

**Issue by akinorikul** [goldfire/howler.js#385]
Hello,
I have an issue with howler, I'm simply playing a sound in an html file. On ios the sound plays but doesn't stop what ever I do, quitting safari, changing tab, the music still plays. 
My sound is set to loop if it can help/
I put a test file here :  http://koutchi.free.fr/content/howler/howler.html
Is it a known bug ? I can't find any comment about that behavior.

**Comment by goldfire** [comment]
From what I understand, this is the behavior of iOS Safari. When you exit the app, it is still running in the background unless you explicitly close it. You should be able to use the page visibility API to handle this though.

**Comment by akinorikul** [comment]
I wasn't aware of this behavior of IOS and the page visibility API, I manage to pause my sound using your tip,
Thank you !
