### ISSUE TITLE
Unable to set property 'bufferSource' of undefined or null reference

### ISSUE THREAD

**Issue by filfat** [goldfire/howler.js#386]
Occurs when rapidly unloading and creating new howler objects.

**Comment by goldfire** [comment]
Is this 1.x or 2.0 and do you have any sample code?

**Comment by filfat** [comment]
2.0.

Just repeat the following several times and you'll get "Unable to set property 'bufferSource' of undefined or null reference"
```javascript
this.Howl.unload();
this.Howl = new Howl(...);
```

**Comment by goldfire** [comment]
This should now be fixed with https://github.com/goldfire/howler.js/commit/efd7f23aa7e327c6eeed91389f9d1c2bd9edba9d.
