### ISSUE TITLE
Check if my sound will play?

### ISSUE THREAD

**Issue by badtant** [goldfire/howler.js#388]
Is there a way see if my device/browser will be able to play a sound I've created?

var blopSound = new Howl({
      src: ['blop.mp3', 'blop.ogg']
});

if(blopSound.willPlay){
 // something
}

I found Howler.noAudio but not sure what it does.
It says false in IE9 but i don't get any sound.

I'm using 2.0.0 beta 4

**Comment by goldfire** [comment]
Yes, that is what the global `codecs` method is for: https://github.com/goldfire/howler.js/tree/2.0#codecsext.

**Comment by badtant** [comment]
Cool, but what does noAudio do then?

**Comment by goldfire** [comment]
If `noAudio` is true then the browser isn't capable of playing any audio. It is possible to disable audio in IE settings.
