### ISSUE TITLE
HTML5 streaming does not seem to work?

### ISSUE THREAD

**Issue by dsulli99** [goldfire/howler.js#389]
Hi,

I put together a jsfiddle for this.  It appears that enabling html5 mode still requires an entire OGG to be downloaded.  For example, if I enable the developer tools in Chrome, turn on throttling, and disable caching, the entire file must be downloaded before the playing event is fired.  Is this expected behavior?  Based on the API docs it looks like HTML 5 should start playing before the entire file is downloaded, i.e.:

"Set to true to force HTML5 Audio. This should be used for large audio files so that you don't have to wait for the full file to be downloaded and decoded before playing."

The JSFiddle for this issue with the 2.0 branch beta code is here:

http://jsfiddle.net/uu4b69mn/12/

I appreciate your help with this.

Dan

**Comment by goldfire** [comment]
That is how it appears to work (and has in the past), but it looks like `canplaythrough` is now simply firing right before `canplay`, at least in Chrome. I've got a few ideas on how howler.js could fix this, but it'll take some time to hash it out and fully test before I can think about adding it into the library. I'll update once I've made some progress on this.

**Comment by dsulli99** [comment]
FWIW I am actually not as concerned about the event firing as the audio actually playing ;)

**Comment by goldfire** [comment]
I've been doing quite a bit of research into this and it appears this isn't really a browser issue like I originally thought. It actually appears to be an issue with the encoding of OGG files not having the duration in the metadata, so the browser can't start playing it until it has fully downloaded. So far I haven't found a workable solution to get around this, but I'm still digging.

**Comment by goldfire** [comment]
I've officially changed the format recommendation from ogg/webm/mp3 to just webm/mp3 (3a607279d4df0d63ee80a37564cd164f9e68b51e). If you are using OGG you simply won't be able to begin playback until the full file has downloaded.
