### ISSUE TITLE
WebAudio stops working after a period of inactivity (Android Chrome on some devices)

### ISSUE THREAD

**Issue by Melatonin64** [goldfire/howler.js#391]
On some Android devices, on latest Chrome using howlerjs 2.0, Web Audio will shutdown after some period of inactivity.
You can read more about the issue [here](http://stackoverflow.com/questions/32236156/webaudio-sound-stops-on-chrome-for-android-after-about-2-minutes) and [here](https://code.google.com/p/chromium/issues/detail?id=518863).

There's a decent workaround suggested on [stackoverflow](http://stackoverflow.com/a/33155239), and it would be great if this would be implemented within howler.js 2.0.

Thanks!

**Comment by goldfire** [comment]
I've found that using suspend/resume can solve this issue, but am still thinking through the best way to handle it. I've outlined my initial thoughts on how to approach the problem in #315.

**Comment by goldfire** [comment]
Also, for reference, this appears to be related to this bug report: https://code.google.com/p/chromium/issues/detail?id=518863

**Comment by goldfire** [comment]
This should now be fixed with 7022ab9fb756e12013b4d455b2765b27827c0ac7.

**Comment by Melatonin64** [comment]
Great - thanks!!

**Comment by tomosaigon** [comment]
I'm now getting the same exact symptoms on Chrome (OS X, not Android) with the latest Howler (2.0.0 via CDNJS). My working work-around is to auto-trigger an audio play every 25 seconds. 

Setting {autoSuspend: false} didn't help.

**Comment by stevenpietzsch** [comment]
Setting {autoSuspend: false} didn't help for me, too. Auto-trigger a play every 25 seconds is very unlovely, but sadly seems to be the only option...
