### ISSUE TITLE
"Plugin: Effects Methods" support

### ISSUE THREAD

**Issue by webtech1980** [goldfire/howler.js#396]
This is probably a stupid question but will the "Plugin: Effects Methods" work on a device that does not support the Web Audio API?

**Comment by goldfire** [comment]
No, this was the reason for splitting those out into a plugin. The idea is that everything in core will work whether or not Web Audio is supported, and anything else should be in a plugin.

**Comment by webtech1980** [comment]
Cool, Thanks for the info.
