### ISSUE TITLE
nodejs howler error

### ISSUE THREAD

**Issue by elachere** [goldfire/howler.js#398]
Hi,

I saw Howler is now on npm, so I want to use it on a NodeJs server.
I don't know if I'm doing wrong (I probably do), but when I try this : 

var Howler = require('howler');
var Howl = Howler.Howl();

var sound = new Howl ({
  					urls: ['path/to/file.mp3']
				}).play();

I got this error : 

self._autoplay = o.autoplay || false;
                      ^
TypeError: Cannot read property 'autoplay' of undefined
    at Object.Howl (/home/pi/Documents/mg_app/node_modules/howler/howler.js:227:23)

PS : i'm running the server on a RaspberryPi B+ on raspbian

Thanks in advance

Edit : the '^' is supposed to point the o object

**Comment by metalim** [comment]
Howler is client-side library, meaning it needs browser environment. Npm package is made only for browserify usage, which is convenient tool for client-side applications.

**Comment by elachere** [comment]
Ok thanks, I didn't know. Anyway I re-implemented it in Python so I can use the pygame library, and it works perfectly.
Thank's again for your response :)

**Comment by kelceyp** [comment]
I'm using Howler in the browser, Im using browserify (and it's all working fine). I tried using Howler with node.js however so that I could use it nodeunit tests but even after installing https://github.com/sebpiq/node-web-audio-api I continue to get the error message 'No audio support'.

Just an FYI

**Comment by fatuhoku** [comment]
Shame really want to write code (and test!) audio outside the browser first and then port it into the browser. Didn't manage to install web-audio-api either.

**Comment by kasperhollaender** [comment]
Does anyone know if this is still not possible to run directly on the server? :-)
