### ISSUE TITLE
Add method to determine if sound is playing

### ISSUE THREAD

**Issue by ndarilek** [goldfire/howler.js#40]
Not sure if I'm not getting some aspect of Howler, but there seems to be no method for determining if a given howl is playing.

I'm using an entity system in which entities can indicate a "presence" sound. If the game is active, then any entities with a presence sound should have that sound played. Unfortunately, if I simply loop through all entities and call play() on their registered howls, I get many instances of the same sound overlaying each other.

I'd like it if I can check if a given howl is playing, then _not_ call play(). Or, better yet, perhaps play() could do this check and not start multiple instances...unless one howl is intended to support multiple sounds, in which case it'd be nice to track playing per instance.

**Comment by Salitehkat** [comment]
Hi gavinbeck , 5 years later, did you manage to solve this? how did you prevent the creation of a new instance? I am facing the same problem. Many thanks

> I am creating a looping sound, whose volume fades on scroll (based on a percentage of scrollTop and the distance from the "target"). However, it seems that each time I set the volume, it creates a new instance of the sound. I need to target just the existing instance and adjust only that.
