### ISSUE TITLE
Detect if the file with same "src" is already in the pool and reuse it

### ISSUE THREAD

**Issue by mitar** [goldfire/howler.js#403]
In 2.0. There is something named pool, but it is complicated to use because it is hard to get or control the ID. The best would be that Howler would detect if the URL is already among existing songs and reuse them. The other option would be that I could specify a custom/manual ID with the source which I could reference later on.

So what I am imagining is a case where I have a playlist and I create for few songs, current and next, Howl objects. And as the user is moving backward and forward it would be great if Howl objects could be reused without me having to create another pool outside and maintain it myself. So or I could query based on my own ID, or based on the URL.

**Comment by goldfire** [comment]
The pool is mainly just for internal use by the library. There is already global tracking of what sources have been loaded and the library will only load that once if it is used again in another `Howl`. The pool I believe you are referring to is for the `Sound` objects that are re-used when a new sound is played, strictly for performance/memory reasons.

**Comment by mitar** [comment]
So my use case is that I have a playlist of tracks I want to play. The idea is that I start playing one and then when I detect that the whole buffer of the first track is loaded I go and start loading the second track immediately. The idea was that I would just create `new Howl()` object with the second one, but would not store the object anywhere, just so that I trigger loading, and then when the second track would come to play, I would just recreate it with the same URL. The question with of this ticket was if this would internally reuse the `Howl` instance. Or do I have to create such a pool manually outside.

**Comment by goldfire** [comment]
It won't reuse the `Howl` because that isn't everyone's desired use-case, but it will use the sound you've already downloaded. Take a look at the `loadBuffer` method.

**Comment by mitar** [comment]
That's what I wanted, reusing the sound. Great!
