### ISSUE TITLE
Seeking immediatelly after playing does not work in 2.0 in Chrome

### ISSUE THREAD

**Issue by mitar** [goldfire/howler.js#406]
In Chrome 47.0.2526.73 on Mac OS X, if I do:

```javascript
sound.play();
sound.seek(100);
```

And sound is not yet loaded it does not seek at the beginning.

But if I do `sound.play()` and in the `load` event handler the same seek, then it works.

Using 2.0.0-beta5.

**Comment by goldfire** [comment]
Thanks, fixed in f4bec6d53589407724d81a994f8e288e07dd766b.
