### ISSUE TITLE
Thoughts on 2.0

### ISSUE THREAD

**Issue by dariocravero** [goldfire/howler.js#407]
Hi there,

After working with the library for a while I find it great and I would love to help make it even better. Here are some thoughts (in no particular order) that I have around it, they range from codebase to build process to testing.
- I was wondering if you considered modularising the codebase by splitting it into more files and use browserify to workout dependencies through requires?
- The previous point would allow for a dev to cherry pick some features to use, e.g.: the preloader.
- A gradual migration to ES6 would be a nice to have but I agree t's not a must. I know that #303 suggested using Typescript and it was closed a while ago. I wonder what are your thoughts on allowing for some ES6 features to be used on the code?
- I like the fact that 2.0 has a set of tests that go with it and it would be interesting to do those at a more granular level too. Many may not even need the browser to run. Would you accept a light weight testing helper like [tape](https://github.com/substack/tape)?
- Is there any specific reason why HowlerGlobal should be a global? Is it anything more than an internal?
- A bit off-topic but when I see the state management it makes me think it might be a bit too complex at times. Have you heard of [redux](https://github.com/rackt/redux)? I think it would be interesting experiment to see how Howler's internal state could be managed with it.

I'd be happy to expand on any of the above and contribute with code too of course if the community would like that :).

Thanks for your time!
Darío

**Comment by thangngoc89** [comment]
@dariocravero about redux. I'm integrating howler.js (2.0 beta 5) in my React - Redux project. Everything was controlled with redux

**Comment by j-verre** [comment]
@thangngoc89 saw your react-howler project and it looks promising. I am also looking to integrate with Redux. Any examples you could add the project would be great. Good job.

**Comment by thangngoc89** [comment]
@j-verre I'll try to find time for that. Since everything can be control via props. You can have a state branch in redux store holds all props of a `react-howler` instance. By changing redux store state, you also changing howler state. Simple right ?

**Comment by dariocravero** [comment]
Hey all, sorry, totally forgot to look at this until now. [Here's what we're doing for now](https://github.com/UXtemple/playpause), which abstracts away the implementation of whether you use `howler` or not. [The playground in that app uses media element nodes](https://github.com/UXtemple/playpause/blob/master/playground/nodes.es6) and [here's one implementation with howler](https://gist.github.com/dariocravero/bbf3f1ac382965de3f9f).
The aim of `playpause` is to deal with playlists mainly.

**Comment by arjunkathuria** [comment]
Hi, Is anybody working on this ? 


> was wondering if you considered modularising the codebase by splitting it into more files and use browserify to workout dependencies through requires?
> - The previous point would allow for a dev to cherry pick some features to use, e.g.: the preloader.
> - A gradual migration to ES6 would be a nice to have but I agree t's not a must. I know that #303 suggested using Typescript and it was closed a while ago. I wonder what are your thoughts on allowing for some ES6 features to be used on the code?

i just did something very similar to this for Hammer.js library -> [link](https://gist.github.com/arjunkathuria/6b92f8ac5f34a10e001ab30defe05e68)

interested maintainer(s), hit me up for specifics.
