### ISSUE TITLE
Unable to set crossorigin attribute in 2.0 for HTML5 Audio.

### ISSUE THREAD

**Issue by mmoss** [goldfire/howler.js#410]
It doesn't appear as though there's any way to set the **crossorigin** attribute when the audio node is created.

**Comment by goldfire** [comment]
Can you provide an example or use-case for what you are trying to do?

**Comment by mmoss** [comment]
We have a one domain, but we're attempting to load our audio from a separate domain. The audio isn't playing, even though we've ensured that CORS headers are being set appropriately on the audio files' responses.

**Comment by mmoss** [comment]
Complete false alarm. Appreciate your contributions to the community. We were going to try and submit a PR with a fix, and diagnosed the actual root issue...
