### ISSUE TITLE
[2.0 Beta] Attempting to fade out sound while fading in the sound fails

### ISSUE THREAD

**Issue by DFortun81** [goldfire/howler.js#414]
If you attempt to fade out a sound that is still fading in, the operation will enter an infinite callback loop and fail to fade in or out from that point forward until the page is reloaded.

To fix this, inside of the 'fade' method, check to see if sound._interval exists already, if it does, I clear it out prior to reassigning the value. For best performance, do not delete the _interval element under this condition as removing elements from a dynamic object table can be slow especially if they immediately get reassigned afterwards.

              var vol = from;
              if(sound._interval) clearInterval(sound._interval); // added this
              sound._interval = setInterval(function(id, sound) {

**Comment by goldfire** [comment]
The interval already gets cleared whens tarting a new fade and I'm unable to reproduce any issues with this. If you can create a reproducible test case I'll reopen this.
