### ISSUE TITLE
[2.0 beta] Sound stops at about 30 seconds of a 50 seconds file and don't loop in some browsers

### ISSUE THREAD

**Issue by nhoizey** [goldfire/howler.js#417]
I currently have issues with [sounds not playing at all in Android/Chrome](https://github.com/nhoizey/esviji/issues/135), so I set up a simple test page with Howler 2.0.0 beta 5: http://v2.esviji.com/audio-test.html

I discovered on this page that the sound stop everytime around 30 seconds in:
- Firefox 43.0.3 on my Mac with Mac OS X 10.11.2 (ogg loaded)
- Safari on my iPhone 6s with iOS 9.2 (mp3 loaded)

The player still runs (there are "Sound playing." messages in the window every 50 seconds), but no sound comes out.

The sound plays perfectly on the same Mac, and loops, in:
- Safari 9.0.2 (mp3 loaded)
- Chrome 47.0.2526.106 (ogg loaded)

**Comment by goldfire** [comment]
Thanks, this should be fixed with c8f44a5a4a24cc6eec4f071c6a9b9a6f28e146b4.

**Comment by nhoizey** [comment]
It works now indeed, thanks!
