### ISSUE TITLE
[2.0 beta] No sound in Android / Chrome

### ISSUE THREAD

**Issue by nhoizey** [goldfire/howler.js#418]
I have issues with [sounds not playing at all in Android/Chrome](https://github.com/nhoizey/esviji/issues/135), so I set up a simple test page with Howler 2.0.0 beta 5: http://v2.esviji.com/audio-test.html

Sounds play in desktop browsers and in Safari Mobile (with [some issues](https://github.com/goldfire/howler.js/issues/417)), but not at all on Chrome 47.0.2526.83 on a Nexus 5 using Android 6.0.1 which can't load any of the ogg and MP3 files.

**Comment by goldfire** [comment]
That page doesn't seem to be loading, do you have any sample code?

**Comment by goldfire** [comment]
The latest commit may have fixed this as well. I just tested on a Nexus 7 with the same test I used for the Firefox issue and it all played through fine on Chrome.

**Comment by nhoizey** [comment]
Whoops, sorry, I moved the page there: http://v2.esviji.com/tests/

I don't see much code commits since I created the issue 4 days ago, which are referring you to?

**Comment by denvist** [comment]
Same issue on Android 4.4 + Chrome.

Code:

```javascript
Howler.mobileAutoEnable = false;

var streams = [
    'http://october.radio10.live/storage/app/media/preroll.mp3'
    ,'http://ic.radio10.live/stream.mp3'
];
var preroll = new Howl({
	src: [streams[0]]
	,autoplay: false
	,html5: true
	,onload: function()
	{
	    log.append("preroll - onload");
	}
	,onplay: function(){
	    log.append("preroll - onplay");
		stream = new Howl({
			src: [streams[1]]
			,html5: true
			,onload: function()
			{
			    log.append("stream - onload");
			}
			,onplay: function()
			{
			    log.append("stream - onplay");
			}
			,onend: function(){
    		    log.append("stream - onend");
    		}
		});
	}
	,onend: function(){
	    log.append("preroll - onend");
		stream.play();
	}
});
```

Output:
`preroll - onload`
`preroll - onplay`
`stream - onload`
`preroll - onend`
`stream - onend`
`stream - onplay`

**Comment by nhoizey** [comment]
I solved the issue by using WebM sources: https://github.com/nhoizey/esviji/issues/135#issuecomment-170331431

**Comment by goldfire** [comment]
@denvist Are you running latest Chrome? I just tested your sample code on a Nexus 7 and it ran without any issues. How are you triggering the preroll to play (I just setup a page with a button in my test)?

**Comment by agentfitz** [comment]
I am also noticing that my sounds are not playing back on Android/Chrome.

Chrome 51.0.2704.81

Desktop Chrome plays back as expected: http://lexoapp.com/lesson/hola-soy-tony
Android Chrome plays, but output is silent: http://lexoapp.com/lesson/hola-soy-tony

File type is .mp3.

**Comment by goldfire** [comment]
Can you give sample code? All of our tests are working on the latest Chrome for Android.

**Comment by agentfitz** [comment]
I will prepare a stripped down test case ASAP. Thanks for the response.

**Comment by goldfire** [comment]
They are just in the 2.0 branch right now (tests and examples), none are on a web server yet (but will be when the howler.js 2.0 site goes live).

**Comment by peplamb** [comment]
If html5 is set to true it is not working in Android Google Chrome Browser (no sound), it works when I set it to false. I am using version "version": "2.0.3".  Is there a way I can enable html5 in android browser? 

-- Thanks!

**Comment by goldfire** [comment]
@peplamb Are you saying this same code is working for you with 2.0.2 and not 2.0.3 or just in general?

**Comment by peplamb** [comment]
@goldfire thanks for the quick reply, in general it isn't working in Android if i set html5 = true regardless of the version (i moved back to 2.0.2 and it still isn't working)

**Comment by pkr31** [comment]
OMG :0 :0 :0   ITS LIKE MIRACLE .... my mp3 files doesn't played on my android phone since i am using howler..... but eventually it works with the audio jack cable (a speaker cable / jack in my case)....Connect your phone with some speakers /headfones and guess what yr music will be played in yr app...Wow iT works for me ...You don't believe me ...jst try it

**Comment by obiot** [comment]
sorry for bringing this one up, but indeed when forcing the html5 mode under Android / Chrome, the auto-unlock feature does not work (just experienced it on a Android 6 platform + latest chrome).

**Comment by obiot** [comment]
@goldfire can we re-open this one, as it's still an issue ?

**Comment by goldfire** [comment]
@obiot What are you doing to reproduce this issue? Seems to still be working in our game.

**Comment by goldfire** [comment]
@obiot Also, is this the same as #839?

**Comment by davidmartinezros** [comment]
@goldfire I try howler.js with html5=true and aoutplay=true and on android samsung S7 doesn't play the music.
The onload method and the onplay method are executed on the mobile also, but the sound doesn't play.
If I run the pause() and the play() methods, then the audio sounds, but not when loads the page.
On desktop platform all works fine!
What can I do?
Thanks,
David

**Comment by goldfire** [comment]
@davidmartinezros Check the mobile playback section of the readme for details, but basically you can't autoplay on mobile. Audio playback can't start until a sound has played within a user action (tapping on a button for example).

**Comment by davidmartinezros** [comment]
@goldfire then how can I do to show a button for play or pause the music working on desktop and mobile?

With this code:

let template = this;
        this.sound = new Howl({
            src: ['./assets/audio/Rhodesia_MkII.mp3'],
            autoplay: true,
            loop: true,
            volume: 0.3,
            html5 :true,
            onload: function() {
                template.loaded = true;
            },
            onplay: function() {
                template.playing = true;
            }
        });

Where loaded shows the buttons and playing show play button if it's true and pause button if it's false?
