### ISSUE TITLE
Ext does not support dynamic url like "http://foo/?id=bar"

### ISSUE THREAD

**Issue by willove** [goldfire/howler.js#420]
I feel very confused with Howler(2.0.0 beta5) on line 439,this expression does not support the use of dynamic url  audio. like "http://foo/?id=bar".the expression cannot get the ext type.
To solve this problem, I added a ext type in the end. like "http://foo/?id=bar&out.mp3". expression on line 439 should be improved.
thx.

**Comment by goldfire** [comment]
The example given doesn't have an extension at all, so no matter what you change in the expression it isn't going to find one in `http://foo/?id=bar`. In that case you would want to manually specify the `format` for each `src`. I'll re-open if you've got a specific example of  URL that contains an extension and isn't working.
