### ISSUE TITLE
Play from blob

### ISSUE THREAD

**Issue by Slind14** [goldfire/howler.js#423]
Hey,

I'm trying to play a m4a file from a blob. Using the html 5 audio directly works fine:

```
var audio = new Audio(fileURI); 
audio.play();
```

But neither v1 nor v2 work:

```
      var sound = new Howl({
          urls: [fileURI],
          ext: "m4a",
          buffer: true,
          volume: 1
        });
      sound.play();
```

```
      var sound = new Howl({
          src: [fileURI],
          ext: "m4a",
          html5: true,
          volume: 1
        });
      sound.play();
```

For reference, I came across a similar report, but without working solution: https://github.com/goldfire/howler.js/issues/369

Is this a known issue, am I missing something?

**Comment by goldfire** [comment]
The `ext` property was actually changed back to `format` as it was in 1.x (decided format made more sense and there was no good reason to change it). Also, unless you are using the latest commit on 2.0, the format needs to be in an array.

**Comment by Slind14** [comment]
ohh, that worked, thanks.

**Comment by weuderr** [comment]
work for me 

`      const blobUrl = [URL.createObjectURL(new Blob([arrayBuffer], {type: 'audio/mp3'}))];
      item = new Howl({
          src: blobUrl,
          format: ['mp3'],
          html5: true,
          volume: 1
      });`
