### ISSUE TITLE
Single Instance Loopable Audio

### ISSUE THREAD

**Issue by DFortun81** [goldfire/howler.js#424]
If you attempt to play a loopable audio asset that is supposed to fade in / out and then pause, attempting to re-initiate the fade in while a fade out is already happening causes the sound to continue fading out instead or create an additional instance of the sound based on whether or not the pause occurred.

To fix this, I added a check for whether an asset was intended to loop in the play function like so:

        for (var i=0; i<self._sounds.length; i++) {
			if ((self._sounds[i]._paused && !self._sounds[i]._ended) || self._sounds[i]._loop) {
				num++;
				id = self._sounds[i]._id;
			}
        }

This seemed to fix the multiple instance problem, but the fade in / out problem still persists.

**Comment by goldfire** [comment]
Is this referring to 2.0 or 1.x?

**Comment by DFortun81** [comment]
2.0

**Comment by goldfire** [comment]
This is partly taken care of with 51921596bc8f4d8cf2d836aa65bfca7290f71c89. However, I don't really follow what you are saying with the other part. Do you have a sample?

**Comment by goldfire** [comment]
I'm still unable to reproduce the multiple instance issue you are referring to. If you can provide an example I'll reopen this.
