### ISSUE TITLE
[2.0 Beta] Safari bookmark causing audio to not play.

### ISSUE THREAD

**Issue by micahlisonbee** [goldfire/howler.js#425]
Strange behavior in Safari (9.0.2). When I bookmark a page with howler audio, close tab and come back to the page from the bookmark link, the audio does not play when <code>.play()</code> is called.

Seems like some type of Safari caching issue but I can't pinpoint it.

<code>sound.playing()</code> returns <code>true</code>, however <code>sound.seek()</code> returns <code>0</code>

I've replicated the issue from the Howler.js home page: http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library

**Comment by goldfire** [comment]
The howler.js page uses 1.1.x, have you been able to reproduce using 2.0? The last few betas of 2.0 have a few different updates that address some similar sounding issues in Safari.

**Comment by micahlisonbee** [comment]
Yes I'm able to reproduce the issue on 2.0.

**Comment by goldfire** [comment]
Do you have a code sample? I'm unable to reproduce this in my testing so far.

**Comment by micahlisonbee** [comment]
I'll try beta6 first and see if the issue persists...

**Comment by micahlisonbee** [comment]
@goldfire just installed beta7 and it seemed to fix the issue, thanks!

**Comment by goldfire** [comment]
Great, thanks for the update!
