### ISSUE TITLE
sounds not stop()ing in IE10, 11

### ISSUE THREAD

**Issue by maupin** [goldfire/howler.js#427]
I have a single page app that allows people to advance quickly forward and backward through content, each time playing an audio file.  Each time they advance, I stop() all Howls, then play() the relevant one for that content.  However on IE it seems like Howls that haven't loaded in yet don't receive the stop() signal and end up playing once they're loaded.  This results in anyone who speeds through the content hearing a cacophony of sounds play when the browser finally "catches up."

On Chrome, all works as expected.

**Comment by goldfire** [comment]
Can you give a code sample that reproduces this?

**Comment by maupin** [comment]
Unfortunately at the moment I cannot.

**Comment by goldfire** [comment]
I'm not able to reproduce an issue with stopping in IE, but if you can put together a sample code I'll take a look again.

**Comment by willtonkin** [comment]
In case this is useful to anyone, I can produce this behaviour in IE11 if I do:
`Howler._howls[0].seek(0);`
Immediately before calling:
`Howler._howls[0].stop();`

Not a problem, I just removed the initial `seek()` and it was no longer a problem.
