### ISSUE TITLE
Pos3d Left/Right Panning

### ISSUE THREAD

**Issue by skepticalmartyr** [goldfire/howler.js#428]
Hello,

I'm having an issue with getting the results I want from the pos3d method. Essentially, I have a game where depending on the source of an explosion, I want to play the sound effect from the left/right speaker. The problem I've noticed is that it seems to be inconsistent with the panning. Even when the source of the event (in this case an explosion) is in the same spot, the sound will sometimes play from the wrong side. Here is a look at the code I am using:

I added a "pan" prototype to the Howl object so I could use some information from other parts of the code to tell it where I want it to pan. "soundMgr" is just a custom module that contains all of the howls. The idea is that we pass in the x coordinate of an item and then depending on which side of the screen it falls on, play the sound on that side of the screen.

```javascript
Howl.prototype.pan = function(x) {

    var position = x / soundMgr.screenWidth();
    var posRound = Math.round(position * 10) / 10;

    if (x > soundMgr.screenWidth() / 2) {
        this.pos3d(position);
        console.log("play right");
        console.log("x is: " + x + ",Position is: " + position);
    } else if (x < soundMgr.screenWidth() / 2) {
        //play sound on the left
        this.pos3d(position - 1);
        console.log("play left");
        console.log("x is: " + x + ",Position is: " + (position - 1));
    } else {
        // play sound in the center
        this.pos3d(0);
        console.log("play center")
    }

    this.play();

    return this;

}
```

In my head this should work because it's passing in the correct value for the side from where I want to play the sound. Even when the parameter for the pos3d method is the same, it does not always yield the same result. Is this a known issue with the pos3d method or am I not using it correctly?

I am new to the world of development so if there's anything you need to me to clarify just let me know! Thanks in advance to the awesome Howler community.

Alex

**Comment by goldfire** [comment]
I'm not sure what your value for x is, but keep in mind that a value of 1 is directly in the center and anything negative is to the left. We've got this implemented in CasinoRPG without any issues, so no there aren't any known issues with this implementation.

**Comment by skepticalmartyr** [comment]
Thanks for the response. The problem was that I was not using it correctly!
