### ISSUE TITLE
When changes the instance's urls on the IE the Howler plays the older one

### ISSUE THREAD

**Issue by pamelazagatti** [goldfire/howler.js#429]
After create a Howler instance, I call the method "url" with the new urls, then I call "play" function, so it plays the first url sound, It only happens on IE on the Firefox and Chrome work correctly.

Ps: During my investigation I notice that the Howler adds a new node each time that function "url" is called and the function "_inactiveNode" match and return the first node created, so the new node with the new urls is never used.

**Comment by goldfire** [comment]
This functionality is being removed in 2.0 as it was never able to work consistently. I recommend just creating a new Howl if you want to use a new source.

**Comment by korymath** [comment]
Wanted to follow up on this? 

How might we access a Howl that is created with a new source in a function, with a global method to call pause? Maybe I am missing something simple, but I don't know how the global scope can connect with the newly build local Howl.
