### ISSUE TITLE
Not working in webview

### ISSUE THREAD

**Issue by DarrylD** [goldfire/howler.js#432]
Works fine the following:
- Desktop browser (chrome)
- Mobile Browser (chrome)
- Emulator (kinda, sound cuts off on longer audio)

But when i fire it up in a web view, no dice. Any ideas why? Using ogg files.

**Comment by goldfire** [comment]
Which webview are you referring to and what version of howler.js are you using?

**Comment by DarrylD** [comment]
Sorry, Android using Cordova (with crosswalk) and using 1.1.26.

**Comment by Bored0ne** [comment]
I have mine making noise, but I'm unable to change the volume using a slider on android, I wasn't sure if I needed to add on to this thread or post as a separate issue.
I have Cordova 6.0.0
Howler 1.2.29
Crosswalk 16
JQM 1.4.5
and Android 5.1
I have ogg, mp3, and wav files.
If necessary I can share my source code.

**Comment by lovebdsobuj** [comment]
Android WebView doesn't play local Audio file. I'm searches lots of about this... but nothing happen. Android WebView remotely playing sound well but locally not playing not working...

**Comment by MrGlasspoole** [comment]
@lovebdsobuj, there is a difference between local files in Chrome on Android (WebView) and Cordova.
The people here use Cordova and there it works because with Cordova you build an app.

**Comment by goecia** [comment]
This may be old, but I've been using two sources (AAC & OGG) for cross browsing support and Howler was working fine with cordova. Once the app was ready to tweak into optimization I removed one source. For some reason not even the preload works with one (either aac or ogg). But it works just fine when I add both.
