### ISSUE TITLE
Sound is not playing on Iphone

### ISSUE THREAD

**Issue by usama831** [goldfire/howler.js#439]
Hi, I am using  version "1.1.29" of howler.js.

On android phone sound is playing good on click & shake but, 
On IPhone sound is not playing.

How can I fix this?? to play sound on IPhone as well

this is my code for shake & click:

```javascript
function shakeEventDidOccur () {
			var sound = new Howl({
				urls: ['assets/shaking-sound.mp3'],
				autoplay: true,
				loop: true,
				});
			sound.play()
                         }
$( "#click_body" ).one( "click", function() {
                  		var sound = new Howl({
				urls: ['assets/shaking-sound.mp3'],
				autoplay: true,
				loop: true,
				});
			sound.play()
}
```

Tell me if anything is wrong with my code

**Comment by goldfire** [comment]
For one, you don't want to create the Howl inside the click event. You also might want to try listening to the `touchend` event instead of just `click`.

**Comment by usama831** [comment]
Ok let me try, I will comeback to you shortly
