### ISSUE TITLE
Howler 2.0 : .rate(x) calls desync the timer that lines up with previous duration value.

### ISSUE THREAD

**Issue by dreamstrata** [goldfire/howler.js#442]
An example of a problem which stems from this is attempting to make a progress bar to sync up with the duration. Even though onend events are on schedule, the seek value remains at the pace of its initialized timer.

**Comment by goldfire** [comment]
Thanks for catching this one, should now be fixed with 94079644c85787e5dca71c51ffaa8cb04682a939.

**Comment by dreamstrata** [comment]
Alright, wexcellent. I'll check it out when testing my ogg looper.
