### ISSUE TITLE
Create Examples/Demos

### ISSUE THREAD

**Issue by goldfire** [goldfire/howler.js#444]
There's been a lot of requests for use-case examples and demos. I'm planning to add the following before 2.0 is released and will update the progress on these here. Any feedback/ideas is appreciated!

- [x] Audio player with playlist support.
- [x] Live streaming player.
- [x] Spatial audio in 3D environment.
- [x] Sprites visualized.

**Comment by goldfire** [comment]
I think the audio player should be kept pretty minimal so that it can work on desktop/mobile and so the UI can get out of the way of the functionality that someone might want to pull from. Here's a quick concept of what I've got in mind.

![howler_player_mockup](https://cloud.githubusercontent.com/assets/882005/12861903/613f6cd6-cc2c-11e5-8962-97680edc8836.png)

**Comment by goldfire** [comment]
I had some time today to work on the audio player example and the current progress is now up at https://github.com/goldfire/howler.js/tree/2.0/examples/player. It is fully functional, but is still missing volume control, song selection and a few areas of polish. If there's anything else that you think it could use please let me know.

**Comment by goldfire** [comment]
The audio player is now complete, any feedback/testing or thoughts on how to improve it are appreciated.

**Comment by goldfire** [comment]
The live streaming audio player is now complete: https://github.com/goldfire/howler.js/tree/2.0/examples/radio

**Comment by nicholaswagner** [comment]
Just wanted to leave a note and say thank you for creating this.

**Comment by goldfire** [comment]
The 3D spatial audio demo is now complete: https://github.com/goldfire/howler.js/tree/2.0/examples/3d

**Comment by goldfire** [comment]
The audio sprite demo is now complete: https://github.com/goldfire/howler.js/tree/2.0/examples/sprite
