### ISSUE TITLE
webm does not fire end event

### ISSUE THREAD

**Issue by psirenny** [goldfire/howler.js#446]
My webm sounds don't fire the end event when they are finished playing. I don't have this problem with mp3 or ogg files. For what it's worth, the webm files were converted with ffmpeg using the `-dash 1` output option and encoded with libopus.

**Comment by goldfire** [comment]
Can you provide a specific example as I'm not able to reproduce such an issue?

**Comment by psirenny** [comment]
Here's a [jsbin example](https://jsbin.com/beteril/edit?html,js,console,output). The mp3 file fires both the play and event event but the webm file only fires the play event.

**Comment by goldfire** [comment]
There appears to be something wrong with the encoding of your WebM file as it has no duration or bitrate. This is what I get when I run `ffmpeg -i file.webm` on your sample file:

```
Input #0, matroska,webm, from 'file.webm':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.007000, bitrate: N/A
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp (default)
```

**Comment by psirenny** [comment]
Aha, for whatever reason I think the metadata for webm isn't written when I stream from ffmpeg to s3. I'm not sure why it works just fine for mp3 and ogg. Thanks for your help.
