### ISSUE TITLE
[2.0] Looping a sprite sound 

### ISSUE THREAD

**Issue by Tolmark12** [goldfire/howler.js#451]
Looping doesn't seem to work with my sprite sound. The sound plays, but doesn't loop. Am I doing this correctly?

```javascript
data = {
  sprite: {
    a: [0,1000],
    b: [1100,2000],
  },
  src: ["sprite.mp3"]
}
sound = new Howl(data);

id = sound.play('a');
sound.loop(true, id);

**Comment by goldfire** [comment]
Are you seeing this behavior in a specific environment? Here's a fiddle doing exactly what you are doing and working fine: https://jsfiddle.net/v4pc17be/.
