### ISSUE TITLE
Lower runner unhandled exception

### ISSUE THREAD

**Issue by bflora2** [goldfire/howler.js#452]
Here is the Howler portion of a call stack from a very low runner unhandled exception I've been seeing:

```
l@https://www.jigsawexplorer.com/scripts/howler/howler.min.js:2:18708
i.prototype.load@https://www.jigsawexplorer.com/scripts/howler/howler.min.js:2:6077
i.prototype.init@https://www.jigsawexplorer.com/scripts/howler/howler.min.js:2:5559
Howl.prototype.init</<@https://www.jigsawexplorer.com/scripts/howler/howler.min.js:4:2279
i@https://www.jigsawexplorer.com/scripts/howler/howler.min.js:2:4452
JEPlayer/je.applause</init@https://www.jigsawexplorer.com/scripts/player/je-player.js?ver=06110724:6097:25
```
The exception contains no error message and is triggered by the following code:

```
var audioPath = 'https://d1fkqtp7g4b0i5.cloudfront.net/puzzles/resources/audio/';

new Howl({
src: [audioPath + 'applause.ogg', audioPath + 'applause.mp3'],
      volume: 0.3
});
```
I don't know how to reproduce the error, it's showing up from the field by my error reporting system. The error occurs maybe .01% of the time. I realize you may not be able to resolve this with so little information, but I thought I report it in case it leads you to see a bug in the code.

**Comment by goldfire** [comment]
Which version are you using and you are saying the error happens immediately when the `Howl` is setup?

**Comment by bflora2** [comment]
The exception is occurring in v2.0.0-beta7, but I was seeing it in an older version of v2.0 as well. I upgraded to v2.0.0-beta7 about a week or two ago to see if it would resolve the problem, but I've seen the exception twice more since.

The error happens when a new Howl is instantiated, as shown in the code snippet. Given the rarity with which the exception occurs, my first guess would be that my CDN may be triggering the exception by failing to deliver the audio file.

**Comment by bflora2** [comment]
I have kept the last eight of these errors and I've just noticed they all came from the Windows edition of Firefox v43. Probably not a coincidence.

**Comment by goldfire** [comment]
If it was related to the CDN, this commit checking for status code should take care of it: 7271794ef69f851971495872a5b5d7600c126d7b.
