### ISSUE TITLE
3d sound emitters in Howler 2.0

### ISSUE THREAD

**Issue by OpherV** [goldfire/howler.js#458]
I'm trying to implement howler 2.0 with the 3d audio plugin in my 3d web game (preview up on [opherv.com](opherv.com)) , and I came across a certain problem.

In my game I have characters walking around the world. Each character has a set of actions which are associated with a sound (e.g. eat/attack/die). Right now I can only set the position attribute per Howl instance. I'd like to share one Howl instance per sound effect across all characters - rather than create a new Howl per sound per character and than remove it when the character dies.

Is there a way to create a sound emitter of sorts that has its own 3d space, and have Howl instances play using its position? Or maybe just have the Play function accept position as an optional argument? Or is there a better way of going about it without having to create and destroy all of these Howl instances?

**Comment by goldfire** [comment]
The way things are setup now you'll need to use separate Howls. This is what we do in CasinoRPG without any issue. The way that 3D sound is setup in the Web Audio spec is currently in flux, so once that fully stabilizes I'll be revisiting this.

**Comment by goldfire** [comment]
Sorry, I just realized that I read this question incorrectly. If you pass the sound id into Howl.pos as the final parameter, then you can modify the position of each sound independently no problem. For an example, take a look at the 3d demo in the examples directory.
