### ISSUE TITLE
Sound node are not properly recycled under Ejecta (html5 mode)

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#459]
Hi there,

I noticed that when running under Ejecta, sound node are not properly reused, which ends up by audio assets being reloaded every time a new call to Howler.play() is done. 

I did some debugging, focusing on the play, ended, stop and all related functions but I could not really put my finger on it... except that at some point, a node whose `_ended` attribute is set to `true` when fully played, suddenly switch back to `false` somewhere before the next play, and is then not reused by the `_inactiveSound()` function (that then decide to create a new node).

it's pretty easy to reproduce, assuming you have a XCode environment running with Ejecta, just play any short sound repeatedly (i mean manually, not by setting the loop attribute) and the issue will present after a few play. Here I just spent one full day on this trying to find where was the issue, but I could not find it.... so giving up for today :)

Is there anyone here using Ejecta 2.0 as well Howler 2.0 and having the same issue, or am I the only one ?

**Comment by obiot** [comment]
fount the issue : https://github.com/melonjs/melonJS/commit/ef556182f442a0eb58acfecc8b07ad6060909d5a

this is caused by Ejecta changing back the `readyState` value from 4 (ready to play) to 2 (no enough data to play the next frame), and this for audio sound that were already (pre)loaded with a `readyState` of 4. 

weird bug, submitted another ticket on Ejecta side, but with this other [Pull Request](https://github.com/goldfire/howler.js/pull/456) I have now Howler 2.0 (through melonJS) fully running like a charm with Ejecta 2.0 :):):)

**Comment by goldfire** [comment]
Thanks for tracking that down, I've included the hack in c3a751c5aa5890a2c953589164c4f74eaf4b07d5.

**Comment by obiot** [comment]
you are welcome !

do note that if you prefer to implement the hacks (until its officially fixed in the next major ejecta release) you might then also include the one i mentioned in that ticket : https://github.com/goldfire/howler.js/issues/457
