### ISSUE TITLE
1.x & 2.x WebAudio not unloaded cleanly

### ISSUE THREAD

**Issue by wittnl** [goldfire/howler.js#461]
For a single howl object, the sequence `play()`, `unload()`, `play()` will fail with an unhelpful error:

> Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'

I found this is caused by `_loaded` not being reset to false in the unload handler which prevents the cache from reacquiring that AudioBuffer. Couldn't hurt to have a public method for checking the load status as well. Here's a fiddle demonstrating the problem http://jsfiddle.net/wittnl/vhsfdm1k/19/

**Comment by goldfire** [comment]
Thanks for catching that, fixed in 37197a7adf5960eed788bad0b5806d8ab3edbd95.

**Comment by wittnl** [comment]
Thanks. Is 1.x in maintenance mode at this point? I know 2.0 is close but I'd prefer to wait until it's mainlined before switching.
