### ISSUE TITLE
[2.0] Changing Pitch of a Howl

### ISSUE THREAD

**Issue by NavidK0** [goldfire/howler.js#462]
I've looked around for this, but I couldn't seem to find a way to actually change the pitch of a howl. I know that you can change the rate of a Howl with the rate property, but is there something for pitch?

**Comment by NavidK0** [comment]
According to Web Audio spec: https://www.w3.org/TR/webaudio/
modifying the rate should also modify the pitch, so I'm not sure if it's intentional that it doesn't in howler.js, or perhaps it's Chrome causing this.

**Comment by goldfire** [comment]
Changing the rate does change the pitch unless you are falling back to HTML5 audio.

**Comment by NavidK0** [comment]
Ah! Right... I  have to use HTML5 audio for a good portion of sounds because the sounds need to be streamed. Thanks for your help.
