### ISSUE TITLE
[2.0] reverse stereo, position channels separately

### ISSUE THREAD

**Issue by metalim** [goldfire/howler.js#463]
Is there a way to set position of stereo channels separately?

Our use case is chase sound, that gradually pans from left to right, and we need same sound panning from right to left as well.

If it's possible to play same sound with reversed channels (L->R, R->L), then there would be no need to include additional sound for right-to-left chasing.

**Comment by goldfire** [comment]
Not at the moment, but the Web Audio spec for positional audio is in flux and we'll be updating the 2.0 effects plugin once that matures a bit more.

**Comment by goldfire** [comment]
Sorry, I just realized that I read this question incorrectly. If you pass the sound id into Howl.pos as the final parameter, then you can modify the position of each sound independently no problem. For an example, take a look at the 3d demo in the examples directory.

**Comment by metalim** [comment]
While original question referred to positioning left and right channel of single stereo sound separately, splitting stereo into 2 mono sounds and positioning them will do the work. Thanks for the tip.

**Comment by joesnow** [comment]
Metalim, when you have a minute please post a simple example of your solution for dynamically panning two mono sounds.

**Comment by metalim** [comment]
joesnow, I don't have that project anymore.

**Comment by Diex** [comment]
hi @goldfire : is there any straightforward solution for this: I need independent level control for each channel. I was trying this: https://stackoverflow.com/questions/32460123/connect-analyzer-to-howler-sound using channelSpliltter then channelMerger (currently working on plain WebAudio) but I can't make it to work using Howler. any thought will be appreciated. Thanks for your work !

**Comment by azael-leal** [comment]
Hola, Diex, ¿pudiste solucionar ese inconveniente que tenias? De ser así, ¿podrías mencionarme cómo lo lograste? Necesito hacer lo mismo, pero igual no me funciona, sólo me funciona usando la API nativa de Web Audio, con Howler no me es posible.



> hi @goldfire : is there any straightforward solution for this: I need independent level control for each channel. I was trying this: https://stackoverflow.com/questions/32460123/connect-analyzer-to-howler-sound using channelSpliltter then channelMerger (currently working on plain WebAudio) but I can't make it to work using Howler. any thought will be appreciated. Thanks for your work !
