### ISSUE TITLE
[2.0] ios unlock doesnt work in cordova ios (UIWebView)

### ISSUE THREAD

**Issue by benconnito** [goldfire/howler.js#464]
It attaches to touchend, calls the unlock function, tries to play the empty buffer, but that never fires the source.onended event. so it never sets 

self._mobileEnabled = true;
self.mobileAutoEnable = false;

**Comment by goldfire** [comment]
Is this replicable in the Cordova Browser app? I tested it and the onended callback always fired, but maybe I'm doing something differently.

**Comment by benconnito** [comment]
I ran it on a cordova iOS build. Audio never played. Switched to 1.x branch, swapped out the 'src' for 'urls' and it worked.

I put some trace statements in the _enableMobileAudio and inside the onended event and saw the outer trace but not the onended trace.

**Comment by goldfire** [comment]
Are you using 2.0.8 and do you have sample code to reproduce the issue? I just setup a test Cordova build on iOS and the sound played fine.
