### ISSUE TITLE
Sond doesn't play in Opera 35

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#465]
```javascript
var s1 =  new Howl({
  src: [ ... valid url goes here ]
});
```

s1.play(); returns the int ID but no sound is played Opera 35.
Chrome and IE11 seems to work fine.

Howler 1.x used to work on all browsers correctly... after upgrading to 2.x it does not anymore.

**Comment by goldfire** [comment]
It is working fine in my tests. What kind of file are you using and/or can you provide a jsfiddle/codepen that replicates the issue?

**Comment by tomasz-swirski** [comment]
mp3 128bps

**Comment by themoonrat** [comment]
According to this, opera can be sketchy in supporting mp3. Try with a .ogg instead?

http://stackoverflow.com/questions/28237510/does-opera-support-audio-mp3-files

**Comment by tomasz-swirski** [comment]
... If Opera35 can't play mp3 with Howler2 because of lack of mp3 support why same file works perfectly fine with Howler1 ?

**Comment by tomasz-swirski** [comment]
Is it possible that Howler 1 supports mp3 for Opera via html5 and Howler 2 is utilizing Web Audio Api ?

**Comment by tomasz-swirski** [comment]
@goldfire, can You take a look ? :)

**Comment by obiot** [comment]
you can try to force html5 with Howler2 by setting `html5` to `true` when creating a new Howl object. You'll see then if it makes any difference

**Comment by tomasz-swirski** [comment]
@obiot - this is what i've did and the results are.   If  html5 flag is set to false then mp3 fails to play both Desktop and Mobile (android) opera. If html5 flag is set to true then desktop Opera handles mp3 correctly... however mobile opera still does nothin.  Yet mp3 plays ok on both Opera browsers when played with Howler 1.  Also i've noticed that html5 flag set to true makes _webAudio flag false for desktop Opera but it doesn't affect mobile Opera (it stays true).  @goldfire can you fix mp3 handling for Opera ? :) It was perfectly fine in Howler 1 :)) and i'll be happy not to have special hacks for Opera

**Comment by goldfire** [comment]
Closing as this has been continued in #481.
