### ISSUE TITLE
Mobile Android Web-Based app has no control over sound

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#468]
I have app which loads html content from my server, however sounds I create with howler2 are not preloaded and requires real event to occure (touchend used in howler2 for iOS somehow do not work for android app) and i need to bind additional onClick with sound.play();  ... after that sound plays fine but i can not stop or pause sound with sound.pause() and sound.stop()  <- this works fine when content is loaded via chrome, firefox and opera for android but not dedicated android app .

**Comment by goldfire** [comment]
Can you provide some more details about how to reproduce such as Android version, browser/webview, etc?
