### ISSUE TITLE
Howler 2.0 does not work anymore with "local files"

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#469]
following the below change, howler is emitting a `loaderror` when used locally (e.g. debugging on a local machine) : https://github.com/goldfire/howler.js/commit/7271794ef69f851971495872a5b5d7600c126d7b
the issue being that when accessing files locally, the XMLHttpRequest status is equal to `0` (same behaviour at least on Chrome, Safari, Firefox).

adding the following condition fix the issue : ` && code !== '0'`, but else on melonJS side we just check for value 200 or 0, and that works beautifully everywhere :)
https://github.com/melonjs/melonJS/blob/master/src/loader/loader.js#L120

**Comment by goldfire** [comment]
Thanks, I've added that in now. Out of curiosity though, how are you reproducing that? My local tests are returning a status code of 200 on Chrome for OS X.

**Comment by obiot** [comment]
Hi,

On my side I'm also on OSX and I'm just opening my index.html page with Safari or Chrome (that by the way needs to be launched with the flag "allow-file-access-from-file")

That weird that you don't have this issue on your side... Maybe i'm doing something wrong?

**Comment by goldfire** [comment]
Ah okay, I was testing either using a local web server or without the flag. I see it now, thanks again.
