### ISSUE TITLE
buffer: ture not calling onend...

### ISSUE THREAD

**Issue by JenGL** [goldfire/howler.js#470]
Hi,

i'm evaluating howler for a work project and i have a problem on chaining sounds.
My goal is to stream an mp3 file that is downloaded in chunks and put in play the chunks one by one.
To chain the sounds i'm using the "onend" property of the sound object.

`const sound = new Howl({
          urls: [URL.createObjectURL(blob)],
          format: this._crtAudioStreamer.metadata.data.extension,
          buffer: true,
          onend: () => {
            this._chainNext();
          }
        });`

the problem is that after the first cunk is played the onend function is not called if buffer property is set to true.
I'm missing anything ? Is there a better way to chain sounds ?

**Comment by JenGL** [comment]
One more thing. I add that this bug is present also in the 2.0 version :)

**Comment by goldfire** [comment]
Does each chunk contain its own duration data?

**Comment by JenGL** [comment]
I don't know... (Honestly i don't think they have...) , but it's only the first chunk that it's not calling the onend function... The others do. And if I set buffer (or html5 with versione 2.0) to false everything goes fine
