### ISSUE TITLE
Looping problems with howler

### ISSUE THREAD

**Issue by czarczar** [goldfire/howler.js#472]
This is not an issue, but a clearance.
The core version 2.0 BETA of Howler solves a lot of problems.
Certainly concerning different instances of looping sounds, but other issues as well.

If you use the core-version 2 notice that you have to change the name of the array urls to src.
So, instead of:
`var sound = new Howl({
  urls: ['sound/mp3/public2.mp3']
}).play();`

use:

`var sound = new Howl({
  src: ['sound/mp3/public2.mp3']
}).play();`

and it works (backwards compatible with version 1.29, but you need to change this).
Sounds obvious, but there is no documentation yet on the beta of howler 2.0 and this is the main difference. And be sure, uptill now, to use the core version.

The core version 2.0 BETA of Howler solves a lot of problems.
It works really well. Thanks!

**Comment by goldfire** [comment]
Full documentation for 2.0 is available at https://github.com/goldfire/howler.js/tree/2.0, though a migration guide is in the works.

**Comment by czarczar** [comment]
Thanx!
I checked further in other browsers.
Howler 2.0 is great, howler 1.29 for me is obsolete, Howler 2.0 core works perfectly in most browsers, howler 1.29 has a lot of issues solved in 2.0 CORE. Thanx very much, very good work, world leading!

**Comment by goldfire** [comment]
Thanks! Getting very close to being able to merge into master.
