### ISSUE TITLE
seek returning bad values when changing the playback rate after a period of time

### ISSUE THREAD

**Issue by vladflorescu94** [goldfire/howler.js#473]
If you play a song with playback rate 1 and after some time you change the playback rate, you will notice that the seek method will return values starting with the value returned by the seek method at the moment you changed the playback rate.

In the last moment of the playback you could check that the returned value would be song.duration() + (elapsedTimeWhenChangedRate * newRate - elapsedTimeWhenChangedRate * initialRate) instead of song.duration().

I use howler-2.0.0-beta8

**Comment by goldfire** [comment]
Here's an example I put together that shows everything working as expected:

I begin playing an audio file of duration 300. After 5 seconds, I change the rate from 1 to 2. I then log the seek position and duration. At this point the seek is at 5 seconds and the duration is now 150. After 5 more seconds, I log the seek position and duration, and it shows 10 seconds and 150 respectively.

If you can provide a specific example of this not working I'll reopen this.

**Comment by vladflorescu94** [comment]
And should it work that way ? Shouldn't seek be relative to the song's rate ? Then how could you indicate the playback position if you change the rate at a moment ?

For example I play an audio file of duration 300. After 100 seconds I change the rate from 1 to 2. Seek position is 100, duration 150. After 100 seconds seek position is 200 and duration is 150, but it's bad because time passes 2 time faster in song and 100 seconds = 200 seconds at rate 2.

So song is now finished but seek time is neither 150 nor 300, it's 200. Seems pretty wrong.

**Comment by goldfire** [comment]
That isn't quite right. If you waited another 100 seconds, the song would have completed 50 seconds ago and everything would have worked correctly.

I can see where there might be confusion depending on how you look at it. I saw it as altering the duration and progressing through time at the same speed, but you can also look at it as the same duration, but progressing through time at a different rate (your example).

In both cases you'll get the same end result. I'll go ahead and reopen this as it may make sense to think about it from the perspective of moving through time at a faster rate.

**Comment by goldfire** [comment]
I've been thinking through this one quite a bit more this evening and have made the following change to the behavior: 2a9c13b5bbe7865e865491b92086b4b14e930fcf. This should now perfectly match the behavior in HTML5 Audio and the behavior you see in a native media player. Thanks for bringing this to my attention!

**Comment by vladflorescu94** [comment]
Cool, thanks ! :D But I think sound._playStart variable's name is pretty confusing right now :))
