### ISSUE TITLE
whileplaying event

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#475]
Is there any "whileplaying" event  fireing repeatedly while sound is playing??
(im looking for something that i can bind with progressbar in my player) ;)

**Comment by tomasz-swirski** [comment]
This is my quick workaround. My intentions was not to modify internal lib and provide solution using only Howler2 API.  It works fine. It needs to be initialized for each $howl instance though.   

var initHowlOnWhilePlaying = function($howl) {
  $howl.interval, $howl._onwhileplaying = [];
  $howl.on('play', function (soundId) {
    $howl.interval = setInterval(function () {
      $howl._emit('whileplaying', soundId, [$howl.duration(), $howl.seek()]);
    }, 100);
  });
  $howl.on('stop', function(){
    clearInterval($howl.interval);
  });
  $howl.on('end', function(){
    clearInterval($howl.interval);
  });
}

$howl.on('whileplaying', function(soundId, data){ console.log(data); });


Also it would be nice to have multiple events assigning feature like jQuery has.
$howl.on('end, seek, play',  function(){});  :))

Best regards.

**Comment by goldfire** [comment]
Something similar is used in the `/examples/player/` demo.

**Comment by hamzawain7** [comment]
@goldfire Please see this https://github.com/goldfire/howler.js/issues/977#issuecomment-458499068
