### ISSUE TITLE
calling .play() for single Howler object

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#476]
When .play() called multiple times two things pop ups. First is parallel sound playback. Second is that .pause() and .stop() does the same thing (stops playback). Also .duration() is bugged, as it returns point (on the timeline) on when second .play() tooked place.

**Comment by goldfire** [comment]
This is the correct behavior in 2.0. A single Howl can playback multiple sounds. If you don't pass in a sound id, then it acts as a group rather than controlling a single sound.
