### ISSUE TITLE
HowlerGlobal is not defined

### ISSUE THREAD

**Issue by j-verre** [goldfire/howler.js#478]
In reference to ticket [https://github.com/goldfire/howler.js/issues/422]
Running tests in mocha, I am still getting this issue with beta7.

_Either of these work..._
```
var Howl = require('howler/howler.core.min.js');
import {Howl, Howler} from 'howler/howler.core.min.js';
```
_These do not..._
```
var Howl = require('howler');
import {Howl, Howler} from 'howler';
"ReferenceError: HowlerGlobal is not defined"
```

**Comment by goldfire** [comment]
This should be working in beta9, which I'll push out soon. Please update this thread if you are still having issues at that point.

**Comment by brenwell** [comment]
I am having the same issue with `howler@^2.0.3`

**Comment by mcgoooo** [comment]
i still see tis in howler 2.0.4

**Comment by mcgoooo** [comment]
i uses this issue to fix the problem
https://github.com/goldfire/howler.js/issues/637

**Comment by everm1nd** [comment]
@mcgoooo this leads me to "ReferenceError: Audio is not defined". don't you know a solution for this. I use JSDOM v11, so Audio-wrapper is defined there, but seems that Howler can't pick it up :(

**Comment by mcgoooo** [comment]
@everm1nd i have no idea i am afraid.

**Comment by chrisregner** [comment]
#637 worked on me. Thanks, @mcgoooo.

**Comment by paulrosen** [comment]
I'm seeing this with version 2.1.0.

**Comment by ajs139** [comment]
It could be that this condition should not be be `else`:
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L2470
In some environments (such as Create React App), you can have _both_ `window` and `global` defined - where `window` is a JSDOM `window`, and `global` is the Node global object.
