### ISSUE TITLE
Keeping sound on pause causes unload

### ISSUE THREAD

**Issue by Creylon** [goldfire/howler.js#479]
Hey, I'm using howler.js to build my own javascript music player. When I hear a song and pause it for a while (about 1 to 5 minutes) it fires the onend event which to me indicates that the sound has been unloaded. Could that be an issue or is it me? I use howler.js v1.1.29

**Comment by goldfire** [comment]
Do you have a reproducible case and do you know if the same thing happens in 2.0?
