### ISSUE TITLE
Opera Issue

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#481]
Desktop Opera 
Version:	36.0.2130.32 - Opera is up to date
Update stream:	Stable
System:	Windows 10 64-bit (WoW64)

Mp3 file format fails to play with webaudio interface (html5: false).
If i set html5 option to true the sound is played but not preloaded (the load is made at .play() time).
Calling .load() has no effect.

**Comment by tomasz-swirski** [comment]
Ok i found code responsible for this behavor:

`    _setupCodecs: function() {
      var self = this || Howler;
      var audioTest = new Audio();
      var mpegTest = audioTest.canPlayType('audio/mpeg;').replace(/^no$/, '');
      var isOpera = /OPR\//.test(navigator.userAgent);

      self._codecs = {
        mp3: !!(!isOpera && (mpegTest || audioTest.canPlayType('audio/mp3;').replace(/^no$/, ''))),

`
Why Audio.canPlayType is called for Opera while using Web Audio Api interface?
Also Opera handles mp3 perfectly fine - so why force-disable this format anyway?

**Comment by goldfire** [comment]
This was added with commit https://github.com/goldfire/howler.js/commit/cb5d497aeb50a3924d885fb4b8ef478ab9bff096. The reason being that Opera can be pretty flaky with MP3 support, reporting that it supports it, yet not actually playing anything back. It looks like newer versions may have fixed this, so I'm looking into this again to see if an improved workaround is possible.

**Comment by goldfire** [comment]
It looks like Opera 33 fixed the issues with MP3 playback, so this check has been updated to reflect this: https://github.com/goldfire/howler.js/commit/77e2340427db244c68c1d91fb89bb5008ccd8f49.
