### ISSUE TITLE
Android Mobile browser issue with html5 set to true

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#482]
Becasue Opera (both mobile and desktop) doesn't play mp3 files with webaudioapi (via howler object) i've decided to force-enable html5 by setting html5 to true. However now Mobile Opera and Chrome plays only half of my mp3 files.

File coding is:  MP3/ 44100Hz, 96kbps, Mono
Size: 23,99KB, length: 1.695

(all of my files are under 2 sec in length and all are cutted in half when playing with html5).

**Comment by tomasz-swirski** [comment]
I've did some debugging my self and this is what i've found out.

In the .play() method there is code like this:

        var timeout = (duration * 1000) / Math.abs(sound._rate);
        if(timeout !== Infinity) {
          self._endTimers[sound._id] = setTimeout(self._ended.bind(self, sound), timeout);
        }

which works perfectly fine ... unless 'timeout' has invalid value... and then the bad things starts to happend because onend function stops the sound, rises  "onend" and "paused" flags.

My solution to fix that is to relay on the html5 onended function when html5 is in use.


      if(self._webAudio){
        // Create a timer to fire at the end of playback or the start of a new loop.
        var timeout = (duration * 1000) / Math.abs(sound._rate);
        if(timeout !== Infinity) {
          self._endTimers[sound._id] = setTimeout(self._ended.bind(self, sound), timeout);
        }
      } else {
        sound._node.onended = self._ended.bind(self, sound);
      }

Works for me.
Best regards.

**Comment by goldfire** [comment]
Thanks, this should now be fixed with 2de5d2b3bb847233b9fe032a1dd10cfe95967cae.

**Comment by yumewang** [comment]
Hi，same problems: **can not work at  Android Webview, but work fine at Android browser**.
I defined like below:
`
new Howl({
    src: ['../assets/test.mp3'],
     html5: true,
    preload: true,
    onload: function () {
         console.log('here is loading ')
    },
})
`
This resourse(.mp3) had 10 minutes.
![12](https://cloud.githubusercontent.com/assets/2267888/25526788/cc2a7140-2c47-11e7-9c2f-6a7f1ae4d132.png)

And then I test
`
<audio :src="../assets/test.mp3" controls="controls">
   Your browser does not support the audio element.
</audio>
`
I found out it works at Android Webview & Android browser. Why?
Can you give me a favor to fix this, just let me know if I ignore something.
If I want to fix this problem, I need to set setTimeout as above?

Thank you very much.
