### ISSUE TITLE
[2.0] Bring Howler.unmute() back

### ISSUE THREAD

**Issue by alvinsight** [goldfire/howler.js#485]
Hi guys, 
Good work on the V2, I really like the new API, except for one thing, it seems like `Howler.unmute()` was replaced by `Howler.mute(false)` I don't think this is as straightforward as explicitly calling "unmute".

The boolean parameter looks like something that would indicate what to mute, not something that is making the method do the opposite of what its name implies.

I'm happy to write a PR that adds unmute back but internally just calls `Howler.mute(false)`

Thank you, 
Alvin

**Comment by goldfire** [comment]
The API is pretty much set in stone at this point, so I can't see this changing at this point and I still feel that the boolean is a cleaner solution.
