### ISSUE TITLE
［2.0, iOS] audio context not unlocked with a swipe gesture

### ISSUE THREAD

**Issue by branaway** [goldfire/howler.js#486]
A simple tap worked to unlock the audio context, while a swipe gesture did not. 

The sample:

http://test.joy-read.com/view/5528

There would be no sound played if a user swipe upward to reveal the content. Tapping on the screen before swiping worked. 

A little debugging showed that the source.onended was never called even though the unlock() was called if the first user action had been a swipe.

**Comment by goldfire** [comment]
Do you know what element the `touchend` event was firing on vs the `touchstart`?
