### ISSUE TITLE
[2.0 beta9] dubious unloading in _enableMobileAudio 

### ISSUE THREAD

**Issue by branaway** [goldfire/howler.js#490]
the newly added Howler.unload call in the _enableMobileAudio have caused all of the preloaded audio to reload when they were called to play, otherwise my app would preloaded many audio clips in a batch and use them later in the game.

**Comment by goldfire** [comment]
Can you give an example? The unload should only fire on mobile and before any preloading as started.

**Comment by branaway** [comment]
This is how it might have happened:

In IOS, my page started and I created bunch of Howler objects. Preloading kicked in and users waited for preloading to finish. The unlock function defined in the _enableMobileAudio were invoked each time a sound clip was loaded, but the source.onended (line 255) was never called, because there had been no user interactions to unlock the audio context in Safari. The key point is that mobileAutoEnable was thus always true so previous AudioContext was destroyed again and again.

**Comment by goldfire** [comment]
Thanks for the extra details, this commit should fix that problem: 7ee1ba0e7ae6cf58ce11bc3b772bed3481e6d2e2.

**Comment by branaway** [comment]
Thanks for the quick response. I haven't tested the commit, but in my case where user actions take place after multiple Howler objects have been created, the _enableMobileAudio will be called again and again until a user action is detected and the safari audio context is unlocked. 

I'll see if the side effect is harmful.
