### ISSUE TITLE
On End returns before audio playback finished

### ISSUE THREAD

**Issue by brianlmerritt** [goldfire/howler.js#492]
Using howler.js from an angular app, we find the audio calls the on end function virtually as soon as play began.

```javascript
var audio = assessmentFactory.getAudioObject();
console.info("Audio Object Selected");
console.info(audio);
$scope.audio = audio ;
audio._sprite[name] = [start, duration];
audio.on("end", function () {
    $scope.audio = false;
    console.info("Ended audio at: "+moment().format("hh:mm:SSS"));
    return deferred.resolve("Audio finished");
});
console.info("starting audio play for: " + name + " " + moment().format("hh:mm:SSS"));
audio.play(name);
```

With durations from 2 to 6 seconds, the function is called typically 100 milliseconds after the call.

Browser is Chrome 49 (latest)

**Comment by goldfire** [comment]
What version are you using and can you provide the code sample of the `Howl` that gets setup?

**Comment by brianlmerritt** [comment]
Hi - just downloaded so 1.1.29 version (was on 1.1.25)

Initialisation code =

`onElementLoaded: function (obj, el) {
                        if (obj.type === "AUDIO") {
                            audioObject = new Howl({
                                urls: [obj.source],
                                autoplay: false,
                                sprite: {}
                            });
                        }`

**Comment by brianlmerritt** [comment]
Closing issue - error was my moment.js format (should have been hh:mm:ss:SSS)
