### ISSUE TITLE
[2.0 beta10] a howl array just onload once in IOS

### ISSUE THREAD

**Issue by ztommy** [goldfire/howler.js#493]
Code like this:

    var audios = [
        'mp3/1.m4a', 'mp3/2.m4a'
    ];
    var howlArr = [];

    for (var i = 0; i < audios.length; i++) {

        var _url = audios[i];
        var _sound = new Howl({
            src: [_url],
            autoplay: false,
            loop: false,
            volume: 1,
            onload: function () {
                console.log(111);
            },
            onloaderror: function () {
                console.log("load error");
            }
        });
        howlArr.push(_sound);
    }

in [beta10.0], Console.log(111) just work once. I'm hope can work twice. 
[beta 8.0] is work ok. please test and help, thanks.

I'm chinese. english is not good, so sorry.  

04/01 : sometime it's work ok! I don't reappeared now...

**Comment by SlawomirMazgaj** [comment]
I was just about to open same issue. Bumping up this one instead.

**Comment by ztommy** [comment]
@SlawomirMazgaj @goldfire 
this issue in howler.min.js . use src/howler.core.js is ok.

**Comment by ztommy** [comment]
@goldfire 
I find this bug in 
`if (ctx.sampleRate !== 44100) {
       Howler.unload();
  }`
if my sampleRate is 48000, onload once. 
delete this code, work ok. but distortion issues back. I don't known how to fix it.

**Comment by goldfire** [comment]
Do you have any other details about how to reproduce this? I've been testing both with the minified and un-minified files and haven't been able to reproduce this behavior with the exact sample code you provide. What steps are needed?

**Comment by ztommy** [comment]
This issues is randomness. same code, some iphone6, iphone6plus are good, some are bad. I've debug the code, if run bad, ctx.sampleRate not 44100, maybe 48000. I don't know how the sampleRate is changed.
So i don't  known how to reproduce this. Try more phone can reproduce.

**Comment by goldfire** [comment]
I still haven't been able to reproduce this and haven't seen anymore reports of this. Going to close for now, but will reopen if anyone is still seeing it.
