### ISSUE TITLE
Including Howler (without using it) pauses iOS background audio

### ISSUE THREAD

**Issue by ruddzw** [goldfire/howler.js#494]
I've got an issue where simply including howler as a javascript include on the page, without actually using it, pauses iOS background audio. That is, users navigate to our home page, or about page, etc., pages which don't actually use howler, even though the rest of our application does, and audio immediately pauses. This is before setting `Howler.iOSAutoEnable` or `Howler.mobileAutoEnable` would have an effect. Seems like this *might* be a duplicate of #239. Might also be iOS 9 only, that's the only OS I have available to test with.

I've tracked the issue to this line in the Howler initialization, creating a web audio api audio gain node: https://github.com/goldfire/howler.js/blob/7ee1ba0e7ae6cf58ce11bc3b772bed3481e6d2e2/src/howler.core.js#L2059

    masterGain = (typeof ctx.createGain === 'undefined') ? ctx.createGainNode() : ctx.createGain();

Is this unavoidable? Or could this be delayed until howler is actually used?

**Comment by goldfire** [comment]
How is the background audio being played?

**Comment by ruddzw** [comment]
Just any background audio -- Music, Spotify, a podcast player... Meaning, some other app's background audio.

**Comment by goldfire** [comment]
This should now be fixed with https://github.com/goldfire/howler.js/commit/762c544585300a34b80ed8c0627e08bece615687. It now waits to setup the AudioContext until a `Howl` has been created.
