### ISSUE TITLE
Change rate while looping

### ISSUE THREAD

**Issue by Bagongo** [goldfire/howler.js#496]
I can't manage to change the rate property for a looping howl after it starts playing. Is there a way to do that?

Thanks!

**Comment by goldfire** [comment]
Which version are you using? You should be able to do this in 2.0, but if it isn't working please provide sample code.

**Comment by Bagongo** [comment]
You are right, I am sorry, I was using the older version.
How do you use the 2.0 package though? What files are essential to be put inside the project we want to use howler with? In the previous version I just imported howler.min.js but with 2.0 it doesn’t seem to be enough..
thx!!!

**Comment by goldfire** [comment]
howler.min.js includes the core and effects plugins, so that should be everything you need still. Be sure to check the documentation in the 2.0 branch as a few things have changed (such as `urls` now being `src`).

**Comment by Bagongo** [comment]
Yes, you are right… howler.min.js is sufficient and I actually had to change urls into src.
 It’s working great now! Thanks for the help and for sharing such an amazing tool!!!
