### ISSUE TITLE
Howler.codecs not initialized

### ISSUE THREAD

**Issue by ajs139** [goldfire/howler.js#497]
In `HowlerGlobal.init`, `noAudio` is set to true before calling `_setup`, so `_setupCodecs` is not called until after a Howl object is created, which calls `setupAudioContext`.

This prevents using `Howler.codecs` to determine which file types can be loaded before creating a Howl.

**Comment by goldfire** [comment]
Thanks, `Howler.noAudio` now defaults to `false`.
