### ISSUE TITLE
Please, help with sprite looping 

### ISSUE THREAD

**Issue by Alsobrook** [goldfire/howler.js#499]
The desired behavior: 

I have one mp3 file 28 seconds. On start page playing intro from 0 to 19 seconds, after end begin music from 19 to 28 seconds, and must play with loop until user turn this off manualy. Try different approaches: 
1. Two howler objects with OnEnd event start;
2. One howler object with changing parameters 

But both situation have problems with stop playing sound or looping two music sprites in time. Find another solution on GitHub, but and this still isn't work (both sprites loop in same time, not one). Please help. 

Howler object init; 
```javascript
  var sound = new Howl({
        urls: ['../music/sound.mp3'],
        buffer: true,
        sprite: {
            a: [0, 18999],
            b: [19000, 9000],
        },
    });

   Howl.prototype.playString = function(str){
        if(str.length>1){
            this._onend[0] = function(){this.playString(str.substring(1,str.length));};
        } else {
            this._onend[0] = function(){};
        }
        if(str.length>0){
            if(str == 'b') {this._loop = 'true';};
            this.play(str.substring(0,1));
        }
    };
    sound.playString('ab');
```

I spend almost week to do this. Please help

**Comment by goldfire** [comment]
If you want `b` to loop, just simply set it as `b: [19000, 9000, true]`. The 3rd parameter tells it to loop. However, I would suggest using 2.0 as it fixes a lot of issues with sprites.
