### ISSUE TITLE
[2.0 beta 11] sound not playing in Android (was working in beta 8)

### ISSUE THREAD

**Issue by Friksel** [goldfire/howler.js#501]
First of all, great work and thanks for the nice lib!
I use howler 2.0 betas in my projects. I skipped beta 10, but in beta 11 the sound is not playing in Android anymore. At least not in chrome browser. This was working before on beta 8. 
After going back from beta 11 to beta 8 again, sound is playing fine again.

**Comment by goldfire** [comment]
This appears to have been related to another issue that was iOS-based and should now be fixed (pos-beta11 commits). I just tested it on Chrome on Android and all of the audio tests/demos worked. If you are still seeing an issue I'll reopen this.

**Comment by Friksel** [comment]
Nice! Thanks!

**Comment by Friksel** [comment]
This still doesn't play sounds, while beta 8 still does. Am I missing something? Is there something changed in the API between beta 8 and beta 11?

**Comment by goldfire** [comment]
No, there shouldn't be anything in the API different. Do you have some sample code?

**Comment by Friksel** [comment]
Yes, this is the howler-part in the project. initSound() is called when the document is ready and playSound() on a mousedown event.

```
var snd, sndLoaded = false;

function initSound() {
	var soundURLs = ['sound.ogg', 'sound.mp3'];
	snd = new Howl({
	    src: soundURLs,
	    autoplay: false,
	    loop: false,
	    volume: 1,
	    onload: function () { sndLoaded = true; }
	});
}

// TRIGGERD BY A MOUSEDOWN EVENT
function playSound() {
  if (sndLoaded) { snd.stop().play(); }
}

```

**Comment by goldfire** [comment]
I just setup an identical test and everything worked correctly. What version of Chrome/Android? Do you have anything outside of that modifying Howler global?

**Comment by Friksel** [comment]
Thanks for your quick actions @goldfire 
I'm using Chrome for Android 49.0.2623.105. There's nothing modified in Howler global.

I did some further testing here today with a simple project from scratch, like you did. I see it working with just one sound too. The same as you have seen. Both on desktop (mouse) as on Android Chrome it's working fine.

But then I created a simple project using multiple instances of Howl and that's when it's happening. Multiple instances are still working fine in desktop browsers, but in Android Chrome, only the LAST sound of the intances loads (or triggers the onload-event) and plays. 
BTW The sounds all have different filenames.

Here's my test code:

HTML:
```
<!DOCTYPE html>
<html>
<head>
	<style>
		.block {
			display:inline-block;
			width:100px;
			height:100px;
			margin-right: 10px;
			background: #F00;
			cursor: pointer;
		}
	</style>
</head>
<body>
	<div id="block0" class="block" data-index="0"></div>
	<div id="block1" class="block" data-index="1"></div>
	<div id="block2" class="block" data-index="2"></div>
	<div id="block3" class="block" data-index="3"></div>
	<div id="block4" class="block" data-index="4"></div>
  	<script type="text/javascript" src="howler.core.min.js"></script>
  	<script type="text/javascript" src="project.js"></script>
</body>
</html>
```

JS:
```
howlerTest = (function() {
    "use strict";


    var snd = [], 
        shp = [],
        soundLoaded = [];
        
    
    (function() {
        for (var i = 0; i < 5; i++) {
            shp[i] = document.getElementById('block'+ i.toString() );
            soundLoaded[i] = false;
            
            
            (function(index) {
                snd[index] = new Howl({
                    src:  ['sound'+index.toString()+'.ogg', 'sound'+index.toString()+'.mp3'],
                    autoplay: false,
                    loop: false,
                    volume: 1,
                    onload: function () {
                        alert('sound ' + index + ' loaded');
                        soundLoaded[index] = true;
                        
                        shp[index].addEventListener('touchstart', onPointerDown);
                        shp[index].addEventListener('mousedown', onPointerDown);
                    }
                });
            })(i);

            
        }
    })();

    function onPointerDown(e) {
        var index = e.currentTarget.getAttribute('data-index');
        alert('pointer down on ' + index.toString() + ' soundloaded[' + index + '] = ' + soundLoaded[index]);

        if (soundLoaded[index]) {
            snd[index].stop().play();    
        }
        
    }

})();
```
Next to this I have the following files in the root:
`sound0.mp3 and sound0.ogg     to   sound4.mp3 and sound4.ogg`

**Comment by Friksel** [comment]
btw I was using 2.0 beta 12 for this tests

**Comment by ztommy** [comment]
maybe your Howler.usingWebAudio = false;
setup the AudioContext not success in line 2055. try debug it.

**Comment by Friksel** [comment]
Thanks for your thoughts @ztommy , AudioContext is initiated already on line 2048, so that works as expected. On line 2103 Howler.usingWebAudio = true and Howler.noAudio = false, so everything seems to be okay there.

**Comment by Friksel** [comment]
@goldfire @ztommy I got to the spot where something is going wrong:
on line 1998 in howler.core.js (beta 12) on the first 4 Howl instances (given my last example code above) the array `self._sounds` is empty when debugging on Android Chrome. Only the last Howl instance (for the fifth sound), is having this array filled with a filename. For this reason the condition `(buffer && self._sounds.length > 0)` returns `false` and the `loadSound()` method is only executed on the last Howl instance.

At the moment there are some other things I need to do (it's a little busy here right now), so I have to stop debugging now, but hope this helps

**Comment by bsliran** [comment]
Hey, I can confirm that is happening for me as well on android (beta12),
iOS Safari/FireFox/Chrome/ works tho.

**Comment by goldfire** [comment]
I made a few commits to address a few similar issues and that seems to have taken care of this issue as well based on my latest testing. I'll reopen if you are still seeing something related to this though. Thanks for the help debugging!

**Comment by Friksel** [comment]
Your welcome. The uncompressed howler works perfect now, thanks!

**Comment by Friksel** [comment]
Hi @goldfire Since thisone (and I guess some other important issues) are fixed, could you, if possible, create a new beta release so that we have a new 'version'-number? Thanks!
