### ISSUE TITLE
unused local variable in the `duration` function

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#507]
the `sound` local variable at the following line is actually not used in the `duration` function :
https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L1346

is there something missing, or just a left-over from a previous refactoring ?

**Comment by obiot** [comment]
and by extension, same for the `id` parameter

**Comment by obiot** [comment]
looks like it should return `sound._duration;` instead :)

**Comment by goldfire** [comment]
This is correct in that the sound isn't used or required there, but it does bring up a good point. When checking duration, do we really want to always get the source duration, or the duration of the sprite being played (which if none is specified would be the length of the full track)?

**Comment by obiot** [comment]
when checking for the duration, is the source duration and the sprite being played not the same ?

**Comment by goldfire** [comment]
The source duration would be the duration of the entire file, which is what the duration method always returns right now.

**Comment by obiot** [comment]
yes, so you can remove the dead code then and the unused argument, or at least comment then :)

**Comment by obiot** [comment]
Cool, my linting task can feel happy again ;):):)
