### ISSUE TITLE
Not works with browserify?

### ISSUE THREAD

**Issue by Bogdaan** [goldfire/howler.js#508]
Hi, i have issues with module loading. Lib not works with amd/commonjs corectly (as described)
```TypeError: Howl is not a constructor```
```TypeError: Howl is not a function```

Сorrect case
```
var Howl = require('howler');

var messageSound = new Howl.Howl({
  src: ....
});
```

**Comment by goldfire** [comment]
75228018eab23a0749f5df611a55043af53f785c should fix that issue.

**Comment by zapalagrzegorz** [comment]
Well, Bogdaan's solutions is still needed.

**Comment by Felix8971** [comment]
You can import howler.core.js file from https://github.com/goldfire/howler.js/blob/master/src/howler.core.js and add this line at the end of the file:

`module.exports = Howl; `

then you just have to import it as a simple module in your main js file:

`var Howl = require('./howler.core.js');`

 `var sound = new Howl({
      src: ['sound/coucou.mp3'],
      volume: 1,
  });`

`sound.play();`

**Comment by idpokute** [comment]
Bogdaan's solutions is still needed....I hope this info should be in the document.
