### ISSUE TITLE
A paused song will still call onend function

### ISSUE THREAD

**Issue by Jones-S** [goldfire/howler.js#509]
I have a song with an onend function (actually that one plays the next song)
If I pause the first song though, the onend will still be called after the duration of the song.
So with a song of 30sec, and pausing after 15s will result in 15s of silence and then the second song is played automatically, but I never resumed playback.

I guess this could be linked to https://github.com/goldfire/howler.js/issues/504

Any ideas how I can get the onend only to execute if a song is really ending (hearable)?

Cheers

**Comment by Jones-S** [comment]
Ok. I got it. I had to pass the songs instance ID to the pause method.
If someone ever wonders how:

First I save the current instance id in a variable
```
var current_playback_id = 0;
song.play(function(sound_id){
    current_playback_id = sound_id; // save intance id
});
```
and pass that one to the pause command
```
song.pause(current_playback_id);
```

Cheers

**Comment by goldfire** [comment]
Just a heads up as well, this shouldn't be an issue in 2.0.

**Comment by Jones-S** [comment]
Because I needed this functionality to stop just all Howls I switched to the 2.0 branch.
Unfortunately some things are not working anymore.

Exactly the code above will not fire anymore, but I still need to save the sound ID.
By using 
```
song.play(function(sound_id){
    current_playback_id = sound_id; // save intance id
});
```

I am getting a error message:
`TypeError: undefined is not an object (evaluating 'o._sprite[e]')`

But how can I retrieve the sound ID with howler 2.0?

Thanks for some help here.

**Comment by goldfire** [comment]
There's no callback anymore, you would do it like this:

```javascript
current_playback_id = song.play();
```

**Comment by Jones-S** [comment]
Ah perfect. That was what I expected in the first place before I had to find out the callback method.
Thanks a lot.
Cheers

**Comment by agentfitz** [comment]
For what it's worth, I am still seeing this bug in the 2.0 branch using the "no callback" syntax. I am on `v2.0.0-beta14`, I provided a couple more details on [issue 504](https://github.com/goldfire/howler.js/issues/504)

**Comment by agentfitz** [comment]
Ok, I figured out how to reproduce this reliably in the 2.0 branch. All you need to do is set the rate and the "end" event becomes unreliable:

```
sound.rate(1.0);
sound.play();
// "end" event will be busted
```

**Comment by vin-ni** [comment]
Doesn't work for me, even when adding `rate`.

Instead of calling pause(), I'm now calling stop(), which doesn't trigger the `end`. My audio is short, so there's no problem jumping back, but I'm thinking, there might be a way to save the time and seek back to the position.
