### ISSUE TITLE
IE11: unload() for html5 audio initiates a new request + results in console error.

### ISSUE THREAD

**Issue by aroth** [goldfire/howler.js#510]
*IE11 on Windows 7*

Calling unload() on a Howl object created with `html5: true` is causing IE to make a new request to `/` which often results in the error:

`MEDIA12899: AUDIO/VIDEO: Unknown MIME type.`

This error is due to the fact that IE has associated a media content type with `sounds[i]._node` and the content returned from the new request is coming back as `text/html`. 

The new request is triggered by this line in `#unload`:

```
sounds[i]._node.src = '';
```

Is it necessary to set `src` to an empty string? And if so -- can it be done in a way that doesn't result in a new request?

See the image below for a full walk through:

![screen shot 2016-04-22 at 2 22 27 pm](https://cloud.githubusercontent.com/assets/542/14751048/0f291022-0896-11e6-98e1-d56a1cd9b203.png)

**Comment by goldfire** [comment]
Thanks, 745a726fe518e48baf8eb9accf144e4875b710a1 should fix this.
