### ISSUE TITLE
no sound on iOS 6.1.6

### ISSUE THREAD

**Issue by Angel-Gonzalez** [goldfire/howler.js#516]
I can't make it work on Ipod iOS 6.1.6 here is my code.
`$(document).on('click', 'a.audio-play', function () {
 sound = new Howl({
            src: [$(this).data('audio')],
            html5: true
        });
        sound.play();
}`
in the array its a url to the file. The playing() property returns false
Any help would be much appreciated

**Comment by goldfire** [comment]
You might try defining the Howl outside of the click callback.

**Comment by Angel-Gonzalez** [comment]
Thanks for the idea, but for my app not make sense to do it without a call, since it's an audio library and have at least 50 sounds on page, i think its not efficient to load all files before any user action. Anyway... i manage to use a pure Web Audio Api function and worked from the click callback. I'll try other approach from your suggestion.
