### ISSUE TITLE
2.0 How to cancel loading before it's finished.

### ISSUE THREAD

**Issue by micahlisonbee** [goldfire/howler.js#520]
If I create a `new Howl()` and want to cancel/reset the object and cancel the `onload` callback before the sound has loaded, is that possible? The use case is when a user selects a different sound (track) before the previous has been loaded.

```js
var track = new Howl({
  src: 'sound.mp3',
  volume: 0.8,
  onend: soundJSComponent.trackFinishedPlaying,
  onload: soundJSComponent.trackHasLoaded
});	
```

**Comment by micahlisonbee** [comment]
Or is it better practice to create a `new Howl()` instance for every separate sound (our app is a library of audio tracks)? If so, what is the best way to reference the instances once they've been created?

**Comment by micahlisonbee** [comment]
To answer my first question, the `unload()` method?

**Comment by goldfire** [comment]
Yes, `unload` would be the only way to stop the download. This destroys the `Howl`, so you'd want to create a new one. Maybe looking at https://github.com/goldfire/howler.js/tree/2.0/examples/player would be what you are looking for, which keeps track of multiple `Howl` instances, but could just as easily just keep one and unload the previous.

**Comment by micahlisonbee** [comment]
Thanks!
