### ISSUE TITLE
AudioContext broken on Android Chrome (at least 50.0.2661.89)

### ISSUE THREAD

**Issue by arya-s** [goldfire/howler.js#522]
We are using howler (2.0 beta 13) to play audio in our SPA and encountered issues on Android phones with Chrome 50.0.2661.89 (issue might exist in lower versions as well but we didn't test that).

Whenever we encounter a new sound to play in our system, we instatiate a new Howl and play it. We allow replaying of sounds in our interface, however after 30 seconds, sounds are not replayable. The same happens when we go to different apps and come back to Chrome.

We tracked the issue down to the AudioContext breaking after 30 seconds and my guess is that it's related to auto suspending.

One workaround is to unload howler every time but obviously we don't want that.

Another workaround, and the route we chose, is to close the current AudioContext in `setupAudioContext` and then call `setupAudioContext` in `_refreshBuffer`.

As this happens on every play, it's not optimal but it fixes our issues.

Edit: Our workaround: https://github.com/arya-s/howler.js/blob/android_chrome_audiocontext_fix/src/howler.core.js

**Comment by goldfire** [comment]
Do you have a reproducible test case? I haven't been able to reproduce in my testing so far.
