### ISSUE TITLE
CLSID?

### ISSUE THREAD

**Issue by pixelhugger** [goldfire/howler.js#523]
Hi

I have been asked to provide a CLSID for Howler, to ensure it runs on a client's network - they lock down everything they don't like and use these ID's as a method of selection.

Is this something that exists or you can create/provide?

Thanks for your help!

**Comment by goldfire** [comment]
You'll need to provide some more details as I'm not even sure what a CLSID is in relation to a Javascript library.

**Comment by pixelhugger** [comment]
Here's the request, with a little more detail:

> Testing has shown that there is an add-in that is currently disabled through group policy. We do this by enabling the Add-on Management policy “Deny all add-ins unless specifically authorised in the Add-on list”. The Add-on list is then populated using the add-ons CLSID which has to be entered in the format {000000000-0000-0000-0000-0000000000000}.
 
> As I am unable to identify the add-in being used by the website for audio playback, I would be grateful if you will advise the name of all add-ins required for correct operation and their corresponding CLSID to enable us to add these to the group policy and which should resolve the issue.

Googling found this:
http://www.danfergusdesign.com/classfiles/generalReference/objectTag.html

> To specify the Quicktime player: classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab"
> To specify the Windows media Player: classid="clsid:22D6F312-B0F6-11D0-94AB-0080C74C7E95" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/ nsmp2inf.cab#Version=6,0,02,902"
> To specify Real Audio: id=RVOCX classid="clsid:CFCDAA03-8BE4-11CF-B84B-0020AFBBCCFA"
> To specify the Flash Shockwave Player : classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/ swflash.cab#version=8,0,22,0"

...which looks about right.  So I 'just' need one for Howler  :)
