### ISSUE TITLE
Fading doesn't work?

### ISSUE THREAD

**Issue by Cailleach-Bhan** [goldfire/howler.js#524]
Hi! I'm not very versed in javascript, so maybe this is a very stupid mistake... But if I want to fade something out, it doesn't seem to work? Fading in doesn't work either. My code (Using 2.0):

```
audio = new Howl({
  src: ['/audio.wav']
});

function audiostart(){
  var audioplay = audio.play();
  audio.play(audioplay);
}

function audiofade(){
var audioplay = audio.play();
audio.fade(1.0, 0.0, 100, audioplay);
}
```

Am I doing the ID's wrong? Please help, I need to get this to work by tomorrow. Thank you so much!

**Comment by goldfire** [comment]
The first issue is that you should only be calling `play` once. You don't need to pass the `soundId` if you aren't playing multiple sounds, so you could just do:

```javascript
var audio = new Howl({
  src: ['/audio.wav']
});

function audiostart(){
  audio.play();
}

function audiofade(){
  audio.fade(1.0, 0.0, 100);
}
```

If you are going to play multiple sounds, be sure to store the value returned from calling `play` in the correct scope.

**Comment by Cailleach-Bhan** [comment]
I do have more than one sound! How would I do it then? Where and how do I need to apply the ID? I am sorry for the trouble, I'm quite new to all this!

**Comment by goldfire** [comment]
```javascript
var audio = new Howl({
  src: ['/audio.wav']
});

var soundId;
function audiostart(){
  soundId = audio.play();
}

function audiofade(){
  audio.fade(1.0, 0.0, 100, soundId);
}
```

**Comment by Cailleach-Bhan** [comment]
Thank you so much for your patience and help! It works now!
