### ISSUE TITLE
unable to play rtmp stream

### ISSUE THREAD

**Issue by ashwin31** [goldfire/howler.js#528]
server url: rtmp://cdn-sov-2.musicradio.com:80/LiveAudio/
mount point: HeartLondon

**Comment by ashwin31** [comment]
hi @goldfire do you have any suggestions? I don't want to deal with flash.

**Comment by goldfire** [comment]
As far as I'm aware, RTMP is a Flash-only protocol and will not work with HTML5 Audio.
