### ISSUE TITLE
issue with access control

### ISSUE THREAD

**Issue by ashwin31** [goldfire/howler.js#530]
I am developing a radio stations aggregation site and I do need to play others streams in my site. Now I am facing issue with CORS I think.

I am getting error in console though its working.

This is from chrome console.
XMLHttpRequest cannot load http://icecast.omroep.nl/funx-hiphop-sb-mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

but I am not getting this error when tried with soundmanager2. 

What am I missing?

**Comment by goldfire** [comment]
If you are using 2.0 you need to set `html5` to `true` or `buffer` to `true` on 1.x. It works on soundmanager2 because it is using HTML5 Audio by default, which doesn't have the CORS limitation like Web Audio. Setting the property in howler forces the same behavior.
