### ISSUE TITLE
Performance/leak issue.

### ISSUE THREAD

**Issue by bQvle** [goldfire/howler.js#532]
When I leave my game open for several hours, settings the volume (setValueAtTime) of howls becomes a heavy task.

![image](https://cloud.githubusercontent.com/assets/12952595/15635040/44a53cfc-25d4-11e6-915b-f7ae6ae16212.png)

Here is a json represensation of all howls (Howler._howls)
https://gist.github.com/bQvle/318aac6ef9e7a4cea11f860296e9c52f

And here is one of a fresh instance with no issues
https://gist.github.com/bQvle/ab18b3b86de0f3030e4a263ec2cd2493

**Comment by goldfire** [comment]
Can you provide some more details about your implementation? We have more sounds than that in CasinoRPG and haven't seen similar behavior.

**Comment by bQvle** [comment]
Basicly I have a bunch of active events/objects thats updated in a loop. if the event has a sound attached to it I update the volume (based of its distance to the "camera/screen" center). ustually my entire scene has 30 active events. (but that includes things without sound) and the events usually last for 1-30 seconds before they are cached and later reused.

I'll do some more testing tomorrow (I need to leave the game running for the night) If its because of something i do, it could be if i fail to manage the Active/Cache property and I end up with the same object multiple times in Active. (causing it to call the volume function several times each tick). it doen't seems so in small testing. but I'll need to have a look when its actually taking the hit.

**Comment by goldfire** [comment]
Any updates on this? I tested this out on our game leaving it open for quite some time (we do something similar where we update volume of different objects on screen based on distance) and setValueAtTime barely registered, so I'm still not sure how to reproduce.

**Comment by bQvle** [comment]
Hi James, 

I'll check it again soon, we suddenly got busy because someone found our game and made a youtube video. suddenly we were on literally every game-site on the interweb :) so all focus had to shift towards servers, critical exceptions etc. :)

**Comment by bQvle** [comment]
Hi James,

Its still a problem (I left this running for 8 hours)
![image](https://cloud.githubusercontent.com/assets/12952595/15806397/c6c35f5c-2b42-11e6-92b0-1f28090a86c0.png)


The Animate function is the gameloop which calls EventHandler.UpdateEvents

All that does is:
```
UpdateEvents: function (delta) {
        for (key in this.Active) 
            this.Active[key].update(delta);  
    }
```

Theres only 18 Active Events (not all of them have sound, maybe 50%) and only if they are visible on screen.

```
Object.keys(Game.Server.EventHandler.Active).length 
18
```

This is whats in the "AirDrop" event's update function. (its a looping plane engine sound)

```
if (!this.soundPlaying) {
        if (onscreen) {
            this.engineSound.Play(this.soundPosition.x, this.soundPosition.y);
            this.soundPlaying = true;
        }
    }
    else {
        if (!onscreen) {
            this.engineSound.Stop();
            this.soundPlaying = false;
        } else {
            this.engineSound.SetPosition(this.soundPosition.x, this.soundPosition.y);
        }
    }
```

and this is the SetPosition function that adjusts the volume 
```
Game.Objects.Sound.prototype.SetPosition = function (x, y) {
        this.distanceFactor = Point.Distance(Game.Camera.audioCenter.x, Game.Camera.audioCenter.y, x, y);
        var t = this.distanceFactor / 2500;
        if (t < 1) t = Math.sin(Math.pow(t, 0.3) * Math.PI * 0.5);
        this.distanceFactor = Lerp(1, 0, t); 
        var volume = this.currentVolume * this.distanceFactor;
        this.audio.volume(volume, this.id);
    }
```



The AirStrafe which takes more CPU time has 2 sounds, one for engine and one for shooting. none of them are looping. but both uses the same SetPosition function.

All sounds gets a random variation in rate every time they are played. and its not a problem in the beginning. (just after many hours).

**Comment by bQvle** [comment]
Hi James, did you solve this issue?

**Comment by goldfire** [comment]
I've never been able to reproduce this. Happy to reopen and keep looking if we've got any other details to work off of.

**Comment by bQvle** [comment]
All I can think of is that I change the rate a lot, could there be any leaks in that regard?

If you want you could try running http://tankwars.io after 5-6 the performance drop should be really noticable, and if you record the timeline, it shows that it spends most of the time in "setValueAtTime"
