### ISSUE TITLE
HTML5 Audio and looping sound not working

### ISSUE THREAD

**Issue by JacoBotha** [goldfire/howler.js#533]
Hi Guys

Ive noticed when using homescreen mode on iOS devices using a version of iOS lower than 9.0 that looping does not work correctly when using audiosprites.  What I am seeing is that it plays the correct sprite but instead of looping that sprite it just continues playing the mp3 file that contains that sprite.

This might be related to the following issue : #269 

The solution there seems to be forcing HTML5 Audio on versions of iOS prior to 9.0

I have done a test using chrome on MAC and forcing HTML5 Audio, which resulted in the same issue.

So I had a look at the ended() function, particularly at the following section:

    // Restart the playback for HTML5 Audio loop.
    if (!self._webAudio && loop) {
        self.stop(sound._id).self.play(sound.id);
    }

It seems that chaining the stop() and play() functions does not work as intended, resulting in some timing issues.  When I change the code to look like this :

    // Restart the playback for HTML5 Audio loop.
      if (!self._webAudio && loop) {
        self.once('stop', function(){
          self.play(sound._id);  
        }.bind(this));

        self.stop(sound._id);
    }

Looping works again(although not very seamless)

**Comment by goldfire** [comment]
Can you give a test case? I just setup a fiddle that forces HTML5 and loops a sprite that works as expected on Chrome.

https://jsfiddle.net/kabdddaq/

**Comment by JacoBotha** [comment]
After some testing it seems to be the sprite I am using.  Could you give an example of the command you used to create the audiosprite in you fiddle.
