### ISSUE TITLE
When calling howl.unload() and play(): Failed to set the 'buffer' property on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by arya-s** [goldfire/howler.js#534]
I have encountered an issue when calling `howl.unload()` on some howls, but not all howls part of Howler.

Please see https://jsfiddle.net/yzv7txsy/ and execute the following steps:
1. Click all play buttons once. Sound should play.
2. Click reset
3. Click the static play buttons which should play sounds since `unload()` was not called on the sound's `howl` object.
4. The following stack trace shows up in console:

```
howler.core.js:1726 Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
Howl._refreshBuffer	@	howler.core.js:1726
playWebAudio	@	howler.core.js:636
Howl.play	@	howler.core.js:663
window.playStatic	@	(index):65
onclick	@	(index):118
```

Maybe there's a better way to handle caching/unloading?

Edit:

This seems to happen when the audio URI of the non-unloaded howl matches the URI of the unloaded howl as was the case in the above fiddle. It works fine here with unique URIs:
https://jsfiddle.net/t6362hkn/1/

Edit 2:

When opening 3 tabs of https://jsfiddle.net/t6362hkn/1/ on Android 4.4.2, Chrome 50.0.2661.89 audio stops playing completely when switching between tabs.

**Comment by goldfire** [comment]
This should now be fixed with 851bf349c155db40462613d88848ab7f23e05c02.
