### ISSUE TITLE
setting the playback position on long mp3 files

### ISSUE THREAD

**Issue by agentfitz** [goldfire/howler.js#537]
First of all, thank you for making Howler.js, it kicks butt.

I have a question regarding the playback of long mp3 files (10-20 minutes or perhaps longer), and setting the playback position dynamically (with javascript) based on user interaction (for example, using arrow keys to skip ahead or rewind a track).

From my experience with html5 audio, the currentTime position is unreliable when dealing with long files, leading to inaccurate placement of the playhead upon changing the position.

I noticed that howler.js has a setting `buffer: true`, or `html5: true` in the 2.0 branch, that should be used for long files, but my concern is that this will lead to the inaccurate position issues I am describing.

Are you aware of the issue I am describing? Would there be any difference in using the 1.0 or 2.0 branch in the way this is handled? 

Here is a [stackoverflow post](http://stackoverflow.com/questions/25468063/html5-audio-currenttime-attribute-inaccurate) which gets into this and also references aurorajs as a possible solution.

My Web/Html5 audio knowledge is limited so I thank you for whatever insight you can share.

Brian

**Comment by goldfire** [comment]
I haven't seen this specific issue before, but I would only recommend using MP3 as a fallback with WebM as the default. I'm guessing you won't see this problem with a WebM file.

If the audio is that long, you are going to have worse issues if you try to play it through Web Audio instead of HTML5 Audio. You'll have to download the full file upfront and decode it before playback can begin. Also, decoding such a large audio file in the browser can often run into issues and cause crashing (not as big of an issue as it used to be, but can still be an issue, especially on lower-end hardware).

**Comment by agentfitz** [comment]
Ever since your comment I've been researching this topic, I'm happy to use WebM if it does the trick, but I've seen nothing about WebM being used for [purely audio](http://stackoverflow.com/questions/37820448/is-webm-for-audio-too-or-just-video). Everything I'm seeing talks about WebM as a video specific format. Am I missing something?

**Comment by goldfire** [comment]
WebM is definitely used for audio as well, we use it as the default in all of our projects. It can also use the .weba extension, but .webm works just the same.

https://github.com/goldfire/howler.js/tree/2.0#format-recommendations

**Comment by agentfitz** [comment]
Ok, last question (sorry to bother you on this). How do you generate your WebM files? I have many thousands of mp3's. I tried to convert one to WebM using FFMPEG and it came out as a zero byte file. I've also searched far and wide for an mp3 to webm conversion utility and none seem to exist. Thoughts?

**Comment by goldfire** [comment]
ffmpeg has never failed me for any converting needs, but check the console output to see if the needed library isn't installed on your computer. It is the same as converting to and from any other format with ffmpeg for the most part, as long as you have the codecs installed.

**Comment by agentfitz** [comment]
Thanks James! The output error it showed me did not indicate the [importance of the order](http://stackoverflow.com/a/35247468/720486) of the -strict -2 flags. Got it now though, thanks for your help. I'm going to play with webm and see if it works to address this currentTime property situation in long files.
