### ISSUE TITLE
Howler 2.0 - fade() function doesn't update volume property

### ISSUE THREAD

**Issue by shibekin69** [goldfire/howler.js#539]
Hi!

Playing around with Howler 2.0, and I notice that when doing a fade() on a Howler object, upon finishing the fade in or out, the final tweened volume of the object doesn't get updated to reflect the new volume value.  So for example:

var sound = new Howl({...});
sound.fade(0, 1, 500);

//Once sound has faded in type the ff in console. Returns 0 rather than 1
sound.volume();

So if sound has a volume of 1, then I fade it out to 0, sound.volume() returns 1 rather than 0.

I also noticed that I can't just assign to the onfade (function) property once the Howl object has been initialized like so:

var sound = new Howl({...});
sound.onfade = function() { console.log('This should show in the console after fading, right?'); }
sound.fade(0, 1, 500);

Update: I went back to Howler 1.1.29, and the fade() function there updates the volume property after the tween.

**Comment by goldfire** [comment]
Do you have a test case? I just setup a fiddle with what I thought you were describing, but it works as expected: https://jsfiddle.net/w6Lfodk0/.

Also, you can't assign directly to `onfade`, that can only be assigned as part of the `Howl` options. There is an `on` and a `once` method for listening for events in 2.0.

**Comment by eZethNesthrown** [comment]
I have tested the code and it didn't work as it supposed to be.
```javascript
var sound = new Howl({
	src: 'https://dl.dropboxusercontent.com/s/1ycx2rq7szhi8sx/test2.mp3',
	autoplay: true,
	volume: 0,
	onload: () => {
		console.log(sound.volume());
		sound.fade(0, 1, 5000);
		sound.once('fade', function(){
			console.log(sound.volume());
		});
	},
	onplay: () => {
		console.log('Sound played')
	}
});
``` 
Output is
```
0
Sound played
0
```
Both `sound.volume()` returns 0

**Comment by goldfire** [comment]
@eZethNesthrown Thanks for the test case! The latest commit on master should fix this.

**Comment by ratul-devR** [comment]
Is there any way to fade at the ending of the audio?

**Comment by muava12** [comment]
i get this problem now
