### ISSUE TITLE
returned value from seek() incorrect when player is paused

### ISSUE THREAD

**Issue by agentfitz** [goldfire/howler.js#543]
I am on the 2.0 branch (v2.0.0-beta14)

Scenario 1:

1. start playback of file `var mySoundId = mySound.play()`
2. seek sound `mySound.seek(10, mySoundId)`
3. call `mySound.seek();`
3. correct time reported

Scenario 2:

1. start playback of file `var mySoundId = mySound.play()`
2. **pause** playback of sound `mySound.pause(mySoundId);`
3. seek sound `mySound.seek(10, mySoundId)`
4.  call `mySound.seek()`
5. incorrect time reported

**Comment by goldfire** [comment]
Thanks, this should be fixed with c6f826d4532c2695c0dae6b77bda758639dce597.

**Comment by agentfitz** [comment]
Great news! Thanks James.
