### ISSUE TITLE
Global Volume not working?

### ISSUE THREAD

**Issue by AshotN** [goldfire/howler.js#544]
I can't seem to get the global volume function to work.

`
import { Howl } from 'howler'

Howl.volume(value);
`

Gives the error

`Uncaught TypeError: _howler.Howl.volume is not a function`

**Comment by goldfire** [comment]
What environment are you trying to do this in and what version of howler?

**Comment by AshotN** [comment]
Node using React with Babel

Howler 2.0 Beta 14

**Comment by goldfire** [comment]
Global volume is changed with `Howler.volume()`.

**Comment by hirasso** [comment]
Seems like you have to call it like this at the moment:
```javascript
Howler.Howler.volume(0.3);
```
of course this looks kind of broken ;)
