### ISSUE TITLE
calling rate method breaks "end" event.

### ISSUE THREAD

**Issue by agentfitz** [goldfire/howler.js#546]
howler.js v2.0.0-beta14 - testing in Chrome browser on OSX.

_Setting the playback rate (using the `sound.rate()` method) will cause the Howler `end` event to fire unexpectedly._

Scenario 1:
1. load your sound, passing the `rate: 1.0` option into the load method
2. call `sound.play();`
3. call `sound.pause();`
4. "end" even never fires. correct behavior

Scenario 2:
1. load your sound
2. call `sound.rate(1.0);`
3. call `sound.play();`
4. call `sound.pause();`
5. "end" event will fire after x number of seconds (x being the length of the audio file), even though playback has been paused. incorrect behavior.

Scenario 3 (same issue, even simpler):
1. load your sound
2. call `sound.rate(1.0);`
3. "end" event will fire after x number of seconds (x being the length of the audio file), even though the sound was never played. incorrect behavior.

**Comment by goldfire** [comment]
Thanks, fa457698d8b7ab04c948a1ab3876cc9b1642d23f should take care of this one.
