### ISSUE TITLE
Loop and seek breaks when switching tabs

### ISSUE THREAD

**Issue by AnderbergE** [goldfire/howler.js#548]
When I play a sound which is looping it will not work correctly when I switch tabs.

I used this fiddle: https://jsfiddle.net/kabdddaq/
And changed `sound.play('one');` to
```
sound.play('beat');

setInterval(() => {
	console.log(sound.seek(), Date.now());
}, 1000);
```

Start the fiddle and then change tabs. Looping will be delayed, sometimes about one second. Is there anyway to fix this? You can see by the console printouts as well.
I've also noticed that in some cases the seek function will get out of sync. I have in my project a sound that is 4 seconds, it loops good, but the seek will not display the accurate time, it will wander away from where it actually is in the sound. That makes all events fire at the wrong times as well. In that case I use mp3 encoding.
I have these issues mostly in Chrome 51, but also in Firefox.

I use Howler 2.0 beta 14.

**Comment by goldfire** [comment]
This is because all browsers throttle background tabs, including timeouts. There is no way to workaround this throttling, and I haven't found any way to work around the issues you describe other than pausing playback when switching tabs.

**Comment by AnderbergE** [comment]
I see, that's a bit sad for all of us :(
But thank you for clearing up the issue for me!

**Comment by goldfire** [comment]
Yeah, it makes sense why it is done, but certainly causes issues in this regard. We've faced problems with this in our own games. If we find a solution we'll of course get it into howler.js.
