### ISSUE TITLE
Stop event fired at the end of a loop

### ISSUE THREAD

**Issue by Mesoptier** [goldfire/howler.js#549]
I expected the `stop` event to be fired only when a sound will no longer continue playing. But with both `html5: true` and `loop: true`, it will be fired simultaneously with the `end` event when a sound reaches its end, before starting again. This is because the following [code](https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L1589) calls `.stop()` and `.play()`:

```
// Restart the playback for HTML5 Audio loop.
if (!self._webAudio && loop) {
  self.stop(sound._id).play(sound._id);
}
```

However, I don't think events should be emitted for these calls as they are an implementation detail.

Howler version: `2.0.0-beta14`

**Comment by bbottema** [comment]
This is still (again?) a bug:
```
let playingInstance = sound.play();
sound.loop(true, playingInstance);
```
This still raised an 'end' event when the sound is done and loops.
