### ISSUE TITLE
sound.rate() not working on Chrome in Android

### ISSUE THREAD

**Issue by agentfitz** [goldfire/howler.js#551]
I'm not sure if there is a workaround for this or not, but the howler `rate()` method is not having any effect on Android Chrome.

There seems to be an [outstanding issue](https://bugs.chromium.org/p/chromium/issues/detail?id=263654) for this in the Chromium issue tracker. Is it just not supported?

Based on my testing of the `rate()` method:

| browser | platform | status |
|--------|-------|------|
| Chrome | osx | OK |
| Firefox | osx | OK |
| Chrome | android | not working |
| Firefox | android | OK |

**Comment by goldfire** [comment]
Yes, until that issue is fixed, I don't think there's any way around that. However, this does only affect HTML5 Audio, so if you don't set `html5` to `true` then rate will still work.
