### ISSUE TITLE
no sound on iOS with V2

### ISSUE THREAD

**Issue by C10B** [goldfire/howler.js#552]
Hi,
Not sure if this is the right place to ask, (it's more likely to be an issue with my code that with the howler library!)

I have a demo running and it's fine on my Windows computer, but iOS is silent. I'm using MP3 files and simply playing them when certain actions happen on the screen.

Any tips please? If you want to see my demo let me know and I can send you a link.

Thanks
Tim

**Comment by goldfire** [comment]
Are any of these actions triggered by a screen touch? No sound can play on iOS until a sound is played within a user event, namely `touchend`.

**Comment by C10B** [comment]
I have this
<div class="pagenext" onclick="nextPage();"></div>

and it's nextPage() that calls the sounds to be played

**Comment by C10B** [comment]
onclick="nextPage();"

**Comment by goldfire** [comment]
Okay, then I would need to see some sample code that reproduces this.

**Comment by C10B** [comment]
http://www.eveshamsolutions.co.uk/audiobook5/default.html
click anywhere on the first page and the sound should play
click again to the 2nd page and new sounds should fade in, and some fade out
(only the first 3 pages are done so far)

**Comment by goldfire** [comment]
From first glance, it looks like the issue may be that sound is triggered indirectly from user input. It is actually being called inside of a timeout after an async call to load some data, which the browser won't actually consider coming from user input. You don't actually have to play each sound within a click, but audio has to be "unlocked" before any others will start.

**Comment by C10B** [comment]
I see. I'll add another sound directly to the click and see what happens. Thanks for your help so far

**Comment by C10B** [comment]
Can you have another look? I've added a touchend event (and show an alert to prove it is firing). Still silent at the moment. Thanks v much

**Comment by goldfire** [comment]
Try changing it to `touchend`. As of iOS 9, `touchstart` won't work to unlock audio.

**Comment by C10B** [comment]
I must still be doing something wrong as my iphone is still silent in both Safari and Chrome. I've tried using touchstart, touchend, onclick. Do you have some kind of "hello world" example that you know works on iphone that I can start with? Thanks.

**Comment by goldfire** [comment]
Yes, the tests in https://github.com/goldfire/howler.js/tree/2.0/tests or the examples in https://github.com/goldfire/howler.js/tree/2.0/examples/. You can see the tests live at https://beta.howlerjs.com/assets/howler.js/tests/.

**Comment by C10B** [comment]
I think I've found it!
In your tests you add html5:true to your sounds. Without this my phone is silent, but with it I've started getting something. I made several changes to the code so I can't be 100% sure yet - but I'll experiment further and let you know (although you probably know already if it's likely to be the cause). Thanks. Tim.

**Comment by C10B** [comment]
OK HTML5 isn't the real issue. The real issue is this. If I define a new howl, click something to unlock it, I can then play it many times. I can assign a new howl to the same variable and therefore play different sound. But... what I can't do is create a completely new howl and make it work - it's as if the click to unlock a howl instance only unlocks that one, and new ones can't be created on the fly. (only on ios - on my pc it all works perfectly well). 
Do you want me to try and rig up a demo of this problem?

**Comment by C10B** [comment]
Please have a look at this demo http://www.eveshamsolutions.co.uk/audiobook5/howlproblem.html which is minimal code to show the problem I am facing. After all my talking rubbish above, it might well work out to be an issue with timers.

**Comment by goldfire** [comment]
It actually appears to be an issue with the encoding of the files themselves. The tests/examples use a mix of `html5: true` and not. On mobile I highly recommend not using `HTML5 Audio unless it is a large audio file, as the Web Audio API works much better most of the time.

I re-encoded your jump.mp3 file with ffmpeg (just using `ffmpeg -i jump.mp3 jump2.mp3`), switched back to Web Audio and it all worked perfectly on desktop and iOS.

https://jsfiddle.net/ge23nqzz/

**Comment by C10B** [comment]
Your fiddle works fine for me too. How strange though, that the sound file worked OK once, but not twice. I appreciate your help - I'll now encode my MP3 files. (I don't really understand what the re-encoding did - but I'll do the same to all my files and see what happens!)

**Comment by C10B** [comment]
Conclusion: in the end I've had odd problems with MP3 files on iOS. Some play once, some play twice, some don't play at all. The ffmpeg converter seemed to fix some (but truncate others). Another online converter also created MP3s that didn't play on iOS. At this stage I don't know if it's a quirk with Apple, or with Howl. For now though I've converted everything to WAV and all issues have gone away. All of my sound clips are very short so the extra file size doesn't worry me.

**Comment by C10B** [comment]
(Note: In case anyone finds this useful, WAV files take a very long time to load before they can be played. AAC files appears to be as fast loading as MP3 and are currently working perfectly on iOS.)

**Comment by isaacalves** [comment]
I've spent hours trying sounds to work on iOS and tried all sorts of things. I resisted using CreateJS for a long time but when I did it, it worked straight away. I wish I could have sounds working on iOS using a lean API like Howler, because It's so much leaner. Hope that's helpful!
