### ISSUE TITLE
Reusing an existing howl object

### ISSUE THREAD

**Issue by mvinayakam** [goldfire/howler.js#558]
Hello

I have a playlist of mp3s to play for my audio guide application. It works perfectly on my PC. However on mobile devices, it has started giving me the dreaded "need User gesture" error.

I am using howler.js version -  v1.1.29

Now a single mp3 can be played by clicking on the play but I want it to switch over to the next one when onend is fired. Creating a new howl object triggers the same "User gesture" error.

How can I reuse the same howl object for the new mp3 url?

` function playAudio() {
        sound = new Howl({
            urls: [exhibitAudioMedia[currentExhibit][currentIndex]["url"]],
            buffer: true,
            loop:false,
            onload: function () {
                console.log("Song loaded");
            },
            onend: function () {
                console.log("On end fired");
              //  playNext();
                currentIndex = currentIndex + 1;
                playAudio();
            }
        }).play(function (soundId) {
            console.log("soundId: " + soundId);
            currentSoundId = soundId;
        });
    }`

**Comment by goldfire** [comment]
This is an issue that we'll need to figure out a real solution for, but until then a hacky solution could be something like:

```javascript
sound.stop();
sound._sounds[0]._node.src = '/path/to/new/sound.mp3';
sound._sounds[0]._node.load();
sound.play();
```

**Comment by mvinayakam** [comment]
Thanks.

**Comment by zerdmann** [comment]
Curious if this issue ever got an official solution or if this workaround is still the best solve for this?

**Comment by QiannanXu** [comment]
But in this case the sound duration is not updated.
