### ISSUE TITLE
Issue with loop after resuming

### ISSUE THREAD

**Issue by Tokyonono** [goldfire/howler.js#56]
Hi,
Thanks for the great library.
I have a problem when resuming a music which must loop: only a small portion of the sound loops, it doesn't restart from the beginning. I guess that the current position ("pos") is somehow corrupted.
Here is how to reproduce it:
1/ Load some sounds (I do it in a class)

``` javascript
// sound
sound: false,
soundFX1: new Howl({urls:["SFX1.mp3","SFX1.ogg"]}),
soundFX2: new Howl({urls:["SFX2.mp3","SFX2.ogg"]}),
soundFX3: new Howl({urls:["SFX3.mp3","SFX3.ogg"]}),
music: new Howl({urls:["music.mp3","music.ogg"], volume:0.5, loop:true}),
```

2/ Start the music on a click event:

``` javascript
toggleSound: function () {
        if(this.sound) this.music.pause();
        else this.music.play();
        this.sound = !this.sound;
}
```

3/ Play some sounds:

``` javascript
playSoundEffect: function () {
if (this.sound){
        var playablesounds = [this.soundFX1, this.soundFX2, this.soundFX3];
        var soundtoplay = playablesounds[getRandomInt(0,2)];
        soundtoplay.play();
    }
}
```

For information: function getRandomInt (min, max) {
    return Math.floor(Math.random() \* (max - min + 1)) + min;
}

4/ Toggle sound near the end of the music by calling toggleSound() : only a small portion of the sound will loop. I could not determined exactly how or when it happens...

For now I decided to replace "this.music.pause();" by "this.music.stop();". It is not the behaviour I want, but it works.

**Comment by huwllewellyn** [comment]
This was my solution
```
let gasLooper;
let gasSound = new Howl({
    preload:true
  , src: require('./assets/audio/Gas-loop.mp3')
  , autoplay: true
  , volume: 0.5
  , onplay: ()=>{
    gasLooper = setTimeout(()=>{
      gasSound.play();
    },450);
  }
  , onstop: ()=>{
    clearTimeout(gasLooper);
  }
});
```
