### ISSUE TITLE
Sounds do not play when master volume is 0 before play

### ISSUE THREAD

**Issue by AnderbergE** [goldfire/howler.js#561]
Create a sound. Then do this:
```
Howler.volume(0);
sound.play();
Howler.volume(1);
```

Sound is not heard. It seems to be playing, but it volume is 0, though it says 1. If you set sound.volume(1); after Howler.volume(1); you will hear the sound.

(Borrowed an older jsFiddle and changed it)
https://jsfiddle.net/ge23nqzz/1/

**Comment by goldfire** [comment]
Thanks, this should be fixed with 5ea9cb650592f3c9d44517ca3821265adb261136.

**Comment by AnderbergE** [comment]
Great! Thank you!
