### ISSUE TITLE
Howl.unload() on a object with buffer set to true does not cancel the request

### ISSUE THREAD

**Issue by Dadibom** [goldfire/howler.js#566]
When changing music, I call both stop() and unload() on the old tracks in queue. Note that these are tracks that have been created but the clip has not been played, in order to reduce the gap between tracks. The downloading seems to stop, but the request remains flagged as "not complete" in chrome. This causes the browser to hit the max parallell request limit after a while and all requests will be stalled, not even letting me refresh the page.

**Comment by goldfire** [comment]
What version are you using?

**Comment by Dadibom** [comment]
1.1.29!

**Comment by goldfire** [comment]
This appears to have been fixed in 2.0.

**Comment by Dadibom** [comment]
Indeed it is, and there is even less delay when playing a clip in 2.0, so that's perfect. Thanks! :)
