### ISSUE TITLE
Documentation (2.0 branch)

### ISSUE THREAD

**Issue by Dadibom** [goldfire/howler.js#571]
Hey, this part of the documentation is probably wrong. It lists the global method 'pos(x,y,z)' two times with different explanations.

`Global Methods

pos(x, y, z)

Helper method to update the stereo panning position of all current Howls. Future Howls will not use this value unless explicitely set.

pan: Number A value of -1.0 is all the way left and 1.0 is all the way right.
pos(x, y, z)

Get/set the position of the listener in 3D cartesian space. Sounds using 3D position will be relative to the listener's position.

x: Number The x-position of the listener.
y: Number The y-position of the listener.
z: Number The z-position of the listener.`

**Comment by goldfire** [comment]
Thanks for catching that, fixed now!
