### ISSUE TITLE
Fade does not alter the return value of volume()

### ISSUE THREAD

**Issue by Dadibom** [goldfire/howler.js#575]
I'm creating a howl, playing it and using fade(0,desiredvolume,time) to fade the track in. If desiredvolume is 0 (anything over will make volume() work correctly), the track will be quiet as expected but calling volume() will return 1. This was not the case in 1.x, only in the 2.0 branch.

**Comment by Dadibom** [comment]
It does not matter if i manually call volume with 0 before the fade call, fade(0,0,time) will still make volume() return 1

**Comment by Dadibom** [comment]
Quick fix: throw this into the very beginning of the fade method
`if(e==0&&o==0){this.volume(0);return}`

**Comment by alvinsight** [comment]
This might explain some weird behaviour I've been getting, I ended manually tweening the volume I think

**Comment by alvinsight** [comment]
Just to make sure @Dadibom the master branch of howler is now the v2, so if the master branch works then it's not v1 -> v2 problem
