### ISSUE TITLE
Base64 encoded audio/x-mp3 not detected

### ISSUE THREAD

**Issue by Mirodil** [goldfire/howler.js#576]
Basic example does not work with `base64`
https://jsfiddle.net/Mirodil/rertdm41/

**Comment by goldfire** [comment]
Your sample fiddle is working for me. Where are you not seeing it work?

**Comment by Mirodil** [comment]
can you check now, in my browser it is not working (Chrome 51.0.2704.103 m )

**Comment by goldfire** [comment]
If you change to `data:audio/mp3` instead of `data:audio/x-mp3` it works: https://jsfiddle.net/rertdm41/4/. We'll have to get that added in in an upcoming update.

**Comment by Mirodil** [comment]
thanks
