### ISSUE TITLE
Audio on "end", is getting triggered as soon as we play the audio for the 2nd time

### ISSUE THREAD

**Issue by chetansind** [goldfire/howler.js#580]
Audio callback on end is not triggering on end of play when it is played for the second time.
When an audio is played for the second time, on "end" is getting triggered as soon as we play the audio. But it works fine when we play it for the first time on page load.
 
Please advise.

**Comment by goldfire** [comment]
Can you provide sample code?

**Comment by chetansind** [comment]
Here in the below code, i have created methods to load, play and stop. Where in I'm using callback to play sequence of audio files, by taking names added in the array "sounds" as queue. 

Im using the callback to play the next audio in the array. First time the callback is getting triggered and the audios in the  array is playing one after the other, but when I call the the audio to play in between the list of array "sounds", the end event is getting triggered calling of play method and all audio files in queue are playing and overlapping. Don't know why it is happening.

Please suggest.

var sounds = {},
		 soundsDuration = {},
        resumeSounds = {},
        AlternateAudioManager,
        fadeOutInterval;
		
	AlternateAudioManager = {
        slideDuration: 0,
        soundsDuration: sounds,
        loadSound: function (name, path, type, volume, callback) {            
            var soundpath = "./assets/sound/",
			request;

            soundpath += path + ".mp3";

            if (sounds[name] !== undefined) {
                console.log("sound with this name already exists");
                callback();
                return;
            }
            sounds[name] = new Howl({
                urls: [soundpath],
                onload: function () {
                    console.log("Loaded sound: - " + soundpath);                    
                    sounds[name].audioDuration = sounds[name]._duration;
                    console.log("sounds[name].audioDuration : " + sounds[name].audioDuration);
					
					if(callback !== undefined){
						callback();
					}
                }
            });
            sounds[name].type = type;
            sounds[name].playing = false;
            sounds[name].pausestate = false;
        },
        unload: function (name) {
            if (sounds[name] !== undefined) {
                sounds[name].unload();
                
                console.log("sounds[name]. unload" + sounds[name]);
            }
        },
        playSound: function (name, loop, callback) {
            //debugger;
            try {                
                    //sounds[name].source.start(0);
                    console.log("./assets/sound/" + name);

                    if (loop || sounds[name].type === "effect") {
                        sounds[name].volume(0.2);
                    }
                    
                    sounds[name].playing = true;
                    sounds[name].callback = callback;
                    sounds[name].play();
                    if (sounds[name].callback !== undefined && sounds[name].playing !== undefined) {
                        sounds[name].on('end', function () {
                            //console.log('Audio ended');
                            sounds[name].playing = false;                            
                            sounds[name].callback();
                            
                        });
                    }
                
            }
            catch (e) {
                alert(e);
            }
        },
        stopAllNonLoopSounds: function () {
            var item;
            for (item in sounds) {

                if (sounds.hasOwnProperty(item)) {
                    if (sounds[item] !== undefined)
                        if (!sounds[item].looping) {
                            console.log('stop sound: ' + sounds[item]);
                            sounds[item].stop();
                        }
                }
            }
        }
    };`

**Comment by goldfire** [comment]
It is difficult to tell without being able to actually test the sample, but I would suggest first upgrading to 2.0 and looking at the example which works similar to how you describe: https://github.com/goldfire/howler.js/tree/master/examples/player.

**Comment by chetansind** [comment]
I did used the new 2.0 version, post that i'm getting error
"howler.js:394 An array of source files must be passed with any new Howl."

`screeshot`
![image](https://cloud.githubusercontent.com/assets/3175165/17241741/0fd171c0-5591-11e6-95ad-5030cb04ee56.png)

**Comment by chetansind** [comment]
can we remove the event on "end" in howler JS?

**Comment by goldfire** [comment]
There is a migration guide here at https://github.com/goldfire/howler.js/blob/master/CHANGELOG.md and yes, in 2.0 you can set an event to only fire once with `once`.

**Comment by chetansind** [comment]
Thanks, it was helpful. :+1:
