### ISSUE TITLE
Trouble with pause()

### ISSUE THREAD

**Issue by elachere** [goldfire/howler.js#582]
I'm using the Howler js library to set a player in an app running through Electron. First everything seemed to work well, but after a few weeks using the app, a bug occurs repeatedly, but not constantly : the `pause()` function doesn't work. Here's some piece of code : 

Initialization : 

        var is_paused = true;
		var currentTrack = "track1";

		var tracks = 	{"track1" :  new Howl({urls: ['path/to/track1.mp3']}),
						"track2" : new Howl({urls: ['path/to/track2.mp3']}),
						"track3" : new Howl({urls: ['path/to/track3.mp3']})
		};
Then I have a few buttons for play/resume, pause, stop, and play a specific track : 

    $('#playS').click(function(){
			if (is_paused){
				tracks[currentTrack].play();
				is_paused = false;
			}
		});

    $('#pauseS').click(function(){
			tracks[currentTrack].pause();
			is_paused = true;
		});

    $('.trackBtn').click(function(){
			tracks[currentTrack].stop(); 
			currentTrack = $(this).attr('id');
            tracks[currentTrack].play();
			is_paused = false;
		});

The problem is that sometimes (generally after 40-45 min of a track playing), the `pause()` function just do nothing, which is really annoying cause I need to pause the track and play another 30 sec file and then resume the current track. I checked the console while the bug occurs, it says absolutely nothing. I have no idea where the bug comes from.
One more thing, when `pause()` doesn't work, if I click `play()` the track plays from the begining, and I have control on this second instance of the track. It's like the first instance has reached end, but still playing, I don't understand what's happening, really need help on this.
Thank's in advance.

**Comment by goldfire** [comment]
Have you tried upgrading to 2.0 to see if that fixes the issue?

**Comment by elachere** [comment]
That's what I did and indeed it fixed the issue, I forgot to feedback. Closing this :)
