### ISSUE TITLE
Start playing sound when phone locked

### ISSUE THREAD

**Issue by whimsicaldreamer** [goldfire/howler.js#585]
I am making a chat script where I need to play sound as message arrives. Is it possible to start playing even after screen lock as I have seen this play sound even when screen locked but in that case the playing should have started before screen lock. Plus I see in sometimes the sound file gets prepared to be downloaded in case IDM is installed.

**Comment by goldfire** [comment]
As far as I am aware, there is no way to do this from within a mobile browser.
