### ISSUE TITLE
howler loads audiosprites file multiple times in IE 11

### ISSUE THREAD

**Issue by FFankias** [goldfire/howler.js#587]
We are using audiosprite  in howler.js and I noticed strange behavior in EI (v11).
Audiosprite file loaded multiple times with different size and sometimes howler plays whole soundsprite without the interaptions.

Also there strange behavior in IE in the Audio Sprite demo https://howlerjs.com/ 
Screenshot: https://i.gyazo.com/923f11481a8335522bb2771c0741a5fd.png

In Chrome everything works fine.

**Comment by goldfire** [comment]
As far as I have been able to tell, this is a bug with IE11 itself. I'm not aware of any way to get around this, but will be happy to re-open if anyone has any ideas.

**Comment by xl1** [comment]
I also faced this problem. What I am trying is:

1. Download sound files by XHR.
2. Create blob URI.
3. Use this URI for `src` instead of raw file paths.

Then downloading itself is done only once.
```js
var xhr = new XMLHttpRequest();
xhr.open('GET', './sprite.mp3', true);
xhr.responseType = 'blob';
xhr.onload = function () {
    var sound = new Howl({
        src: [URL.createObjectURL(xhr.response)],
        format: ['mp3'],
        sprite: { test: [1000, 5000] }
    });
};
xhr.send();
```

**Comment by a7517** [comment]
Have you solved this problem?
