### ISSUE TITLE
The doc is outdated ?!?! fadeIn/fadeOut

### ISSUE THREAD

**Issue by manodupont** [goldfire/howler.js#588]
The home page howler.js shows methods fadeIn and fadeOut,

When i look in the code, it says only method fade:  function( ..... )

So the doc is outdated.

**Comment by goldfire** [comment]
The docs are not outdated, `fadeIn` and `fadeOut` were replaced with `fade` in 2.0. The website doesn't have any documentation on it (https://howlerjs.com).
