### ISSUE TITLE
Duration wrong

### ISSUE THREAD

**Issue by manodupont** [goldfire/howler.js#589]
So i have these settings ...

```
var t2 = "https://avid-scp-public-assets-01.devops-int.avid.com/g-KeP6dwSrmNuWyUzUwI0WEqdav1rkuAlyl8bBWl9LXvvPOzrWNAR5P46CGTy7Kp"

this.howler = new Howl({
  src: [t2],
  format: ["webm", "mp3"],
  html5: true,
  buffer: true
...
})
```

when i look for duration i have ```duration 2388.9```.
If i just cut and paste my src in another tab, the duration is like 39000.

Why is that ? I lost like 30 seconds with Howl ...

**Comment by goldfire** [comment]
The duration is in seconds, and 39:48 is 2388 seconds, so it is working correctly.

**Comment by manodupont** [comment]
Geeez! sorry bout that. Maybe a cup of coffee would help

**Comment by goldfire** [comment]
I know the feeling 😄

**Comment by bbottema** [comment]
Still, it's not in the documentation that it is in seconds, @goldfire
