### ISSUE TITLE
Stop() didn't reset seek to 0 when invoking pause() before it

### ISSUE THREAD

**Issue by asjmtz** [goldfire/howler.js#595]
I am using Howler to make a player. And I found that when I invoked `sound.pause()` before invoking `sound.stop()` , the `stop` function did not reset seek to 0. I don't know if it is a special design. 

Demo
https://jsbin.com/xeqeciz/edit?html,js,console,output

**Comment by Stenerson** [comment]
@goldfire can you publish this fix to npm? I'm trying to implement more Howler features, including `stop()`, in [react-howler](https://github.com/thangngoc89/react-howler) but I'd like to wait until this is published upstream.

Thanks! 😎
