### ISSUE TITLE
Fade-outs not running when volume is changed

### ISSUE THREAD

**Issue by RyanHecht** [goldfire/howler.js#600]
My page has a slider that allows users to change the volume, and a websocket connection that can tell it to fade-out the sound that's currently playing. If the user slides the slider, the call to .fade() does not take place.

**Comment by goldfire** [comment]
When volume is changed, any active fade is cancelled. What behavior are you expecting?

**Comment by RyanHecht** [comment]
In previous versions, fades continued even when the volume was changed. Can I make a fade ignore volume changes and continue regardless?
