### ISSUE TITLE
sound sprite format not compatible with audiosprite

### ISSUE THREAD

**Issue by raphaelstary** [goldfire/howler.js#601]
sound sprite format not compatible with audiosprite anymore.

howler.js:398 An array of source files must be passed with any new Howl.

format changed with howler version 2.0.0: looking now for a 'src' key (previously 'urls')

**Comment by goldfire** [comment]
I'm not affiliated with that project, but it looks like someone has already submitted a PR: https://github.com/tonistiigi/audiosprite/pull/49.

**Comment by raphaelstary** [comment]
ok thx.

but you could adapt your documentation,
it says, 'An easy way to generate compatible sound sprites is with audiosprite.'

and or add a notice to v2 release notes under 'Breaking Changes',
that v1 was looking for 'urls' with sprites and v2 needs 'src'

**Comment by goldfire** [comment]
Thanks, I didn't realize I had missed that in the migration guide.
