### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by sibelius** [goldfire/howler.js#603]
How can I use it with webpack?

**Comment by FullR** [comment]
You can load your sounds using [file-loader](https://github.com/webpack/file-loader). Just pass the result of your `require` as the `src` option.

**Comment by sibelius** [comment]
I add something like this:

```js
import Howler from 'howler';
const { Howl } = Howler;
```

and it did work, tks

**Comment by cjke** [comment]
You can also just do:

`import { Howl } from 'howler';`
