### ISSUE TITLE
HTML Audio causing my VO to be cut off (mostly an IE issue)

### ISSUE THREAD

**Issue by rroylance** [goldfire/howler.js#606]
I'm using Phaser for my game and encountered this and reported it to them (https://github.com/photonstorm/phaser/issues/2718) and thought I'd try out Howler to see if the problem is Phaser specific and turns out it wasn't.

I have created my audiosprite that contains the VO for my game and when loading into the game it plays fine in Web Audio but several of the lines get cut off when in HTML Audio. For example I'll have the line "Can you please find the thing that is" "12" "units long?" each being it's own sprite, one being triggered after the other in the end event; in Web Audio it plays fine, however in HTML Audio I'll hear "Can you please find the thing that" "12" "units lo". It doens't happen every single time, but happens more often then not.

It seems as though maybe there's a slight delay before the audio actually starts but the end event is called as if it started playing instantly. I've tried everything I can think of from Phaser but since it impacts Howler as well I figured I'd mention it, hopefully you can see something I don't.

[Live example; https://codepen.io/rroylance/pen/GqbBxk?editors=0011](https://codepen.io/rroylance/pen/GqbBxk?editors=0011)

Thanks.

**Comment by goldfire** [comment]
#720 has been merged and should fix this.
