### ISSUE TITLE
Calling play after initializing with autoplay causes restart on pause

### ISSUE THREAD

**Issue by Stenerson** [goldfire/howler.js#607]
**Reproduction steps:**
1. Create Howl: `var howl = new Howl({src: [sound1], autoplay: true});`
2. Call `howl.play()`
3. Wait some time and call `howl.pause()`
4. Call `howl.play()` again

**Expected result:** Howl plays from the position it was paused at
**Actual result:** Howl restarts from the beginning

I found this while trying to fix thangngoc89/react-howler#13 and while I can understand that calling `play()` right after autostarting seems odd (it probably is) I didn't expect it to behave in this way.

I created a [JSBin reproducing the issue](https://jsbin.com/fonewaz/edit?js,console,output). Comment out the first call to `play()` to hear the regular, desired playback.

**Comment by goldfire** [comment]
The reason for this is that you are actually playing two instances of the sound simultaneously. When you call `play` without passing a sound ID, it checks to see if there is a single paused to sound to play. If there isn't, it starts a new one. To fix this would require a breaking change in changing how `play` works, so it needs more thought put into it.

**Comment by Stenerson** [comment]
Thanks @goldfire. This makes sense. I wondered if this was the case - when I was trying to reproduce with JSBin I occasionally got some sound overlap which suggested that two instances were playing but I was too focused on the pause "issue" to think about it. 

I'd be very supportive of closing this but I'll leave it up to your judgement. As I said in the issue, I think this is an odd (and probably improper) use case. I was concerned that this might be a bigger issue but your explanation is perfect.

**Comment by Stenerson** [comment]
I think this is actually desired behavior so I'm going to close. If you disagree and want to provide functionality to address both use cases, reopen at will 😄
