### ISSUE TITLE
Impossible to play after a loaderror

### ISSUE THREAD

**Issue by SuperSkunk** [goldfire/howler.js#613]
Hi,

When I have a 404 during the load a sound, it's impossible to play another sound after.
I have some difficulties to understand the noAudio variable.

When a sound failed to load (with a 404 error), nodeAudio is set to true. Why ?
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L1905
```
if (self._node.error && self._node.error.code === 4) {
  Howler.noAudio = true;
}
```

When I want to play a new sound after it, it's impossible because if noAudio is true, then all source will fail even if they could play.
https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L475
```
// If no audio is available, quit immediately.
if (Howler.noAudio) {
  self._emit('loaderror', null, 'No audio support.');
  return;
}
```

Should I reset Howler after an error ?

**Comment by ejacquier** [comment]
Hi,

Any update on this issue?
We noticed the same thing on our game.

As a workaround, we are changing back the Holwer.noAudio flag to false when a loaderror happen.
