### ISSUE TITLE
volume dosen't work on mobile but work on pc

### ISSUE THREAD

**Issue by cztflove** [goldfire/howler.js#614]
`

```
$('.icon-music').on('click',function(){
        var _this = $(this);
        if(_this.hasClass('stop')){
            _this.removeClass('stop');
            cfg.audio.volume(1);
        }
        else{
            _this.addClass('stop'); 
            cfg.audio.volume(0);
        }
    });
```

`

i want to mute all the music when i click the button, but it doesn't work on mobile, the music is still playing

**Comment by goldfire** [comment]
Which mobile browser and have you tried using the `mute` method?

**Comment by cztflove** [comment]
yep~i have tried the`mute(true/false)`, it works on wechat for Android but doesn't on wechat for ios

**Comment by cztflove** [comment]
and i found some Android would delay for several seconds when i played the first sprite
`audio.play('one')`

**Comment by maslick** [comment]
same thing, can't control playback volume on ios 9 - safari, chrome...

**Comment by goldfire** [comment]
Are you forcing HTML5 audio? Unless it has changed, I believe HTML5 Audio can't change the volume on Mobile Safari. I just tested with Web Audio and the volume change works fine.
