### ISSUE TITLE
Can we manage playing sequence of short duration MP3 files ?

### ISSUE THREAD

**Issue by shivrajsa** [goldfire/howler.js#624]
I have a app developed using [MIDI.js](https://github.com/mudcube/MIDI.js) where I can create sequence of notes (for song) & play with useful parameters. Mainly I can manage duration of each note.I can loop array of notes which is very easy.

Can we achieve same using this library? I have set of all MP3 files for notes, is it possible to play them in sequence while controlling duration for each note ?
Please guide.

**Comment by TaxableApples** [comment]
Yeah,
Use Sprites and then play the next mp3 with the event listener.

//define the sounds
var sound1 = new Howl({
  src:['sound1.mp3'],
  sprite: {
    startDuration:[0, 3000]
  }
});

var sound2 = new Howl({
  src:[sound2.mp3'],
  sprite: {
    startDuration:[0, 3000]
  }
});

// play the first sound
function playIt() {
  sound1.play('startDuration');
};

// loop to the next sound
sound1.on('end', function(){
  sound2.play('startDuration');
});

//loop back to the first sound
sound2.on('end', function(){
  sound1.play('startDuration');
});
