### ISSUE TITLE
add callback to fade when it finishes fading?

### ISSUE THREAD

**Issue by maslick** [goldfire/howler.js#625]
It would be nice to have a callback once the fading effect has finished. 

```
sound.fade(1, 0, 1000, id, function(s) {
   s.stop();
});
```

Otherwise I have to register an `onfade` handler and check the status audio.playing() and then actually stop/pause the playback.

Usually one has controls (audio.stop, audio.pause, audio.play, etc.) assosiated with a button click. Not the audio itself.

**Comment by Jokero** [comment]
Actually `howler` 1.x.x supports it:

* **fade**: Fade a currently playing sound between two volumes.
  * *from*: `Number` Volume to fade from (`0.0` to `1.0`).
  * *to*: `Number` Volume to fade to (`0.0` to `1.0`).
  * *duration*: `Number` Time in milliseconds to fade.
  * *callback*: `Function` (optional) Fires when fade is complete.
  * *id*: `Number` (optional) The play instance ID.

I'm also interested why it was deleted

**Comment by AzureusSme** [comment]
+1

**Comment by jeromelunch** [comment]
+1

**Comment by themoonrat** [comment]
For those who want a quick solution to this now, this will fade out the sound playing from whatever it's current volume is to silence, and then stop it.

```
sound.once( 'fade', () => { sound.stop( id ); }, id );
sound.fade( sound.volume(), 0, 1000, id );
```

**Comment by DerGav** [comment]
I think your solution might not work when there are multiple fades going on @themoonrat. 
Here is a problem I ran into: https://codepen.io/DerGav/pen/JjXpyNr
Am I missing something?

**Comment by ekokotov** [comment]
+ 1
