### ISSUE TITLE
Variable Volume 

### ISSUE THREAD

**Issue by Nick-Riggs** [goldfire/howler.js#63]
Is it possible to play a single Howl at different volumes? In my example: I have an explosion sound that needs to be softer the further a player is away from the event. Do I have to create a new instance of a Howl for this? I was hoping to reuse the existing Howl, something to the effect of:

```
sound.play({ volume: 0.25 });
```

**Comment by cdauth** [comment]
I have a similar case where I want to play the same sound multiple times concurrently with different volumes. Using `sound.volume()` with the ID that I received from `sound.play()` will work, but the first short bit of the sound will be played with the default volume.

A workaround might be to create multiple Howl objects with the same parameters, but in my case I have a library that gets passed a Howl object, and I don't see a simple way to clone it.

A workaround for now is to set `sound._volume`. This will affect the volume of the next `sound.play()` call without affecting the currently playing instances of `sound`. Maybe the play function could have a parameter for the volume?
