### ISSUE TITLE
Audio will not play if pause() has been called before play()

### ISSUE THREAD

**Issue by DoktorFloydberg** [goldfire/howler.js#639]
I noticed that no audio will be played (or silently?) if pause() is called before the first call of play()

e.g. You have the following code:

``` javascript
sound.play();
sound.pause();
sound.play(); // Sound
```

But the following will not produce any audio at all:

``` javascript
sound.pause();
sound.play(); // No sound
```

Tested it with Nodejs, Chrome and Firefox.
Also this issue seems to be independent wether HTML5 or WebAudio is used or enforced.

**Comment by icdindia** [comment]
you can check if the audio is playing and then pause it. 

works just fine:

```
if (sound.playing()) {
      console.log("audio playing")
      sound.pause()
    }
sound.play(); 
```
