### ISSUE TITLE
HTML5 first as option

### ISSUE THREAD

**Issue by bestander** [goldfire/howler.js#64]
Hi, I'd like to assign self._webAudio to `false` when constructing Howl object.

The reason is that html5 audio is CORS tolerant and I'd like to play sounds from other domains without making an XHR request every time.

**Comment by Thinkscape** [comment]
:+1: It'd be great if this was documented though :-)

**Comment by goldfire** [comment]
Documented here: https://github.com/goldfire/howler.js/tree/2.0#html5-boolean-false

**Comment by TimAstier** [comment]
Setting html5 to true did solve the CORS issue in my case.

**Comment by viewescape** [comment]
How to get around CORS error when must use web audio (for seamless looping).  So html5 and buffer must be false in this case.
