### ISSUE TITLE
Stop() doesn't stop sounds that are currently loading

### ISSUE THREAD

**Issue by AshotN** [goldfire/howler.js#641]
My current setup is as such, users click on a song and  the following happens
- Stops previous song
- Loads the new song
- Plays new song

So imagine we have two songs, Song A and Song B

If user clicks on Song A and before it has finished loading they click on Song B. The stop() method will not interrupt Song A's loading. And they play over each other. 

My solution so far has been to use unload() but these clears the cache which isn't desirable.

**Comment by goldfire** [comment]
Can you provide a test case? Are these different sounds each in their own `Howl` or in separate `Howls`? If they are in the same, are you passing the `id` to `stop`?

**Comment by AshotN** [comment]
Ok, I think I figured it out and its not Howlers fault but my own instead. 

Is it possible to add a global stop function? Similar to how unload works currently but without the cache clearing part.

**Comment by goldfire** [comment]
You can stop a group by calling `.stop()` with no parameters. Do you mean a global stop like `Howler.stop()`?

**Comment by AshotN** [comment]
Yes a global stop

One that would stop all audio and loading of audio

**Comment by goldfire** [comment]
The only way to stop loading of audio with HTML5 Audio is to unload it. Web Audio won't be in a state to stop until it has fully loaded. Is the motivation for this more about the loading or stopping of the sound?

**Comment by AshotN** [comment]
Both really. Currently unload() is doing the job but it is clearing the cache. 

I'm using howler as a music application.  If the user skips a bunch of songs, I don't want them all to load

**Comment by goldfire** [comment]
So maybe an option to `unload` without clearing the cache makes sense?

**Comment by AshotN** [comment]
Ya. Just cancel current connections and stop all playing sounds but leave cache alone

**Comment by AshotN** [comment]
Any progress on this @goldfire ?

**Comment by martonic** [comment]
I have searched in vain for a definition of "group".  

How can I create a group?  

How can I add a sound to a group, or specify the group for a given sound?

Many thanks, great library!

**Comment by miksansegundo** [comment]
I'm reading the examples and the docs and I'm not able to stop all sounds before play a new one.

Looking some code extracted from the the [radio example](https://github.com/goldfire/howler.js/blob/master/examples/radio/radio.js): it looks pretty simple, just using `.stop()` on any instance of `Howl`.
```
    play: function(index) {
        var self = this;
        var sound;
        index = typeof index === 'number' ? index : self.index;
        var data = self.stations[index];
        if (data.howl) {
            sound = data.howl;
        } else {
            sound = data.howl = new Howl({
                src: data.src,
                html5: true,
                format: ['mp3', 'aac']
            });
        }
        sound.play();
        self.toggleStationDisplay(index, true);
        self.index = index;
    },
    stop: function() {
        var self = this;
        var sound = self.stations[self.index].howl;
        self.toggleStationDisplay(self.index, false);
        if (sound) {
            sound.stop();
        }
    },
```

But I must miss something because I can't make it work. Please help @goldfire :)

**Comment by miksansegundo** [comment]
Here is my file. I have tried both `.stop()` and `.stop(playingID)` without success.
```import { Howl } from 'howler'

let playingID

function audioPlayer({ src, autoPlay = false, onEnd = () => {}, onPlay = () => {} }) {
  const audio = new Howl({
    src: [src],
    autoplay: false,
    loop: false,
    volume: 0.5,
    onend: onEnd,
    onplay: onPlay,
    html5: true,
  })

  function play() {
    playingID = audio.play()
  }

  function playAlone() {
    audio.stop(playingID)
    playingID = audio.play()
  }

  if (autoPlay) playAlone()

  return {
    playAlone,
    play,
  }
}

export default audioPlayer```

**Comment by martonic** [comment]
playingID.stop();



-----Original Message-----

**Comment by miksansegundo** [comment]
Thanks @martonic but `playingID` is just the ID not the sound instance. Finally I have fixed my issue keeping in memory my last instance played because I only need a sound at once.

```
import { Howl } from 'howler'

let lastAudio

function audioPlayer({
  src,
  onStop = () => {},
  onLoad = () => {},
  onEnd = () => {},
  onPlay = () => {},
}) {
  const audio = new Howl({
    src: [src],
    autoplay: false,
    loop: false,
    volume: 0.5,
    onend: onEnd,
    onstop: onStop,
    onplay: onPlay,
    onload: onLoad,
    html5: true,
  })

  function stopLastAudio() {
    if (!lastAudio) return
    lastAudio.stop()
  }

  function playAlone() {
    stopLastAudio()
    audio.play()
    lastAudio = audio
  }

  return {
    playAlone,
  }
}

export default audioPlayer

```

**Comment by martonic** [comment]
yes, that looks good



-----Original Message-----

**Comment by abrehamgezahegn** [comment]
Hello. Anything new on this?

**Comment by sfuxal** [comment]
`Howler.stop()` has recently been added. 
https://github.com/goldfire/howler.js/blob/master/CHANGELOG.md

**Comment by vantamtran10** [comment]
You can use the stop() like me: 
audioPlayer:Howl = null;                                   // first of all, I use one variable to tracking Howler
then in the function play, I check and set: 
function play(){
if (this.audioPlayer != null){
      this.audioPlayer.stop();
}
this.audioPlayer = new Howl({});                     // set a new file to play
this.audioPlayer.play();
}

**Comment by liwBh** [comment]
> Howler.stop()

Gracias esa fue la solución en mi caso

**Comment by fromage9747** [comment]
Howler.stop() doesn't work for me.  If I skip 5 tracks quickly, so they are still loading.  I will still land up with two tracks playing and can only control one of them.
