### ISSUE TITLE
Issue in latest version of Chrome?

### ISSUE THREAD

**Issue by bQvle** [goldfire/howler.js#642]
Ever since Chrome updated, some sounds play extremely loud (randomly).

It can be provoked like this:

```
var test = new Howl({
        src: '/shot.mp3',
        volume: 0.1,
        loop: false,
        rate: 1,
        autoplay: false
    });


setInterval(function(){
   var id = test.play(); 
   test.volume(Math.random() * 0.1,id); 
   test.rate(Math.random() * 0.5 + 0.7, id); 
}, 100);
```

If it doesn't act up right away, try starting 2-3 intervals at the same time.

**Comment by goldfire** [comment]
I haven't been able to reproduce this so far. Can you create a fiddle with an actual audio file that is causing the issue?

**Comment by bQvle** [comment]
this example might be a little extreme, but it forces the issue
https://jsfiddle.net/kk5809f4/5/

If it doesn't make any sound, try refreshing the page when it reaches around 500 plays

**Comment by goldfire** [comment]
Interesting, I do have some issues on Chrome 55, but on Canary it seems to work perfectly. Since this does seem to be the same issue as #647, I'm going to close this one and keep the discussion going on that issue.
