### ISSUE TITLE
Does not wait for AudioContext to be ready after autoResume

### ISSUE THREAD

**Issue by niklasf** [goldfire/howler.js#643]
The start of sounds will be cut off after an auto resume, short sounds will not be heard at all. Experiencing this in Firefox 49.0.2 but not in Chrome.

```
<script src="../src/howler.core.js"></script>
<script>
var h = new Howl({
  src: ['Move.ogg', 'Move.mp3']
});
h.play();
setTimeout(function () {
  console.log('tick');
  h.play();
}, 31000);
</script>
```

Expected: Hear Move.ogg twice at an interval of 31s, actual: hearing only the first one

**Comment by goldfire** [comment]
Thanks for catching this, https://github.com/goldfire/howler.js/commit/3abbeed9d03be7d300bf87918704945be1b7c055 should fix this.

**Comment by isaacl** [comment]
@goldfire Are you planning a release for this commit? If not, do you have an idea when the next minor release will be?

**Comment by goldfire** [comment]
@isaacl I should have time to get a new release out on Friday or this weekend. I've got a few other small things I want to get in it as well.
