### ISSUE TITLE
volume after playing

### ISSUE THREAD

**Issue by k888168168** [goldfire/howler.js#647]
Hi,
I want to change volume after play.

> var id = howl.play();
howl.volume(0.1, id);

It works!
But sometimes fail to change.
I can hear big volume of this sound.

**Comment by goldfire** [comment]
Can you provide a working example? I'm unable to reproduce this issue. Also, what browser/platform?

**Comment by k888168168** [comment]
Thanks. @goldfire 

> Platform: Windows 7
Browser: Google Chrome 54.0.2840.71 m (64-bit)

I'm using audiosprite as a Howl.
And I want to change volume individually.
So I build a manager to do this.

	var howl:Howl;
	var channel:{id:number, name:string};

	howl = this.soundMap[key];
	var channelID = howl.play(key);
	channel = {'id':channelID, 'name':key};

	//new channel
	var channelList: {id:number, name:string}[];

	if(!this.channelMap.containsKey(key)) {
		channelList = [channel];
		this.channelMap.add(key, channelList);
	}
	else {
		channelList = this.channelMap[key];
		channelList.push(channel);
	}

	// add id map channel object
	this.channelMap.add(channel.id.toString(), channel);

	if(cb != null)
	{
		this.completeCbMap[key] = cb;
	}

	howl.once('end',this.onSoundComplete.bind(this), channel.id);
	howl.volume(this.effectVolume * this.gameEffectVolume, channel.id);

It my play code.
I think it can simplify into

> var id = howl.play();
howl.volume(0.1, id);

Right?

**Comment by k888168168** [comment]
Now I use some hacker trick to solve this issue.
> var voll = toVolume ;
var vol = howl.volume();
howl['_volume'] = voll;
var channelID = howl.play(key);
howl['_volume'] = vol;

Change '_volume' value before play and revert it after play.
It works well.
But hacker.

**Comment by jgranick** [comment]
We are seeing a similar issue, we use code similar to this:

```js
var id = howl.play ();
howl.volume (0, id);
```

It works at first, but some users are reporting that sounds are still heard. If you call this code in `requestAnimationFrame`, after about 128 plays it will begin to play with full volume... perhaps it falls back to HTML5 audio?

**Comment by bQvle** [comment]
Pretty sure its the same issue I've got, after chorme updated
https://github.com/goldfire/howler.js/issues/642

**Comment by goldfire** [comment]
Okay, so I'm able to reproduce this now (https://jsfiddle.net/kk5809f4/4/), though I'm still not sure what is causing that. In that fiddle it happens very rarely, which makes it a trickier to track down.

**Comment by bQvle** [comment]
Try playing multple different sounds simutaniously and at an Extreme rate just to se If it provokes it, and try from different hardware maybe cheap audio devices is more prone to do it.

**Comment by goldfire** [comment]
The issue in the fiddle I posted above still happens in Chrome 55, though seemingly not as frequently. However, I can't get it to happen at all in Chrome Canary. Is this the case for all of you as well, or is my example just not an extreme enough case?

**Comment by rvion** [comment]
why can't we just set audio volume per sprite ? or create a sound and set its volume before pressing play ?
