### ISSUE TITLE
Advanced sound effects

### ISSUE THREAD

**Issue by proyb6** [goldfire/howler.js#660]
Are there any plugins or plan to develop to handle individual, group or all sprites with:
Reverb
Convolution
Flanger
Wahwah
Distortion
Phaser
Limiter
Low/High pass filter
Compression

**Comment by goldfire** [comment]
Yes, this is something I want to add in the future through the use of plugins (if anyone wants to help get the ball rolling that would be appreciated as well).

**Comment by tobium** [comment]
any news here?

**Comment by proyb6** [comment]
Closed because the issue is no longer need for me, Aopted Go language for performance reason.

**Comment by homerjam** [comment]
Please re-open

**Comment by ProgrammingLife** [comment]
Any news? I wanna have reverb feature 😀

**Comment by proyb6** [comment]
@ProgrammingLife You can open your case, close due to stale issue and Pizzicato have a similar feature which I've experiment long time ago.

https://alemangui.github.io/pizzicato/

Thank you.

**Comment by proyb6** [comment]
@h0merjam The door is open at Pizzicato.

**Comment by electrovir** [comment]
Is there yet a way to accomplish this?
