### ISSUE TITLE
Fadeout cutoff issue

### ISSUE THREAD

**Issue by proyb6** [goldfire/howler.js#662]
Fadeout duration initially cutoff after 1000ms has become shorter and shorter duration each time I click in repetition.
```
<script src="howler.js"></script>
<script>
    var sound = new Howl({
      src: ['sound.wav']
    });

function down() {
sound.play();
sound.fade(0,1,1);
}

function up() {
sound.fade(1,0,1000)
}
</script>
<p onmousedown="down()" onmouseup="up()">Click the text!</p>
```

**Comment by jfizz** [comment]
@proyb6 I am experiencing the same issue. Were you able to find a solution?

**Comment by jfizz** [comment]
I was able to resolve the issue. In my case, I was attempting to fade a sprite. To do so, you must pass the _id of the sprite sound to the fade function.

**Comment by wildfiremedia** [comment]
Cool, if you don't mind to share a code example?

**Comment by proyb6** [comment]
Great, if you don't mind sharing a code example?

**Comment by jfizz** [comment]
Sure, first I find the sound ID by searching through the _sounds array. Once you find the sound, pass the _id field as the fourth parameter to the .fade function.
```
var audio = new Howl();
var soundId = findSoundId(audio._sounds);
audio.fade(fromVolume, toVolume, duration, soundId);
```
