### ISSUE TITLE
typo in the documentation

### ISSUE THREAD

**Issue by alien35** [goldfire/howler.js#663]
I believe there's a misprint in the documentation:
Howler.mobileAutoEnable should be Howler.mobileAudioEnable

index.d.ts reads:

interface HowlerGlobal {
...
mobileAudioEnable: boolean,
...
}

so I'm pretty sure this is the case.

Best,

**Comment by goldfire** [comment]
It looks like that is a typo int he TypeScript definition (which I don't have anything to do with). If you look in the actual source (https://github.com/goldfire/howler.js/blob/master/src/howler.core.js), there is no `mobileAudioEnable`.
