### ISSUE TITLE
Spatial Audio not working in 2.0.2

### ISSUE THREAD

**Issue by ahsquared** [goldfire/howler.js#664]
We have a fairly involved project using Howl (works great btw!), but we noticed that spatial audio stopped working when we switched from 2.0.1 to 2.0.2 using howler.min.js

If we swap those files and change nothing else spatial audio stops working. We were hoping to fix the safari context resume problem with 2.0.2, but are handling that ourselves now and using 2.0.1.

Thanks for the great lib!

**Comment by goldfire** [comment]
Can you give an example of what isn't working and is this in any particular browser/OS? I just tested both spatial audio demos on howlerjs.com and they both seemed to be working for me (https://howlerjs.com/#spatial & https://howlerjs.com/#basic).

**Comment by ahsquared** [comment]
Sorry it took me so long to get back to you, launch was insane, but now that it's live and the holidays are over, I had time to create a test case. I couldn't get spatial audio to work on JSBin or CodePen, so I made a small repo. You can see it here:
https://github.com/ahsquared/howler-spatial-test

The project we used Howler on is here, in case you're interested: https://www.nhtsa.gov/lastcall/
