### ISSUE TITLE
When muting, fading sounds are not muted when using webAudio

### ISSUE THREAD

**Issue by soruly** [goldfire/howler.js#666]
when webAudio is used, it only checks if howler is muted before fade starts. It doesn't check if it is muted while fading (which is handled by linearRampToValueAtTime ). It seems that howler does not disconnect nodes correctly when muting?

```
self.sound.fade(0,1,2000,id);
self.sound.mute(true);
```
The above code doesn't play any sound on HTML5 audio (correct)
But when webAudio is used, the fade in still plays

Ref: (howler v2.0.2)
https://github.com/goldfire/howler.js/blob/v2.0.2/src/howler.core.js#L1109

The workaround is to set {usingWebAudio: false} in global options.
It works well with HTML5 audio.

**Comment by soruly** [comment]
This issue is because howler use the same node for fading and muting. So when we mute and unmute during volume fade, it cannot restore the incomplete fade. One suggestion would be have a separate gain node to control global volume, and another gain node for fading.

Ref:
https://github.com/goldfire/howler.js/blob/v2.0.2/src/howler.core.js#L960

**Comment by soruly** [comment]
```
var sound = new Howl({
    src: ['sound.mp3']
});
```
calling global mute `Howler.mute(true);` works fine, it only happens when calling per sound mute `sound.mute(true);`

**Comment by Jokero** [comment]
Also faced with this bug. Yeah, global mute works but this is not an option for me. 
Plunker https://plnkr.co/edit/49UZfvZen8M3xiADRwAn?p=preview

@soruly Do you see any pitfalls with using `{usingWebAudio: false}`?

**Comment by Jokero** [comment]
> Do you see any pitfalls when using {usingWebAudio: false}?

Found that using html5 audio is bad approach, because sounds that were not caused by user action in mobile browser (tap for example) will not play. What I see in console of chrome for android:
```
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
```
There are no such errors when using WebAudio, so it is the only correct approach in modern browsers
