### ISSUE TITLE
Problem with duration = Infinity

### ISSUE THREAD

**Issue by Gijserman** [goldfire/howler.js#67]
For some reason, some systems (maybe in a specific network) return "Infinite" as audio duration. This causes the plugin to go crazy when you loop a sound, 'cause it immediately fires the end event when played. I think it's a pretty rare issue, but it happened on some client's machines in firefox only (version 22.0).

**Comment by amirh715** [comment]
I have the same problem and I'm using html5. howler.duration always returns `Infinity`

**Comment by deowansajal** [comment]
I'm also getting the issue

**Comment by Mani-Gme** [comment]
> I have the same problem and I'm using html5. howler.duration always returns `Infinity`

Did you get any fix?
