### ISSUE TITLE
Android resume failure, state 'resuming'

### ISSUE THREAD

**Issue by k888168168** [goldfire/howler.js#676]
Hi all,
I'm using howler in a cross domain iframe.
In Chrome Desktop version. It plays well.
But in Chrome Android version, I will got and warning message by `AudioContext.resume()` .

> An AudioContext in a cross origin iframe must be created or resumed from a user gesture to enable audio output.

The last `Howler.state` was be 'resuming'.
And can not play audio anymore.
How could I  fix it?

**Comment by goldfire** [comment]
You could set `autoSuspend` to `false` and this shouldn't be an issue (https://github.com/goldfire/howler.js#autosuspend-boolean-true).

**Comment by k888168168** [comment]
I try to set `autoSuspend` be `false`
But It not work.

**Comment by k888168168** [comment]
We are assume `self.ctx.resume().then( handle_function )` (in `howler.core.js` line:398)
the handle_function will be call.
In cross domain iframe, handle_function will not be call.
So `self.state` will stop at `'resuming'`.

**Comment by k888168168** [comment]
#679
