### ISSUE TITLE
AAC on Edge

### ISSUE THREAD

**Issue by filerun** [goldfire/howler.js#677]
AAC is being reported by Howler as unsupported on Edge, while it works just fine.

**Comment by goldfire** [comment]
The library uses what the browser tells it. Edge is saying it doesn't support AAC, which means there may be a bug in the browser itself. Howler is correctly reporting that AAC in an MP4 container is supported. If anyone has a workaround for this that would be great; however, I don't think doing browser detection is a good idea.

**Comment by filerun** [comment]
The browser does report as unsupported, although Howler plays it fine. I never trust what browsers are reporting anyway, I test and see what works and what doesn't and use it accordingly. Browsers bugs never stopped people from achieving goals. It might be worth at least mentioned to people so they know if they are missing out on something.
