### ISSUE TITLE
Error on playback in Firefox 50

### ISSUE THREAD

**Issue by filerun** [goldfire/howler.js#678]
> Media resource data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA= could not be decoded.

> uncaught exception: undefined

**Comment by goldfire** [comment]
That doesn't appear to be a valid audio file. You'll get a load error with that in any browser, not just Firefox.

**Comment by filerun** [comment]
That is the error, not the file. The file plays, that's the error in the console, even though the file plays.

**Comment by goldfire** [comment]
Can you provide a reproducible test case (possibly a jsfiddle or at least access to the file throwing this error)?

**Comment by filerun** [comment]
Just hit "unload()" on any Howl object on Firefox. The loaded file is not relevant. What you said above that doesn't look like a valid audio file is actually from Howler's source code, inside the unload method.
