### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of null at HowlerGlobal.codecs

### ISSUE THREAD

**Issue by adnanibric** [goldfire/howler.js#680]
Hi, 

We have used howler  v1.1.25 and when migrating to v2.02 we get this issue and script broke.

Older version load method did not call:

```javascript
// Check if this extension is available.
        if (Howler.codecs(ext)) {
          url = self._src[i];
          break;
        }
```

and everything is working fine.

New script is calling Howler.codecs with extension and if in some case invalid file without any extension is passed to script javascript will stop executing. I think script should not break javascript it should be more robust and I suggest inserting check if extension exists: 

```javascript
/**
     * Check for codec support of specific extension.
     * @param  {String} ext Audio file extention.
     * @return {Boolean}
     */
    codecs: function(ext) {
      if (ext) {
          return (this || Howler)._codecs[ext.replace(/^x-/, '')];
      }
      
    },
```

Please let me know what do you think about this?

Thanks,
Adnan

**Comment by Chrischuck** [comment]
I'm getting this issue as well.
