### ISSUE TITLE
No sound on Samsung devices with Android 4

### ISSUE THREAD

**Issue by LillyWebsites** [goldfire/howler.js#690]
Hi! I'm using Branch 2.0 in a phonegap app, which is in Beta on Google PlayStore.  It is working except on Samsung devices with Android 4. I just need a simple sound, 
`var sound = new Howl({
		  src: ['res/raw/warning.mp3']
		}).play();`
(Adding /android_asset/www/ before the path didn't change anything)
What can I do to get it working?

**Comment by viniciusbo** [comment]
I'm also experiencing this issue. For some reason v2.0.0-rc2 works on Android 4.4.4, but v2.0.2 doesn't.

**Comment by goldfire** [comment]
This should now be fixed in v2.0.3, but I'll reopen if not.
