### ISSUE TITLE
Unable to stop sound when using pos() in 2.0.2

### ISSUE THREAD

**Issue by joppe** [goldfire/howler.js#693]
I want to report a bug for 2.0.2 that occurs in Firefox (not in Chrome).
When using the pos method of the Spatial plugin it is not possible to stop/pause/mute/unload the sound. It is only possible to set the volume or the pos.
This was not a problem with version 2.0.1, so I downgraded the package and now it works. I use Firefox 50.1.0.

**Comment by goldfire** [comment]
This should now be fixed in v2.0.3, but I'll reopen if not.
