### ISSUE TITLE
Chrome doesn't support "audio/ogg; codecs=opus" with WebAudio, only with HTML5

### ISSUE THREAD

**Issue by golddranks** [goldfire/howler.js#695]
I was bitten by this: I have `.ogg` files that are encoded in `opus`. They work fine with `<audio src="test.ogg">`, but refuse to play with Howl. When I set HTML5 on, they play even with Howl.

Should there be an automatic fallback to HTML5 in this case?

Judging from StackOverflow[1], Chrome supports only `audio/webm; codecs=opus` with the WebAudio API.

[1]: http://stackoverflow.com/questions/41613665/does-chrome-not-support-audio-ogg-codecs-opus

**Comment by goldfire** [comment]
Are you sure there isn't an issue with your specific file? Chrome is reported as supporting Opus in OGG: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats.

**Comment by golddranks** [comment]
I had problems when Howler used the JS API to play those files, and not when the HTML5 fallback was used. However, I tried to reproduce the problem now, and failed to do so. So it remains a mystery why it didn't work back then (and why setting `html5: true` fixed it), but as it works at the moment, I'm going to close this.
