### ISSUE TITLE
Live Stream and audio G.711 support

### ISSUE THREAD

**Issue by mburger81** [goldfire/howler.js#700]
I have two questions,

a) does the player support G.711 a-law + u-law audio codec?
b) We have a live stream which has not Content-Length, does the lib support live streams?

**Comment by goldfire** [comment]
1. I am not familiar with G.711 and haven't heard of any browsers supporting it (if someone knows differently feel free to post it or open a PR).
2. Yes, howler.js has full support for streams (here's a live demo: https://howlerjs.com/#radio).
