### ISSUE TITLE
Adjusting the volume to prevent clipping when triggering multiple sprites at once...

### ISSUE THREAD

**Issue by DavidSanwald** [goldfire/howler.js#702]
Is there an elegant/non hacky way in howler to dynamically adjust the volume of the single played sprites, so that they don't clip (but keeping their combined volume as close to the max volume as possible)? My sprites are all at the same volume...

Maybe I'm overlooking something...

**Comment by DavidSanwald** [comment]
Okay, my bad. Didn't expect it would be so easy to add a compressor with the Web Audio API. This is even better than I hoped.

**Comment by t22james** [comment]
@DavidSanwald are you able to give any hints on how you achieved this?

**Comment by Ekuju** [comment]
I'm interested as well

**Comment by Ekuju** [comment]
For future reference, this is how you achieve it
```
const compressor = Howler.ctx.createDynamicsCompressor();

Howler.masterGain.disconnect(Howler.ctx.destination);
Howler.masterGain.connect(compressor);
compressor.connect(Howler.ctx.destination);
```

but also this does't solve the problem of static when playing multiple audio components at once. it probably does sound legitimate clipping though.
