### ISSUE TITLE
calculate sound volume at listener current position

### ISSUE THREAD

**Issue by ahmedelmahalawey** [goldfire/howler.js#703]
Is there a way to know the current volume of a sound located at position (Xs, Ys, Zs) to a listener located at position(Xl, Yl, Zl). can you please provide an example for that.

Thanks

**Comment by goldfire** [comment]
The volume of the sound never changes as the listener moves, and the difference in sound isn't exposed as far as I am aware. That being said, I haven't looked into it much, so there may be a way to do it. I'll reopen this if anyone has any ideas.
