### ISSUE TITLE
seek(X) then pause() fails

### ISSUE THREAD

**Issue by implicitdef** [goldfire/howler.js#704]
Hi

**It seems that doing .seek(X) and immediately .pause() causes the .pause() to not be applied to the actual sound.**

Tested on Chrome.
See the following codepen : http://codepen.io/implicitdef/pen/MJRmMz
Steps to reproduce :
- click "Play"
- click "Seek to time 30 and immediately pause"

Expected results : 
The sound should go to time 30 but be immediately stopped.
Actually : 
The sound jumps to time 30 but keeps playing.

If you look at the console you'll see that after the incriminated .pause() call, I'm printing the result of .playing(), which does return false, even though the sound is evidently playing.
This seems to indicate that Howler at this point messes up its internal state and doesn't get that the call to .pause() failed.

Note that wrapping the call .pause() call in a window.setTimeout seems to make it work again.

**Comment by zefie** [comment]
I'm finding your test to be worse than you explain on my Chrome. I did what you said to reproduce, and it does what you state.

However,then I can't use the Pause link at all. I try clicking "Seek to 0", still can't pause. "Seek to 30", still can't pause. In fact the pause functionality does not get restored until I click Play again., thus resetting Howler.

For reference, this is on version 56.0.2924.87 (64-bit)

**Comment by goldfire** [comment]
Yes, I would recommend pausing before seeking for now. In the current master build, the setTimeout has been removed, which leads to a separate issue. I've opened a new issue (#718) to track it. I suspect the timeout may have played a part in this issue, but this new bug is making that hard to test.
