### ISSUE TITLE
opus not playing on safari

### ISSUE THREAD

**Issue by sombriks** [goldfire/howler.js#706]
hello, first of all amazing library, works like a charm in any civilized platform and browser.

i`m facing however problems with safari and mac os. 

Debugging a while i found that opus codec isn't present at safari.

![captura de tela 2017-02-18 01 07 31](https://cloud.githubusercontent.com/assets/556695/23090204/ca884fae-f576-11e6-953b-41d2c2d319f5.png)

Is there anything i can do to make possible safari (and maybe mobile safari. and maybe ios webview...) reproduce opus format?

thanks in advance.

**Comment by zefie** [comment]
Unfortunately not. If the browser doesn't support it, there is not much Howler can do. I found to be cross compatible I had to encode my audio files to m4a, webm (vorbis) and mp3. Of course opus could be added to that list but since its relatively new compared to the other formats (webm is new too but vorbis is not), it will likely be a while before it can be the only solution provided.

Howler is designed to accept multiple formats in its source for this reason.

**Comment by sombriks** [comment]
Hi @zefie thanks for the reply.

I'll keep it in mind and make sure that something like m4a or mp3 gets uploaded to the server.

A bit off-topic, but when it comes to safari we have a few caveats that aren't expected. lack of opus format is just one of those. Apple could be more web-friendly, IMO.

**Comment by goldfire** [comment]
@sombriks Apple has definitely become very unfriendly to the web (I assume the App Store is a big reason why). We've spent countless hours over the last few months hacking together fixes for Safari in our latest project. It seems to have gotten worse than Internet Explorer, which for any long-time web dev is somewhat hard to believe.

**Comment by voron** [comment]
What about Safari 11, it supports opus

**Comment by bartuer** [comment]
Now, the fact is Safari 11 not support play opus natively, but iOS 11 and macOS High Sierra can play opus in caf (Core Audio Format).

**Comment by ronkorving** [comment]
It's supposedly possible, but I've yet to see a single web example that works. If anyone knows of any, I would love to know!

**Comment by obiot** [comment]
Just curious, but why use opus ? For the web and lossy ausio, those days (with modern browsers), webm with a fallback to mp3 is certainely more than enough

**Comment by ronkorving** [comment]
Opus compresses *a lot* better than MP3.
Also, I thought webm was video?

**Comment by zefie** [comment]
webm can hold vorbis as well, even though that doesnt work on apple.

If you are interested in gapless looping with howler check out [my unofficial modifications](https://loops.planeptune.org/?debug=core) to howler. For cross-browser compatiblity and gapless looping I suggest encoding AAC, WebM (Vorbis) and MP3. This covers nearly any browser. In my experience Chrome and FF on windows will get WebM (vorbis), Apple gets AAC, and IE gets either AAC or MP3 depending on the version.

**Comment by ronkorving** [comment]
@zefie It looks like AAC is pretty well supported [across the board](https://caniuse.com/#feat=aac)

**Comment by AnthumChris** [comment]
Opus can be played in Safari 11+ with WebAssembly and the Web Audio API:

> https://fetch-stream-audio.anthum.com
<br>https://github.com/AnthumChris/fetch-stream-audio

Using an exponential playback buffer, larger files (I tested with 6 min songs) can be played as long as too many unplayed `AudioBuffer` objects are not scheduled.

**Comment by pixel-paul** [comment]
Is it possible to fallback to a mp3 file if the opus stream can't be played?

**Comment by chrisvire** [comment]
[ogv.js](https://github.com/brion/ogv.js/) does WebAssembly transcoding of Ogg Opus in WebM on Safari and Mobile Safari, but doesn't have UI components.
