### ISSUE TITLE
Download the Sprites as mp3 or wav

### ISSUE THREAD

**Issue by ersigcha23** [goldfire/howler.js#708]
Is there any way to download an audio sprite as mp3 or wav file?

**Comment by goldfire** [comment]
There are a few tools out there that can generate sprites for you. One of them is https://github.com/tonistiigi/audiosprite.

**Comment by EugeneHerasymchuk** [comment]
Guys, how did you solve this problem on client side? 
Or there is no other workaround not to use node.js?
