### ISSUE TITLE
SoundID collisions

### ISSUE THREAD

**Issue by lucap86** [goldfire/howler.js#709]
Hi,
first of all thanks for the great library

I've took a look to the soundID generation

```
      // Generate a unique ID for this sound.
      self._id = Math.round(Date.now() * Math.random());
```
It's not very probable but it is possible to have soundIDs collisions

eg.
1487925777697 * 0.5112335233809231 =round(760677537861.3374) = 760677537861
1487925777698 * 0.5112335233809231 = round(760677537861.8486) = 760677537861

so the question is
Why don't just use global ```counter``` that start from 0
every time a new id is needed ```getNextID()``` just ```return ++counter;```

**Comment by themoonrat** [comment]
Sounds like a plan to me
