### ISSUE TITLE
Preload music duration or some data only

### ISSUE THREAD

**Issue by StefansArya** [goldfire/howler.js#711]
Can howler.js preload only the music duration from MP3 or maybe limiting the preload size?
I'm noticed when I tracking the network traffic my music was fully downloaded. It will be a bandwidth wasting if I only want to load all the music to get the music duration..

For the example:
I initialize the Howl
```
var myPlayer = new Howl({
  		src: ['http://example.com/music1.mp3'],
  		html5: true,
  		buffer: true, 
  		format: ['mp3'],
  		preload: true,
  		autoplay: false
});
myPlayer.on('load', function(){
	$('.player-time .duration').html(myPlayer.duration());
});
```

`music1.mp3` have 2mb size, I expect myPlayer to preload only for 500kb or 1mb. But myPlayer was preloaded whole of the mp3...

**Comment by goldfire** [comment]
The browser doesn't give control over this. Once you start to load, it is going to keep loading until it has all of it.
