### ISSUE TITLE
Calling play/pause rapidly in Chrome can cause error

### ISSUE THREAD

**Issue by goldfire** [goldfire/howler.js#718]
This appears to be related to Chrome issue (it is marked as fixed, but it isn't): https://bugs.chromium.org/p/chromium/issues/detail?id=593273

Basically, if you run the following on a sound that is already playing:

```javascript
sound.pause();
sound.play();
sound.pause();
```

You will get the following error in Chrome:

    Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by inear** [comment]
Here is an article describing the issue. https://developers.google.com/web/updates/2017/06/play-request-was-interrupted Is this something that could be handled by howler?

**Comment by nboliver** [comment]
+1 for this issue.

Maybe returning the `audio.play` promise discussed above in `sound.play()` could let developers work their own soltion?

Encountering when trying to play => seek => pause 
(seek while paused)

**Comment by smakinson** [comment]
I'm building a vuejs/quasar UI around howler with a seek bar and when I scrub the slider that calls seek I also see the error.

**Comment by goldfire** [comment]
This has been fixed with #835.
