### ISSUE TITLE
howler.core vs howler?

### ISSUE THREAD

**Issue by abumere** [goldfire/howler.js#722]
Was poking around the docs and couldn't seem to find thing that explains the difference between howler.js and howler.core.js and which is recommended for basic audio playback

**Comment by goldfire** [comment]
howler.js is just the combined howler.core.js and howler.spatial.js. If you don't need stereo or 3D positional sound, then core is all you need.

**Comment by timavaza** [comment]
I was also stuck - read all the documentation and couldn't find an explanation.. Suggest this one should remain open till the documentation is updated.

**Comment by underthegui** [comment]
Same here. I tried looking into the examples to figure it out, but ended up here. I'd like to echo @timavaza 's recommendation.
