### ISSUE TITLE
Support of Angular 2

### ISSUE THREAD

**Issue by Apfelkuchen91** [goldfire/howler.js#727]
I want to use this in a Angular 2 App. Is this possible?

**Comment by Jerczu** [comment]
Yeah just import it as any other external library. Not really user ng2 in a long time but if I can import it for react you should be able to do that for NG2

> import { Howl } from './howler'

**Comment by peterpeterparker** [comment]
Install howler:

    npm install howler --save

Install typescript definition:

    npm install @typings/howler --save-dev

Import howler in your class:

    import { Howl } from 'howler'

**Comment by pinnprophead** [comment]
npm wasn't able to find @typings/howler

**Comment by almgwary** [comment]
Not found : @typings/howler

**Comment by peterpeterparker** [comment]
@almgwary didn't you forget the `@` ? `@typings/howler` not `typings/howler`

**Comment by almgwary** [comment]
found it here `npm install --save @types/howler `

**Comment by almgwary** [comment]
@peterpeterparker 
where to init it in angular 2 app  ? 

* declarations
* imports
* bootstrap
* entryComponents
* providers

**Comment by almgwary** [comment]
can you just show us an example ?

**Comment by peterpeterparker** [comment]
unfortunately I don't have a working example to share :(

**Comment by almgwary** [comment]
i did it, you don't have to init howler with angular app, just import it in your component and use it

```
import { Howl } from 'howler'


@Component({
  selector: 'page-welcome',
  templateUrl: 'welcome.html'
})
export class WelcomePage {

  constructor(public navCtrl: NavController) {

     var sound = new Howl({
      src: ['http://server8.mp3quran.net/ahmad_huth/001.mp3'],
      html5 :true
    });

    sound.play();

   }

   
 
}
```

**Comment by ADFPassion** [comment]
May Allah bless you my friend , it was nice to hear the output as words of Allah <3
