### ISSUE TITLE
Continous play on Safari Mobile iOS

### ISSUE THREAD

**Issue by antwake** [goldfire/howler.js#728]
While trying the player example, I realized that it works on Safari desktop but not on Safari Mobile on iOS.
I know there's a limitation from Apple to mandate user interaction to play a media but I'd thought you'd have find a workaround since you provided the playlist functionality.

Do you plan on adding this feature?

thanks!

**Comment by webmagnets** [comment]
I need multiple mp3s to play one after another after pressing <button>Start</button>

This is working for me everywhere I've tested, except ios.

Any ideas on how to get it work in ios?

**Comment by jurajkapsz** [comment]
Having the same issue, also on some Android devices (viewed through Browserstack.com).

**Comment by malinga91** [comment]
@webmagnets @jurajkapsz Did u find any solution for this?

**Comment by bbrooks** [comment]
I'm having the same issue, iOS 11 won't allow me to sequence mp3s after one user interaction. 
Just try running the Basic Function -> Run Web Audio Test from the homepage gallery on an actual iDevice. Works fine in the simulator, but plays nothing on an actual iDevice.

**Comment by bbrooks** [comment]
@webmagnets  @jurajkapsz  @malinga91 
Turns out you can play a sequence by swapping out the source of the audio object that initially played due to user interaction:

https://jsfiddle.net/bbrooks/pk9h3j2x/

Tested on my iPhone.

**Comment by aareeph** [comment]
Hi @bbrooks is it working fine for you when the device is locked or Safari browser is in background? I am able to play only first sound in a sequence in that case.

**Comment by goldfire** [comment]
This should now be fixed in v2.1.0 using the HTML5 Audio pool.

**Comment by industral** [comment]
it will not work when iPhone will be locked. It will just play the first track and stop.
