### ISSUE TITLE
Fade out works, but fade in does not

### ISSUE THREAD

**Issue by jun-rocketgames** [goldfire/howler.js#731]
//Fade out works great:
audio.Fade(1, 0, 5000);

//Fade in does not work; the audio plays loud right away
audio.Fade(0, 1, 5000);

workaround:
create a loop with delays and adjust the volume that way

**Comment by goldfire** [comment]
Can you provide a test case where it doesn't work? It is working fine in our demo tests.

**Comment by jun-rocketgames** [comment]
sorry, it was user error.  I had code after the fadeIn set the volume up.  Looking good =)
