### ISSUE TITLE
No stereo/panning in Chrome

### ISSUE THREAD

**Issue by bartcheers** [goldfire/howler.js#745]
I'm trying to pan sounds and tried both the Stereo method and the .pos() method. But it seems that Web Audio is not being detected on Chrome and these methods do not have an effect.

The problem is still present when I try other JS audio libraries. I also tried older releases of Howler.

Has there been some change to the latest version of Chrome?

Thanks.

**Comment by goldfire** [comment]
Both stereo and panning are working fine for me in the latest Chrome (https://howlerjs.com/#spatial). If you are still having this issue, please post a test case and I'll reopen.
