### ISSUE TITLE
Pause/Resume HTML5 issue

### ISSUE THREAD

**Issue by digitronics** [goldfire/howler.js#751]
I'm making a react/redux app with electron. I've run into a bit of an issue. What I've found while doing some debugging is this [line](https://github.com/goldfire/howler.js/blob/master/src/howler.core.js#L743) isn't getting set.

I logged `seek` and `node.currentTime` and seems `node.currentTime` is getting set to `0` when trying to resume.

![img](http://i.imgur.com/9KOzj0C.png)

If I don't force HTML5 this works. But I'd like to use HTML5 as it reduces loading time for songs.

**Comment by Stenerson** [comment]
Are you able to reproduce this outside your app (in jsbin or similar)? 

Is it possible that you have multiple sounds defined? I'm thinking *maybe* a new howler sound instance is being created each time the app is "reloaded" by HMR and the seek position is being found from a different sound instance than you're expecting? *Maybe?*

**Comment by digitronics** [comment]
That's what I thought at first too. But I added a log in the `Sound.create()` to see if it was creating a new audio element, and it wasn't. I'm gonna continue to dig a bit see if I can come up with anything else.

**Comment by digitronics** [comment]
I think I've got it. Seems its the way I'm getting the audio. Don't thing the server is returning the correct mime type. Changing out the `src` from another source seems to make it work.

**Comment by Stenerson** [comment]
Off topic: Out of curiosity, have you checked out either:
- [redux-sounds](https://github.com/joshwcomeau/redux-sounds) or
- [react-howler](https://github.com/thangngoc89/react-howler) (shameless plug)

**Comment by digitronics** [comment]
I have but both don't quite do what I want them to do. react-howler, would work in my case, but its a very simple module so I ended up recreating it on my own with a few extra functions.

**Comment by digitronics** [comment]
So did some digging and it was because my content wasn't being served as a stream and didn't have the `Content-Range` header along with it, thus the audio wasn't seekable. I'm going to close this as I've solved my issue.
