### ISSUE TITLE
[Mobile Web Safari] Before click anywhere on my website, i cannot hear the sound.

### ISSUE THREAD

**Issue by hotanlam** [goldfire/howler.js#759]
My code in javascript file:
```
sound = new Howl({
                src: [<my sound>]
              })
sound.play();
``` 
When I open my website by PC Web. It's working, i can hear the sound
But i open my website by Mobile Web Safari. I cannot hear the sound. And after i clicked anywhere on my website, the sound was played.

Do anyone can help me?

**Comment by goldfire** [comment]
This is addressed in the documentation: https://github.com/goldfire/howler.js#mobile-playback

**Comment by hotanlam** [comment]
@goldfire i try with code:
```
Howler.mobileAutoEnable = false;
sound = new Howl({
                src: [<my sound>]
              })
sound.play();
```
But it still is not working, and after i clicked anywhere on my website, i also cannot hear the sound.
:(

**Comment by hotanlam** [comment]
@goldfire Any suggestions from you.
