### ISSUE TITLE
refDistance Clarification in Docs?

### ISSUE THREAD

**Issue by chuckhacker** [goldfire/howler.js#772]
What exactly is refDistance? What happens to far away sounds if I double it? What happens to far away sounds if I halve it?

If I want a "far away" sound to appear to be effectively "louder," how should I change the value of refDistance?

As feedback, the documentation doesn't really explain much with this one here, leaving me more confused with additional unanswered questions. Thanks.

**Comment by goldfire** [comment]
I've just updated the readme for this section to hopefully be more clear.
