### ISSUE TITLE
audio sprite error when using html5 = true

### ISSUE THREAD

**Issue by themoonrat** [goldfire/howler.js#775]
The commit stop html5 audio working for me (webaudio is fine)

https://github.com/goldfire/howler.js/commit/39ac41c0f14b022f763a00f8ab9924b3b96239c0
Lines 1655 to 1661.

The following part of that gives an error
```
if (!self._webAudio && !self._node.ended)
```
Because self._node doesn't exist. I tried changing that to !sound._node.ended, because that location DOES exist, but the bug persists, because sound._node.ended always returns false.

I can replicate this in IE or Chrome, as long as .html5 = true is set. By removing the above lines, everything works fine.

I preload all sounds, and pass to Howler as a blob ... the opposite use case for why this code was introduced!

**Comment by goldfire** [comment]
Thanks for catching this, it should now be fixed on master!
