### ISSUE TITLE
The method "pause(id)" didn't work 

### ISSUE THREAD

**Issue by seito2014** [goldfire/howler.js#781]
Hi Sir :)
The method "pause(id)" didn't work in my case but just "pause()" could work.
This is my report.

## The follow case didn't work

```
const howlSounds = new Howl({
    src: [ soundData ],
    volume: 0.5,
    sprite: {
        soundA: [1500, 4500, true],
        soundB: [0, 1000]
    }
});

howlSounds.pause(soundA);
```

## But this could work
```
const howlSounds = new Howl({
    src: [ 'sounds.mp3' ],
    volume: 0.5,
    sprite: {
        soundA: [1500, 4500, true],
        soundB: [0, 1000]
    }
});

howlSounds.pause();
```

Thank you for using this library!

**Comment by goldfire** [comment]
The ID that you pass into `pause` is the value returned from the `play` method. The only place you would ever pass the sprite name is the `play` method.

**Comment by seito2014** [comment]
I misunderstood it !
