### ISSUE TITLE
No sound in latest Firefox

### ISSUE THREAD

**Issue by zcr1** [goldfire/howler.js#782]
I am having issues playing sound in Firefox. No issues present in Chrome but Firefox doesn't even attempt to fetch the file in the network tab. Using Howler 2.0.4

`
let Howl = require('howler').Howl;
var sound = new Howl({
   src: ['/sounds/songs/start-menu.mp3']
 });
 sound.play();
`

**Comment by themoonrat** [comment]
Have you tried also specifying an ogg fallback, in case Firefox doesn't support mp3?

**Comment by zcr1** [comment]
Thanks - that ended up working.
