### ISSUE TITLE
Do the howler support scroll in the playlist?

### ISSUE THREAD

**Issue by itsucks** [goldfire/howler.js#785]
![image](https://user-images.githubusercontent.com/7105813/27213550-4260d566-529a-11e7-83c9-484e397490e0.png)
Just like that, I got 11 parts. What about more?

**Comment by itsucks** [comment]
OK, I did some changes in style.css, it worked!

**Comment by ogerasymenko** [comment]
What changes you did for scrolling?

**Comment by aleksandrgordienko** [comment]
@ogerasymenko you can add `overflow-y:auto;` to the `#list` class for achieving that
