### ISSUE TITLE
cordova IOS no sound at all!

### ISSUE THREAD

**Issue by eliech** [goldfire/howler.js#788]
how to use with cordova? i linked the 4 links from the cdn
works great in simulator but in ios 10.3.2 no sound at all
and

```javascript
 sound.once('load', function () {
   sound.play();
 });
```

is not being called

**Comment by goldfire** [comment]
Can you provide more details of your code setup? We are using Cordova for some projects and haven't had any issues.

**Comment by eliech** [comment]
Can you provide me with the code than i can use? Im building an app music player with cordova
And i need to implement howler but a global variable so i can play a song wherever im in the app..? And please one more thing
The background audio is working but the controls and the song name and cover are not appearing correctly
