### ISSUE TITLE
Event "fade" not working on firefox

### ISSUE THREAD

**Issue by xMADOXX** [goldfire/howler.js#790]
Hi,
I'm using Howler to create my audio component and where I'm really interested in is to be able to fire when an audio has ended to fade. So I've used howler function like that : (this function allow to smoothly switch between two sources)
```
            var self = this;

            if(!this.current.audioSource.playing()){
                  this.current.audioSource.play();
            }
            this.oldCurrent.audioSource.fade(volume, 0, time);
            this.current.audioSource.fade(0, volume, time);

            this.oldCurrent.audioSource.once('fade',function(){
                  // Utils.log(self.oldCurrent.firstName +" is now OFF and\n"+ self.current.firstName+" is now ON");
                  self.oldCurrent.audioSource.stop();
            });
```
It works perfectly on Chrome but on Firefox, the event is called randomly (and for most of the time not even called). The function is called when I clicked on a button. 

Can someone help me on this point ?
Thanks in advance!

**Comment by goldfire** [comment]
What type of audio file are you using?

**Comment by xMADOXX** [comment]
All source files are mp3
