### ISSUE TITLE
the use of _queue

### ISSUE THREAD

**Issue by rogerwang2014** [goldfire/howler.js#794]
hello~friend, i want to display several songs in one page, and these songs could control with only one process bar, e.g. the first song contains 25%, when the bar goes to 26%, play the second one.   hope you can show me an example, thanks a lot!

**Comment by goldfire** [comment]
You would likely want to chain `end` events. However, as this isn't an issue with the library I'm going to close this. You may want to post on stackoverflow.com with the `howler.js` tag.
