### ISSUE TITLE
Any plan to promisify Howl?

### ISSUE THREAD

**Issue by nicgirault** [goldfire/howler.js#799]
Hello,

Thanks for this amazing project.

Would it make sens to promisify Howler? For example I would like to write this kind of code:

```javascript
const hello = new Howl({src: ['hello.webm']})
const byebye = new Howl({src: ['byebye.webm']})

hello.play()
.then(() => {
  byebye.play()
})
```

It's quite simple to wrap the librairy but I'm surprised it's not included in the librairy. Any reason why it's not implemented?

Otherwise what would be your suggestion to implement a quiz with multiple oral questions (my sounds) and waiting for user answer before playing next question?

Thanks for your help

**Comment by goldfire** [comment]
Promises generally replace callbacks, which aren't generally part of Howler as the library mostly uses events for everything (https://github.com/goldfire/howler.js#listen-for-events). This isn't to say promises won't be added in the future, but it isn't a priority at the moment as the API was never setup like that.

**Comment by nicgirault** [comment]
Thanks for the answer

**Comment by Fragilem17** [comment]
+1 for promises, especially on the the fade method :-)
