### ISSUE TITLE
Pausing a sound that is triggered by "on('end',..."

### ISSUE THREAD

**Issue by DavidDrees** [goldfire/howler.js#800]
Hello!

I posted this question on the GoldFireStudios page but didn't receive a response, so maybe someone here will be able to help? Thanks!

--

I'm stuck at the following point. The idea is to play an intro sound, which on end, will trigger another sound that will loop indefinitely (until paused). However, I'm having trouble getting the looping (2nd) sound to pause. I can play and pause the first sound btw.

Please view my following code:

```
document.getElementById("play").addEventListener("click", play);
document.getElementById("playbutton").addEventListener("click", play);
document.getElementById("pausebutton").addEventListener("click", pause);

var sound = new Howl({
  src: ['res/beats/1.mp3'],
  preload: true,
  autoplay: false,
  volume: 1,
});

sound.on('end', function(looper){
  var sound = new Howl({
  src: ['res/beats/1loop.mp3'],
  loop: true,
  buffer: true,
  preload: true,
  autoplay: true,
  volume: 1,
});
console.log(sound);
});

function play(){
  sound.play();
}

function pause() {
  console.log("pause triggered");
  sound.pause();
}
```

Thank you!

**Comment by themoonrat** [comment]
Only took a quick glance, but you have 2 vars called sound that'll be clashing

**Comment by DavidDrees** [comment]
Good point themoonrat:

This code is changed but still having issues:

`
document.getElementById("play").addEventListener("click", play);
document.getElementById("playbutton").addEventListener("click", play);
document.getElementById("pausebutton").addEventListener("click", pause);
		
		
		var sound = new Howl({
			src: ['res/beats/1.mp3'],
			preload: true,
			autoplay: false,
			volume: 1,
		});

		
			
		
		sound.on('end', function(loop){
			var loop = new Howl({
				src: ['res/beats/1loop.mp3'],
				loop: true,
				buffer: true,
				preload: true,
				autoplay: true,
				volume: 1,
			});

		});
		
		
		function play(){
			sound.play();
		}
		
		function pause() {
			console.log("pause triggered");
			sound.pause();
		}
`

**Comment by goldfire** [comment]
The problem is that you have two separate howl instances (`sound` and `loop`), but your pause function is only pausing the first one.
