### ISSUE TITLE
Uncaught ReferenceError: Howl is not defined

### ISSUE THREAD

**Issue by desper4do** [goldfire/howler.js#801]
Does it need to be run on server?

**Comment by desper4do** [comment]
I'm including lib like one of these:

    <script src="node_modules/howler/dist/howler.js" type="javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.4/howler.js" type="javascript"></script>

and just opening html locally

**Comment by Stenerson** [comment]
Nothing special is required to load/use Howler. [Here's a stand alone jsbin](http://jsbin.com/natimup/edit?html,js,console) that loads Howler from the CDN via `script` tag and autoplays a sound. 

I use this as a template for reproducing bugs so it's pretty bare bones. Hopefully it helps!

**Comment by desper4do** [comment]
Thanks for a help. It was actually my silly error, my html knowledge got rust :)
