### ISSUE TITLE
Volume can't be changed on iOS

### ISSUE THREAD

**Issue by Taxel** [goldfire/howler.js#805]
Hi @goldfire, 
In my Meteor Cordova App I am using Howler for audio playback of two separate tracks. The volume of those tracks can be changed via a simple crossfader (middle: both vol. 1, left: only one track vol. 1, other one vol. 0, linearly interpolated...).
Everything works fine in Chrome and Android, but on iOS changing the slider has no effect on the actual audio volume. From Howler's perspective, however, the volume is set correctly (I have tested this by constantly outputting the current _howler.volume() ).
We have tested several iOS versions (devices as well as in the simulator), but the problem is always the same: Volume is apparently set and stored correctly in Howler but what you hear stays the same.

Some help with this would be highly appreciated.
Thanks in advance,
Taxel

**Comment by goldfire** [comment]
If you have `html5` set to `true` then this is not possible on iOS ([Apple docs](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html)). However, if you don't use HTML5 Audio then it should work fine.
