### ISSUE TITLE
playing multiple sounds doesnt work in 2.0.4, sound id always 1001

### ISSUE THREAD

**Issue by markknol** [goldfire/howler.js#806]
I get the same id `1001` on each howl instance when I do `howl.play()`. 
I reverted to 2.0.3 and then it works again. 

I used this code in constructor of my class:
```
this._sound = Sounds.instance.GHOST_MOVE;
this._soundId = this._sound.play();
console.log("ghost", this._soundId);  
this._sound.volume(0, this._soundId);
this._sound.loop(true, this._soundId);
```

When I create 4 ghosts in my game:

* Version  2.0.4 logs: 1001,1001,1001,1001 (unexpected) 
* Version  2.0.3 logs: 1,2,3,4 (expected) 

Tested on:
- Windows 10
- Chrome 60.0.3112.90 (Official Build) (64-bit)

**Comment by markknol** [comment]
😕  After some investigation, it seems I cannot update volume separatly even if ids are diffreent. I "fixed" it by creating multiple Howl objects with same sources, but according the readme this should not be needed. I don't really get what I am doing wrong.

**Comment by goldfire** [comment]
Can you show a full example? This is definitely working correctly as it works fine in all of the tests/examples and our games as well.

**Comment by markknol** [comment]
No cannot give example. Sorry it does seem to work all good bow. Not sure what was going on.
