### ISSUE TITLE
mobileAutoEnable non functional on ios safari

### ISSUE THREAD

**Issue by BennettStaley** [goldfire/howler.js#807]
I'm having a pretty frustrating issue. I've tried every solution under the sun and I cannot get the mobileAutoEnable to work properly on any iPhone or iPad I've tried.

So far I've:
- manually forced mobileAutoEnable to true, 
- disabled html5, 
- included formats: mp3, m4a, webm, ogg, wav, and more
- switched to using audioSprites
- defined a Sound constructor like in the "3d" example
- defined sound playing prototypes ontop of that
- and just about everything else you can probably thing of.

yet still, safari refuses to play any sounds even after user interaction. I reference the "3d" example because it obeys the phone's mute switch and auto enables itself correctly.

A workaround I introduced was my own event listener on window, shown below. This "works" however it does not care if the phone is silent or not, unlike the "3d" demo. This is a huge issue as bypassing the ringer switch for notification sounds is not a good idea.
```javascript
const unlock = () => {
  // unlocks sounds for mobile devices (ios / safari)
  biddingSound.playSound('BID'); // defined as a sprite (plays fine on desktop)
  setTimeout(() => {
     // then it removes itself from window.
    window.removeEventListener('touchstart', unlock, false);
  }, 500);
};

// if we are on mobile, set the listener
// isMobile is a boolean value that detects mobile browsers
isMobile && window.addEventListener('touchstart', unlock, false);
```

Below you can find the whole code of my sound module.

```javascript
// @flow
import { Howler, Howl } from 'howler';
import { isDeviceIOS, isDeviceAndroid } from 'lib/platform';

const isMobile = (isDeviceIOS || isDeviceAndroid);
const canVibrate = 'vibrate' in navigator || 'mozVibrate' in navigator;
if (canVibrate && !('vibrate' in navigator)) {
  navigator.vibrate = navigator.mozVibrate;
}

const vibrate = () => {
  // catch, if mobile, but no vibrate method.
  navigator.vibrate && navigator.vibrate(500);
};

const Sound = function() {
  // Setup the shared Howl.
  this.sound = new Howl({
    src: [
      '../output.mp3', // these are actually hosted offsite on an amazon s3
      '../output.webm', // these are actually hosted offsite on an amazon s3
    ],
    html5: false,
    preload: true,
    sprite: {
      SILENCE: [
        0,
        1000,
      ],
      TIMER_BEEP: [
        2000,
        548.5714285714284,
      ],
      BID: [
        4000,
        1358.3673469387759,
      ],
      BID_USER: [
        4000,
        1358.3673469387759,
      ],
      NOTIFICATION_CLERK: [
        7000,
        1515.102040816327,
      ],
      NOTIFICATION_SOLD: [
        7000,
        1515.102040816327,
      ],
      NOTIFICATION_BIDDING: [
        10000,
        1227.7551020408168,
      ],
    },
    volume: 0,
  });

  this.playSound = (soundImport: string) => {
    this.soundPlayer(soundImport);
  };
};

Sound.prototype = {
// create the soundplayer
  soundPlayer(
    soundImport: string,
  ) {
    isMobile && vibrate();
// calls the playsound
    this[soundImport] = this.sound.play(soundImport);
    this.sound.volume(0.2, this[soundImport]);
  },
};

const biddingSound = new Sound();

biddingSound.mobileAutoEnable = true; // sanity check, i know this doesn't do anything
Howler.mobileAutoEnable = true;

// export the function to use elsewhere on the site
export default biddingSound.playSound;
```

This is all working on desktop. 
I'm at a loss. Any Ideas?

**Comment by goldfire** [comment]
From a skimming of the code, I'm not seeing anything that stands out as being an issue. Are you saying that after clicking somewhere on the screen the audio still doesn't work (with the mute switch turned to un-mute)?

**Comment by BennettStaley** [comment]
Yes. Neither works, muted or not. The solution I implemented was a sort of hack to get it working,  with the downside being it takes over the phone audio and ignores the mute switch. (you can see the aws url in the control center, constantly looping). 

I think it might be some error with the way its working with webpack / react. Thoughts?

**Comment by BennettStaley** [comment]
As an update, I'm closing this as i found a solution, as well as a bug.

1. The mobileAutoEnable setting does NOT work within a react-webpack transpiled app. You must build your own, like the one above. (which works great with sprites that have silence at the beginning)

2. If any other part of your app is using HTML5 Audio, it will override the WebAudio setting within howler. I had an issue where a live chat app was using HTML5 Audio and forcing howler to use it as well.

Hopefully this helps someone else and they spend WAY less time debugging than I did.

**Comment by roshangm1** [comment]
Can I see the code for your hack ? My code works on Desktop seamlessly but not on Android and iOS. 
What do you purpose for playing music on the page load in mobile without user interactions ?
