### ISSUE TITLE
How can i control the onplay event frequency

### ISSUE THREAD

**Issue by Saul-Shen** [goldfire/howler.js#809]

**Comment by goldfire** [comment]
I'm not sure I follow what you are asking. Can you explain further?

**Comment by Hokkaidosunny** [comment]
Except onplay, onstop, ...., if there is an onprogress event would be great. This event would be triggered by the controlled frequency, and can tell me the progress of the audio. Now, I know I can use setInterval to detect the audio progress, but onprogress event would be better.
