### ISSUE TITLE
Android webview can not play audio files.

### ISSUE THREAD

**Issue by QiannanXu** [goldfire/howler.js#810]
HI @goldfire 

Please refer to the latest response in this issue. https://github.com/goldfire/howler.js/issues/482

 I got the same issue on Mobile 『MeiZu』and 『Xiaomi』，both work in browser, but not in APP webview. 

My spiking result is when this device loaded this audio file, it always returned 0 for audio.duration and 0 for audio.seek. 
Any thinking about this issue?

**Comment by QiannanXu** [comment]
And also when I open your demo page `https://howlerjs.com/` in above device webview, such as the first one `Music Player`, it just keeps looping to next song and never play any sound.

**Comment by erikhu** [comment]
you write the permissions in the manifest?

**Comment by PEZO19** [comment]
I have a very similar problem [here](https://stackoverflow.com/questions/50437894/how-to-play-audio-in-android-webview-with-react-and-howler-js).

**Comment by SolidZORO** [comment]
+1
