### ISSUE TITLE
event playerror does not exists in v2.0.4

### ISSUE THREAD

**Issue by nicgirault** [goldfire/howler.js#813]
This code trigger an error:

```javascript
sound.once('playerror', (sid, message) => {
    console.log('play error', message)
}
```

TypeError: Cannot read property 'push' of undefined
    at Howl.on (howler.js:1552)
    at Howl.once (howler.js:1612)
    
I looks like the event is not defined:

![image](https://user-images.githubusercontent.com/551837/30158963-49a6e6b2-93c7-11e7-8bdd-1b0aadaec624.png)

**Comment by goldfire** [comment]
This is fixed on master and will be included in 2.0.5.
