### ISSUE TITLE
Volume for sprites

### ISSUE THREAD

**Issue by jneuendorf** [goldfire/howler.js#817]
Is it possible to play different sounds of a sprite with different volumes or would I have to create a `Howl` for each individually 'volumed' sound?

**Comment by themoonrat** [comment]
According to the docs
```
volume([volume], [id])

Get/set volume of this sound or the group. This method optionally takes 0, 1 or 2 arguments.

volume: Number optional Volume from 0.0 to 1.0.
id: Number optional The sound ID. If none is passed, all sounds in group have volume altered relative to their own volume.
```

This, with a howl, calling ```.volume(0.5)``` would halve the volume of any sounds on that Howl, or, after playing a sound, you get an id back. Use that id when calling volume and pass through that id you go, and it'll lower the volume of just that ``` .volume(0.5, 12421)```

**Comment by jneuendorf** [comment]
Thanks, that seems to work 😄 

Just one more question (since you're a contributor ^^): How does `relative to their own volume` work? If a sound is at `1.0` and I set `.volume(0.5)` it'll be `0.5` (all good).
But if the volume value is really relative I couldn't change it back to `1.0` (because the max allowed value is `1.0` and I'd have to use `0.5 * 2.0 = 1.0`)

**Comment by themoonrat** [comment]
Correct (tho don't know if you can set a volume of higher than 1, haven't tried it, so it may be if the Howl volume is at 0.5, effectively the individual sound may never be louder than 0.5, with its own volume at 1).

Essentially, if you're going to be handling individual sound volumes, then don't touch the overall Howl volume to avoid confusion. Well, I touch it occasionally if I wanted to fade all sounds out to silence, for example, but that's it.

**Comment by jneuendorf** [comment]
Thanks for clarification!
