### ISSUE TITLE
fade event in once method doesn't differentiate between fade in and fade out

### ISSUE THREAD

**Issue by mojenmojen** [goldfire/howler.js#818]
```
ambHowl.once(
    'fade',
    () => { ambHowl.unload(); },
    audioId
);
```
I use fade to fade in audioId, and then I have the code above to have it unload after a fade out. However this code unloads after the fade in. 

Is there a way to specify which fade I want it to occur on, or is there another way I could go about this?

**Comment by goldfire** [comment]
There is only one event for this, but you could check the volume of the sound inside of the callback.

**Comment by mojenmojen** [comment]
OK, I'll try that. Thank you for the prompt reply.
