### ISSUE TITLE
playing method returns false when sound is playing

### ISSUE THREAD

**Issue by mojenmojen** [goldfire/howler.js#819]
```
var ambSound = new Howl({
    src: [ ambience ],
    loop: true,
    volume: 1
});
var ambSoundId = ambSound.play();
var isPlaying = ambSound.playing( ambSoundId );
```

In the above code, the sound is audible but isPlaying returns false.

v.2.0.4

**Comment by goldfire** [comment]
That is technically correct because when you check `.playing()`, the sound likely hand't actually started since the playback is async. It won't be set to playing until the browser actually begins the playback.
