### ISSUE TITLE
Radio demo doesn't play in Opera 48

### ISSUE THREAD

**Issue by EugeneRush** [goldfire/howler.js#820]
Radio demo doesn't play in Opera 48

**Comment by goldfire** [comment]
It looks like this is because of a mixed content warning. Unfortunately, SomaFM doesn't appear to have HTTPS support, so we may need to find alternate radio streams that do to get this working again. Does anyone have any suggestions?

**Comment by EugeneRush** [comment]
Demo (sound manager) working in opera (Mixed Content too)
https://codepen.io/EugeneRush/pen/gmGdqy

**Comment by goldfire** [comment]
I just tested in the latest Opera and it is working for me again. I'll reopen if you are still having this issue.
