### ISSUE TITLE
Fade refactor means some sounds stay faded out

### ISSUE THREAD

**Issue by themoonrat** [goldfire/howler.js#823]
Working with sound sprites, and fading sounds in and out in the game I'm making. I'm playing a sprite sound at normal volume, then fading it out. I then play a new instance of that sound, and this new instance has the same faded out volume as the previous instance (when it's a new instance, so should be at normal volume again).

Haven't quite managed to nail down a narrow scope reproduction of the issue outside of the game lib, but working on it!

The commit here: https://github.com/goldfire/howler.js/commit/dbdf373f33412a7b7839b2ce2665f9db74200ea1
is what breaks it. The howler version before this commit works fine

**Comment by themoonrat** [comment]
Got it!

Using the sound2 file from the Howler tests

```
const sound = new Howl({
  src: ['./snd/sound2.webm', './snd/sound2.mp3'],
  sprite: {
    one: [0, 450],
    two: [2000, 250],
    three: [4000, 350],
    four: [6000, 380],
    five: [8000, 340],
    beat: [10000, 11163]
  }
});

// Clear listener after first call.
sound.once('load', () => {
    window.setInterval( () => {
        const id = sound.play('beat');
        sound.fade(sound.volume(), 0, 3000, id);
    }, 2000 );
})
```

So you see, I'm saying fade from whatever the _current_ sound volume is, to 0. Well, it's not getting the volume of the new sound instance I've just created, it's getting the volume of the previous instance (which has already faded out to some degree)

**Comment by goldfire** [comment]
Thanks for the test case, I've tracked it down and will have the fix on master shortly.
