### ISSUE TITLE
Audio is muted even after one time user interaction.

### ISSUE THREAD

**Issue by roshangm1** [goldfire/howler.js#839]
I can only hear sound when there is user interaction in mobile (Android and iOS) everytime. I thought, it was suppose to work this way:

**Expected:**
User interaction (play first song)
Play other songs in the playlist without any user interaction (with unmuted audio).  

**Reality:**
User interaction (play first song)
I think songs in the playlist are played but i can't hear any sound without user interaction.

HTML5 is true.

**Comment by goldfire** [comment]
Unfortunately, this behavior doesn't work the same with HTML5 Audio on Android. I'm not sure of any workaround at this time, but if one is found we'll get it implemented.
