### ISSUE TITLE
Calling 'seek' throws Unhandled Promise Rejection in Safari

### ISSUE THREAD

**Issue by Joebayld** [goldfire/howler.js#840]
Hi all, 

Noticing some strange behavior. I have the onplay callback trigger another function that seeks the track to a specific time. This works great in Chrome, however, the seek method throws an error in Safari. It says 'Unhandled Promise Rejection: [object DOMError]'. Any ideas on this?

**Comment by TxAg12** [comment]
Sounds like their lockout of media files. Does it work if HTML5: false?

**Comment by goldfire** [comment]
Do you have a test case? I just setup a fiddle doing what I think you are saying and I didn't get any errors in Safari.

**Comment by eugene-lazarev** [comment]
Hey @goldfire, it is actually appears everywhere in Howler on Safari 11 Mac OS. Even on your "Music player" violet demo

**Comment by eugene-lazarev** [comment]
I found the problem and after fast googling I found a solution.

Please check my pull request and accept it ASAP because for now any Howler 2.0.x is crashing on Mac OS Safari 11 when you use "seek" method.

Thank you very much.

**Comment by fabswt** [comment]
Still getting these in Howler 2.0.12 and 2.0.13 with Safari Version 11.0.1 (12604.3.5.1.1). Getting it in a personal project where it causes the audio to stop working, and getting it in the violet Music player demo too:

![screen shot 2018-07-04 at 11 12 51 am](https://user-images.githubusercontent.com/3042488/42268476-e555a332-7f7b-11e8-8430-646bafe7a8ea.png)

I wasn't able to trigger them on demand yet.

**Comment by goldfire** [comment]
@fabswt Any idea what triggers this? I haven't been able to get it to happen on my end yet.

**Comment by Krankypanky** [comment]
Hello I do have the same issue - sound is not playing on safari on iphone, ipad and macbook.
<img width="837" alt="screen shot 2018-07-30 at 17 10 07" src="https://user-images.githubusercontent.com/25614254/43406003-8f50aeb4-941b-11e8-9273-e16471606730.png">
