### ISSUE TITLE
in 2.0.5 'end' event is not firing anymore in IE11 

### ISSUE THREAD

**Issue by Friksel** [goldfire/howler.js#841]
After upgrading a project from Howler 2.0.3 to 2.0.5, the 'end' event is not being fired in IE11 anymore (using .mp3). The event still works in Edge (using .mp3) and Opera and Chrome (using .ogg) are still working fine too. After downgrading to Howler 2.0.4 or 2.0.3 the event is working fine again.
Tested in two different projects.

**Comment by washu** [comment]
same here

**Comment by stephanedemotte** [comment]
same here, on chrome mac.

**Comment by tspringborg** [comment]
Windows IE 11 in browserstack. Same thing.
