### ISSUE TITLE
Content and file type for streaming

### ISSUE THREAD

**Issue by volkan-umg** [goldfire/howler.js#845]
Hello,

Does it stream audio for all content types or do we need to have a specific type? Also do you know if it supports mp4 for streaming?

When I play mp3 it sends one request but when I use mp4 it sends 3 requests. It's not entirely clear to me whether it's streaming or not mp4 audios.

Any ideas are welcome.

Thanks in advance.

**Comment by goldfire** [comment]
If the browser supports it then howler supports it. Take a look at https://github.com/goldfire/howler.js#format-recommendations.
