### ISSUE TITLE
Media control widget on lock screen on ios

### ISSUE THREAD

**Issue by joker-777** [goldfire/howler.js#849]
Hello,

Thanks for your awesome library. We would like to use your library to play short audio files in an online trainer. While doing this we can see this control widget on iPhone and ipads when the screen gets logged. Is there any way how we can disable this?

![photo](https://user-images.githubusercontent.com/378859/32610075-f338ca76-c561-11e7-8038-7503577ce410.jpg)

Thanks

**Comment by joker-777** [comment]
@goldfire Hi, could you give me some feedback about this problem?

**Comment by goldfire** [comment]
Unfortunately, I don't believe there is a way to disable that. I've looked for a workaround in the past and couldn't find anything. If anything has changed I'll be happy to re-open this and get it implemented.

**Comment by joker-777** [comment]
@goldfire Thanks for your response. Good to know that you are aware of it. Any idea why it doesn't happen with SoundManager2?

**Comment by joker-777** [comment]
@goldfire Hi, any news about this. I'm especially interested in why this doesn't happen with soundManager2 but with Howler?
