### ISSUE TITLE
Problem with player

### ISSUE THREAD

**Issue by yoyakuio** [goldfire/howler.js#850]
Hello,
I am using on my record vinyl platform the following plugin that is using Howler's Audio Library : 
https://codecanyon.net/item/fullwidth-audio-player-wordpress-plugin/1321160

I contacted the developer of the plugin because of the issue and he answered me "have no idea how to improve this . The audio library I am using its not developed by me." and proposed me a refund...

So I'd like to present the problem and see how we can resolve it : 

Here's my online record store : https://www.yoyaku.io 
The snippets of every product are lasting around 1min30 and in my sector our customers they advance very fast to check if they like the sound. 
When you play a product and then click in order to advance in the track it stops brutally. 
You have to relaunch the track once again. 
It works the first time you try, but at the second try on an other product it doesn't work neither on SAFARI nor CHROME. 
I made a small video recording my screen with notes to show you : 
https://player.yoyaku.io/mp3/PROBLEME_PLAYER.mp4

The developper of the plugin proposed me a refund of the plugin since the problem is apparently from Howler's audio library, but we uploaded over 4000 tracks using this plugin and the migration would take a month of waste of time of a guy of our team. 

I would be very grateful to have a solution and have this situation enlightened. 

Thank you

**Comment by goldfire** [comment]
I'm not quite sure this is a howler issue unless I'm missing something. If you are using howler directly and seek on multiple different tracks it continues to work correctly (for example, check our player demo at https://howlerjs.com/#player).
