### ISSUE TITLE
Problem playing mp3 file on Edge

### ISSUE THREAD

**Issue by KenilDomadia** [goldfire/howler.js#852]
I am trying to play mp3 file on Microsoft edge browser using howler. I receive the error in console as `WEBAUDIO17014: Decoding error: The stream provided is corrupt or unsupported.`

**Comment by goldfire** [comment]
It sounds like a problem with your specific file, you might want to try re-encoding it. I'm not seeing any issues playing MP3 files on Edge.

**Comment by kPanesar** [comment]
MP3 files work fine for me as well in Edge. Have you tried different MP3 files? As @goldfire said, your file might be corrupt to begin with.

**Comment by KenilDomadia** [comment]
I converted wav to mp3 files and was trying to play the files. I tried reconverting these files and it worked now. Thanks!
