### ISSUE TITLE
How does Web Audio API cross domain?

### ISSUE THREAD

**Issue by 0x2018** [goldfire/howler.js#860]
I'm writing analyser.
I need to use Web Audio API, so I can't use html5.

No'Access-Control-Allow-Origin'header is present on the requested resource.

**Comment by a7517** [comment]
the problem is, when you use the html5 option, you cannot get data out of the audioContext analyser.

**Comment by goldfire** [comment]
The `Access-Control-Allow-Origin` header must be set on your server (or wherever the audio file is being loaded from).
