### ISSUE TITLE
Audio playback randomly stops on iOS

### ISSUE THREAD

**Issue by jeffreylanters** [goldfire/howler.js#862]
I'm working on a mobile web app, where audio is key. It is embedded in an WKWebView in a native iOS app. Audio works perfectly, but sometimes audio playpack randomly stops when returning to the app. This only happens when the app was put in background mode, but I did not find a patern when it's happening.

When it happens, pressing my volume buttons no longer adjusts the app volume, but adjusts the ringer volume instead. I'm using Howler 2.0.5 in ReactJS, running iOS 11.1 on an iPhone 7 plus. No error's are caused and the object carrying the Howl's is not touched and is still in memory.

I have tried things such as minizing the app, player music from another app, returning to my app. Locking my phone or making a call. Non of these attemps seem to cause the error. Is there a way I cloud unload everything and reload, or re-trigger the audio playback? Is anyone experiencing the same problems? Any solution?

Thanks in advance!

**Comment by tonyka** [comment]
I have the same problem on iOS Safari and after some searching (and anguish) I wrote it off as Apple just being Apple. I even wrote a contrived example without Howler and it still doesn't work correctly. So I'm positive that Howler isn't the problem here.

Not only does the sound stop randomly but if you're using sprites, the seek value sometimes randomly resets to 0 so you're playing the wrong sound.

Safari is the new IE6. No fullscreen API, buggy WebAudio, buggy WebGL, doesn't respect user-scalable=no, randomly resizes the viewport and many other things that make you want to pull your hair out.

**Comment by jeffreylanters** [comment]
FYI - I moved the audio player in my Xcode project and handle them with WKMessages.

**Comment by damrbaby** [comment]
I ran into the same issue in Safari on iOS 11 and WKWebView, and was able to ensure audio played on resume with the following code:

```javascript
// Ensure audio doesn't cut out when backgrounded and resumed on iOS
document.addEventListener('visibilitychange', () => {
  const { ctx } = Howler;
  if (ctx && !document.hidden) {
    setTimeout(() => {
      ctx.resume();
    }, 100);
  }
}, false);
```

**Comment by maxijonson** [comment]
For anyone running into this issue in 2024, @damrbaby 's solution is on the right path, but `document.hidden` didn't do it for me. If it doesn't work for you either, try checking `document.visibilityState` instead. Maybe something changed since 2018 to those APIs...

```ts
// Ensure audio doesn't cut out when backgrounded and resumed on iOS
document.addEventListener('visibilitychange', () => {
  const { ctx } = Howler;
  if (document.visibilityState !== "hidden") {
    setTimeout(() => {
      ctx?.resume();
    }, 100);
  }
}, false);
```

**Comment by suzukieng** [comment]
Sorry for hijacking this ticket. I am not a Howler.js user, but I do use the WebAudio API and I'm seeing intermittent cases where the AudioContext is in 'interrupted' state after a Home Screen App (PWA) returns back to focus, and resuming the context after the visibility changes back to 'visible' resolves, but the AudioContext switches immediately back to 'interrupted'. I can not reliably reproduce it, unfortunately, but it has happened at least once and I was able to confirm that calling .resume() on an AudioContext with state 'interrupted' can resolve but the state immediately switches back to 'interrupted'.

Some people in other Github issues of other projects claim that .resume() must be called from a UI event like 'touchend', and I think that may have something to do with it. I already have 'on touch' logic for creating and resuming the AudioContext in place, my thinking currently is that whenever the state goes to 'interrupted' I could basically discard or mark it as 'stale', and start listening for a touch event to create a new AudioContext.

Just wondering if @maxijonson 's workaround is working for everybody but me. :-)

Oh, and if there are support groups for people having to deal with WebAudio on iOS, point me to them...
