### ISSUE TITLE
Some incoming WebAudio API deprecations

### ISSUE THREAD

**Issue by ibc** [goldfire/howler.js#863]
In Chromium 62:

> [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
> 
> [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

**Comment by goldfire** [comment]
Thanks, looking into this now. Closing this one as duplicate of #856.
