### ISSUE TITLE
Do you have an example of dragging progress bars?

### ISSUE THREAD

**Issue by 0x2018** [goldfire/howler.js#864]
I'm very sorry, I can't implement a drag - and - drop audio progress bar.
The following is my code, and the progress bar I created can't be dragged when it is played.
And it is not possible to display the cached progress.

> 
    $(document).ready(function () {
        var progress = $('.progress');
        var onSlide = true;
        progress.rangeslider({
            polyfill: false,
            rangeClass: 'rangeslider',
            disabledClass: 'rangeslider--disabled',
            horizontalClass: 'rangeslider--horizontal',
            verticalClass: 'rangeslider--vertical',
            fillClass: 'rangeslider__fill',
            handleClass: 'rangeslider__handle',
            onInit: function () {
            },
            onSlide: function (position, value) {
            },
            onSlideEnd: function (position, value) {
                onSlide = true;
                sound.seek(value);
            }
        });
        var sound = new Howl({
            src: ['http://localhost:63342/9a97da5f5ac50d63f01e094b6f6ba4b2.mp3'],
            html5: false,
            onplay: function () {
                var duration = Math.round(sound.duration());
                progress.attr("max", duration);
                progress.rangeslider('update', true);
                console.log(formatTime(duration));
            }
        });
        sound.play();
        function formatTime(secs) {
            var minutes = Math.floor(secs / 60) || 0;
            var seconds = (secs - minutes * 60) || 0;
            return minutes + ':' + (seconds < 10 ? '0' : '') + seconds;
        }
        (function callee() {
            if (sound.playing() && onSlide) {
                var seek = Math.round(sound.seek());
                console.log(formatTime(seek));
                progress.val(seek).change();
            }
            requestAnimationFrame(callee);

        })();
    });

**Comment by GeanAlexandre** [comment]
https://github.com/GeanAlexandre/howler-progress-bar
