### ISSUE TITLE
window globals are created even when using AMD

### ISSUE THREAD

**Issue by ibc** [goldfire/howler.js#865]
These [lines](https://github.com/goldfire/howler.js/blob/master/dist/howler.js#L2237) are generating many `window.XXXXX` even when using CommonJS (`const howler = require('howler')`)  to load howler.js within a browserify based app.

So I don't think that the comment above is true:

```
  // Define globally in case AMD is not available or unused.
  if (typeof window !== 'undefined') {
    window.HowlerGlobal = HowlerGlobal;
    window.Howler = Howler;
    window.Howl = Howl;
    window.Sound = Sound;
  } else if (typeof global !== 'undefined') { // Add to global in Node.js (for testing, etc).
    global.HowlerGlobal = HowlerGlobal;
    global.Howler = Howler;
    global.Howl = Howl;
    global.Sound = Sound;
  }
```

Well, being honest, what those lines are doing is defining globals in case AMD is available or not. This is: always.

Just wondering, why such a manual [build system](https://github.com/goldfire/howler.js/blob/master/package.json#L24)? From my experience, it's much better to have a source tree that uses CommonJS's `require()` or ES6 `import` to load other files in the tree, expose the entry point in the `main` field of package.json and, if you also wish to provide a bundled/dist file, just have a browserify/webpack task somewhere (gulp/grunt) that generates such a single bundled file in `/dist` so users can take it for using howler.js within a legacy `<script>` tag.

NOTE: If you use browserify for that purpose, it won't generate globals unless necessary. Also, you may want to create a **single** global `Howler` rather than polluting any app with globals such as `Sound`.

**Comment by jmo84** [comment]
I agree that "window" shouldn't be assigned to unless absolutely necessary because it does nothing but slow down the host app. Although Howler does check for "exports" and "define" it still pollutes the "window" no matter what.

**Comment by ibc** [comment]
@goldfire any update to this? Would you accept a PR with a new build system based based on browserify (for generating the bundle/dist library)?

**Comment by ibc** [comment]
Friendly ping. Any change to get a response, please?

**Comment by Offirmo** [comment]
I’m starting a full ESM app and I get `Uncaught (in promise) ReferenceError: HowlerGlobal is not defined (howler.js)`
