### ISSUE TITLE
[Feature Request] Support external loader

### ISSUE THREAD

**Issue by k8w** [goldfire/howler.js#869]
For example, support PIXI.loader

This can be achieved by allow `new Howl({ src: Audio })`

`Audio` is loaded by external loaders.

Alternatively, support `new Howl({src: Blob})`

**Comment by themoonrat** [comment]
you _can_ create a new howl via src: blobUrl. Our games do that.
And you can create your own plugin middleware to the PIXI loader to support loading sounds as blobs (your own version of https://github.com/englercj/resource-loader/blob/master/src/middlewares/parsing/blob.js)

**Comment by k8w** [comment]
@themoonrat I've tested that, really works.
Also I noticed that memory usage seems increased after use dataUrl.
Does it matter in your games?

**Comment by themoonrat** [comment]
Have you revoked the blob after the sound has loaded and decoded?
set the onload function of config json to do something like 
`window.URL.revokeObjectURL( blobUrl )`

**Comment by k8w** [comment]
Oops, that's the reason! Thanks~ @themoonrat
