### ISSUE TITLE
Deprecation warning: StereoPannerNode.pan.value

### ISSUE THREAD

**Issue by rensrongen** [goldfire/howler.js#872]
Setting stereo on Howl objects will now trigger the following deprecation warning in Chrome 63:

[Deprecation] StereoPannerNode.pan.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by gamecubate** [comment]
I thought this issue had been resolved for 2.0.9. Yet the same warning is seen when sourcing howler from https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.9/howler.core.min.js .
