### ISSUE TITLE
onload fires too early when load multiple files

### ISSUE THREAD

**Issue by oriole9g** [goldfire/howler.js#873]
This is my use case:

```
sounds = [];
for (i = 0; i <= 7; i++) {
  sounds[i] = new Howl({
    src: ['mp3/sound' + i + '.mp3'],
    preload: true,
    onload: soundLoaded(i)
  });
}
```

I expected that every onload call fires when the mp3 was fully loaded but only works with the first element, following elements fires onload instantly.

Any idea?

**Comment by goldfire** [comment]
You either need to bind `soundLoaded` or use `let` or `const` to fix the scope issue.
