### ISSUE TITLE
PIXI + Howler + Webview

### ISSUE THREAD

**Issue by led76marx** [goldfire/howler.js#875]
I am trying to load three sounds sprites into my app's Webview (needless to say this works well in Chrome/Firefox etc). The app is in PIXI.

var sound = new Howl({  
     src: ['sound.mp3'],
       sprite: {
       audio: [0,350],
       brush: [350, 16150],
       notep: [16500, 691]
      }
 });
I play the sounds like this:

sound.play('brush');
Instead of hearing the 3 sounds, the whole file is played once. Then if I play the first or the second sound I hear the whole sound file (all 3 sounds). The third one is played correctly after the whole file is played once. Does it have to do with Android's assets? I just use this code in Android Studio, nothing else:

WebSettings webSettings = webView.getSettings();
webSettings.setJavaScriptEnabled(true);
webView.loadUrl("file:///android_asset/index.html");
Anyway, is there any working code, any very simple example I may use for this task? I have lost 2 days for just playing with these three sounds. If there is any other workaround I would be happy to try...

Many thanks

**Comment by goldfire** [comment]
Did you ever figure out what was going on here? Is this using Cordova or something else?

**Comment by devyeshtandon** [comment]
@led76marx I am facing this issue 5 years later, lol. Do you remember how did you fix this?

**Comment by led76marx** [comment]
Hi @devyeshtandon - I am really sorry, I don't remember if I ever fixed this or why I closed the issue as resolved without explaining what I did. Although I abandoned the project, I promise I will try to find the last version of my code and get back to you if I resolved it somehow.

**Comment by devyeshtandon** [comment]
Thanks @led76marx ❤️
