### ISSUE TITLE
IE11 never emits "end" event

### ISSUE THREAD

**Issue by jperezdavinchi** [goldfire/howler.js#876]
Debugging I saw this part of the code, IE11 always enter in the condition and it stays in a loop
![image](https://user-images.githubusercontent.com/28526655/34041001-79016eb0-e196-11e7-8baa-bf58fde56bd7.png)

**Comment by goldfire** [comment]
This should be fixed in master, but if you are still seeing it after 2.0.6 is released let me know and I'll reopen this.
