### ISSUE TITLE
Release const fix

### ISSUE THREAD

**Issue by uorbe001** [goldfire/howler.js#879]
https://github.com/goldfire/howler.js/commit/fcaee4feee276feabae9474ad6257077b017cfb6 fixes an accidental `const`, but the `dist` file hasn't been built or the npm version released. 

Would it be possible to have either of those done so we can update to 2.0.6 without breaking older browsers, please?

**Comment by goldfire** [comment]
2.0.7 is now on npm.

**Comment by uorbe001** [comment]
thanks!
