### ISSUE TITLE
JAVA Class ServerSocket

### ISSUE THREAD

**Issue by appstation** [goldfire/howler.js#880]
I want to stream between Browser (using Howler.js) and remote Server running my Java Appliccation using the classes ServerSocket, AudioSystem, AudioInputStream etc.... with direct TCP IP connection. 
What is the best way to realize that ? ... The microphone signal also should be transferred ... I think this should be possible ?
Any Idea ?

**Comment by goldfire** [comment]
Unfortunately, this sounds like something outside the scope of howler.js. It might make more sense to ask this on StackOverflow.
