### ISSUE TITLE
Error on edge, WEBAUDIO17055: Cannot set buffer after it has been already been set.

### ISSUE THREAD

**Issue by vantreeseba** [goldfire/howler.js#890]
WEBAUDIO17055: Cannot set buffer after it has been already been set.

**Comment by positivew** [comment]
I have also experienced that error in console on Edge. The project is using howler.js version 2.0.7.

**Comment by goldfire** [comment]
Has anyone figured out a reproducible test case for this?

**Comment by jfizz** [comment]
I was able to reproduce using this https://jsfiddle.net/85a6jgb3/8/.

Steps:
1) Go to Browserstack and select Win10/Edge17 and open developer tools.
2) Using the file input field, select the video file at Documents/video/sample_mpeg4
3) Wait a few seconds and the error will appear.

**Comment by killroyson** [comment]
I am using howler.js v2.0.15 and seeing this error whenever a sound instance is stopped. Any progress on the issue?

**Comment by Jokero** [comment]
Also faced with that

**Comment by rin3s** [comment]
@goldfire 
You can reproduce this on Edge, by visiting the **Audio Sprites** demo on the www.howlerjs.com page.
Play a sprite once, and once it has finished playing, it will throw the error.

Seems the `catch` throwing it here:
https://github.com/goldfire/howler.js/blob/9e1d0a83a67c6e43ca9602ac2b783e1fc867f579/dist/howler.js#L1986

and it's called here as `self._cleanBuffer(sound._node)`:
https://github.com/goldfire/howler.js/blob/9e1d0a83a67c6e43ca9602ac2b783e1fc867f579/dist/howler.js#L1810

Edge version:
 42.17134.1.0
Microsoft EdgeHTML 17.17134
