### ISSUE TITLE
Radio Example- Plays once 

### ISSUE THREAD

**Issue by jverk** [goldfire/howler.js#892]
When you play a station in the radio example it plays on the first click.  Once you navigate to another station and return to the already played station it will not play a second time.

This happens in the live demo too.

**Comment by sharathannaiah** [comment]
I'm too facing the similar issue. Please provide a solution as soon as possible,

**Comment by sharathannaiah** [comment]
Got any update on it jverk?

**Comment by jmo84** [comment]
Looks like the "Music Player" demo works but "Live Radio" does not after returning to a previous track.
