### ISSUE TITLE
Don't assign to "window" if "exports" or "define" available

### ISSUE THREAD

**Issue by jmo84** [goldfire/howler.js#894]
In a browser, I can't have my "window" populated with Howler's classes. My unit testing software declares Howler's classes as a global variable leak. I can't pass a proxy "window" object from my sound code because parts of Howler use the "window" object if defined (which is good). Adding to the "window" namespace slows down a host application because it increases variable resolution times.

My solution:

 ```javascript
function exportHowler(ns) {
	ns = ns || {};
	ns.HowlerGlobal = HowlerGlobal;
	ns.Howler = Howler;
	ns.Howl = Howl;
	ns.Sound = Sound;
	return ns;
 }
 
 if (typeof define === 'function' && define.amd) {
	define(exportHowler());
 } else {
	exportHowler(
		(function() {
			if (typeof module !== 'undefined' && module.exports) {
				return module.exports;
			} else if (typeof exports !== 'undefined') {
				return exports;			
			} else if (typeof global !== 'undefined') {
				return global;
			} else if (typeof window !== 'undefined') {
				return window;
			}
		})()
	);
}
```

**Comment by ibc** [comment]
Same as #865

**Comment by jmo84** [comment]
I posted the issue because I wanted bring attention to the fact that unit testing software like Mocha and QUnit both fail a test when Howler adds to the `window` because it's considered a global variable leak.

My build system injects Howler into the main output package so I don't have the option of adding it as a dedicated script tag before loading the unit testing framework.
