### ISSUE TITLE
5.1 surround audio support

### ISSUE THREAD

**Issue by dburongarcia** [goldfire/howler.js#895]
Hello, I've searched a lot for documentation or samples using Howler.js with 5.1 surround audio, but I haven't found any. I'm getting things done with Web Audio API, but Howler needs far less code to achieve many things. Any tips? Thanks

**Comment by jmo84** [comment]
Howler plays Dolby Audio (5.1 and 7.1) but only Edge and Safari support the format.

https://github.com/goldfire/howler.js#dolby-audio-playback

https://developer.dolby.com/News/Goldfire_Adds_Dolby_Audio_Support_to_howler_js.aspx
