### ISSUE TITLE
playlist in the player example is not centered, here's a quick fix!

### ISSUE THREAD

**Issue by quinton-ashley** [goldfire/howler.js#906]
The playlist is not centered in the player example, here's a quick fix:
```javascript
#list {
	width: 100%;
	position: absolute;
	top: 50%;
	transform: translateY(-50%);
}

.list-song {
	width: 100%;
	height: 4vh;
	font-size: 3vh;
	line-height: 4vh;
	text-align: center;
	font-weight: bold;
	color: #fff;
	text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.33);
}
```

Also just wanted to say thank you so much for making this project!  A star really isn't enough and it's so impersonal.  This project will allow me to close my soundcloud account and share lossless quality flac files of my music!

**Comment by goldfire** [comment]
Thanks, I really appreciate it! Which browser are you seeing it not centered in? This is what it looks like for me:
<img width="1563" alt="screen shot 2018-02-16 at 2 18 18 pm" src="https://user-images.githubusercontent.com/882005/36327450-4eb7e6ec-1324-11e8-9f16-12f860c4f17a.png">

**Comment by quinton-ashley** [comment]
You're welcome!  Hmm that's interesting, I'm using Google Chrome on macOS High Sierra.  When you add more tracks does it stay centered in your browser?
