### ISSUE TITLE
Howler Not Playing Sound On Chrome Android

### ISSUE THREAD

**Issue by rakshithsj30** [goldfire/howler.js#907]
Hi,
I integrated howler js library into my website. When I open my website on my android phone using chrome, the sound is not playing.

This is my code:
 var sound = new Howl({
  src: ["some song url"],
 html5:true,
mobileAutoEnable :true
});

Android Chrome Version: V64.0.32
Android Version: Marshmallow

The song is playing in the proprietary browser on Android.

Please help me to fix the issue

**Comment by themoonrat** [comment]
There must be a user interaction before sound will work. You can't just have music playing automatically when the page loads
