### ISSUE TITLE
Suggestion: onfinish event

### ISSUE THREAD

**Issue by saidbakr** [goldfire/howler.js#911]
While `onend` event is limited in loops. i.e it fired at the end of every loop, so a new event `onfinish` will be sufficient to be fired when the sound is stopped regardless how many we loop the sound.

**Comment by webketje** [comment]
This is already available as `onstop` or in what context do you mean *the sound is stopped*?
If you want an event to fire at the end of a fixed amount of loops you can easily implement it like so:

```
function onFinish(loopingHowl, numLoops, onFinishCallback) {
   var counter = 0;
   var listener = function() {
     counter += 1;
     if (counter === numLoops) {
        onFinishCallback();
        loopingHowl.off('end', listener);
     }
   };
   loopingHowl.on('end',  listener);
}
```

**Comment by saidbakr** [comment]
@webketje  Yes this is sufficient.
