### ISSUE TITLE
Consider adding your module eports to the bottom

### ISSUE THREAD

**Issue by ogomez92** [goldfire/howler.js#916]
Hi!
You should consider adding your exports to the bottom because otherwise the 3d positioning can't be accessed via things like import and webpack.

Thanks!!

**Comment by Ghorthalon** [comment]
Unless there's another way to do this I'd also consider this a pretty urgent issue if you use the NPM package. Without moving the export definitions I cannot get 3D positioning to work. This means that for those cases, depending on the NPM package does not work and you have to modify the code.

**Comment by goldfire** [comment]
@Ghorthalon Can you explain what you mean? We use the NPM package in all of our projects without any issues, including with 3d sound.
