### ISSUE TITLE
When played in an <iframe>, Howler.mute does not cause sounds to be muted

### ISSUE THREAD

**Issue by kurozael** [goldfire/howler.js#917]
If our game is viewed through an <iframe> the game still plays sounds even though `Howler.mute(true)` is set. The issue is noticeable on the Oppo A11 in the native browser.

`Howler.volume(0)` also doesn't work, BUT by setting a volume of 0 to individual sounds you can get them to effectively mute.

My workaround currently is to loop all playing sounds and apply a multiplier of 0 to their base volume when I want to mute the game.

**Comment by goldfire** [comment]
I'm not familiar with this device, can you provide some further details about the browser/version and OS that is being used? All of our games are loaded in iframes and we aren't seeing this behavior on any of the environments that we test.
