### ISSUE TITLE
Can't play the file of .m4a

### ISSUE THREAD

**Issue by Mimperial** [goldfire/howler.js#919]

**Comment by themoonrat** [comment]
m4a works fine for me and in the examples on the howler website. You'll need to provide a fiddle and more details please.

**Comment by Stenerson** [comment]
MP3s and MP4s are not currently supported by FireFox or Opera. Without more details it's hard to say if that's the problem you're having but I know it's a common problem.

https://en.wikipedia.org/wiki/HTML5_audio
