### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by freitasjuciel** [goldfire/howler.js#920]
I'm using the onloaderror and onplayerror to capture the execptions but some decoding audio error goes to console.

<img width="570" alt="captura de tela 2018-03-08 as 10 25 51" src="https://user-images.githubusercontent.com/7970477/37153408-637f7a76-22bb-11e8-96f5-a3e0c572abfa.png">

**Comment by goldfire** [comment]
This should be getting handled in v2.0.14 (will be released later today), but let me know if you continue to see this issue.
