### ISSUE TITLE
Internet Explorer 10 - Looped Audio plays only twice

### ISSUE THREAD

**Issue by Take5dev** [goldfire/howler.js#921]
```
audioPlayer = new Howl({
	src: ['audio.aac', 'audio.mp3'],
	loop: true
});
```

In Internet Explorer 10 audio from this code plays only twice
so I had to add not very beautiful solution like:

```
onend: function() {
	if(ie && ie <= 10) {
		// tricky IE10 bug
		audioPlayer.play();
	}
}
```

It seems to me that after 1st play a looped sound object is copied without (or with wrong) loop param.

**Comment by stativka** [comment]
The same for IE11
