### ISSUE TITLE
How to limit _howls size

### ISSUE THREAD

**Issue by nanek** [goldfire/howler.js#926]
I have a single page app, that plays lots of audio files. Over time, the `_howls` array continues to grow and increase in size. Is there a way to set max size for this to prevent saving references indefinitely?

I see there is Howler.unload(), which removes all audio and clears out _howls, however I'll need to determine when best to call this. If we could limit it to 30 for example it could cache the most recent but drop the old ones.

A different use case, is I have some audio that I would like to cache, as we play it often and other audio that we just play once and never again that I don't need to cache. It would be nice to indicate different cache buckets.

**Comment by goldfire** [comment]
In addition to `Howler.unload()`, there is also `Howl.unload()` to clear out individual sounds: https://github.com/goldfire/howler.js#unload.
