### ISSUE TITLE
Fade doesn't work when using html5 mode

### ISSUE THREAD

**Issue by SteveEdson** [goldfire/howler.js#932]
Tested on Safari on iOS 11.3, sample code:

```javascript
const audio = new Howl({
    src: 'audio.wav',
    autoplay: false,
    html5: true,
});

function play() {
    audio.play();
}

function fade() {
    audio.fade(1, 0, 1000);
}
```

```html
<span onclick="play()">Play</span>
<span onclick="fade()">Fade</span>
```

The fade method has no effect. (I'm using html5 mode as I'm getting awful crackling and popping otherwise)

**Comment by goldfire** [comment]
Unfortunately, HTML5 Audio can't control the volume on iOS, so there is no way to get fading to work without Web Audio.

**Comment by SteveEdson** [comment]
I understand that, however, is it not possible for it to throw a DOM
exception or return false / a failed promise when html mode is being used?
Right now, I want to fade and then pause, I'm having to use timeouts which
seems a bit messy.

Thanks

**Comment by goldfire** [comment]
It should still go through the time set in the fade and fire the event at the end even though it doesn't change the volume. Are you saying it isn't doing that for you?

**Comment by SteveEdson** [comment]
Sorry, missed your reply. 

Correct, when I tried this, the stream didn't stop at all, I had to implement my own setTimeout to make sure it would stop.
