### ISSUE TITLE
Audio keep playing after new browser page

### ISSUE THREAD

**Issue by wijesijp** [goldfire/howler.js#935]
I am new to howler. This is the first time I am using it.

When I change the browser tab I expected audio to pause playing.
But it keep playing.

Is there a way to stop audio in this situation? 
Maybe there is a setting i have to enable?

**Comment by goldfire** [comment]
This is something you would need to handle within your own application, but it is fairly easy using the page visibility api. We've used https://github.com/ai/visibilityjs in some projects without any issues.
