### ISSUE TITLE
rate does not work for IE 11

### ISSUE THREAD

**Issue by wijesijp** [goldfire/howler.js#936]
I am new to howler. This is the first time I am using it.

To reduce the file size I speed up the audio file.
Then I set the rate to 0.5 when I play the audio.

The audio plays perfectly on all other browsers except IE 11.
I am using IE 11.371.16299.0

This is the code i used;

 var _backgroundSound = new Howl({
        src: ['audio/AMBIENCE.mp3'],
        loop: true,
        volume: 1,
        rate:0.5

    });

    _backgroundSound.play();

Is there a way to fix this? Is there a setting to get it working?

**Comment by goldfire** [comment]
Are you saying that it doesn't slow it down or that it doesn't sound right?

**Comment by wijesijp** [comment]
It is heard in 2x speed. It does not slow down.
As rate 0.5 has no effect.

I noted same issue on Safari browser running on Mac OS.

All other browsers the code works perfectly.

**Comment by wijesijp** [comment]
I tested new version. 
But it is still not working properly on IE.

Here is a link to my project.
https://www.dropbox.com/s/2i9r0mzhmmsbhzl/mytest.rar?dl=0

**_But I noted following;_**

If I use "sound1.mp3" that comes with the project

I could double click the html file and rate is working properly on all browsers
I could also host the project web server (i used beefy ) and it works correctly on all browsers

If I use my audio file 'AMBIENCE.mp3' 
when i start the html file by double clicking the rate does not work on **any browsers**.
When I host the project on web server rate does work on all browsers except IE.

Can you please advice?
