### ISSUE TITLE
Urgent issue: Looping html 5 audio stops looping after pause/play and there is no way to re enable it

### ISSUE THREAD

**Issue by ogomez92** [goldfire/howler.js#941]
Hi.
As the title says, if you set an html5 audio to loop and then pause it, after you play it again it stops looping. and I can't set looping to true again.

Please fix, my project uses loops heavily.

Thanks.

**Comment by goldfire** [comment]
Can you provide a test case? I just tested what you described and it worked correctly. Also, are you seeing this on a specific browser/device?

**Comment by jabacchetta** [comment]
Can confirm this as well. Will be diving in more this week and report back if I have anything else to add to the discussion.

Related:
https://github.com/goldfire/howler.js/issues/947
https://github.com/goldfire/howler.js/issues/934

**Comment by jabacchetta** [comment]
Haven't had a chance to debug this in Howler yet, but here's what I've figured out so far. In order for audio to work:

On Safari desktop and Safari iOS, if looping, html5 option must be false, and if not looping, html5 option must be true. On Chrome Android, if not looping, html5 option must be false, but it does not care about html5 option if looping.

As a temporary workaround, I have the following code to set the `html5` option:

```javascript
let html5 = false;
if (isSafari && !loop) html5 = true;
```
I'm still attempting to untangle a web of audio bugs that we're currently experiencing, though. And even with this solution, we're getting severe delays on audio playing in iOS. I'm assuming this is unrelated, and will post a new issue once I find out more.
