### ISSUE TITLE
Deprecated APIs

### ISSUE THREAD

**Issue by brettbond** [goldfire/howler.js#943]
FYI, I see these two deprecated API warnings in Console:

howler.min.js:2 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
_ @ howler.min.js:2
howler.min.js:2 [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

**Comment by goldfire** [comment]
This should be fixed in master. I'll try to get an update out to npm soon. I've been swamped and also out of the country, otherwise I would have already gotten it published.
