### ISSUE TITLE
cant resume audio when set html5 to true

### ISSUE THREAD

**Issue by hossy13** [goldfire/howler.js#947]
hi 
i cant resume the audio when i set the html5 to true .
why is that?

```
var sound = new Howl({
                        src: [$this.music.url],
                        loop: true,
                        volume: .7,
                        html5: true,
                    })
playOrPause(sound,id) {
           
                if (sound.playing(id))
                    sound.pause(id)
                else
                    this.sound.play(id);
}

**Comment by goldfire** [comment]
Can you provide a test case? I just tested what you described and it worked correctly. Also, are you seeing this on a specific browser/device?

**Comment by diegovdc** [comment]
I have the exact same issue, using version `2.1.1`, here is a working example:

```js
const sound = new Howl({
    src: "https://ia801400.us.archive.org/34/items/space-is-the-place/VIU-barcelona_V2.mp3", 
    html5:true
})

sound.play()
setTimeout(sound.pause, 5000)
setTimeout(sound.play, 7000)
```

**Comment by avirtum** [comment]
Have the same issue on Chrome.

**Comment by KmeCnin** [comment]
Same issue here.
`Google Chrome: Version 79.0.3945.88 (Official Build) (64-bit)`
Issue appears only with html5 to `true`

**Comment by epikoder** [comment]
Same issue here.. Just noticed it was `html5: true` that's the problem. `Edge 85.0.564.63 (official build) (64 bit)`

**Comment by epikoder** [comment]
Tested the player example on same browser and it's working. I'm using webpack. Seems it's something to do with the audio
