### ISSUE TITLE
Forcing sounds to redownload, avoiding cache

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#951]
Hi, in my app, I have to overwrite the very same mp3 file, and redownload it from time to time,
problem is Howler is  playing the old file, I guess because of the browsers cache.

To avoid that, traditionally, we would add a random parameter at the end of the url, like: ?v=21332 , 
but when I try to pass that to howler it fails, it doesn't like any extra bits after the .mp3 

how can I force howler to redownload the latest version without taking the one cached by the browser?
thanks a lot

**Comment by goldfire** [comment]
Well, it should still be able to extract it even with a query string. You might try specifying the format (https://github.com/goldfire/howler.js#format-array-) and see if that fixes it.

**Comment by javismiles** [comment]
Thank you goldfire, I took a look but not sure how to specify that,
my format is simply the url finished on .mp3 plus a ?v=randomnumber, 
how would I specify that in the format-array?
thank you very much

**Comment by javismiles** [comment]
I can see this
format: ['dolby', 'webm', 'mp3']
but how am I going to specify a variable ending after the extension in that field?

**Comment by goldfire** [comment]
If you are only loading an mp3 then just set it as `format: ['mp3'],`.

**Comment by javismiles** [comment]
yes, that works in the sense that it doesnt give error anymore and it accepts it. Unfortunately its still loading the old cached mp3

**Comment by javismiles** [comment]
all right, i made it work, by using a php proxy,
var theurl = 'https://xxxxxx/proxymp3.php?id='+audtoload+'#' + new Date().getTime();

this way it works so we can close this, thank you

**Comment by TxAg12** [comment]
Caching is a server/browser issue.
