### ISSUE TITLE
Events not firing when using Seek; works without Seeking, events stop working after Seeking

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#952]
Good day,
I have a number of howl objects declared, with onend and onstop events,
for some odd reason, those events fire the first time one of those sounds arrives to the end, but after the first time, those sounds keep playing and ending but those events never fire again,
why would this happen?

my sounds have
html5:true,
autoplay: false,
buffer: false,
loop: false,

thank u very much

**Comment by javismiles** [comment]
I am manually playing the sounds each time using play(), and sometimes  they stop on their own, and other times I use pause to pause them, before later using play and seek to restart them, but the thing is that the onend and onstop events never ever fire again,  they only do once, the first time

**Comment by javismiles** [comment]
This is really odd, all events fire only the first time one of the sounds gets to the end, never again, and cant make them  happen again, despite those sounds starting and finishing with no problems, no errors, etc

**Comment by javismiles** [comment]
wow i found the reason,
it;s because i use  Seek!  using seek kills all the events, why?

plcur=myObj[index].audio.play();
myObj[index].audio.seek(3,plcur);

if i delete the seek line, events fire again normally,
why is the seeking line stopping them? i get no errors anywhere

**Comment by javismiles** [comment]
thats very weird, because i do need to use seek to position myself 3 seconds from the start every time, but if i use seek, the onend etc events disappear, oops, so weird,
if i delete the seek line, they reappear, 
and i get no errors, nothing, sounds play all well, so odd

**Comment by goldfire** [comment]
Can you provide a full example including how you are setting up the event listeners?

**Comment by javismiles** [comment]
the code is part of a very large project but let me put here the portions that are relevant, really there is not much to it:

version Im using:
/*! howler.js v2.0.9 | (c) 2013-2018, James Simpson of GoldFire Studios | MIT License | howlerjs.com */

my audio elements are created like this:

`
Elem.audio = new Howl({
	src: [theurl],
	autoplay: false,
	html5:false,
	loop: false,
	buffer: false,
	format: ['mp3'],
	volume: 1,
	onloaderror: function(v1,v2){},
	onplayerror : function(v1,v2){
        onplay: function(){},
        onend: function(){
           console.log("audio ended. This only works if I don't  use seek. If I use seek, this does not fire.");
        },
        onstop: function(){},
        onload:	 function(){
 		var pl=this.play();
		this.seek(3,pl);								
	},							
							
	});

then in other parts of the code:
plcur=myObjects[myindex].audio.play();
myObjects[myindex].audio.seek(3,plcur);
`

That's all there is to it.

If i use the seek as shown above, the onend events  do not fire.
If I play without using the seek, then the onend events fire all normally

very odd

**Comment by goldfire** [comment]
This appears to be fixed in the latest release as I can no longer replicate it. If you are still having this issue let me know and I'll re-open.
