### ISSUE TITLE
iOS Safari audio inside of setTimeout()

### ISSUE THREAD

**Issue by jabacchetta** [goldfire/howler.js#958]
I'm running into an issue where audio is not playing on iOS Safari when it's executed inside of `setTimeout()`. 

All other browsers work fine. And even iOS seems to work in specific situations (e.g. only if I create the `howl` within a second of a user interaction).

The problem is, this audio is continuously played throughout the game at random times (a game with rising bubble animations that pop with audio when they rise to the top). I can create the `howl` without a problem, but on iOS I can only `play()` it once.

I'm assuming this is an iOS limitation, as opposed to a Howler bug. But figured I would check here anyway to be sure, and to get suggestions for workarounds.

**Comment by goldfire** [comment]
This is an issue with mobile and now Chrome on the desktop as well (https://gameanalytics.com/blog/gameanalytics-game-designers-perspective.html). Audio must be unlocked in a user interaction before anything can be played. I would recommend not forcing HTML5 Audio as this makes the issue even worse on mobile.

**Comment by jabacchetta** [comment]
@goldfire Thanks for the quick reply.

I don't appear to be having any issues on the latest Chrome build.

We do have a start button that initiates the game and appears to work fine in all other audio scenarios.

Regarding HTML5 Audio, it currently appears to be necessary on Safari, as I've documented on #941 .

And, did you mean to link to a game analytics article? A bit confused on what I'm supposed to be reading there.
