### ISSUE TITLE
Spatial sound pool cache bug 

### ISSUE THREAD

**Issue by Qriva** [goldfire/howler.js#962]
I am using single sound in two ways: as **spatial** sound and **normal** one.
When I play for example 3 times spatial sound (by settting `pannerAttr`) its is all fine.
Playing normal sound after this works correctly too but there is a problem with cache if i stop my sounds.

After using `.stop()` to stop all sounds in a group, when I use normal `play()` play again then my sound is played as spatial. 
If I click play few times the **n**'th sound will be normal (4th one for this example). 
It looks like Howler cache spatial sounds as the normal one and then after using `play` instead of "clean" sound I get the old one with the old `pannerAttr`.
I think this is not expected behaviour. 

What is the best solution to fix it for now? 
Disable cache for each sound used this way or there is another option?

**Comment by goldfire** [comment]
Thanks, this should now be fixed on master.
