### ISSUE TITLE
Howl not defined

### ISSUE THREAD

**Issue by JohnMaestas** [goldfire/howler.js#964]
Hello new to howl and am have issues when trying to get sounds to play. Error Howl is not defined

**Comment by eugene-lazarev** [comment]
Hey @JohnMaestas,
That error means your page have not loaded howler.js.
Please make sure you have include <script src="/path/to/howler.js"> in your page.
For yourself information: https://github.com/goldfire/howler.js#quick-start

**Comment by JohnMaestas** [comment]
Yeah its there , I am having problems with the cross origin request error

**Comment by eugene-lazarev** [comment]
So this problem is not about howler itself, correct? I think you can search CORS in google and do what you want to do (I have no idea what it is exactly).

**Comment by Aarbel** [comment]
Got this error while importing howler as const on an Electron environment.

const { Howler } = require('howler').

Everything was solved importing as a var

```JS
var howler = require('howler');

new howler.Howl({…})

```
