### ISSUE TITLE
How to import Howler core in Webpack4/npm/Babel without plugins and other extras?

### ISSUE THREAD

**Issue by Friksel** [goldfire/howler.js#971]
Before using Webpack, in the past I just used the minified Howler core-file to exclude unused extras in the build to keep build as small as possible. But how can we do this with imports in Webpack? I only see people using { Howl } from 'Howler', or 'Howler from 'Howler'. I would expect something like { HowlerCore } from 'Howler', or { HowlerCore, HowlerPlugins } from 'Howler', but can't find anything on that.
I tried some things myself, but so far without luck. It looks like stuff like the spatialplugin still gets included in the outputbundle.

How to only include Howler core by using es6 imports?

Thanks

**Comment by Friksel** [comment]
@goldfire Thanks for adding the 2.1.0 milestone on june, but we're at 2.1.1 now and the spatial/effects extras are still imported and appear in the webpack build.
I couldn't find nothing about this in the changes list. Did I overlook something or am I missing something?

**Comment by Friksel** [comment]
Hi @goldfire, it's been over a year since this request. Unfortunately the Spatial Plugin is still included when importing the howler module using Webpack. I believe little users use the spatial plugin and want it in the output. So I am surprised it's still not possible to leave it out using imports, like it was possible when using the single files before.

Any progress/news on this?

**Comment by Friksel** [comment]
Hi @goldfire, it's years since this request. You added the 2.1.0 milestone, but we're at 2.1.3 now and it's still not done. 

On my request for an update last year you didn't even respond, which would have taken you only one minute. I think is pretty bad you just ignore your users for so long and it comes across as arrogant to me.

I am going to look for alternatives now or build one myself.

**Comment by 0xdevalias** [comment]
@Friksel Just stumbled upon this, haven't tested the output, but would something like this solve your need?

```javascript
import { Howl, Howler } from 'howler/src/howler.core'
// import 'howler/src/plugins/howler.spatial'
```

**Comment by Friksel** [comment]
@0xdevalias Thanks. For my projects I only needed to import Howl, so not Howler. It works well with tree shaking in Webpack too when Howler is excluded from imports. Not sure when the Howler object might be needed, but this also works fine here webpack build:

`import { Howl } from 'howler/dist/howler.core.min';`

**Comment by Friksel** [comment]
@0xdevalias Thanks. For my projects I only needed to import Howl, so not Howler. It works well with tree shaking in Webpack too when Howler is excluded from imports. Not sure when the Howler object might be needed, but this also works fine here webpack build:

`import { Howl } from 'howler/src/howler.core';`

**Comment by Chroma72** [comment]
I just added 'export default Howl;' to the end of the 'howler.core.min.js' file from the 'dist' folder and then did a **import Howl from '/js/mod/howler.2.2.3.core.min.js'** and that works for me. The js/mod folder is just the path to where I keep that file. Would be nice for a proper .mjs release though.
