### ISSUE TITLE
Howler orientation error on safari

### ISSUE THREAD

**Issue by gillesboisson** [goldfire/howler.js#976]
We have an issue only in safari (version 2.0.5 of howler).

The orientation method crash when it try to execute sound._panner.orientationX.setValueAtTime. sound._panner.orientationX is equal to undefined. 

```js
if (sound._node) {

//...
              setupPanner(sound, 'spatial');
            }
           

            sound._panner.orientationX.setValueAtTime(x, Howler.ctx.currentTime);
            sound._panner.orientationY.setValueAtTime(y, Howler.ctx.currentTime);
            sound._panner.orientationZ.setValueAtTime(z, Howler.ctx.currentTime);
          }
//...
```
It's really weird. I never had this kind of issues before.

**Comment by goldfire** [comment]
Can you try the latest version (2.0.12)? This should have been fixed since the release you are using, but I'll reopen if you are still having this problem.

**Comment by gillesboisson** [comment]
thanks @goldfire , but I still have the issue on 2.0.13. If it can helps : you can test it here 
http://boat.dotify.eu : start a game > select a level > select a boat.

**Comment by goldfire** [comment]
Thanks, I just saw where I missed that in one section. I'll have an update out later today with the fix.
