### ISSUE TITLE
Howls that fail to load aren't removed from Howler.howls when calling unload()

### ISSUE THREAD

**Issue by dgrenzo** [goldfire/howler.js#978]
`
    let failed_howl = new Howl({
      src: [''],
      onloaderror: () => {
        Howler.unload();
      }
    });
`

I think it is because the .splice is happening inside a loop at line 1583 of howler.core.js that never gets executed for Howls that haven't loaded.

**Comment by goldfire** [comment]
Thanks! It was indeed in the wrong spot and shouldn't have been inside that for loop.
