### ISSUE TITLE
Spatial Audio + Loop crash in 2.0.13

### ISSUE THREAD

**Issue by timothyallan** [goldfire/howler.js#985]
Works great in previous versions, but I now get `Failed to set the 'loopEnd' property on 'AudioBufferSourceNode': The provided double value is non-finite.` when trying to play a looped spatial audio file now with 2.0.13.

Setting loop to false plays the sound just fine.
Not setting any `pannerAttr`'s also plays the sound fine.

```
      // Setup looping and playback rate.
      sound._node.bufferSource.loop = sound._loop;
      if (sound._loop) {
        sound._node.bufferSource.loopStart = sound._start || 0;
        sound._node.bufferSource.loopEnd = sound._stop;
      }
```

It craps out in the section above as `sound._stop` is undefined;

As a secondary issue: if I set loopEnd to 0 in that above code, I start getting other `pannerAttr` property errors unless I supply every single `pannerAttr` attribute, whereas before it would use the defaults if I only supplied a couple.

**Comment by goldfire** [comment]
Do you have a test case of what triggers this? We have quite a few looping spatial sounds in our games that are running 2.0.13 and we haven't seen this come up so far.

**Comment by timothyallan** [comment]
As far as I know, I'm simply making a new sound, setting the spatial properties, and it's conking out. 
```

        this.audioPlayer = new Howl({
          src: file.link,
          autoplay: false,
          loop: false,
          volume: 0.5,
          onplay: action('onplay', () => {
            console.log('onplay!');
            this.isAudioPlaying = true;
          }),
          onend: this.handleAudioStop,
          onstop: this.handleAudioStop,
          onload: this.handleAudioLoaded,
          onloaderror: this.handleAudioError,
        });

this.audioPlayer.pannerAttr({
              coneInnerAngle: 360,
              coneOuterAngle: 360,
              coneOuterGain: 0,
              maxDistance: 10000,
              panningModel,
              refDistance: 0.8,
              rolloffFactor: 2.5,
              distanceModel: 'exponential',
            });
```
if I comment out the `this.audioPlayer.pannerAttr` part, it works.

**Comment by goldfire** [comment]
Thanks, I'm able to reproduce the issue now.
