### ISSUE TITLE
html5 audio doesnt play in safari desktop

### ISSUE THREAD

**Issue by indexofrefraction** [goldfire/howler.js#987]
i noticed that html5 audio does not play in safari desktop 
(maybe the same in chrome)

play() is called but there is no sound
and no console output  (promise errors or something)

(note: without html5:true everything works fine)

**Comment by goldfire** [comment]
The HTML5 samples on https://howlerjs.com are working for me in Safari. Do you have a sample of something that isn't working?

**Comment by indexofrefraction** [comment]
after a lot of tests i can say
- my sounds play if i use them in the howler core html5audio tests 
- my sounds do not play in the context of my website.
- but if i just switch from html5=true to false, they do play!

is there anything that could interfere with html5 playback?

**Comment by indexofrefraction** [comment]
if i go to tests/js/core.html5audio.js,
remove the click event listener and just start the demo,
 i get the same behaviour

in my website i have clicks before i start the (html5) sounds..
does it need a play() inside the click event?

**Comment by themoonrat** [comment]
Yes. Most browsers these days restrict usage of audio unless an initial sound was played within a click event

**Comment by indexofrefraction** [comment]
ok, but is there a way to determine if this has happened already?
how can i know if i can play html5 or not?

**Comment by goldfire** [comment]
Yes, unfortunately, Safari's autoplay policies require that the sound is played within a user interaction like a click. The unlock method we have in howler won't work for this, so you'll have to make it work on your application end.
