### ISSUE TITLE
usingWebAudio is not initialised until a first HTLM5 audio is loaded

### ISSUE THREAD

**Issue by obiot** [goldfire/howler.js#993]
Hello,

When on a HTML5 Audio platform only. I noticed that `Howler.usingWebAudio` is not properly set until a first audio asset is loaded.

For now I'm tricking it by calling `Howler.mute(false)` before doing anything which will create an AudioContext and set the `usingWebAudio` flag.

Is this me understanding this wrongly, or could this be improved by create an audio context upon Howler initial setup.

Thanks

**Comment by goldfire** [comment]
Pros and cons either way. Howler used to create the AudioContext when it was first setup, but this caused other issues. For example, on mobile if you had audio playing in a background app and opened a page with howler, the background audio would stop even if howler never played any audio.
