### ISSUE TITLE
Non-HTML5 Audio distorts in iOS 11 Safari 

### ISSUE THREAD

**Issue by aareeph** [goldfire/howler.js#994]
I am experience audio distortion issue after refreshing iOS 11 Safari Tab. I checked other threads here before posting this issue. This issue isn't happening in HTML5 audio however my problem is that I need to use Non-HTML5 audio. 

I am already calling `Howler.unload();` method on Page load but still getting the same audio distortion.

P.S. My code is working fine on iOS 10.

Any solution?

Thanks!

**Comment by themoonrat** [comment]
This could be you requiring a user interaction to enable sound. On refreshing a page, you don't have a user interaction yet

**Comment by aareeph** [comment]
@themoonrat  sorry I didn't mention. I am experiencing this issue after a user interaction i.e. pressing a "Play" button on screen after Safari tab is reloaded.

**Comment by goldfire** [comment]
Can you provide any sort of test case? I'm having a hard time replicating this on my end.

**Comment by aareeph** [comment]
Hi @goldfire, thanks for trying this issue at your end. Apparently the issue was causing because of playing different sound files with different encodings. I was playing one mp3 file and one m4a file simultaneously. After having both files in m4a format the issue is resolved.

Thanks for your time and making this wonderful library :) Really appreciated!
